### ISSUE TITLE
PaddleOCR json.exe-应用程序错误，识别失败（win10 x64）

### ISSUE THREAD

**Issue by jsnjjqp** [hiroi-sora/Umi-OCR#1]
运行程序后，弹窗显示：

> PaddleOCR json.exe应用程序无法正常启动（0xc0000142）。清单击确定"关闭应用程序。
![屏幕截图 2022-04-12 182154](https://user-images.githubusercontent.com/50790914/162941414-ca5636e1-1d59-4598-b57c-c769c9dabe93.png)

输出面板显示：

> 识别失败，错误码：300
> 错误信息：向识别器进程写入图片地址失败，疑似该进程已崩溃。[Errno 22] Invalid argument

![屏幕截图 2022-04-12 182255](https://user-images.githubusercontent.com/50790914/162941448-1350818d-b2dc-4a2a-821d-b58b1d76bfcc.png)

系统：Windows 10 专业版  64 位操作系统
版本号：21H2

**Comment by hiroi-sora** [comment]
0xc0000142是一个很宽泛的报错，代表未正确加载某个dll库。
虽然也有可能是“找不到”某个dll，但这种情况下报错弹窗一般会明确指出该dll的名字；所以我更倾向于是已找到但未正确加载dll——比如找到了同名但内容不同的dll，或找到了位数不符合（32位/64位）的dll，这种情况下会报 0xc0000142 。

PaddleOCR-json.exe是c++编译的opencv程序，需要依赖众多的Windows系统库和vc运行库等。为了保证在不同的系统上能运行起来，我已尽量把相关的dll都找到、并放入发行版程序的`PaddleOCR-json`文件夹中，这样程序就会优先加载相对路径下的dll，而不使用系统绝对路径下的自带库，减少因系统自带的dll版本不对而导致的报错。本程序可以在未安装任何补丁和vc运行库的原始win10上正常工作。

但是也许还存在漏网之鱼，即我没有注意到的系统dll调用。又恰好您电脑上的该dll被修改过，或者注册为另一个版本；导致本程序无法加载。理论上，只要知道这个dll的名字，然后把正常版本的（别的能用的电脑上的）dll放入程序`PaddleOCR-json`文件夹，就能让程序优先加载该正常dll。可惜难点是，仅凭现在的报错信息无法定位到这个dll的名字……非常抱歉。
同理，重装解决99%的问题。即，将所有系统dll恢复为最初。不过为了这玩意而重装显然不值得，哈哈。

还有一些偏门方法：将别的正常电脑上的 system32 整个复制过来；或`for %1 in (%windir%system32*.dll) do regsvr32.exe /s %1`重新注册所有dll文件；或（非中文系统）将系统时区改回中国。但这些方法目测不见得有效，还可能带来额外的麻烦；不建议使用。

**Comment by GT-ZhangAcer** [comment]
可以试试安装个Microsoft Visual C++ Redistributable(VC redist 2013-2019)，另外Windows7如果没启动自动更新的话也不是很容易去适配

**Comment by hiroi-sora** [comment]
楼主你好，方便提供下当初遇到这个bug时电脑的CPU型号么？
