### ISSUE TITLE
这个可以做成接口的形式吗

### ISSUE THREAD

**Issue by xiaohuaAndxiaolin** [hiroi-sora/Umi-OCR#10]
我想调用接口方式来调用,可以不?

**Comment by hiroi-sora** [comment]
[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json#paddleocr-json-%E5%9B%BE%E7%89%87%E8%BD%AC%E6%96%87%E5%AD%97%E7%A8%8B%E5%BA%8F) 了解一下~~
