### ISSUE TITLE
文字格式建议：希望增加一个保持原排版的参数选项

### ISSUE THREAD

**Issue by jimmie0204** [hiroi-sora/Umi-OCR#103]
识别之前的文字段落之间有空行，识别之后希望能保留

**Comment by hiroi-sora** [comment]
由于不同文章（尤其是混排版面）字体大小、行间距、段落块位置等具有不确定性，比较难判别出空行，容易误判。

**Comment by hiroi-sora** [comment]
新版本已支持保留原始排版的缩进和空格。（但空行仍会被省略）
