### ISSUE TITLE
软件禁用网络启动后识别直接卡死

### ISSUE THREAD

**Issue by NullPointExceptionForEveryone** [hiroi-sora/Umi-OCR#104]
软件启动后为什么会进行网络请求，使用win10防火墙软件禁用网络连接后，打开识图直接软件无响应，麻烦解答一下我的疑惑

**Comment by hiroi-sora** [comment]
您是在哪儿下载的？

本项目中没有任何发起网络请求的代码和功能，设计来就是在完全离线的场景下使用。所有代码开源，更不可能含有恶意代码。

**Comment by NullPointExceptionForEveryone** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/31579822/226781616-4ad5cd85-4220-4f4f-9a85-bd4683106bc8.png">
这是我下载的截图，是在
https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.2
下载的

**Comment by hiroi-sora** [comment]
你好。非常感谢你提供的信息。

经过研究后，我发现这个问题的起因：在本项目中，使用了Python标准库中的asyncio库来构造多线程，以便完成一些异步操作。本项目在开启一次任务时（v1.3.3在启动软件时也会）创建一个事件循环：
```python
# 在当前线程下创建事件循环
self.__runMissionLoop = asyncio.new_event_loop()
```
间接调用Python标准库的 `Python\Python308\Lib\asyncio\windows_events.py` 及 `proactor_events.py` 。

内置的 SelectorEventLoop 实现会在初始化时调用 _make_self_pipe() 函数，创建自身读写管道，用于在等待异步 I/O 事件时进行阻塞。在 Windows 平台上，该实现会使用套接字socket来模拟管道。因此，Windows 平台上使用 asyncio 可能会在启动时会发起一些本地网络请求，一般来说仅有 127.0.0.1 这个本地环回地址，不会发到外网。

具体来说，`proactor_events.py` 在第620行左右创建 `BaseProactorEventLoop` 的子类的对象，在第761左右会调用以下代码来创建两个互相连接的socket对象（客户端和服务端）来实现跨进程/线程通信：
```python
self._ssock, self._csock = socket.socketpair()
```

从这里你也可以看到，客户端和服务端都是程序本身，并没有与其他应用交互。
