### ISSUE TITLE
建议：调用windows内置的截图不保存图片

### ISSUE THREAD

**Issue by 11yiyang** [hiroi-sora/Umi-OCR#105]
调用windows内置的截图进行ocr识别，发现软件识别完后不会删除图片，是否可以增加该功能？或者软件已经有类似功能而我没发现？

**Comment by hiroi-sora** [comment]
你好。使用Win+Shift+S截图，并把图片自动保存至硬盘，这是Windows 11新增的系统功能。
如果你想关闭这个功能，可以参考这篇文章：
https://www.yundongfang.com/Yun194129.html

**Comment by 11yiyang** [comment]
作者你好。系统为win10。调用windows内置截图是“截图和草图”应用。已设置不自动保存，经测试，直接使用“截图和草图”应用，不会自动保存，多次截图，本地只会保留最新的截图信息（一张最新的截图和多次截图的json文件）。但是使用ocr软件调用windows内置截图（调用的是截图和草图应用），会自动保存图片，截图完windows消息会立即通知已经保存图片，且在本地ScreenClip文件找到截图图片副本，共两张图片。

**Comment by hiroi-sora** [comment]
我明白了，你说的是不是`C:\Users\……\AppData\Local\Packages\MicrosoftWindows.Client……\TempState\ScreenClip`中的临时文件？

这个文件夹是Windows系统管理的，它按一定规则决定何时清除其中的截图副本。比如我的机器上，并不会只会保留最新的截图副本，而是保存了多张。可能不同情况下，生效的规则也不一样。

本软件并没有与这些临时文件交互的机制，所做的只是监听快捷键然后从剪贴板内存中读图而已。

或许你也不用太担心临时文件占用空间的问题，Windows会自动管理它们并在需要时清除它们。

**Comment by hiroi-sora** [comment]
另外补充：
我在 [微软文档](https://learn.microsoft.com/zh-cn/windows/uwp/launch-resume/launch-screen-snipping) 了解到，使用某些API唤起系统截图确实可以指定是否提前删除临时文件。
![image](https://user-images.githubusercontent.com/56373419/226685904-12386c1e-f889-4cb0-a09e-3bb23066b9a3.png)

但本软件并未使用这些API。无论是按Win+Shift+S触发OCR，还是通过软件面板上的按钮触发截图OCR，都是监听/发送键盘事件来唤起系统截图，所以也无法指定这个删除文件的参数。

**Comment by 11yiyang** [comment]
了解了。感谢回复！！！

**Comment by 11yiyang** [comment]
@hiroi-sora 多屏幕截图不正常解决办法。右键打开软件属性-兼容性-更改更高DPI设置-把替代更高DPI缩放行为选中，然后确定，重启软件即可

**Comment by hiroi-sora** [comment]
> 多屏幕截图不正常解决办法

嗯，感谢提醒。

我以前曾想到过这个解法，[代码里也写过自动禁用DPI缩放的功能](https://github.com/hiroi-sora/Umi-OCR/blob/release/1.3.3/ui/win_main.py#L58)，可以达到同样的效果。不过考虑了一下觉得还是有缺陷，比如4k屏+200%缩放下会让软件界面变得很小，不适合所有用户，于是最后就没有启用这个功能。后来我也忘了这回事。

不过现在想想，也不失为一种可选的解法，等下更新到Readme里。再次谢谢提醒~
