### ISSUE TITLE
【CPU不兼容】识别器初始化失败，PaddleOCR-json.exe报错0xc0000142

### ISSUE THREAD

**Issue by asdf3201** [hiroi-sora/Umi-OCR#11]
windows 10 64位系统，请帮忙看下。
![Capture](https://user-images.githubusercontent.com/27761975/188097721-cb9cfcd8-2330-4b15-958e-60a847afb0fd.PNG)
![2](https://user-images.githubusercontent.com/27761975/188097739-553e09e1-66e3-418f-8c44-2f6795b6edfc.PNG)
![3](https://user-images.githubusercontent.com/27761975/188097890-0062da06-281c-4dad-8dfd-1819c00358b7.PNG)

**Comment by hiroi-sora** [comment]
你好，可以提供一下CPU具体型号和Win10具体版本号吗？

0xc0000142可能是由于CPU不支持某些指令集、或Win10某些运行库版本不兼容导致，我排除一下问题。

查CPU型号：任务管理器 ⇒ 性能。
查Win10版本：Win+R ⇒ 输入`winver`。

**Comment by asdf3201** [comment]
数据见下图
![image](https://user-images.githubusercontent.com/27761975/188170024-d6371695-f686-4642-af03-9e8b73ce82fc.jpeg)

**Comment by hiroi-sora** [comment]
很好！大概知道问题所在了。

烦请再帮我一个忙，用 [CPU-Z](https://www.cpuid.com/downloads/cpu-z/cpu-z_2.02-cn.zip) 查看一下处理器参数，将首页截图给我，如下图

![imagefc1df8594e7e3ab8.png](https://tupian.li/images/2022/09/02/imagefc1df8594e7e3ab8.png)

**Comment by asdf3201** [comment]
请见下图

![image](https://user-images.githubusercontent.com/27761975/188188304-46137cbe-7fb1-4faf-bcde-be4afb6238e4.jpeg)

**Comment by hiroi-sora** [comment]
感谢你的测试！使我找到了这个项目最神秘的Bug的产生原因。

结论： `0xc0000142` 代码报错是由于CPU不支持AVX指令集引起。

![imagec0a3ba962da6ed46.png](https://tupian.li/images/2022/09/02/imagec0a3ba962da6ed46.png)

PaddleOCR-json识别引擎依赖的Opencv图像处理库，默认启用了AVX指令集加速。PaddleOCR C++ 本身也需要AVX支持。因此在CPU无avx的机器上，引擎无法加载dll完成初始化。

关于解决方案：

我在未来可能提供一个 no_avx 版本的软件以供这些cpu使用。遗憾的是Opencv和Paddle官方似乎未提供 no_avx 版动态库，我可能需要改写源码并编译它们；这对我来说是个未知的工程。所以，短时间内你确实是没办法使用本软件了

**Comment by asdf3201** [comment]
好的，这是台工控机，CPU比较冷门，还好家里另外一台电脑可以正常使用。
