### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by ye13533167453** [hiroi-sora/Umi-OCR#110]
![89a86003018bff586f79faccffb9b7b](https://user-images.githubusercontent.com/7224845/230515195-e2cb3e71-760c-483c-bf75-ef3060047edf.png)
python调用启动时，仅初始化只有100M左右，正常。
当ocr方法调用多次时，paddleOCR-json.exe进程的内存逐步飙到七百多M，而且，你停止调用ocr，内存并不会释放

**Comment by YuGuii** [comment]
是的，我也遇到了这个情况，调用次数多了以后内存占用直接上天。

**Comment by hiroi-sora** [comment]
内存占用高是PaddleOCR-json引擎的祖传问题，可以见[之前的issue](https://github.com/hiroi-sora/Umi-OCR/issues/92)。

作为应对措施，v1.3.3版本更新了内存清理功能，可以实现楼主说的“停止调用OCR一段时间后自动释放内存”的功能。或者设定内存上限，比如超过500MB就自动清理。使用方法[详见README](https://github.com/hiroi-sora/Umi-OCR#%E5%86%85%E5%AD%98%E6%B8%85%E7%90%86)。

**Comment by gsx008com** [comment]
采用 Umi-OCR_Paddle_v2.1.4.7z 版本，32G内存 每隔5s调用一次，数千次后，大概2h左右，也会导致内存耗尽，机器死机。按默认8G清理，配置了的，感觉没有限制住。

**Comment by gsx008com** [comment]
> 采用 Umi-OCR_Paddle_v2.1.4.7z 版本，32G内存 每隔5s调用一次，数千次后，大概2h左右，也会导致内存耗尽，机器死机。按默认8G清理，配置了的，感觉没有限制住。

准备试一下 Rapid版本了，不然只能重启机器，继续脚本了。
