### ISSUE TITLE
有的空格识别不出来，怎么解决？

### ISSUE THREAD

**Issue by nissansz** [hiroi-sora/Umi-OCR#113]
有的空格识别不出来，怎么解决？

**Comment by hiroi-sora** [comment]
建议下载并导入英文库来识别纯英文段落。默认的中英文通用识别库是存在空格丢失的问题。
[issue #100 ](https://github.com/hiroi-sora/Umi-OCR/issues/100)
[issue #42 ](https://github.com/hiroi-sora/Umi-OCR/issues/42#issuecomment-1297480599)

**Comment by jake0070** [comment]
截图识别后怎么显示快捷识图和时间戳，有办法不让它自动生成吗，只生成需要识别的内容
