### ISSUE TITLE
截图识别后所产生的问题

### ISSUE THREAD

**Issue by jake0070** [hiroi-sora/Umi-OCR#114]
截图识别后怎么显示快捷识图和时间戳，有办法不让它自动生成吗，只生成需要识别的内容

**Comment by hiroi-sora** [comment]
设置→快捷识图→勾选`自动清空面板`

![image](https://user-images.githubusercontent.com/56373419/230967232-d85b1f88-f7d8-4917-a19b-17d9261b802a.png)

**Comment by jake0070** [comment]
已解决，谢谢

**Comment by hiroi-sora** [comment]
> 按照操作已经解决不显示时间戳的问题了，但是无法实现多次识别内容合并了。只显示单次截图内容了

是的，设定上 多次识图产生的文字要通过时间戳来分隔，隐藏时间戳只能显示单次的文字。

如果你一定要提取多次识别的内容，有一个简便的办法：Umi-OCR设置中开启自动复制结果，连续多次截图OCR，然后按Win+V在剪贴板中浏览和粘贴这些文本。

**Comment by jake0070** [comment]
这样还是要进行多次查找和合并内容呀，不能通过修改源代码隐藏“快捷识图和时间戳”吗，有修改配置文件的方法也可以

**Comment by hiroi-sora** [comment]
> 通过修改源代码隐藏“快捷识图和时间戳”

可以的，[ocr/msn_quick.py 第42行](https://github.com/hiroi-sora/Umi-OCR/blob/release/1.3.3/ocr/msn_quick.py#L42) else后面的代码删掉即可。

**Comment by jake0070** [comment]
修改源代码后，如何获取修改后的软件包呢

**Comment by hiroi-sora** [comment]
> 修改源代码后，如何获取修改后的软件包呢

0. 确认修改后的代码跑起来没问题，确认Python已安装pyinstaller（`pip install pyinstaller`）。
1. 运行项目目录下的 `to_exe.py` 一键打包。
2. 打包后生成的exe文件是 `/dist/Umi-OCR 文字识别.exe` 。将引擎组件 PaddleOCR-json文件夹 拷贝到相同目录。

**Comment by jake0070** [comment]
to_exe.py需要修改其中的内容吗
运行项目目录下的 to_exe.py 后
系统提示下列错误
1240:0412/125403.563:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled

**Comment by hiroi-sora** [comment]
> 系统提示下列错误 Passthrough is not supported, GL is disabled

我以前未遇到过这样的错误。看起来是由OpenGL库（或别的GPU库）与GPU驱动的兼容性而引起。

当然，本项目的Python代码并未使用OpenGL或其它与调用GPU有关的库；这个报错大概率是pyinstaller乱塞东西引起。如果你的Python环境中安装过OpenGL，则pyinstaller有一点概率把这个未使用的库也打包进来。

比较简单的处理办法（不一定管用）：指定pyinstaller排除OpenGL（或别的GPU库）。将to_exe.py最后一行的指令修改成：
`pyinstaller --exclude-module OpenGL -F -w -i icon/icon.ico -n "Umi-OCR 文字识别" main.py`
（用--exclude-module来排除不需要的库。）

一劳永逸的处理办法：新建一个Python虚拟环境，仅安装与本项目有关的库，在虚拟环境中打包。

**Comment by jake0070** [comment]
运行主程序main.py没问题，可以打开软件操作页面，也能使用修改后的新功能，即多次截图识别也不自动生成时间戳，可以合并多项内容
但运行生成后的exe文件，系统提示下列错误
Unhandled exception in script
Failed to execute script 'main' due to unhandled exception: No module named 'PlL'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from ui.win_main import MainWin
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "ui\win_main.py", line 10, in <module>
    from ui.win_screenshot import ScreenshotCopy  # 截屏
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "ui\win_screenshot.py", line 6, in <module>
    from ui.win_show_image import ShowImage  # 显示图片窗口
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "ui\win_show_image.py", line 8, in <module>
    from PIL import Image, ImageTk
ModuleNotFoundError: No module named 'PIL'

**Comment by hiroi-sora** [comment]
> ModuleNotFoundError: No module named 'PIL'

“PIL库是需要的，但是未正确打包。”

所以还是用虚拟环境的坑更少。

我这边帮你打包了一份，懒得折腾就用这个吧：
https://hiroi-sora.lanzoul.com/i5JuQ0sseqob

**Comment by jake0070** [comment]
已使用楼主提供的软件包，这个问题已经得到圆满解决。还有一个瑕疵再这里也提一下。就是每次打开软件首次截图识别都会报错，再次截图就能识别
识别失败，错误码：212
错误信息：Clipboard format is not valid.。

**Comment by hiroi-sora** [comment]
> 每次打开软件首次截图识别都会报错212，Clipboard format is not valid.

这个问题也比较棘手，我这边无法复现。看起来似乎是Python模块截完图后未将位图写入剪贴板，导致C++引擎模块读不到东西。

试下：出现这个问题时，Win+V打开剪贴板历史记录，里面的第一项是什么东西？截个图我看看

**Comment by jake0070** [comment]
显示无法启动引擎
![image](https://user-images.githubusercontent.com/102018356/231640474-abb08649-604f-4b8d-9cd5-e8eeff05f07d.png)

**Comment by hiroi-sora** [comment]
也就是你遇到了两种错误对嘛？

> 错误码：212 错误信息：Clipboard format is not valid.

这种情况是引擎已启动，但是未能正确识图。

> 任务失败：无法启动引擎

这种情况是引擎未能启动，与 [issue #97](https://github.com/hiroi-sora/Umi-OCR/issues/97) 类似。

**Comment by jake0070** [comment]
是的，就重启首次截图有点小瑕疵。其他的都正常

**Comment by hiroi-sora** [comment]
关于第二种情况`无法启动引擎`，我的猜测是由于硬件配置等原因，引擎启动较慢，所以上层模块未等到启动完毕就触发了超时，误认为引擎无法启动。

下面这个版本，我把超时判定从5秒延长到30秒，试下还会不会出现第二种情况。
https://hiroi-sora.lanzoul.com/i43BQ0svdmxi

**Comment by jake0070** [comment]
链接怎么打不开

**Comment by hiroi-sora** [comment]
链接，我这边好像没问题呀
![image](https://user-images.githubusercontent.com/56373419/231703608-436c64a2-4484-4470-a544-030ebacc4ccb.png)

或者试试这个总链接进去，下载最新的 v1.3.3.A1 版
https://hiroi-sora.lanzoul.com/s/umi-ocr-test

**Comment by jake0070** [comment]
可以下载了，需要关闭网络代理才能打开链接。测试软件后，已经解决这个小瑕疵
这里问一下楼主，什么时候能让软件支持识别PDF文件，感觉这方面也很值得开发
