### ISSUE TITLE
作者大大，请问代码这一块是如何实现的呢？

### ISSUE THREAD

**Issue by BlueBloodFire** [hiroi-sora/Umi-OCR#116]
请问读取图片和输入文件对应的是代码的哪一个功能？找了好久都找不到QAQ
![image](https://user-images.githubusercontent.com/99856344/231090855-d4a5cafd-970e-4a5c-821c-9e7e913ef60b.png)

**Comment by hiroi-sora** [comment]
教你怎么找：

1. 首先这按钮对应的标签是“浏览文件”，那么在代码编辑器里全局搜索这四个字符，很容易能找到 `win_main.py` 的第163行左右存在一个语句：`self.balloon.bind(btn, '浏览文件')` 。
2. 阅读这行语句的上下文，很容易能在上面一行发现定义这枚按钮的语句：
```python
    btn = ttk.Button(fr1, image=Asset.getImgTK('openfile24'),  # 打开文件按钮
        command=self.openFileWin,
        style='icon.TButton',  takefocus=0,)
```
3. 其中 `command=self.openFileWin` 表明这枚按钮绑定了一个名叫 `openFileWin` 的方法。那么继续用ctrl+f或者用编辑器的跳转功能，能发现同一个文件的第910行定义了这个方法。这就是点击按钮后 打开文件选择窗口的代码了。
4. 阅读这个方法的上下文，可以看到 `draggedImages` 、`addImagesList` 这些都是与载入文件有关的方法，需要配合使用。

**Comment by BlueBloodFire** [comment]
收到了，非常感谢！！！









在 2023-04-11 18:10:19，"hiroi-sora" ***@***.***> 写道：

教你怎么找：

首先这按钮对应的标签是“浏览文件”，那么在代码编辑器里全局搜索这四个字符，很容易能找到 win_main.py 的第163行左右存在一个语句：self.balloon.bind(btn, '浏览文件') 。
阅读这行语句的上下文，很容易能在上面一行发现定义这枚按钮的语句：
btn=ttk.Button(fr1, image=Asset.getImgTK('openfile24'),  # 打开文件按钮command=self.openFileWin,
        style='icon.TButton',  takefocus=0,)
其中 command=self.openFileWin 表明这枚按钮绑定了一个名叫 openFileWin 的方法。那么继续用ctrl+f或者用编辑器的跳转功能，能发现同一个文件的第910行定义了这个方法。这就是点击按钮后 打开文件选择窗口的代码了。
阅读这个方法的上下文，可以看到 draggedImages 、addImagesList 这些都是与载入文件有关的方法，需要配合使用。
