### ISSUE TITLE
文本是从右向左该怎么设置参数呢？

### ISSUE THREAD

**Issue by baixiang-main** [hiroi-sora/Umi-OCR#12]
繁体竖排虽然可以正确识别，但似乎还是从左向右输出，有没有参数设置可以让输出从右向左呢？

**Comment by hiroi-sora** [comment]
感谢你的提议，目前还没有这个功能。更佳的排版方式及自定义排版方向将在以后推出。

如果你急用，且你的识图结果是准确的从左向右。那么可以fork本仓库，在 `release/1.2.6`  `main.py` 的第772行（即 analyzeText() 函数中）加一句：
`oget = reversed(oget)`

这将使所有文段逆序输出，即从右向左。

**Comment by hiroi-sora** [comment]
`v1.3.0` 已更新 实用的竖排文本后处理。支持识别从左向右 / 从右向左的竖排文本，严格按顺序输出。
