### ISSUE TITLE
作者大大，请问这一块要怎么实现呀？

### ISSUE THREAD

**Issue by BlueBloodFire** [hiroi-sora/Umi-OCR#123]
我发现该程序能识别文件夹下的所有图片，但有个问题是它会把文件夹下所有的图片全部同一合并，这样就导致子文件夹们的图片全混在一起了，(比如我有个文件夹，它有两个子文件夹，每个子文件夹都有图片，我希望能拖这个文件夹到程序里，然后程序能分别输出两个子文件夹的图片合并结果，不是混在一起的那种)，若要实现子文件夹的图片分别合并处理，请问代码需要修改哪些地方？

**Comment by hiroi-sora** [comment]
`ocr\output_txt.py` 中，每识别一张图片会调用它的 `img()` 方法。其中 `imgInfo` 字典存放了这张图片的原始路径。

如果你想将合并txt文件输出到每个图片所属的文件夹，可以改写 `ocr\output_txt.py` ，取消它在 `__init__()` 时确定输出路径，改成在 `img()` 中根据图片原始路径求出输出路径。你可以参考 `ocr\output_separate_txt.py` 中的代码。

当然，你还需要处理这些事务：如何在一次任务开始时删除旧的输出文件，以便追加写入到新的文件。如何在结束任务时打开输出文件或文件夹。如何确保开始时间和结束时间信息写入每一个单独的输出文件。等等。

**Comment by BlueBloodFire** [comment]
非常感谢，不过有个问题如您所说，如何在一次任务开始时删除旧的输出文件，以便追加写入到新的文件，这个问题我没有比较好的思路，能方便您说下吗？







在 2023-04-20 01:18:29，"hiroi-sora" ***@***.***> 写道：

ocr\output_txt.py 中，每识别一张图片会调用它的 img() 方法。其中 imgInfo 字典存放了这张图片的原始路径。

如果你想将合并txt文件输出到每个图片所属的文件夹，可以改写 ocr\output_txt.py ，取消它在 __init__() 时确定输出路径，改成在 img() 中根据图片原始路径求出输出路径。你可以参考 ocr\output_separate_txt.py 中的代码。

当然，你还需要处理这些事务：如何在一次任务开始时删除旧的输出文件，以便追加写入到新的文件。如何在结束任务时打开输出文件或文件夹。如何确保开始时间和结束时间信息写入每一个单独的输出文件。等等。

**Comment by hiroi-sora** [comment]
> 如何在一次任务开始时删除旧的输出文件，以便追加写入到新的文件

我有一个思路：

1. 初始化时不要记录单一的输出路径。而是建立一个输出路径列表，初始时列表为空。
2. 输出一张图片时，判断这张图片的目录是否在输出路径列表内：
3.1. 若不在：则计入输出路径列表。然后删除可能存在的旧文件，建立新文件，将**开始时间**和OCR内容输出在到新文件中。
3.2. 若在：则直接将OCR内容输出到新文件中 。
4. 任务完成后，遍历路径列表，将结束时间写入每一个输出文件。
5. 根据配置参数，选择打开这些文件或文件夹。

**Comment by BlueBloodFire** [comment]
了解了，感谢！
