### ISSUE TITLE
N张图片，都是识别部分区域，可以选择一张图片的忽略区域作为模板，列表中的自动引用区域吗？

### ISSUE THREAD

**Issue by alljill** [hiroi-sora/Umi-OCR#127]
请问列表中的同分辨率图片，都是识别局部区域的文字，在选项中保存的识别区域/忽略区域，无法保存应用到列表中的图片，希望增加此功能，谢谢！

**Comment by hiroi-sora** [comment]
忽略区域参数是会应用到列表中所有同分辨率图片的。

如果忽略区域未生效，可能需要注意这点：忽略区域判定比较严格，必须某段文字框（忽略区域设置窗口中的虚线框）完全处于单个判定框内，才会被识别。比如下面这张图，只有Wiki被成功判定，Security和Insights都未被判定。
![image](https://user-images.githubusercontent.com/56373419/233588183-4d594691-f376-4896-9875-2f48ab87cd13.png)

如果有必要，可以尽量拉大判定框的范围。
