### ISSUE TITLE
系统启用UTF-8支持时，含有中文等Unicode字符的图片路径读取错误

### ISSUE THREAD

**Issue by WHYBBE** [hiroi-sora/Umi-OCR#13]
正常ASCII字符文件名的图片可以正常识别

如果使用文件名中带有中文字符的图片会给出以下提示（带emoji表情的文件名也一样）

≦ 测试06123505.png ≧
识别失败，错误码：200
错误信息：Image path not exist. Path:"C:\****\����06123505.png"

并且无法直接拖入程序中

值得一提的是我打开了系统中的“区域-区域设置-Unicode UTF-8支持“，不知道是否和这个有关系

* 系统：Win 11 22H2 25193.1000
* CPU：AMD Ryzen 5 5600X

**Comment by hiroi-sora** [comment]
感谢详尽的反馈，这个Bug确实由系统区域的UTF-8支持引起。[已经修复](https://github.com/hiroi-sora/Umi-OCR/commit/c4b5e714affabbc88b7b257fc6236c03ab58f96e)。你可以使用最新源码，或者下载1.2.7 Alpha测试版：

https://wwn.lanzoul.com/b037embad
密码:1111

Umi-OCR只支持区域为cp936（中文-简体）或cp65001（任意区域，系统开启UTF-8支持）。不过，只有系统启用UTF-8支持时，才能正确读取含emoji等特殊符号的路径。

有问题请继续向我反馈。

**Comment by WHYBBE** [comment]
问题已解决，感谢！
