### ISSUE TITLE
无法启动引擎

### ISSUE THREAD

**Issue by chemhao** [hiroi-sora/Umi-OCR#130]
CPU指令集有AVX，系统是win7的，程序可以打开，但是选中图片后点开始任务会弹出对话框：
任务失败: 无法启动引擎:OCR init fail.
引擎路径: PaddleOCR-json/PaddleOCR_json.exe
启动参数 : -limit_type=max -limit_side_len=960
-cpu_threads=10 -enable_mkldnn=True
--config_path="PaddleOCR_json_config_ch.txt" --use_debug=0

**Comment by hiroi-sora** [comment]
抱歉，目前的版本暂不支持win7。

兼容win7的版本正在研究和开发中。

**Comment by hiroi-sora** [comment]
兼容win7的新版本已开始测试， [详见这里](https://github.com/hiroi-sora/Umi-OCR/tree/dev/rapid/1.3.4) 。
