### ISSUE TITLE
建议Releases里再增加一个包：Umi-OCR.v1.3.4_All_languages.7z

### ISSUE THREAD

**Issue by Jimmy20220531** [hiroi-sora/Umi-OCR#132]
把“多国语言扩展包”添加进去，这样更方便一些，对不？

**Comment by hiroi-sora** [comment]
有道理😂已添加√

以前依稀记得release单个文件只能上传100MB以内的，所以一直分开传。刚试了一下118MB似乎也没问题，哈哈。

**Comment by Jimmy20220531** [comment]
> 有道理😂已添加√
> 
> 以前依稀记得release单个文件只能上传100MB以内的，所以一直分开传。刚试了一下118MB似乎也没问题，哈哈。

如虎添翼！！！
