### ISSUE TITLE
识别是出错，截图或拖放图片，都出错，WIN10系统

### ISSUE THREAD

**Issue by kkjfb** [hiroi-sora/Umi-OCR#134]
![Snipaste_2023-05-03_14-46-49](https://user-images.githubusercontent.com/86990421/235848542-0745037a-50c7-4f01-9b29-51df65b0e02b.jpg)
![Snipaste_2023-05-03_14-47-02](https://user-images.githubusercontent.com/86990421/235848552-e98828df-8db3-4a3f-a217-f3eac4415b29.jpg)
![Snipaste_2023-05-03_14-47-40](https://user-images.githubusercontent.com/86990421/235848556-e8871a59-096e-41a1-9cf9-8c2068f74529.jpg)

**Comment by hiroi-sora** [comment]
你好，0xc0000142大概率是由CPU不支持AVX指令集引起的兼容性问题。请尝试一下 [Rapid引擎版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.4-rapid-alpha) ，它应该不依赖于AVX。

**Comment by kkjfb** [comment]
> 你好，0xc0000142大概率是由CPU不支持AVX指令集引起的兼容性问题。请尝试一下 [Rapid引擎版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.4-rapid-alpha) ，它应该不依赖于AVX。

确实可以了，功能是一样的吗？

**Comment by hiroi-sora** [comment]
> 功能是一样的吗

除了暂时不支持导入多国语言之外，其他功能跟常规版是完全一样的。
