### ISSUE TITLE
请问一下，打包好的exe在windows运行报错 Cannot open Pyinstaller…

### ISSUE THREAD

**Issue by alexya** [hiroi-sora/Umi-OCR#135]
请问一下，打包好的exe在windows运行报错

[492] Cannot open PyInstaller archive from executable <D:XXX.exe>or external archive <D:XXX.pkg>

是什么原因呢

**Comment by alexya** [comment]
我需要安装Python2.x 或者 3.x 么？

**Comment by hiroi-sora** [comment]
你好。这个报错是启动器未找到某些模块，可能由打包错误引起。

1. 是使用本项目的 to_exe.py 脚本进行打包么？
2. 打包过程中有无报错或警告信息？
3. 重新打包一次试试？
4. python版本建议3.8或以上。但 main.py 能运行起来的话，打包一般不会出现问题。
5. 是否同时安装了多个python版本，如同时装了3.8和3.10？如果是，可能调试和打包时的解释器版本号及模块不一致导致此错误。
6. 你的python环境是否重复安装/卸载过一些模块，如win32api？python环境异常也可能引发此错误，调试正常但打包后异常。

如果符合上述5或6，建议在python虚拟环境中重新安装模块并打包。

**Comment by alexya** [comment]
@hiroi-sora 我没有自己打包，我是直接下载released的7zip，解压使用的。
首先，我在我自己的电脑上解压能正常使用。
然后，我把整个文件夹拷贝到u盘，我老婆带到公司去，再拷贝到她公司的机器上，就不能使用了。报错如上。（她是电脑小白）

**Comment by hiroi-sora** [comment]
那确实有点奇怪，我自己也经常在不同机器上拷贝移动这个软件，没有遇到类似的问题。

或许你将整个压缩包拷到目标电脑再解压试试？

**Comment by alexya** [comment]
关键是，官方下载包是7zip压缩的，一般的电脑只能解压zip. 普通办公电脑没有安装7zip
而且，他们公司电脑，好像都是没有权限安装新软件的
抓头……

**Comment by hiroi-sora** [comment]
zip压缩包（不要挂梯访问）

https://hiroi-sora.lanzoul.com/iPVGU0uq8ntc

**Comment by alexya** [comment]
谢谢，我试试
