### ISSUE TITLE
截图区域优化

### ISSUE THREAD

**Issue by Suz1e** [hiroi-sora/Umi-OCR#136]
可以设置截图识别的区域吗？设置固定区域，按下快捷键开始识别，或者一直识别等待出现文字的时候才识别成功。
![QQ截图20230507183541](https://user-images.githubusercontent.com/52779408/236672473-b87b0797-576c-4bf2-982c-6dad8b9c913b.png)
现在每次都需要重新选择识别的区域，稍微有点麻烦

**Comment by hiroi-sora** [comment]
建议收到，下个大版本将会考虑。

**Comment by Suz1e** [comment]
好的 感谢 期待新版本🤩最好是可以只识别文字/字母之类的，然后设置固定区域持续运行，等待文字/字母出现的时候就自动识别，不要识别物体，比如背景是花的图片，现在会直接把物品是什么东西识别出来

**Comment by hiroi-sora** [comment]
谢谢支持~  如果你有急需，可以试试隔壁的 [团子翻译机](https://github.com/PantsuDango/Dango-Translator) ，它是这个领域中的一个优秀项目。我到时候也会参考和学习这个项目👍

**Comment by AndyDavis8** [comment]
固定区域的识别，延伸开来，就可以用于批量证照（固定格式）的识别。   识别区域保存为模板，就是支持多格式证照的识别工具。 😊

**Comment by Faith-Mian** [comment]
> 好的 感谢 期待新版本🤩最好是可以只识别文字/字母之类的，然后设置固定区域持续运行，等待文字/字母出现的时候就自动识别，不要识别物体，比如背景是花的图片，现在会直接把物品是什么东西识别出来

pandaocr 有固定区域识别，没有持续等待，不过鼠标移动到左上角即ocr也不错
