### ISSUE TITLE
多行合并问题 中文加数字或者中文加英文

### ISSUE THREAD

**Issue by w1330200236** [hiroi-sora/Umi-OCR#137]
大佬晚上好软件体验非常好 但遇到一个问题 就是识别内容不能合并到一行 在设置里设置了多行合并也不行 . 不知道是否可以解决这个问题  或者能优化合并.同是中文的话可以合并到一段  但有数字或者英文的情况下就不行了
![f8e63c4ea9278896b4cffba22a4c852](https://user-images.githubusercontent.com/132820624/236674611-afe125d9-285b-42c1-adbf-5c5c6e690b4c.png)

**Comment by hiroi-sora** [comment]
你好，单行合并是有一个阈值，当同一水平线上的两组文本框”挨得非常近“的时候将它们合并为一组。

在你的例子里，有可能两组文本框离得比较远，也可能由于数字和字母混杂导致行高不一致、所以程序判断不属于同一行。

如果你频繁遇到这个问题，并希望自己调整阈值的话也很简单。在 [ocr/tbpu/merge_line_h_m_left.py的__init__](https://github.com/hiroi-sora/Umi-OCR/blob/88dc20f83e00904d0a9ce8b09458b103b0c1b0aa/ocr/tbpu/merge_line_h_m_left.py#LL8C2-L8C2) 里，我们定义了如何判断合并两个水平文本框的阈值 `self.factorX` 、 `self.factorY` 。它对单行合并及多行合并均生效。你可以尝试改大这两个值，看看是否有改善效果。最后运行根目录的 `to_exe.py` 一键打包。
