### ISSUE TITLE
透明化背景的图片无法转换，可以复制粘贴板在软件粘贴测试

### ISSUE THREAD

**Issue by adobe3000** [hiroi-sora/Umi-OCR#138]
<a href="https://imgse.com/i/p9wlNiF"><img src="https://s1.ax1x.com/2023/05/08/p9wlNiF.png" alt="p9wlNiF.png" border="0" /></a>
https://s1.ax1x.com/2023/05/08/p9wlNiF.png
这种图片批量导入转换无法识别，PhotoFiltre Studio X新建一个空白像素的文件，勾选最下面的框自动透明度，可以生成透明背景的文字，可以点击软件上的T图标插入文字测试

**Comment by hiroi-sora** [comment]
> 屏幕截图和导入的识别不一样

主要因为原图是带Alpha通道的，OCR识别的时候会强制合并成RGB三通道，可能这个过程中背景被置成#000000，导致前景和背景的区分过小。再加上竖排文本框在目标检测这一步的置信度会比较低，很可能就被过滤了，导致识别不出文字。

优化的方法暂时没有头绪，得再想想……

**Comment by hiroi-sora** [comment]
另外我的测试结果是，透明背景下 横排文字不能检测纯黑，竖排基本不能检测出。Paddle和Rapid引擎的结效果差不多。

![image](https://user-images.githubusercontent.com/56373419/236720454-cc8aa99e-3612-471f-9409-997e441920a0.png)

**Comment by adobe3000** [comment]
# py代码批量生成汉字图片
from PIL import Image, ImageDraw, ImageFont
import os

# 设置字体文件、字号、颜色和图片大小
font = ImageFont.truetype('simfang.ttf', 23)
color = (0, 0, 0, 150) # 150 alpha
size = (25, 25) # 25x25 像素

# 创建存放图片的文件夹
if not os.path.exists("汉字"):
    os.mkdir("汉字")

# 遍历所有汉字生成20902个汉字的图片
for i in range(0x4E00, 0x9FA6):
    char = chr(i)
    # 创建alpha通道正方形图片
    img = Image.new('RGBA', size, color=(255, 255, 255, 0))
    draw = ImageDraw.Draw(img)
    # 计算文字宽度和高度，并居中绘制
    w, h = draw.textsize(char, font=font)
    draw.text(((size[0]-w)/2, (size[1]-h)/2), char, font=font, fill=color)
    # 保存图片
    img.save(f"汉字/{char}.png")

**Comment by adobe3000** [comment]
from PIL import Image
import os

# 需要安装Pillow才能运行
# pip install Pillow


file_names = sorted([f for f in os.listdir() if f.endswith('.png')])
images = [Image.open(f) for f in file_names]

widths, heights = zip(*(i.size for i in images))

total_height = sum(heights) + 5 * (len(images) - 1)
max_width = max(widths)

new_im = Image.new('RGBA', (max_width, total_height), (0, 0, 0, 0))

y_offset = 0
merged_file_names = []

for im, name in zip(images, file_names):
    new_im.paste(im, (0, y_offset))
    merged_file_names.append(name)
    y_offset += im.size[1] + 5

new_im.save('merged.png')

with open("merged_order.txt", "w") as f:
    for name in merged_file_names:
        f.write(name + "\n")

**Comment by adobe3000** [comment]
选择几个图片合成一个竖排的测试，输出文件名和识别的要对上

**Comment by adobe3000** [comment]
使用simsun.ttc字体，发现错误识别9179个

**Comment by adobe3000** [comment]
上面的代码是将一个个字体文件批量转换的，
使用simsun.ttc字体，发现错误识别9179个

**Comment by adobe3000** [comment]
import os
import re

# 读取txt文件中的所有png文件名
with open('[转文字]_汉字.txt', encoding='utf-8') as f:
    txt_png_files = set(re.findall(r'([\u4e00-\u9fa5]+\.png)', f.read()))

# 遍历文件夹中的所有png文件，对比查找
processed_files = set()
unprocessed_files = set()
for root, dirs, files in os.walk('.'):
    for filename in files:
        if filename.endswith('.png'):
            filepath = os.path.join(root, filename)
            if filename in txt_png_files:
                processed_files.add(filename)
                with open('已处理的图片文件名.txt', 'a', encoding='utf-8') as f:
                    f.write(f'{filename}\n')
            else:
                unprocessed_files.add(filename)
                with open('未处理的图片文件名.txt', 'a', encoding='utf-8') as f:
                    f.write(f'{filename}\n')

**Comment by adobe3000** [comment]
查找出8038个字体图片未识别

**Comment by hiroi-sora** [comment]
如果测试集是2w个汉字，查出几千个无法识别，是正常的😂因为OCR的字典里（即能识别的字符）只有6623个常用文字。
