### ISSUE TITLE
内存占用严重

### ISSUE THREAD

**Issue by yeyt97** [hiroi-sora/Umi-OCR#139]
每执行一次ocr，PaddleOCR_json.exe进程就增加几百兆的内存，这看着好不正常啊

**Comment by hiroi-sora** [comment]
RaddleOCR的传统艺能了，主仓库那边几年前就有人提过issue，一直没法完全解决😂其实内存主要是给mkldnn这个CPU加速库吃掉的，关掉mkl就正常了，可惜性能会损失太多。

如果想降低内存占用的同时保持不太低的速度，可以试试咱 [Umi-OCR.Rapid](https://github.com/hiroi-sora/Umi-OCR/tree/dev/rapid/1.3.4) ，Rapid引擎在占用和性能之间有一个较好的平衡。

**Comment by yeyt97** [comment]
好的谢谢我去试试

**Comment by wizardforcel** [comment]
ai模型需要一次性加载到内存，这很正常。
