### ISSUE TITLE
托盘及快捷键

### ISSUE THREAD

**Issue by walklty** [hiroi-sora/Umi-OCR#14]
首先谢谢。
能否加入最小化到托盘的功能呢，这样我就能让他常驻了。
另外，我通过一些自动化的工具（比如Quicker）尝试操作快捷键的时候，Umi没有反应，必须我按键盘出来的才行。这个有办法调整吗？
再次感谢。

**Comment by hiroi-sora** [comment]
> 能否加入最小化到托盘的功能

OK，下版本考虑加入


> 通过一些自动化的工具（比如Quicker）尝试操作快捷键的时候，Umi没有反应，必须我按键盘出来的才行

我用AHK测试了下，当设置识图快捷键为Ctrl+Shift+A时，使用以下AHK代码是可以正常调起OCR的：
```AutoHotKey
Send,^+A
```
或许你的快捷键含非常规功能键 / Quicker发送的功能键键值不同，导致Umi没能接收到？

如果确实不行，我有个曲线救国的方法：将上述ahk脚本代码改为你的组合键，保存为.ahk文件或打包成.exe，让Quicker执行任务时直接打开运行该脚本，用脚本来间接发送按键指令。ahk的运行速度很快，十几毫秒，不会耽误你太多时间。

**Comment by walklty** [comment]
AHK可以，谢谢。
自动化的使用场景是这样的：启动Umi，截图，通过快捷键把剪贴板内的图片送到Umi，等待Umi弹出txt窗口，关闭umi.
如果Umi能常驻托盘，我就能把第一步和最后一步省掉了。

Quicker中的描述是使用C#语言的SendKeys.send()语法。
您方便就看看，不行就算了。
