### ISSUE TITLE
识别快捷键设置成f4，如果按下 alt + f4 快捷关闭窗口，那么会触发识别，不应该触发才对

### ISSUE THREAD

**Issue by fffandpiao** [hiroi-sora/Umi-OCR#140]
![image](https://user-images.githubusercontent.com/59195257/236727589-86532cd4-f955-4cc9-a8d3-4e91937e0e60.png)

**Comment by hiroi-sora** [comment]
1. 软件设置拉到最下面，勾选”高级选项“，然后重启软件。
2. 软件设置”快捷识图“里会多出一项”组合键判断“，改成”严格“即可。

![image](https://user-images.githubusercontent.com/56373419/236740674-45a24190-27a5-473d-956f-48b34a91d7c7.png)

**Comment by fffandpiao** [comment]
嗦噶，可以了
