### ISSUE TITLE
设置 - 输出面板字体 drop down menu 用滚轮滚会导致后面的主菜单也被滚动

### ISSUE THREAD

**Issue by fireattack** [hiroi-sora/Umi-OCR#143]
如题，其他下拉菜单也有这个问题，只不过这个最明显

**Comment by hiroi-sora** [comment]
哈哈哈哈哈，一年了，终于有人发现这个了🤣乐

容我解释一下：tkinter框架原生并没有”滚动区域“这种组件，所以设置页的滚动窗口是我用画布+事件监听机制手搓出来的。由于一些限制，我无法仅在滚动区域监听鼠标滚轮事件，不得不在整个app范围内接收滚轮事件，导致在程序任何界面上使用滚轮都会触发设置页的滚动。

除此外tkinter还有一些缺陷，比如高分屏适配欠佳等。所以我正在开发的v2.0新版，将换用Qt QML框架来搭建UI，使用体验会更加好。

**Comment by wx00** [comment]
刚刚也遇到这个问题了，就想着上来看看有没有人提过，果然有（
另外一点是输出面板字体的宽度比较小时会直接看不到完整的字体名称，如果有悬停提示就好了

**Comment by hiroi-sora** [comment]
[v2](https://github.com/hiroi-sora/Umi-OCR_v2) 重构UI界面，已解决此问题。
