### ISSUE TITLE
【预告】V2.0版本 | 前景展望 | 意见收集 | 功能投票

### ISSUE THREAD

**Issue by hiroi-sora** [hiroi-sora/Umi-OCR#146]
大家好~  这里是Umi-OCR的开发者hiroi-sora。

Umi-OCR诞生了一年有余，从v1.0到v1.3.4更新了17个版本。在各位用户的建议下，Umi不断成长，规模已经远超项目初创时我的预期。

受限于初期采用的技术框架和一些历史遗留问题，v1.x的更新工作已经遇到了不少瓶颈。于是，我决定启动v2.0版本计划；几乎所有旧代码都会被推翻重构。我会选用更现代的框架和更精巧的代码，为大家带来焕然一新的美观界面，和丰富且可拓展的功能。

当前v2的大部分开发工作已完成，可前往这里体验预览版本：
### https://github.com/hiroi-sora/Umi-OCR_v2

这是预期效果：

![i18n](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/472e7607-920d-4c73-8933-43451fb7ad91)
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/49fa52ef-4d4b-45ba-8c8c-0022edb3ebb2)

## 按照设计目标，预计V2将具有以下特性：
- 技术框架采用 python3.8 + [定制版PyStand](https://github.com/hiroi-sora/PyStand-Sora) + 定制版PySide2（Qt5） + QML 。
- 运行环境采用使用嵌入式Python包（PyStand）+手动裁切模块的模式，比V1的pyinstaller自动打包的启动速度快一倍。
- 主界面框架，从V1的选项卡模式，升级为标签页模式。每个功能（如截图OCR、批量OCR、PDF识别等）是一个单独的标签页。你可以把最常用的功能保留在标签栏便于切换，不常用的则无需占用标签栏的空间。标签栏可以锁定，以防止日常误触。
- 全面适配高分屏，不会再出现V1的模糊问题。（[#33](https://github.com/hiroi-sora/Umi-OCR/issues/33), [#48](https://github.com/hiroi-sora/Umi-OCR/issues/48)）
- 更美观的界面设计，采用扁平化+圆角的设计元素，同时添加适量的动画效果，让软件体验更舒畅。也会为低配置用户提供关闭动画的选项。
- 小白友好度：无需任何调配，下载解压即可使用，常用界面简洁易懂。
- 高手友好度：也可以深度调配，在高级设置面板中修改各种属性。可以在发行包中修改代码来调整功能，支持自定义插件和皮肤。
- 支持换肤，可切换UI配色和样式，支持深/浅色主题。
- 支持国际化，可切换UI语言。（[#89](https://github.com/hiroi-sora/Umi-OCR/issues/89)）
- 低耦合，模块化，支持添加和移除各种功能模块。可能还会提供插件系统，用户可以热添加自定义插件。
- 以顺序队列的方式支持任务伪并发，为局域网服务器模式做准备。
- 与C++引擎的通信机制，由V1的管道改为套接字，以求更好的兼容性。
- 跨平台友好。虽然我可能没有能力和精力去做Linux和Mac的适配，但是在V2的设计中，我会尽力用跨平台的方式去开发，绑定平台的功能也会分离成单独模块以方便移植，让有能力的开发者可以更轻松地进行移植工作。（[#8](https://github.com/hiroi-sora/Umi-OCR/issues/8), [#34](https://github.com/hiroi-sora/Umi-OCR/issues/34), [#73](https://github.com/hiroi-sora/Umi-OCR/issues/73)）

![设计框架](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/008396ed-2299-4f9c-a2f2-c9ed5dd918e6)
按照我的设计理念，Umi-OCR V2 将是一个“OCR Hub”，是一种中枢，能够整合上游的离线引擎、在线接口、翻译机等不同模块，为下游的截图识别、批量识别等不同功能页面提供服务。开发者可以方便的拓展上游模块来为下游提供更高效的服务，也可以方便的拓展下游页面来为用户提供更多样的使用手段。

## V2版开发的优先级

由于人的能力是有限的，V2的开发工作将分为“三步走”策略。

> 高优先级：指V2初版就会搭载的基础、核心功能。中优先级：指V2必定会搭载的功能，设计之初就预留好了接口，但可能不会在初版就推出。低优先级：它们目前可能存在一些技术困难或者得失取舍，将在V2正式版日后的维护工作中慢慢添加。也会为它预留好接口。

（列表中☑︎表示已开发完成。可能更新不及时）

#### 高优先级

- [x] 基于CPU的离线OCR模块。
- [x] V1的两大基础功能：快捷截图识别、批量识别。
- [x] 可切换皮肤主题。
- [x] 系统最低兼容至Win7 x64。
- [x] 命令行模式。

#### 中优先级

- [x] 可切换界面显示语言。
- [ ] 忽略区域。
- [ ] 在线翻译，或者与第三方翻译工具的联动。（[#81](https://github.com/hiroi-sora/Umi-OCR/issues/81), [#108](https://github.com/hiroi-sora/Umi-OCR/issues/108), [#131](https://github.com/hiroi-sora/Umi-OCR/issues/131), [#141](https://github.com/hiroi-sora/Umi-OCR/issues/141)）
- [ ] PDF识别。（[#52](https://github.com/hiroi-sora/Umi-OCR/issues/52), [#79](https://github.com/hiroi-sora/Umi-OCR/issues/79), [#114](https://github.com/hiroi-sora/Umi-OCR/issues/114#issuecomment-1506716926), [#121](https://github.com/hiroi-sora/Umi-OCR/issues/121), [#142](https://github.com/hiroi-sora/Umi-OCR/issues/142)）
- [ ] 高级截图（仿Snipaste，支持贴图）。（[#115](https://github.com/hiroi-sora/Umi-OCR/issues/115)）
- [ ] 二维码识别。（[#95](https://github.com/hiroi-sora/Umi-OCR/issues/95)）
- [ ] 基于GPU的离线OCR。
- [ ] 识别正常图片，输出为Excel。
- [ ] 根据Windows的深/浅模式，自动切换主题。
- [ ] 历史记录系统。

#### 低优先级

- [ ] 插件系统。
- [ ] 离线翻译。
- [ ] 固定区域识别。（[#136](https://github.com/hiroi-sora/Umi-OCR/issues/136)）
- [ ] 识别表格图片，输出为Excel。（[#65](https://github.com/hiroi-sora/Umi-OCR/issues/65), [#101](https://github.com/hiroi-sora/Umi-OCR/issues/101)）
- [ ] 服务器模式：本地的Umi-OCR打开网络端口，局域网内其他设备可以访问并提交图片进行识别。（[#51](https://github.com/hiroi-sora/Umi-OCR/issues/51)）
- [ ] 兼容32位系统。（[#133](https://github.com/hiroi-sora/Umi-OCR/issues/133#issuecomment-1541378365)）

## 叠Buff

由于任务的复杂性，及个人时间精力有限，V2具体推出的时间将不确定，可能需要 **数月之久** 。甚至，面临无法预料的变故时，也存在搁置V2开发计划的可能性。

当然，我热爱Umi-OCR这个项目。会尽力保证不弃坑滴~

开发进度放在新仓库： [Umi-OCR_v2](https://github.com/hiroi-sora/Umi-OCR_v2) 。 **新仓库仅作为V2开发前中期的记录使用** ，后期会弃用，并将新版本代码合并回当前主仓库。

V2开发期间，V1将继续维护，但是会减少大型新功能的推出。

## 关于免费

Umi-OCR 是我个人兴趣开发的项目。按照我目前的想法，在可预见的未来里，Umi-OCR承诺 **不以任何手段盈利** 。包括提供免费下载、不含任何广告、没有需要付费的“高级功能”、无需注册账号、无需关注公众号。所有代码100%开源。短期内，我也不会开设打赏渠道。你的⭐️就是对我的鼓励。

## 关于协作

V2版将有一批功能期待你的参与。比如，国际化适配功能需要译者的协作。UI设计师可以为本项目设计皮肤。程序员用户可以为本项目设计插件。

为了方便协作者，我将会开发一系列的配套工具；比如不会编程的译者也可以用工具提取文本开展翻译工作。

具体的协作细则将在V2开发中后期公布。

## 你的建议

如果你有任何关于V2的建议，欢迎在本issue下提出，或者在 [讨论区](https://github.com/hiroi-sora/Umi-OCR/discussions) 发表新帖。如果多人有同样的提议，很可能改变我的任务优先级，将你的需求视为高优先级任务。

**Comment by hiroi-sora** [comment]
下面是一些问题，希望听取一下大家的看法。你可以点击下方的表情【👍️、🚀、👀、🎉】来给这个问题投票。  
1、你期待V2版本吗？（此题统计人数用）  
【拇指👍️】期待。

**Comment by hiroi-sora** [comment]
2、你的系统是？  
【拇指👍️】Win10/11 x64。  
【眼睛👀】Win7 x64。  
【火箭🚀】Win7 x86（32位）。  
【彩带🎉】macOS或Linux。

**Comment by hiroi-sora** [comment]
3、你的电脑配置是？  
【拇指👍️】较老旧的机器（如8代intel以前）。  
【彩带🎉】较新的机器，但没有独立显卡。  
【火箭🚀】有英伟达Nvdia独立显卡。  
【眼睛👀】有AMD独立显卡。

**Comment by hiroi-sora** [comment]
4、你喜欢自动更新吗？  
【拇指👍️】我喜欢后台自动下载、自动安装的更新服务。  
【彩带🎉】我希望有新版本时自动提醒我。  
【火箭🚀】我希望能手动检查更新。  
【眼睛👀】我不想要联网和检查更新服务。

**Comment by hiroi-sora** [comment]
5、你希望程序打包到什么程度？  
【拇指👍️】我喜欢单个exe可执行文件，尽管这样会难以安装插件和其他语言库。  
【彩带🎉】我认为资源文件（图标、ui文件等）可以打包起来以提高性能，同时支持自己导入插件和语言库。  
【火箭🚀】我希望所有的代码文件（包括ui和逻辑）全部暴露，以便于随时修改或查看程序代码。

**Comment by hiroi-sora** [comment]
6、使用OCR时，除了简体中文和简短的英文，你还会用到的语言是？（多选）  
【拇指👍️】大篇幅英文段落。  
【彩带🎉】繁中。  
【火箭🚀】日文。  
【眼睛👀】其他语言。

**Comment by paul-yangmy** [comment]
顶！！！大佬太强了！！！

**Comment by Suz1e** [comment]
期待，虽然我的建议处于低级优先级/(ㄒoㄒ)/~~

**Comment by raoyi** [comment]
可不可以有文字定位信息，就是返回文字在图片中的坐标信息

**Comment by hiroi-sora** [comment]
> 返回文字在图片中的坐标信息

当前版本可以输出OCR结果的完整信息（含文本框的坐标），在设置里打开 `结果输出→原始信息.jsonl文件` 即可。然后你可以读取该文件，逐行解析json并提取位置信息。

至于精确到单个字符的坐标信息，Paddle引擎是不支持的。Rapid引擎可能支持，但我为了通用性就没有搞它。

**Comment by w1330200236** [comment]
支持大佬 小白不会改代码 希望越做越好 非常喜欢截图OCR功能

**Comment by hiroi-sora** [comment]
@IceYin0 哈哈，感谢支持啦😄

**Comment by zhaoyingchuang** [comment]
作者大大，能不能给这个软件添加这样一个功能：在右下角隐藏托盘的同时可以在后台运行。现在的情况是：显示系统托盘图标这一功能和窗口关闭最小化到托盘是绑定在一起的。我不喜欢在右下角任务栏显示任何图标，只让软件在后台运行就可以啦，这样就好像是系统只带的软件啦。很多第三方开源软件都可以隐藏托盘图标的情况下在电脑后台运行，例如zoomlt、spipaste等。还有一个建议就是希望您能将这款软件定位明确，只专注ocr本身，不要添加其他功能，例如截图，标注，贴图、在先翻译等，我只想要一个干干净净的ocr功能。上面所说只是个人的一些观点。最后感谢您给大家提供这么优秀开源免费的ocr软件，跪拜！

**Comment by hiroi-sora** [comment]
@zhaoyingchuang 感谢你的建议。

> 隐藏托盘图标

我感觉这样不太安全，系统自带软件另说，第三方软件的后台模式总得有个可以看见的入口，让我知道它还在跑着。既隐藏任务栏图标又隐藏托盘图标的话，我认为会不太方便。另外，万一用户在软件设置里取消了所有快捷键，又隐藏了可见入口，就无法用正常的手段唤起它了。

> 只专注ocr本身

这就是为什么V2主界面的核心设计思路是“标签页模式”了。像您这种只需要基础OCR功能的用户，完全可以只打开“截图OCR”的标签页，让主界面上只有这一个“干干净净的ocr功能”。其他功能既不会出现在你的视线里，也不会加载进内存，占用你的CPU。体验上跟纯粹的OCR软件是一毛一样的。至于需要其他功能的用户，比如需要PDF的，那就单独打开PDF标签页；需要翻译的，就打开翻译标签页……。各取所需，所有人的偏好都能得到满足。

**Comment by 1151971148** [comment]
老大你好，希望操作窗口能做一些无障碍相关支持。应为我是一个视障用户，目前的版本对于我们使用的读屏软件来说，操作还是会有些麻烦。窗口的控件几乎无法被读屏软件获取，我们也有一些朋友在使用这款框架，遇到了相同的问题。希望老大能够做一些相关优化，特别感谢。

**Comment by 89huanghaowei** [comment]
加油，蹲一手表格输出。王国之泪真好玩

**Comment by hiroi-sora** [comment]
@1151971148 

> 视障用户

感谢特殊群体的支持，祝愿你们越过越好。

我认为，如果你们是希望把OCR作为使用电脑的辅助手段，比如读取屏幕上面非文本格式的字段；那么与其让OCR软件支持读屏的查找机制，不如直接让OCR软件推出一个面向视障用户的特殊版本，比如说删减不必要的功能，着重于截图和鼠标划词和语音朗读功能，按键设置和使用方法上参考市面上常见的读屏软件，等等。

特殊版本与正常版本使用相同的内核和逻辑，理论上修改的工作量不会很大。在未来有时间和精力时，我可能会再考虑一下。

**Comment by 1151971148** [comment]
特别感谢老大的回复。其实我们现在主要使用离线ocr的场景是把图片形式的文本转换成文本格式。应为我们很多的教科书全部是pdf以及图片。
电脑操作的话，目前大部分读屏软件已经内置了屏幕识别的ocr。用来辅助操作基本够用，但是用来识别扫描的书本精度还是不太够。所以想着用ocr框架配合模型使用。@hiroi-sora @

**Comment by XiaoXiaoYanHe** [comment]
想要后台启动，快捷键截图识别并翻译，翻译内容窗口显示。
支持腾讯百度彩云等大厂的翻译接口，接口比较稳定，大概翻译文本用的流量少，给的免费额度都挺多。（不着急）
对照翻译。（不着急）

**Comment by qjqyp** [comment]
一方面深深的为作者的无私奉献感动，希望你能留个赞助方式，你为爱发电，用户也为爱发电，双向奔赴才能构建更美好的世界。
另一方面在研究工作中，很多时候有很多非常冷门的原版书，只能找到模糊的影印版，而且可能是多语言的，希望能在这方面有很好的支持

**Comment by 1974525360** [comment]
大佬 整一个服务器版本的

**Comment by qjwshz** [comment]
感谢作者创建这么好的惠人项目。目前用得是Umi-OCR.Rapid v1.3.4-alpha.1版本，支持win7，这是个利好。弱弱地咨询两点： V2版本会继续向下兼容 win7吗？  第二个，v2版本会增加对表格的识别支持么？     祝作者身体健康，万事顺心～～

**Comment by hiroi-sora** [comment]
@qjwshz 

1. V2仍会尽力兼容win7，预计离线文字识别等核心功能可以使用。部分附加功能可能无法使用本地版，只能用在线服务。
2. 表格识别已有计划，但不会最优先完成。

**Comment by 2-3-5-7** [comment]
第一个点，我觉得功能上包括命令行的设计，可以参考 [capture2text](https://sourceforge.net/projects/capture2text/)，capture2text 有一个 [Text Line OCR](https://capture2text.sourceforge.net/) 功能，可以不用选取区域，即指即译，词典论坛上 [有人](https://forum.freemdict.com/t/topic/7166) 又封装了一下给 GoldenDict 用

第二个功能上的点，就是模仿微信的 OCR，小众软件上也[有人](https://meta.appinn.net/t/topic/44693)写出类似的，就是让文字浮现在图片上

最后我和楼上的人也有同感，作者你一个人维护的话，首要应当是专注在提升 OCR 的质量上，而非周边附加功能，就像我说的词典软件已经有很多人做了，而准确易用的 OCR 却很少。我还是比较信奉 Unix 哲学 Write programs that do one thing and do it well. Write programs to work together.

当然不论怎样，都祝软件越做越好，让更多人受益，我也只是提出了自己的一点想法。😊

**Comment by sysdzw** [comment]
非常感谢作者大大的无私奉献，希望能安装到服务器上，然后可以开启http服务，这样网页可以调用它比如post一个图片给他返回文字信息。

**Comment by ysml** [comment]
能不能在给软件包时顺便把校验码附上，好确定自己是下载正确的软件包

**Comment by Eyion** [comment]
期待新作，期待表格识别。不知V2的第1个版本预计何时面世？

**Comment by Eyion** [comment]
> 

每个人应用场景不一样，于我而言，公式识别就基本用不上。

**Comment by hiroi-sora** [comment]
@Eyion 

> V2的第1个版本预计何时面世

时间是未知数。虽然开发工作到现在为止没有遇到过大的技术困难，正在逐步推进中。但工作量比较大，我个人的精力、业余时间有限，所以进展速度并不快。也许今年内能搞定初版吧。

**Comment by Doraemon0611** [comment]
希望新版本也会考虑其他程序将Umi-OCR以库文件的形式集成到其他城市中，这样对其他开发者来说真的是有很大帮助。

**Comment by Eyion** [comment]
字体识别和补全功能，方便添加进去吗？或者有无好推荐？

**Comment by clyop** [comment]
希望有post接口

**Comment by hiroi-sora** [comment]
预览版本发布：[dev/20230809](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20230809)

开发进度已完成大半，实现大部分基础功能，达到了预期的优化效果。

解决了一些V1祖传的问题，比如现在能完全兼容高分屏和多显示器了。

欢迎各位测试体验。

**Comment by JusticeRen** [comment]
感谢大佬。
其实我更喜欢V1的UI风格，可否支持切换UI风格？

**Comment by hiroi-sora** [comment]
@JusticeRen 
> 可否支持切换V1的UI风格

抱歉，V2的底层框架基于qt-qml，并不使用windows风格的组件库，而是自绘组件。所以很难切换为V1的windows风格。

V2在一定程度上支持自定义样式，可以自己创建皮肤包来调整界面的颜色等外观；但大幅度切换风格还是比较困难的。

**Comment by lili2092** [comment]
什么都不说了，已star

**Comment by ysml** [comment]
在给包的时候，能否加上校验码？如sha256

**Comment by hiroi-sora** [comment]
> 发布加上校验码

收到 √

**Comment by ReedinGod** [comment]
虽然处于低优先级，不过还是期待能出 Mac 版的。

**Comment by hiroi-sora** [comment]
新预览版本发布。除了`命令行模式`和`截图联动`外，V1现有的功能在V2预览版均已上线。

V2还提供了一批新功能：可预览的截图界面，更丰富精准的段落合并（支持还原代码缩进模式），软件GUI支持多国语言……

欢迎测试体验。

https://github.com/hiroi-sora/Umi-OCR_v2/releases

**Comment by LanRenLan** [comment]
之前有人提到公式识别，我目前用的是https://simpletex.cn/
不知道有没有办法继续提升识别精度，尤其是大量的英文文章，包括图片有一点倾斜角度或者不太清晰的情况下。
日语ocr的精度以前非常差，不过V2好很多了，谢谢大佬。原文都是从维基百科截图的
![image](https://github.com/hiroi-sora/Umi-OCR/assets/112599739/466a196d-4b54-4de3-b82c-91a8cbda6c7c)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/112599739/82970958-ef68-4a10-984b-303b06539294)

**Comment by hiroi-sora** [comment]
@iKun4real 

快捷键的问题也是v1祖传的问题了。python几个常见热键库都存在不稳定的问题，win32批量注册系统层级热键也不太方便。所以我是监听普通按键事件，在软件层级自己维护一条热键列表。

优点是通用，稳定，去年11月更新至今 没有爆出过恶性bug。缺点是默认优先级低，如果有高权限的软件**先拦截了按键事件**，那么Umi-OCR可能就捕获不到同一个按键。

就像你说的，`好像是snipaste没释放按键一样`，实际上是snipaste**拦截了按键抬起事件**，导致Umi认为该按键一直未释放。

（为了缓解这个问题，我设置了按键超时时间，如一个按键按下超过30秒则视为已释放。v1可以自定义设置超时时间，v2之后会开放修改接口。）

而要从根源上解决这个问题，就是给Umi高权限——即给管理员权限。

**Comment by hiroi-sora** [comment]
v2 基础开发告一段落，接下来是长期维护、迭代优化、逐步实现新功能的环节了。

此issue关闭，若大家有任何建议或报bug，请在本仓库或 [v2仓库](https://github.com/hiroi-sora/Umi-OCR_v2) 提新issue。

（过段时间，v2正式版的代码也会迁到此仓库进行维护。）

**Comment by hiroi-sora** [comment]
@2-3-5-7 

最新预览版已支持：模仿微信OCR，让文字浮现在图片上。

![](https://camo.githubusercontent.com/06d4bb9e4e31131364b92fbb9d3770065e363f7ff0c121ff246f51edd83cfa90/68747470733a2f2f74757069616e2e6c692f696d616765732f323032332f31302f31382f363532666561333062303935622e706e67)

**Comment by hiroi-sora** [comment]
@ysml 

数学公式识别已支持。

详见： https://github.com/hiroi-sora/Umi-OCR/issues/254

**Comment by aimarxjg** [comment]
希望主要功能都能做成按钮，记不住快捷键

**Comment by hiroi-sora** [comment]
@aimarxjg 请放心，所有快捷键都有对应按钮的，请在界面上找找。

**Comment by Doraemon0611** [comment]
![无标题](https://github.com/hiroi-sora/Umi-OCR/assets/132356061/b0a43298-6749-4cd5-aa27-7fabf2a56e48)
朋友您好，因为我设置它启动不显示主窗口，但是它图标还在托盘，可不可以在开启Umi-OCR的时候不让它的图标出现在托盘里啊！我想让它完全在后台中运行然后我就可以使用CMD命令来控制它了。

**Comment by longer008** [comment]
能不能在OCR识别后
![image](https://github.com/hiroi-sora/Umi-OCR/assets/37037470/0ac65fc1-6aeb-437f-a007-fd488db4c089)
把繁体字转成简体（不认识的繁体字还要到一些工具中查看）

**Comment by hiroi-sora** [comment]
> 能不能在OCR识别后把繁体字转成简体

该功能比较小众，暂时不会开发。

不过，未来我打算支持自定义的“文本后处理”模块，用户可以编写一些简单的python脚本插件，实现类似繁简转换的自定义功能。

**Comment by peade** [comment]
这个软件功能很强大。唯一希望是能够跨平台支持
