### ISSUE TITLE
大神你好，在第三方软件调用的时候，报错：未找到主程序[Umi-OCR文字识别.exe】。请将命令行入口放在主程序相同或子文件夹 中。

### ISSUE THREAD

**Issue by github2021929** [hiroi-sora/Umi-OCR#147]
版本1.3.4 环境win10

extra文件夹下有umiocr.exe，不行。
把umiocr.exe复制粘贴到根目录与Umi-OCR文字识别.exe肩并肩站着，也不行。

所用C#代码如下：

```csharp
/// <summary>
/// 使用第三方软件来进行图片识别。
/// https://github.com/hiroi-sora/Umi-OCR/releases
/// </summary>
/// <param name="imagePath">需要识别的图片文件路径</param>
/// <returns>返回识别结果</returns>
public static string PerformOCR(string imagePath)
{
    // 本地图片识别
    string ocrArguments = $"umiocr.exe -img= \"{imagePath}\" ";

    // 获取 OCR 应用程序的路径
    string ocrAppPath = @"dependencies\Umi-OCR - 多国语言整合版\extra\umiocr.exe";
    string fullAppPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ocrAppPath);
    // 创建进程启动信息
    ProcessStartInfo startInfo = new ProcessStartInfo
    {
        FileName = fullAppPath,
        Arguments = ocrArguments,
        RedirectStandardOutput = true,
        UseShellExecute = false,
        CreateNoWindow = true
    };

    // 启动外部 OCR 应用程序
    using (Process process = Process.Start(startInfo))
    {
        // 读取外部应用程序的输出
        string output = process.StandardOutput.ReadToEnd();
        // 等待外部应用程序完成
        process.WaitForExit();
        // 返回输出结果
        return output;
    }
}
```

![1](https://github.com/hiroi-sora/Umi-OCR/assets/91621412/730173bb-9609-4051-90f2-ecacea8349d7)
![2](https://github.com/hiroi-sora/Umi-OCR/assets/91621412/0589bdc4-01da-42ba-ac64-718ebd0bbfb0)
![3](https://github.com/hiroi-sora/Umi-OCR/assets/91621412/4be3e6d1-351b-4a27-83ce-096848f8bee0)

**Comment by hiroi-sora** [comment]
你好，这个问题是由于工作目录不正确。你这段代码，我似乎没有见到设置工作目录的部分，因此默认工作目录将是C#环境的路径，而不是umiocr.exe所在的目录，这会导致umiocr.exe无法搜索到主程序的位置。

要设置工作目录，可以用以下的代码：（我不熟悉C#，不确定是否正确。你可以改为从fullAppPath中提取目录）
 ```csharp
// 创建进程启动信息
ProcessStartInfo startInfo = new ProcessStartInfo
{
    FileName = fullAppPath,
    Arguments = ocrArguments,
    RedirectStandardOutput = true,
    UseShellExecute = false,
    CreateNoWindow = true,
    WorkingDirectory = "dependencies\Umi-OCR - 多国语言整合版\extra"  // 设置工作目录为umiocr.exe所在的目录
};
```

另外补充两点：

1. `读取外部应用程序的输出、等待外部应用程序完成、返回输出结果` 这是不必要的，因为umiocr.exe并没有返回值。你要获取OCR文字，可以让Umi-OCR自动输出到剪贴板，然后去剪贴板拿。如果需要让前端应用直接获得OCR信息，不如直接调用 [引擎组件](https://github.com/hiroi-sora/PaddleOCR-json) （反正你已经会用进程间通信了）。
2. 只有楼主这种用语言API来启动子进程的方式，才需要重设工作目录。如果是通过系统调用来启动进程（如`exec(C:\Umi-OCR\umiocr.exe -clipboard)`），则无需手动设置工作目录。
