### ISSUE TITLE
建议识别后导出Excel表格数据，并对应图片超链接，更加实用

### ISSUE THREAD

**Issue by csq4017** [hiroi-sora/Umi-OCR#148]
建议识别后导出Excel表格数据，表格数据第一列是图片名称，第二列识别图片的内容，第三列对应图片超链接，这样可以很快找到需要搜索的内容图片。

**Comment by hiroi-sora** [comment]
OK，已有计划

**Comment by csq4017** [comment]
邮件已经收到

**Comment by csq4017** [comment]
期待你的更新，还有就是要对批量提取的字段，如果可以自定义就好了。
 Copied to clipboard!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月27日(星期六) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hiroi-sora/Umi-OCR] 建议识别后导出Excel表格数据，并对应图片超链接，更加实用 (Issue #148)





 
OK，已有计划

**Comment by WhoIAmm** [comment]
期待大佬的更新

**Comment by hiroi-sora** [comment]
[V2预览版](https://github.com/hiroi-sora/Umi-OCR_v2/releases) 已支持输出csv格式，可导入excel。
第一列图片名称、第二列识别内容、第三列图片路径。

**Comment by csq4017** [comment]
邮件已经收到
