### ISSUE TITLE
使用多国语言扩展包后依旧无法更改识别语言，使用方法二添加语言选项但识别率低。

### ISSUE THREAD

**Issue by 3QMICO** [hiroi-sora/Umi-OCR#151]
问题：使用多国语言扩展包后依旧**无法更改识别语言**，使用方法二添加语言选项但是发现识别准度比较低。
举例：**日文的识别准度低**，且容易无法识别，尤其是在中国语料上识别两种语言组合使用的情况效率很低。
期盼：能否将繁体汉字和日文的文字模型整合起来提高文字模型识别率。

**Comment by hiroi-sora** [comment]
> 无法更改识别语言

多国语言扩展包需要把压缩包内的全部文件覆盖拷贝到软件目录下。你是不是只拷贝了模型库的子文件夹，没有拷贝压缩包内的配置文件config.json ？

> 提高文字模型识别率

以后会研究。
