### ISSUE TITLE
OCR init timeout :5s 

### ISSUE THREAD

**Issue by Asunaz** [hiroi-sora/Umi-OCR#154]
[https://imgse.com/i/pCVguUf](url)
<a href="https://imgse.com/i/pCVguUf"><img src="https://s1.ax1x.com/2023/06/11/pCVguUf.jpg" alt="pCVguUf.jpg" border="0" /></a>

**Comment by Asunaz** [comment]
AMD CPU

**Comment by hiroi-sora** [comment]
请尝试下这个：

[Umi-OCR 文字识别.zip](https://github.com/hiroi-sora/Umi-OCR/files/11714246/Umi-OCR.zip)

（用解压后的exe文件 替换你电脑上原有的软件exe）

**Comment by acrobatman** [comment]
> 方法一：
> 
> 请尝试下这个延长了超时判定时间的修复版本：[Umi-OCR 文字识别.zip](https://github.com/hiroi-sora/Umi-OCR/files/11714246/Umi-OCR.zip)
> 
> （下载并解压，将exe文件 覆盖粘贴到UmiOCR原本软件目录下）
> 
> 方法二：
> 
> 既然报了5s超时，说明Paddle引擎在您的硬件条件下压力比较大，加载速度比较慢。那么，更加轻量的 [Rapid引擎版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.4-rapid-alpha) 也许适合你的硬件。

![Snipaste_2023-06-16_15-46-57](https://github.com/hiroi-sora/Umi-OCR/assets/16357426/c15b00fb-b0ce-4594-8f70-c3ad63097a43)
这个延长超时时间的版本通过edge浏览器下载报病毒

**Comment by hiroi-sora** [comment]
@acrobatman 

我开代码摊的，能卖给你生病毒蛋子？

咳咳，开个玩笑😂肯定是浏览器误报啦。不放心的话，直接拉取本仓库的main分支自己打包也可以滴，main分支也已经修复了这个问题。

**Comment by acrobatman** [comment]
> @acrobatman
> 
> 我开代码摊的，能卖给你生病毒蛋子？
> 
> 咳咳，开个玩笑😂肯定是浏览器误报啦。不放心的话，直接拉取本仓库的main分支自己打包也可以滴，main分支也已经修复了这个问题。

谢啦，刚刚下载1.3.5版本了，没啥问题 👍
