### ISSUE TITLE
建议截图模块增加snipaste

### ISSUE THREAD

**Issue by Joker-jiajiahui** [hiroi-sora/Umi-OCR#155]
第一是软件自带的截图太模糊了，
第二是因为本来这个软件用的就很多，使用win+shift+s不习惯
还是按一下f1习惯，或者改成截图快捷键，就不要单独的截图模块了，直接快捷键调用自己平时用的截图软件就好了

**Comment by hiroi-sora** [comment]
可参考 https://github.com/hiroi-sora/Umi-OCR/issues/96#issuecomment-1455284373
 让Umi-OCR与snipaste联动。
