### ISSUE TITLE
无法启动引擎：OCR init timeout 5s. PaddleOCR-json/PaddleOCR-json.exe

### ISSUE THREAD

**Issue by cnzdq** [hiroi-sora/Umi-OCR#156]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/30411977/18c04dac-36dc-4666-a6c1-4ef691b55835)
用的是amazon的免费云服务器（1核1G），windows server 2022

是配置太差跑不起来吗

**Comment by hiroi-sora** [comment]
不一定是跑不起来。

引擎初始化需要几秒钟时间，一般家用机器在1~3秒内都能完成。所以我就设了5s的超时检测时间，超过5s还没完成初始化则判定失败。
但是，在你这种比家用机配置更低的机器上，可能需要比5s更长的时间完成初始化，所以意外报了超时错误。

解决方法见： https://github.com/hiroi-sora/Umi-OCR/issues/154

**Comment by VainAnts** [comment]
我早上打开软件,下午第一次截图识别使用也会报这个错误

![issuse](https://github.com/hiroi-sora/Umi-OCR/assets/9073302/4cd28822-63d1-45bd-a076-64feb4c05908)
