### ISSUE TITLE
不能适配高分变率的屏幕

### ISSUE THREAD

**Issue by david20718** [hiroi-sora/Umi-OCR#159]
不能适配高分变率的屏幕，使用的时候就自动变成低分辨率状态

**Comment by hiroi-sora** [comment]
[在做了在做了](https://github.com/hiroi-sora/Umi-OCR/issues/146)，V2版本将全面支持高分屏。

**Comment by hiroi-sora** [comment]
[v2版本](https://github.com/hiroi-sora/Umi-OCR_v2) 已全面适配高分屏。
