### ISSUE TITLE
可否命令行支持一下切换”识别语言“的命令

### ISSUE THREAD

**Issue by 2-3-5-7** [hiroi-sora/Umi-OCR#161]
每次都打开软件界面切换太麻烦了，如果命令行支持切换，就可以集成到我已有的 AHK 脚本里了。

我有时看别人的日文 twitter，有时是英文

感谢作者！

**Comment by hiroi-sora** [comment]
嗯，小意思，搞定了。

晚点发个小版本更新。

**Comment by qstdnx** [comment]
> 已发布更新。

你好我在最新版命令文档中没有找到切换识别语言的命令，我也需要脚本来切换识别语言，可否告知。
