### ISSUE TITLE
引擎运行出错

### ISSUE THREAD

**Issue by S091** [hiroi-sora/Umi-OCR#162]
![caaa5bd0b4ae27916cce3f9e8101118](https://github.com/hiroi-sora/Umi-OCR/assets/58965329/73ee9ca8-c2ae-427a-823a-247c037aba38)

**Comment by hiroi-sora** [comment]
是不是win7？是什么CPU？试试 [这个版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.4-rapid-alpha) ？

**Comment by S091** [comment]
> 是不是win7？ 是什么CPU？ 试试 [这个版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.4-rapid-alpha) ？

![image](https://github.com/hiroi-sora/Umi-OCR/assets/58965329/1906f51e-9b7e-4dac-8a03-bb15d50f19d1)
是不是不可以用？

**Comment by hiroi-sora** [comment]
嗯，你这颗U的指令集里没有`AVX`，所以用不了Paddle引擎所依赖的的数学加速库。

但是Rapid引擎依然可以用的，见我上面发的那个版本链接。

**Comment by S091** [comment]
> 嗯，你这颗U的指令集里没有，所以用不了Paddle引擎所依赖的的数学加速库。`AVX`
> 
> 但是Rapid引擎依然可以用的，见我上面发的那个版本链接。

谢谢指导

**Comment by S091** [comment]
> 嗯，你这颗U的指令集里没有`AVX`，所以用不了Paddle引擎所依赖的的数学加速库。
> 
> 但是Rapid引擎依然可以用的，见我上面发的那个版本链接。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/58965329/fb205c24-88b6-40b1-8be6-b085048dc40e)
重启后出现这个问题

**Comment by hiroi-sora** [comment]
@S091 

抱歉，`无法开启高级选项`是Rapid版Umi-OCR的一个bug，暂时未修复。

你可以删掉软件目录下的 `Umi-OCR_config.json` 来恢复初始设置，并暂时不要勾选 `高级选项` 。

**Comment by hiroi-sora** [comment]
请尝试 [v2版本](https://github.com/hiroi-sora/Umi-OCR_v2) ，已全面适配Rapid引擎。
