### ISSUE TITLE
关于特殊字符文件导入处理的不一致

### ISSUE THREAD

**Issue by Faith-Mian** [hiroi-sora/Umi-OCR#163]
1. 文件名包含🔥，文件拖入umi-ocr中无反应。
2. 文件夹中包含🔥的文件，文件夹拖入umi-ocr中正常显示所有文件，但执行识别时候这个文件会报错“识别失败，错误码：200 错误信息：Image path dose not exist.”
3. 不影响使用，欢迎忽略，纯属压力测试：）

**Comment by hiroi-sora** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/4370229a-7dcb-4344-bc3c-a8e7d8f78a11)

嗯，这是引擎组件的一个技术难题。C++读入图片依靠 Windows API 的 `_wfopen()`，在正常情况下无法识别“非标准字符”的utf-8编码，除非在 Windows 上开启`Unicode UTF-8 提供全球语言支持`这个选项。（并不建议开启，会给系统带来更多Bug。）

直接将含Emoji的文件拖入Umi-OCR时也一样，Python的拖拽API无法处理特殊utf-8字符。

目前暂时没有好的解决方法，而且像你说的相对不影响使用，所以先装作看不见😂
