### ISSUE TITLE
繁体竖版识别效果很不理想

### ISSUE THREAD

**Issue by wizardforcel** [hiroi-sora/Umi-OCR#164]
![显化之书_cropped_页面_008](https://github.com/hiroi-sora/Umi-OCR/assets/5080126/02919d16-d1d2-4a51-9299-ca0e13f99afe)

结果：

```

任务开始时间：2023-06-24 03:10:21


显化之书_cropped_页面_008.png

1
是你必須服從·否則便會受罰的死板要求·我熱愛這些原理·不想看到任何人把它們當成了另
種折磨白口的東西
而這正是發生在我的好友派特·黛維森身上的事，我把這本書獻給她·事實上·她是助動這
一切靈威的來源
大約三年前·派特被診斷患有肌菱縮性脊髓側索硬化痘入ALS）·這是一種泛步惡化的疾
病～譯註·亦被稱作葛雷克氏疽或漸凍人），它會使人喪失肌肉功能·最後全身癱漢·派特和她
的許多親友讀過不少吸引力法則的書·因此他們開始分析她如何一吸引到一這種疾病·她又是做
一行威北它品燕上身
我個人立不認鳥她的想法創造出這場磨難·雖然在她生命中曾有過許多恐懼·但那是很久以
前的事了·她已安然度過，而且數十年來一直過著快樂、有意義的生活·此外·派特後來得知
在她被確定診斷為葛雷克氏痘的當時·她居住的小鎮就有六個人也羅思這種十分罕見的疾病·這
個統計數字大幅超出全國的平均值·因此我懷疑是不是某種環境間題在作崇·友人甘蒂絲·珀特
QBS85是位供出科學家，她便認為我們今日所見的許多疾病與環境因素有關n
1
在發病初期·派特老是責怪自己患病，而隨著日子一天天過去，她也然自己沒能扭轉情況a
她認鳥·如果她無法用思想創造奇墳·那地一定是哪徑不對·因此她拼命觀想·想著白己正在康


任务结束时间：2023-06-24 03:10:22
```

（1）竖版书的部分标点和英文全是横过来的，我即使开了文字方向识别也没有用。

（2）段落识别完全没有。

**如果我打算微调模型的话，应该去找哪个项目，有没有详细的指南？**

**Comment by hiroi-sora** [comment]
> 微调模型

请参考 [PP-OCR模型训练](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/training.md)

> 段落识别

竖排段落合并我确实没写，因为感觉用的人不多。需要开发的话请参考 [tbpu模块](https://github.com/hiroi-sora/Umi-OCR/tree/main/ocr/tbpu) 。
