### ISSUE TITLE
支持让同一水平线上的文本识别后不换行，不改变单词顺序

### ISSUE THREAD

**Issue by oplle** [hiroi-sora/Umi-OCR#165]
更新：作者大大已经支持了这个选项“优化单行-模糊匹配”，强烈建议各位试试1.3.6的这个新选项

----

目前在某些英文识别中，会自动分割换行，导致阅读习惯被改变了，还得自己去对比文本，而且你看单词顺序也是乱的，如图所示。
所以想问问有没有办法，可以让每行文本保持原始阅读的样子，中间是空白就空白无所谓，只要在同一行就行
![QQ拼音截图未命名](https://github.com/hiroi-sora/Umi-OCR/assets/91740569/022e96a3-962c-4a61-b1fe-1833cad9e67b)
![QQ拼音截图未命名002](https://github.com/hiroi-sora/Umi-OCR/assets/91740569/131708c4-c305-408c-b679-4a26ae1e72dc)

**Comment by hiroi-sora** [comment]
你应该是调过 `合并段落` 的选项，实际上默认的`优化单行`就能让同一行的单词不换行了。

如果想要同一段落的文本不换行，可以改为`合并多行`。

**Comment by oplle** [comment]
合并多行的几个选项都试过了，照样被换行了，你在下面的网站截图识别就能复现。
https://www.apple.com/
并不是所有的英文都会被换行，我说过了，是部分英文的版面会这样

**Comment by hiroi-sora** [comment]
嗯，我明白了。像 `www.apple.com` 中的文字，要么单词之间的间距太大（顶部导航栏），要么行高字号不一致。

按我的设计思路，这些确实不属于同一段落文字，所以没有进行合并。同一段落文字要求字体大小相近、单词距离贴近。

不过，你可以先按单行合并，将字号及距离相近的文字合并；然后在文本编辑器中将换行符`\n`全部替换为空格。

**Comment by oplle** [comment]
> 嗯，我明白了。像 `www.apple.com` 中的文字，要么单词之间的间距太大（顶部导航栏），要么行高字号不一致。
> 
> 按我的设计思路，这些确实不属于同一段落文字，所以没有进行合并。同一段落文字要求字体大小相近、单词距离贴近。如果判定标准太宽泛，会引起更多误判。
> 
> 不过，你可以先按单行合并，将字号及距离相近的文字合并；然后在文本编辑器中将换行符`\n`全部替换为空格。

行高不一致换行没问题，但是间距大（很多场景并不是在顶部）我倒是不希望换行，会误判不怕，我喜欢完全一致的阅读顺序，最严重是换行后单词顺序都乱了。

并不是所有人都是程序员，去用编辑器修改。我只是看英文网站的时候浏览器不能翻译图片，所以尝试通过本软件来识别翻译，如果被换行或者顺序被打乱了，就会影响阅读，要去一遍遍对比。

如果不麻烦，单独增加个选项，不换行同一高度的文本。

**Comment by hiroi-sora** [comment]
> 单独增加个选项，不换行同一高度的文本

嗯，这个建议可以

**Comment by oplle** [comment]
> 

那就太棒了，感谢

**Comment by oplle** [comment]
不好意思，我看到新功能似乎添加到"合并多行-模糊匹配-合并同一水平线上的文本框"
我并不是需要合并多行，因为把不是同一行的文本进行合并会导致更难阅读文本，所以我设置里面的合并段落功能选择的是"不做选择"。
基于前面的交流，我表述的是希望仅对间距太大的同一文本行进行合并

**Comment by hiroi-sora** [comment]
我添加了一组新的文本后处理叫`优化单行-模糊匹配`，规则是只要行高相近，且上下位置相近的单词，视为同一行。
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/f344d32b-01aa-401c-b21b-c52f656e8ff6)

原始：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/0e57564b-f154-47fd-bd7c-f96fce4675a6)

处理后：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/d5d680f9-3d56-493e-b5da-7d02fa2863d4)
```
a Store Mac iPad iPhone Watch Vision AirPods TV & Home Entertainment Accessories Support Q 0
A
F
iPhone 14
Wonderfull.
Learn more > Buy >
```

这个效果应该符合你的需求。

---

不过可惜的是，目前它难以作用于双栏布局的段落，左右双栏的文本可能被误合并在一起：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/d0fc8c36-9310-4cbc-90d4-8fe160f739d2)
暂时没办法设定一个合适的阈值，能区分文本是否属于不同栏。

**Comment by oplle** [comment]
> 我添加了一组新的文本后处理叫`优化单行-模糊匹配`，规则是只要行高相近，且上下位置相近的单词，视为同一行。 ![image](https://user-images.githubusercontent.com/56373419/250348853-f344d32b-01aa-401c-b21b-c52f656e8ff6.png)
> 
> 原始： ![image](https://user-images.githubusercontent.com/56373419/250348684-0e57564b-f154-47fd-bd7c-f96fce4675a6.png)
> 
> 处理后： ![image](https://user-images.githubusercontent.com/56373419/250348697-d5d680f9-3d56-493e-b5da-7d02fa2863d4.png)
> 
> 效果：
> 
> ```
> a Store Mac iPad iPhone Watch Vision AirPods TV & Home Entertainment Accessories Support Q 0
> A
> F
> iPhone 14
> Wonderfull.
> Learn more > Buy >
> ```
> 
> 这个效果应该符合你的需求。
> 
> 不过可惜的是，目前它难以作用于双栏布局的段落，左右双栏的文本可能被误合并在一起： ![image](https://user-images.githubusercontent.com/56373419/250348800-d0fc8c36-9310-4cbc-90d4-8fe160f739d2.png) 暂时没办法设定一个合适的阈值，能区分文本是否属于不同栏。

这个演示效果已经非常棒了，左右双栏被合并的话，只要留有空隙（空格或原始空白间隔），就不影响

**Comment by hiroi-sora** [comment]
该功能已打包进测试版：[Umi-OCR_v1.3.6_alpha-1.zip](https://github.com/hiroi-sora/Umi-OCR/files/11935060/Umi-OCR_v1.3.6_alpha-1.zip)

有需要的用户可下载尝试。

**Comment by hiroi-sora** [comment]
联动截图修改成了：

1. 需勾选并设定单独的快捷键，以便与普通截图OCR区分开。
2. 无需勾选`自动复制结果`也能工作，联动截图将默认复制结果文本，然后发送指定按键。

关于文本间隔比较大的情况：
做个新选项的代价比较大，特殊分隔符也不太灵活。我得考虑下这个需求大不大，感觉需要这组功能的用户不会很多。

**Comment by oplle** [comment]
> 联动截图修改成了：
> 
> 1. 需勾选并设定独立的`截图联动`快捷键，用这个新的按键来触发。以便与普通截图OCR区分开。
> 2. 无需勾选`自动复制结果`也能工作，联动截图将默认复制结果文本，然后发送`联动发送按键`中设定的组合。
> 
> 关于文本间隔比较大的情况： 做个新选项的代价比较大，特殊分隔符也不太灵活。我得考虑下这个需求大不大，感觉需要这组功能的用户不会很多。

明白了截图联动的功能，我把截图识别和自动复制结果关了，只用截图快捷键能够正常工作，这样很不错

从之前自动换行得出的看法，我以为软件能够很容易区分间隔大不大的情况。目前很多老用户是习惯了或者已经接受了当前的使用体验，我想如果大家都明白了“单行优化-模糊匹配”的巨大好处，这个组合的用户可能会变多，其感官感受大大提升，不过暂时的确是没人从这个方面想过或提出这个问题，所以会显得很小众。

**Comment by hiroi-sora** [comment]
[Umi-OCR_v1.3.6_alpha-1_ttt.zip](https://github.com/hiroi-sora/Umi-OCR/files/11980282/Umi-OCR_v1.3.6_alpha-1_ttt.zip)
我稍微改了下代码，这个👆特殊版本的单行模糊模式可以为水平间距过大的文本插入` | `作为分隔符。正常间距的文本依然以空格分隔。你可以先拿去试试。

效果预览：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/d0fc8c36-9310-4cbc-90d4-8fe160f739d2)
```
Store | Mac | iPad | iPhone | Watch | Vision | AirPods | TV & Home | Entertainment | Accessories | Support | Q
Trade In | Card
Upgrade and save. It's that easy. | Get upto 3%Daily Cash back
with every purchase
See what vour device is worth?
Learn more > | Apply now >
```

经过改动的源代码我也放里面了，你可以自己再调整修改。

**Comment by oplle** [comment]
> 我稍微改了下代码：[Umi-OCR_v1.3.6_alpha-1_ttt.zip](https://github.com/hiroi-sora/Umi-OCR/files/11980282/Umi-OCR_v1.3.6_alpha-1_ttt.zip) 这个特殊版本的单行模糊模式可以为水平间距过大的文本插入`|`作为分隔符。正常间距的文本依然以空格分隔。你可以先拿去试试。
> 
> 效果预览： ![image](https://user-images.githubusercontent.com/56373419/250348800-d0fc8c36-9310-4cbc-90d4-8fe160f739d2.png)
> 
> ```
> Store | Mac | iPad | iPhone | Watch | Vision | AirPods | TV & Home | Entertainment | Accessories | Support | Q
> Trade In | Card
> Upgrade and save. It's that easy. | Get upto 3%Daily Cash back
> with every purchase
> See what vour device is worth?
> Learn more > | Apply now >
> ```
> 
> 经过改动的源代码我也放压缩包里面了，你可以自己再调整修改。这些改动我暂时不会提交到正式分支

哇，效果非常好
Airtime | Avg.Daily EstimatedAudience |  Followers Gain    

请问下，如果我修改 python 的源码脚本后，怎么替换到 exe 里面

**Comment by hiroi-sora** [comment]
[使用源代码](https://github.com/hiroi-sora/Umi-OCR#%E4%BD%BF%E7%94%A8%E6%BA%90%E4%BB%A3%E7%A0%81)

**Comment by oplle** [comment]
> [使用源代码](https://github.com/hiroi-sora/Umi-OCR#%E4%BD%BF%E7%94%A8%E6%BA%90%E4%BB%A3%E7%A0%81)

第一次打包成功了，exe可以正常运行

我打包后exe大小23.5M，我看你发给我的exe才15.1M，我是否应该删除一些解压后的Umi-OCR-main文件夹里面的内容，才能缩小exe大小，但是不确定哪些是可以删除的

**Comment by hiroi-sora** [comment]
因为它打包进了一些你本地python环境中已安装，但本软件中并未使用的库。

如果想追求极限体积，请了解一下 [虚拟环境](https://cn.bing.com/search?q=python+vscode+%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83) ，在虚拟环境中仅安装必要的库再打包。

**Comment by oplle** [comment]
> 因为它打包进了一些你本地python环境中已安装，但本软件中并未使用的库。
> 
> 如果想追求极限体积，请了解一下 [虚拟环境](https://cn.bing.com/search?q=python+vscode+%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83) ，在虚拟环境中仅安装必要的库再打包。

原来如此，不过应该不会影响到使用吧，反正是个人用，随便改来玩，只是包大一些无所谓

**Comment by hiroi-sora** [comment]
是的，不会影响使用。自用的话不用在意

**Comment by oplle** [comment]
> 是的，不会影响使用。自用的话不用在意

好的，感谢作者大大，写了超棒的新选项，还学习到了一些新知识

**Comment by oplle** [comment]
我发现插入的特殊字符改成“零宽字符”是最完美的，阅读时不会产生任何多余的字符信息，翻译也能够完美区分间隔的单词
