### ISSUE TITLE
翻译联动建议

### ISSUE THREAD

**Issue by paul-yangmy** [hiroi-sora/Umi-OCR#166]
大佬，目前使用v1.3.5和欧路词典联动，但有时候使用只想执行ocr而不需要翻译。能不能设计两个截图快捷键呢，这样一个可以联动获得翻译，一个只是单纯的ocr~

**Comment by hiroi-sora** [comment]
建议收到，我会考虑下。

**Comment by hiroi-sora** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/d749ba9b-1075-45c7-843e-6e543fb9dbff)

已打包为测试版：[Umi-OCR_v1.3.6_alpha-1.zip](https://github.com/hiroi-sora/Umi-OCR/files/11935060/Umi-OCR_v1.3.6_alpha-1.zip)

有需要的用户可下载尝试。该版本将联动截图修改为：

1. 需设定单独的快捷键，以便与普通截图OCR区分开。
2. 无需勾选`自动复制结果`选项，联动截图将强制复制结果文本。

**Comment by paul-yangmy** [comment]
大佬nb！
