### ISSUE TITLE
输出的文字怎么默认不带任务开始和结束时间

### ISSUE THREAD

**Issue by Shinnshi0616** [hiroi-sora/Umi-OCR#168]
如题，还有图片名称

**Comment by hiroi-sora** [comment]
抱歉，目前确实没有这个功能。之后考虑加上。

**Comment by hiroi-sora** [comment]
[v2版本](https://github.com/hiroi-sora/Umi-OCR_v2) 选择`p.txt 纯文字格式`即可输出屏蔽任务时间、图片名称等输出。
