### ISSUE TITLE
我需要在您软件的基础上定制一个功能，请问如何联系你？！

### ISSUE THREAD

**Issue by LPJSOFT** [hiroi-sora/Umi-OCR#169]
我需要在您软件的基础上定制一个功能，请问如何联系你？！
或者请联系我lpjsoft@163.com

**Comment by hiroi-sora** [comment]
功能不复杂的话，可以在这里说一下

**Comment by LPJSOFT** [comment]
你好，目前生成的文本是这样的


任务开始时间:2022-11-11 17:37:33


文字1
文字2
文字3
....


        我需要生成的格式要这样的文本（最好是EXCEL表格格式）：用英文的,号分开，每张图片转换成一行
任务开始时间:2022-11-11 17:37:33,文字1,文字2,文字3,....
任务开始时间:2022-11-11 18:37:00,文字1,文字2,文字3,文字4....






在2023年07月6日 ***@***.***> 写道：

功能不复杂的话，可以在这里说一下

**Comment by LPJSOFT** [comment]
收到了吗，请回复 ！？


在2023年07月8日 ***@***.***> 写道：
你好，目前生成的文本是这样的


任务开始时间:2022-11-11 17:37:33


文字1
文字2
文字3
....


        我需要生成的格式要这样的文本（最好是EXCEL表格格式）：用英文的,号分开，每张图片转换成一行
任务开始时间:2022-11-11 17:37:33,文字1,文字2,文字3,....
任务开始时间:2022-11-11 18:37:00,文字1,文字2,文字3,文字4....






在2023年07月6日 ***@***.***> 写道：

功能不复杂的话，可以在这里说一下

**Comment by hiroi-sora** [comment]
收到，我会研究一下，3天内给你答复

**Comment by hiroi-sora** [comment]
可以了，试试

[Umi-OCR v1.3.6_a-1_csv.zip](https://github.com/hiroi-sora/Umi-OCR/files/11990564/Umi-OCR.v1.3.6_a-1_csv.zip)

在`结果输出`里，勾选`表格.csv文件`。
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/0c7e053d-8f8a-41f2-932b-5098db6d6657)

多次任务的结果，会追加写入同一个csv文件内。
可用excel打开和编辑，效果如下图所示，最左边一列为任务开始日期，右边每一格为一张图片的内容
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/2b349321-dfd2-478f-8094-231b7fc0412e)

**Comment by LPJSOFT** [comment]
你好，请问如何感谢你，发个账号给我吧！
我测试了一下，有两个问题
1、新生成的.CSV文件要替换老文件，或者生是新命名，后面加短日期
2、现在生成的文字全部在一个单元格里面，我需要的是要一个个分开。
格式为：
2023/7/9 9:49，图片文件名称1（最好是有），珠晖山地，后，森林公园，，，，，，
2023/7/9 9:49，图片文件名称2（最好是有），珠晖山地，后，森林公园，，，，，，
| 2023/7/9 9:49 | 珠晖山地
后
森林公园
东三环路
虎形山人防公园
咸塘镇
光品
蒸水
蒸湘区
西湖公园
湖南财经工业
职业技禾学院
果
A衡阳东站
水
蒸水风光带
珠晖区
衡阳市
A衡阳站
船山公园
湖南工学院
衡阳师范学院
(东校区)-
苗圃公园
R
信
(区路里)
营盘山公园
后
X013
|



原图片为：

**Comment by hiroi-sora** [comment]
嗯，还有几个问题

1. 第一列的时间，你想要的是本次任务的开始时间（即所有图片的时间一样），还是每张图片分别的完成时间？
2. 你希望每张图片占一行，图片中的每一部分文字占一格？

**Comment by LPJSOFT** [comment]
1、就本次执行任务的时间吧，都一样
2、是的






在2023年07月9日 ***@***.***> 写道：

嗯，还有几个问题

第一列的时间，你想要的是本次任务的开始时间（即所有图片的时间一样），还是每张图片分别的完成时间？
你希望每张图片占一行，图片中的每一部分文字占一格？

**Comment by hiroi-sora** [comment]
可以了
[Umi-OCR v1.3.6_a-1_csv2.zip](https://github.com/hiroi-sora/Umi-OCR/files/11994828/Umi-OCR.v1.3.6_a-1_csv2.zip)

**Comment by LPJSOFT** [comment]
你好，测试过了，暂时没有发现什么问题，请问如何感谢你，让我表示一下心意吧，今后可能还会有需求要麻烦你！




在2023年07月9日 ***@***.***> 写道：

可以了
Umi-OCR v1.3.6_a-1_csv2.zip

**Comment by hiroi-sora** [comment]
暂时不用了，嫌麻烦。

以后有问题可继续来提。
