### ISSUE TITLE
长图识别效果差

### ISSUE THREAD

**Issue by master4orochi** [hiroi-sora/Umi-OCR#17]
![图片](https://user-images.githubusercontent.com/57038887/189465999-4d61bc74-94e9-4d4c-afeb-eb3f8222bd6b.png)
图片是长截图，直接显示了无文字
设置缩放的时候如果图片两条边长差距过大，希望可以考虑一下短边

**Comment by hiroi-sora** [comment]
请在启动参数填 `--limit_side_len=压缩阈值` ，其中压缩阈值是图片长边的一半（仍不准确的话再加大）。实测高7000像素的长图可以正常识别。

![image](https://user-images.githubusercontent.com/56373419/189466211-df9c1563-b264-483a-92b4-700ab2f64dc1.png)

抱歉，这个版本需要填写[启动参数
](https://github.com/hiroi-sora/Umi-OCR#%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)来配置引擎策略确实比较麻烦。以后会优化UI，用更直观的控件来修改各项参数。

**Comment by hiroi-sora** [comment]
`v1.3.0` 已更新 更直观的设置页。
