### ISSUE TITLE
作者您好，可以多开放一些命令行的指令设置吗？

### ISSUE THREAD

**Issue by Doraemon0611** [hiroi-sora/Umi-OCR#173]
多添加一些命令行的设置：
1.增加主程序在后台运行。
2.通过命令行实现点击“屏幕截图”。
3.通过命令行指定生成文本信息的路径。
4.通过命令行指定生成文本文件的名称。

这样感觉就可以通过其他程序来很好的调用 Umi-OCR 这个程序了，并且能很好的控制它。

**Comment by hiroi-sora** [comment]
第2项，屏幕截图指令已经有了。
第1、3、4项指令已添加，语法见上面的commit message。

**Comment by Doraemon0611** [comment]
好的。👍👍
