### ISSUE TITLE
图片文字识别

### ISSUE THREAD

**Issue by ymd123dfg** [hiroi-sora/Umi-OCR#178]
你好，我的项目中想用你的这个图片文字识别，python应该装哪个版本的，环境有什么要求不

**Comment by ymd123dfg** [comment]
1

**Comment by hiroi-sora** [comment]
你好~ 你是想直接使用 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 的python api吗？它对python版本没有特殊要求，因为它只是一个连接c++进程的中转器。具体用法请见上述链接的说明。

**Comment by ymd123dfg** [comment]
好的，谢谢，没使用过python，这个里面哪个方法可以直接使用的，我就想把识别图片返回字符串的那个方法用python写个接口用Java去调，
![image](https://github.com/hiroi-sora/Umi-OCR/assets/140133088/39781ee3-410c-44dd-ab7a-365c02c8dda6)，
![image](https://github.com/hiroi-sora/Umi-OCR/assets/140133088/55ac6ec0-2cd8-4156-b1b9-01fb1d85ea4e)
我就调的这个方法，发现好多地方报错，可以稍微指导一下具体怎么使用嘛

**Comment by ymd123dfg** [comment]
求大佬指导一下

**Comment by hiroi-sora** [comment]
Java Api 也有的，不过v1.3.0版还没更新。你可以用 [v1.2.1](https://github.com/hiroi-sora/PaddleOCR-json/releases/tag/v1.2.1) 版的PaddleOCR-json exe程序 ，有 [现成的Java](https://github.com/jerrylususu/PaddleOCR-json-java-api) 可供使用。

1.3和1.2版在性能上没有任何区别，都能满足你的需求。
