### ISSUE TITLE
使用两个显示屏时，截图窗口变形

### ISSUE THREAD

**Issue by weiningwei** [hiroi-sora/Umi-OCR#179]
如图所示，使用扩展屏时，两个屏幕的比例不一样，截图时窗口变形，根据提示，将截图模式切换为[Windows 系统截图]（两个屏幕的比例是根据系统推荐设置的，推荐的就是不一样大小的，不太想更改了）后，截图的快捷键不能修改，所以想问下，如果想修改截图快捷键同时截图不受影响，只能把两个屏幕的比例设置为一样的嘛？
![image](https://github.com/hiroi-sora/Umi-OCR/assets/38557780/5ad70e42-05bd-483a-b559-8cba081d1d0e)

**Comment by hiroi-sora** [comment]
很遗憾，由于目前UI框架的限制，无法做到自适应不同比例的屏幕。不过正在开发的V2版本会解决这个问题。

**Comment by weiningwei** [comment]
好的，谢谢您的回复

**Comment by hiroi-sora** [comment]
如果你的使用频率高，那么可以参考 [这个issue](https://github.com/hiroi-sora/Umi-OCR/issues/96#issuecomment-1455284373) ，用专业截图软件Snipaste来充当截图模块，联动Umi-OCR进行识别。

**Comment by weiningwei** [comment]
好的，还有我在使用的时候，通过快捷键采用粘贴图片进行识别的时候，不会生效开始识别，只有通过点击窗口中的粘贴图片按钮，才会开始识别，请问这是正常的嘛，还是由于我的问题才会这样？

**Comment by hiroi-sora** [comment]
按理说快捷键粘贴图片和点击按钮粘贴图片的效果是一样的，它们实际调用的代码是同一个。你的问题有可能的原因：

1. 软件中粘贴图片快捷键没有设置好，或者没有启用勾选，导致快捷键未被触发。尝试重新设置一个简短的快捷键，并勾选它。
2. 复制图片后，在太短的间隔内（如0.1s内）就粘贴图片了，导致系统没有及时转移剪贴板权限，软件无法粘贴。（这在低配置/老机器上可能比较明显）

**Comment by weiningwei** [comment]
非常感谢您的回复，发现是我没有勾选，再次感谢您。
