### ISSUE TITLE
竖排日文支持

### ISSUE THREAD

**Issue by lockmatrix** [hiroi-sora/Umi-OCR#18]
样例：
![2yDU3SPl](https://user-images.githubusercontent.com/1844843/189532121-4d097603-778f-4a70-9cdf-9bed085c1872.jpg)

**Comment by hiroi-sora** [comment]
建议收到 √

这实际上是两个问题：第一，ocr引擎使用恰当的模型，输出正确的竖排文本段。第二，umi对得到的文段进行整理排序，以正确的顺序输出为纯文本或其他格式。

对于问题一，我不擅长训练模型，得看看paddle有没有相关模型或等相关领域的大佬提供帮助。另外，umi-ocr的界面、后处理模块，和引擎模块是完全独立的。通过更换本地引擎（甚至在线ocr服务）来适配这种场景也是可行的。

对于问题二，如 [issue #12](https://github.com/hiroi-sora/Umi-OCR/issues/12) 这类关于文段排序的问题。我正在开发一套“文段后处理器”框架，它不仅包含我写的忽略水印区域之类的后处理模块，还可以比较方便的拓展，让别的开发者按自己的需求来开发后处理模块。像日文漫画，可能按常规竖排的逻辑来排版 效果很差，那么就可以再写一套专门针对漫画文段的后处理类。但精力有限，我可能短期内不会着手这类模块的具体实现。
