### ISSUE TITLE
命令行可否增加阻塞模式运行

### ISSUE THREAD

**Issue by Mrqqeat** [hiroi-sora/Umi-OCR#180]
命令行现在执行后没有返回结果，如果想知道是否识别完成需要一直判断识别后的文件是否存在。
可否让命令行执行后直到解析成功才返回，或者有没有其他更好的方法呢

**Comment by hiroi-sora** [comment]
非常抱歉，由于命令行模式是项目后期补充的一个功能，项目前期并没有考虑到，所以 **获取OCR结果并返回给调用者** 的实现比较麻烦。

现在我的开发重心转向V2版本，全新重构的V2将会充分考虑到这些问题，并带来一个完成度更高的命令行模式。

如果你短期内希望改善这个方面，建议开启识别后自动写入剪贴板，然后调用时循环判断剪贴板内是否存在新的文本。可能比判断文件是否存在的效率更高。

**Comment by Mrqqeat** [comment]
> 非常抱歉，由于命令行模式是项目后期补充的一个功能，项目前期并没有考虑到，所以 **获取OCR结果并返回给调用者** 的实现比较麻烦。
> 
> 现在我的开发重心转向V2版本，全新重构的V2将会充分考虑到这些问题，并带来一个完成度更高的命令行模式。
> 
> 如果你短期内希望改善这个方面，建议开启识别后自动写入剪贴板，然后调用时循环判断剪贴板内是否存在新的文本。可能比判断文件是否存在的效率更高。

好的，期待V2~
