### ISSUE TITLE
设置自动开启，开机提示“无法定位序数380于动态链接库……”

### ISSUE THREAD

**Issue by zixuan203344** [hiroi-sora/Umi-OCR#181]
如题，设置开机自动开启，开机弹窗提示“无法定位序数380于动态链接库……”，把这个窗口关掉，然后单独打开UMIOCR软件，软件又能正常工作。

怀疑是C++运行库问题，我把运行库删了，又重装，装旧版，依然有这个提示，百度无果，遂来求教。
![Snipaste_2023-07-24_18-20-32](https://github.com/hiroi-sora/Umi-OCR/assets/3961798/0067aeb0-b6ac-4439-8811-317c687d42d0)

**Comment by hiroi-sora** [comment]
非常抱歉，这个问题我也没有遇见过。

如果手动打开软件没有问题，请尝试下列操作：

1. 打开目录 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup`
2. 新建一个文件 `开机启动Umi-OCR.txt`
3. 在文件内输入 `start "" "Umi-OCR.exe的路径"`
    例如：  `start "" "D:\Program Files Green\OCR\Umi-OCR 多国语言整合版\Umi-OCR 文字识别.exe"`
4. 保存并关闭文件，将文件后缀改为 `.bat`
5. 尝试重启电脑，看看软件是否已经正确开机启动。

**Comment by zixuan203344** [comment]
添加bat启动项的方式，不报错了，但是让软件自启动，依然有这个报错，google不到这个问题。
我是更新到最新的win11系统，怀疑是运行库兼容性问题，但是我没有证据
