### ISSUE TITLE
360安全卫士报错了

### ISSUE THREAD

**Issue by ac6855** [hiroi-sora/Umi-OCR#182]
360安全卫士报错了...

**Comment by hiroi-sora** [comment]
报啥错？

**Comment by ac6855** [comment]
时间	操作	说明	次数
2023-07-27 09:36:32	[已清除]	  发现木马：HEUR/QVM202.0.E53E.Malware.Gen	防护 1 次
详细描述：
木马名称：HEUR/QVM202.0.E53E.Malware.Gen
所在路径：C:\Users\Bee\AppData\Local\Temp\360zip$Temp\360$0\Umi-OCR 多国语言整合版\Umi-OCR 文字识别.exe

**Comment by hiroi-sora** [comment]
`HEUR/QVM202.0.E53E.Malware.Gen`

这句话的意思是：
检测到一种未知的目标，通过启发式分析（HEUR）和特定的规则集（QVM202.0.E53E）进行了检测，并将其归类为通用的恶意软件（Malware.Gen）。

翻译：
360也不知道这玩意是啥，不过它寻思了一下，反正没见过，就当成木马算了。

省流：
## 误报。

另：
你拿这句话`HEUR/QVM202.0.E53E.Malware.Gen`去百度搜可以搜到几页的误报的例子；可以放心的不用管它~
