### ISSUE TITLE
批量识别后能否不输出文件名？

### ISSUE THREAD

**Issue by YuFengNB** [hiroi-sora/Umi-OCR#184]
批量识别后能否不输出文件名？识别整本书很麻烦

**Comment by hiroi-sora** [comment]
[V2预览版](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20230726) 已支持输出为纯文本。

**Comment by YuFengNB** [comment]
> [V2预览版](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20230726) 已支持输出为纯文本。

已解决，感谢
