### ISSUE TITLE
运行程序后系统无法正常休眠

### ISSUE THREAD

**Issue by XiaoHuanwise** [hiroi-sora/Umi-OCR#185]
系统：win11
休眠后电脑会自动自动

**Comment by hiroi-sora** [comment]
你好，按理说我的代码里并没有与自启动或唤醒事件有关的功能。请检查是否连接了某些键鼠硬件，导致了异常唤醒。

**Comment by XiaoHuanwise** [comment]
> 你好，按理说我的代码里并没有与自启动或唤醒事件有关的功能。请检查是否连接了某些键鼠硬件，导致了异常唤醒。

emmm，我做过实验，把程序关掉就能正常休眠，但是一把程序打开休眠就会被唤醒。（当然也有可能是我电脑的问题

**Comment by hiroi-sora** [comment]
是只要进入休眠后，很短时间内（一分钟内？）就会唤醒吗

**Comment by XiaoHuanwise** [comment]
> 是只要进入休眠后，很短时间内（一分钟内？）就会唤醒吗

对，就是休眠完成后（电源指示灯黑），不到10秒就会唤醒

**Comment by hiroi-sora** [comment]
麻烦做以下操作调查一下，非常感谢。

1. 等待该问题复现一次。
2. 打开PowerShell。可以在开始菜单内搜索找到`PowerShell`。
3. 在PowerShell内输入下列代码，可以查询最后一次被谁唤醒。
```
powercfg -lastwake
```
4. 继续输入下列代码，可以显示出哪些系统服务或第三方软件可能导致唤醒事件。（最好一行行输入）
```
Get-ScheduledTask | where {$_.settings.waketorun}
powercfg -waketimers
powercfg -requests
powercfg -requestsoverride
```
5. 输入下列代码，可以显示出哪些硬件可能导致唤醒事件。
```
powercfg -devicequery wake_armed
powercfg -devicequery wake_programmable
```
6. 检查上述代码的输出中，是否包含跟OCR有关的条目。

**Comment by XiaoHuanwise** [comment]
> 

感谢您的耐心指导，我在尝试了之后并没有发现与Omi的相关条目，powercfg -lastwake提示我电脑是由电源按钮唤醒的，并且在我重启之后问题消失，我想这应该是我电脑自身的问题，并且在巧合（也许我昨天神志不清）之下产生的乌龙。非常抱歉打扰到您的工作！

**Comment by hiroi-sora** [comment]
哈哈哈，解决了问题就好~
