### ISSUE TITLE
是否可以支持内存图片的识别？

### ISSUE THREAD

**Issue by ZzAget** [hiroi-sora/Umi-OCR#19]
是否可以支持屏幕区域内直接截图图片进行OCR识别？
另外，是否可以与您取得联系？我的Email：lxjdx@vip.qq.com，期待你的来信。

**Comment by hiroi-sora** [comment]
> 1. 是否可以支持内存图片的识别？

我最近得到了一些朋友的启示，也许应该用别的方法代替引擎中的 [c++ cv::imread 函数](https://github.com/hiroi-sora/PaddleOCR-json/blob/release/1.2.0/project_files/cpp_infer/src/paddleocr.cpp#L184)  。这不仅可以规避类似 [ issue #16 ](https://github.com/hiroi-sora/Umi-OCR/issues/16) Windows宽窄字符转换带来的兼容性问题，还可能赋予引擎 **有限** 的内存识图功能，比如不经过本地，直接读取剪贴板。具体操作还在研究中。

> 2. 是否可以支持屏幕区域内直接截图图片进行OCR识别？

也是正在研究。这个问题与上一个问题无关，即就算没法搞定引擎读图的问题，只用现有的引擎，我可能也会在以后加上屏幕选区截图的功能，只不过依然要通过硬盘中转。当然，受限于功能比较弱的tkinter，可能写起来也不太容易。

> 3. 联系？

抱歉，暂时不太方便私下交流，还请见谅😂

**Comment by ZzAget** [comment]
感谢分享，关于联系，是我有一些想法希望与您交流，或者说可以合作一些实际应用的项目，如果后续有意愿，可以随时联络我，我会持续关注你的更新。
