### ISSUE TITLE
保存路径

### ISSUE THREAD

**Issue by alen978** [hiroi-sora/Umi-OCR#190]
umiocr.exe -img=‪D:\sd.png

命令行读取图片后，如何将识别结果保存到D:\s.txt  ?

再就是有没有可能联网使用？如api 或者布置到服务器或者其他能够间接实现的办法？

**Comment by hiroi-sora** [comment]
> 1. 命令行识别结果保存

命令行模式这方面功能暂时不完善，后续版本会补充。

> 2. 联网使用

未来版本可能会提供简易的服务器模式。

目前， [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 提供了简易了TCP调用模式（对并发的支持较弱）。当然，你也可以基于它的 Python API 或 js API 开发功能更完善的后端。你可以编写任务队列，使其支持伪并发响应。

**Comment by alen978** [comment]
"命令行模式这方面功能暂时不完善，后续版本会补充。"

什么时候解决了在更新日志中提一下，谢谢
