### ISSUE TITLE
璩（qú ）这个字识别不到，这也是个姓。

### ISSUE THREAD

**Issue by Super-Yu-Super** [hiroi-sora/Umi-OCR#193]
璩（qú ）这个字识别不到，这也是个姓。
![b42e61d772a0021f00625e22a4e1e30](https://github.com/hiroi-sora/Umi-OCR/assets/59213663/a476a7b5-d875-4087-b6c6-292a73a397ab)

**Comment by hiroi-sora** [comment]
感谢提出。不过为了效率和模型库容量，目前的轻量级模型库可能不会收录生僻字。

**Comment by Super-Yu-Super** [comment]
明白了，璩（qú ）是二级汉字，而中国常用的一级汉字只有3500个。
相关资料：在国务院关于公布《通用规范汉字表》的通知国发〔2013〕23号
