### ISSUE TITLE
缩放预处理的默认值很坑

### ISSUE THREAD

**Issue by wizardforcel** [hiroi-sora/Umi-OCR#196]
根据我的经验来看，32开本的短边至少要1500px，16开本短边至少要2500px。

准确率不行的时候，希望能看到这个帖子。
以上。

**Comment by hiroi-sora** [comment]
感谢提醒，默认值960针对屏幕小范围截图有比较好的效率和精度，对于你的书籍图片可能精度就不够用了。

在V2版本，将允许在不同的任务情景（截图/批量/PDF）中设置不同的缩放值，以便灵活的应对不同需求。

另外，该值设为32和48的公倍数最适合模型解算。所以对于你的情景，建议设为 2880 。

**Comment by wizardforcel** [comment]
> 感谢提醒，默认值960针对屏幕小范围截图有比较好的效率和精度，对于你的书籍图片可能精度就不够用了。
> 
> 在V2版本，将允许在不同的任务情景（截图/批量/PDF）中设置不同的缩放值，以便灵活的应对不同需求。
> 
> 另外，该值设为32和48的公倍数最适合模型解算。所以对于你的情景，建议设为 2880 。

要不要做成calibre那样，针对不同屏幕尺寸规定不同默认值？

**Comment by hiroi-sora** [comment]
> 针对不同屏幕尺寸规定不同默认值

其实精度需求跟分辨率没有必然联系，而是跟信息密度有关。

比如一个4k分辨率的屏幕，开200%缩放，即两倍的字体大小。那么所需的精度跟1080p屏幕100%缩放没有太大差别。

但如果一些图片，同样的尺寸内塞入了更多文字、字体更小，比如书籍扫描件，那么对精度的需求就增加了。
