### ISSUE TITLE
希望您可以开放一个单独图片的http服务

### ISSUE THREAD

**Issue by suntydic** [hiroi-sora/Umi-OCR#197]
希望您可以开放一个单独图片的http服务，我这边有需求成了可以用客户端扫描图片还想希望可以通过http获取ocr的扫描结果，请问可以增强这个功能吗？另外可以您可以给个联系方式不大神？

**Comment by hiroi-sora** [comment]
V2版本中预计将会搭载http服务功能。

暂不方便给联系方式哈

**Comment by hiroi-sora** [comment]
V2目前支持HTTP接口传输base64图像进行识别。
