### ISSUE TITLE
截图模块选用windows截图时，快捷键问题

### ISSUE THREAD

**Issue by yancy5499** [hiroi-sora/Umi-OCR#199]
系统是win10，设置只改动了这部分
![image](https://github.com/hiroi-sora/Umi-OCR/assets/126537916/068fd38f-5a5a-4c36-97f6-1dc2150a9c69)

若想实现系统截图后自动监听只能通过win+shift+s调用的截图
无法利用print screen按键调用的截图
这两者调用的应用应该是一样的吧，习惯了一个按键了
![image](https://github.com/hiroi-sora/Umi-OCR/assets/126537916/65a4faf8-3c83-44d9-9762-d15278cce535)
若想实现单键截图只能用Umi-OCR的截图模块，但是重新设定一个单键又任意冲突
最和谐的单键截图应该是利用windows的截图快捷键

**Comment by hiroi-sora** [comment]
一个比较简单的方法是用AHK工具将PrtSc映射为Win+Shift+S，脚本代码如下：
```ahk
PrintScreen::#+s
```

这是我打包好的exe： [PrtSc映射Win+Shift+S.zip](https://github.com/hiroi-sora/Umi-OCR/files/12615047/PrtSc.Win%2BShift%2BS.zip)

如果需要开机自启，可以将上述exe的快捷方式放到
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup`
