### ISSUE TITLE
批量识别时会经常出现：行错乱

### ISSUE THREAD

**Issue by kentoog** [hiroi-sora/Umi-OCR#200]
比如图片上的文字是
1
2
3
4
5
但识别出来时
2
4
1
3
5
大部分情况是短行会被识别到段落的前面。
不知道我说明白了没？……
识别数量是250张左右。

**Comment by hiroi-sora** [comment]
你可以体验一下 [Umi-OCR_v2](https://github.com/hiroi-sora/Umi-OCR_v2) 预览版。它升级了文本排序算法，在默认选项下能提供更准确的顺序输出。

**Comment by hiroi-sora** [comment]
v1.3.6 也提供了最新的文本排序方案。
