### ISSUE TITLE
1.3.6 的设置选项是不是回退了

### ISSUE THREAD

**Issue by oplle** [hiroi-sora/Umi-OCR#201]
我下载的是 Umi-OCR.v1.3.6_ALL_languages 放到一个全新目录，发现截图联动功能不存在了，上图
![QQ拼音截图未命名](https://github.com/hiroi-sora/Umi-OCR/assets/91740569/0ecf4fa7-2253-48b8-bde5-322cf81a0bf0)

**Comment by hiroi-sora** [comment]
请现在设置页底部打开“高级模式”然后重启软件，截图联动的选项就出现啦

**Comment by oplle** [comment]
不好意思啊，我都忘了这回事

**Comment by hiroi-sora** [comment]
哈哈，这是我设计的失误，高级模式太不起眼了。v2.0中，高级模式会更显眼、更容易切换，无需重启软件。

不过v2暂时还没更新截图联动功能，你可以过一段时间来体验~
