### ISSUE TITLE
PaddleX更新PP-OCRv4，这里也能更新一下吗？

### ISSUE THREAD

**Issue by yiusing134** [hiroi-sora/Umi-OCR#202]
如题

🔥2023.8.7 发布 PaddleOCR [release/2.7](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.7)
发布[PP-OCRv4](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/PP-OCRv4_introduction.md)，提供mobile和server两种模型
PP-OCRv4-mobile：速度可比情况下，中文场景效果相比于PP-OCRv3再提升4.5%，英文场景提升10%，80语种多语言模型平均识别准确率提升8%以上
PP-OCRv4-server：发布了目前精度最高的OCR模型，中英文场景上检测模型精度提升4.9%， 识别模型精度提升2% 可参考[快速开始](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/quickstart.md) 一行命令快速使用，同时也可在飞桨AI套件(PaddleX)中的[通用OCR产业方案](https://aistudio.baidu.com/aistudio/modelsdetail?modelId=286)中低代码完成模型训练、推理、高性能部署全流程

**Comment by hiroi-sora** [comment]
[v2](https://github.com/hiroi-sora/Umi-OCR_v2) 的`Rapid`版已经默认附带了PP-OCRv4的简中轻量模型，可以去体验一下。

`Paddle`版有一些引擎兼容性问题，暂时不支持v4轻量模型。可以支持server级模型，实测确实有比较高的精度，但在家用设备上速度太慢了，不太实用，所以没有附带。如果想体验，可以自己下载并导入Umi-OCR_v2。

**Comment by hiroi-sora** [comment]
导入PP-OCRv4高精度模型的方法请见：
https://github.com/hiroi-sora/Umi-OCR_v2/issues/12
