### ISSUE TITLE
第一次使用后，发现windows 自带 mspaint 无法启动，闪退。Umi-OCR本身正常使用。

### ISSUE THREAD

**Issue by litbpfmtw** [hiroi-sora/Umi-OCR#203]
第一次使用时，正在使用windows 自带 ms paint ，中途推出再启动，无法启动，任务管理其中，发现paint 闪退。而Umi-OCR本身，可以正常使用。重启机器后，问题依然。

**Comment by hiroi-sora** [comment]
按理说，Umi-OCR与画图（ms paint）没有关系。Umi没有触及有关画图的API、系统组件、系统设置。它们两个进程的资源是隔离的，理论上不可能互相影响。我认为更大的可能是系统其它方面出现了问题，导致画图的异常。

百度上有一些画图闪退、无法启动的例子，你可以按照他们的做法，尝试修复问题。

如果后续发现了更多Umi-OCR干涉画图的信息，或者别的Umi用户出现了类似问题，请继续向我反馈，我会将一步调查。

**Comment by litbpfmtw** [comment]
thanks，检查了，发现注册表被更改了，但原因不详，不过问题解决了，估计不是Umi-OCR的问题

**Comment by xingxinag** [comment]
<img width="873" alt="屏幕截图 2024-01-23 190701" src="https://github.com/hiroi-sora/Umi-OCR/assets/105782492/b1a9514c-0eed-4833-a7e9-712f320156b4">
我的也报错了
