### ISSUE TITLE
有批量的文件夹，文件夹里面有图片，可以批量给文件夹生成单独的txt文本吗

### ISSUE THREAD

**Issue by smile-II** [hiroi-sora/Umi-OCR#204]

**Comment by hiroi-sora** [comment]
你这个需求比较小众。如果你会python，建议你在 v2 的基础上，修改代码来实现。

1. 下载v2版Release包（无需clone原项目）
2. 找到控制 `单独txt输出` 的文件：
`UmiOCR-data\pyapp\ocr\output\output_txt_individual.py`
3. 注意最后3行：
```python
        path = res["path"] + ".txt"  # 同名路径+txt
        with open(path, "w", encoding="utf-8") as f:  # 追加写入同名本地文件
            f.write(textOut)
```
这表明对每一个ocr结果，提取图片的路径，在同路径下生成结果文件。
如 `D:/aaa/bbb.png` 生成 `D:/aaa/bbb.png.txt` 。

你可以将这几行修改一下（大致思路）：
- 提取图片所在的路径 `D:/aaa/`
- 检查该路径下是否存在结果文件 `D:/aaa/结果.txt`
- 如果不存在，则生成该文件，并写入结果。
- 如果已存在，则向该文件追加写入结果。
上述思路即可实现 “批量给每个文件夹生成一份单独的txt文本” 。

**Comment by smile-II** [comment]
作者你好，图片排序方式可以设置吗，这里图片2排在10后面了
![image](https://github.com/hiroi-sora/Umi-OCR/assets/58884505/0f2c34b6-1d27-4e8d-b043-8399ff0c6f24)

**Comment by hiroi-sora** [comment]
这里的排序是文件管理器中的排序。建议将一位数补0，如 `1` → `01` ，这样文件管理器就能正确按序号排序。再拖入Umi-OCR里就行了。
