### ISSUE TITLE
服务端部署-linux，http服务访问希望安排上

### ISSUE THREAD

**Issue by hongwazi** [hiroi-sora/Umi-OCR#205]
下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注

**Comment by hiroi-sora** [comment]
谢谢支持~

HTTP服务模式正在开发中。

不过，Umi-OCR本质上还是个面向普通人（而非开发者）的桌面软件。虽然v2将支持通过命令行实现大部分操作，但是GUI是软件底层框架中不可缺少的部分。在纯命令行的Linux发行版上（缺少桌面环境和OpenGL支持），Umi-OCR很可能会因为无法加载GUI，而整体无法运行。今后Umi-OCR可能会优先支持 Ubuntu Desktop 这样带桌面的发行版。

Umi-OCR v2 的服务器模式，开发思想是在 家庭/办公室/实验室 的局域网环境中，可以充分利用一台高性能PC，为其它设备提供OCR算力。因此它对生产环境的一些要求，如高并发、安全性等，可能不太能满足。

**Comment by iszmxw** [comment]
> 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注

可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)

**Comment by hongwazi** [comment]
> > 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注
> 
> 可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)

如果要在公司使用的话，可能就不太行了，网络上可能不太行，最好全部离线。

**Comment by iszmxw** [comment]
> > > 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注
> > 
> > 
> > 可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)
> 
> 如果要在公司使用的话，可能就不太行了，网络上可能不太行，最好全部离线。

网络上怎么不行，一样使用

**Comment by hongwazi** [comment]
> > > > 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注
> > > 
> > > 
> > > 可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)
> > 
> > 
> > 如果要在公司使用的话，可能就不太行了，网络上可能不太行，最好全部离线。
> 
> 网络上怎么不行，一样使用

公司网络比较严格，可能访问不到。。看了下镜像挺大的，试了下在阿里云安装镜像，状态是up的，但是公网访问不到1224端口，不知道为啥，已经添加到安全组了。telnet1224没有问题，但是本机curl也不行。。

**Comment by iszmxw** [comment]
> > > > > 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注
> > > > 
> > > > 
> > > > 可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)
> > > 
> > > 
> > > 如果要在公司使用的话，可能就不太行了，网络上可能不太行，最好全部离线。
> > 
> > 
> > 网络上怎么不行，一样使用
> 
> 公司网络比较严格，可能访问不到。。看了下镜像挺大的，试了下在阿里云安装镜像，状态是up的，但是公网访问不到1224端口，不知道为啥，已经添加到安全组了。telnet1224没有问题，但是本机curl也不行。。

你要远程一下到容器里面启动相关软件先

**Comment by yy121121** [comment]
> > 下载使用了感觉很好用，cpu识别速度和精度都不错的。希望能够适配服务端部署的方案及开放http服务访问，点赞点赞，会持续关注
> 
> 可以看看我部署方案 ，封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)

兄哋,你这个方案我看了,不错啊,虽然属于是曲线救国,但我还是要给你赞赞赞

**Comment by hiroi-sora** [comment]
最新测试版中，已实验性支持 Linux 平台。经测试，对 Debian 系发行版的兼容性较好。

有能力的用户，也可以根据我们文档，从源码构建Umi-OCR。然后打包docker。

https://github.com/hiroi-sora/Umi-OCR/releases
