### ISSUE TITLE
关于命令行调用的一些问题的处理建议

### ISSUE THREAD

**Issue by kawvin** [hiroi-sora/Umi-OCR#206]
1、当使用命令行进行调用的时候，如果程序已经在后台运行了，会弹出【Umi-OCR 已在运行】需要确认是否多开的提示，能否添加一个选项【单进程运行】来避开这个对于命令行调用的影响；
2、1.3.5版本的，复制后直接发送按键的功能，更方便进行AHK等程序的调用集成，能否再考虑恢复一下1.3.5版本的功能，或者将自动复制结果及联动功能更改为
[ ] 自动复制结果
[ ] 自动复制结果并联动发送按键    （按键内容）
[ ] 截图联动 （按键内容）  联运发送按键     （按键内容）

**Comment by hiroi-sora** [comment]
1. 注意命令行调用入口是程序目录的`extra/umiocr.exe`，而不是软件常规入口`Umi-OCR 文字识别.exe`。使用命令行专用入口的话，就不会弹出多开提示，而是直接唤起已启动的Umi主进程 进行任务。
2. 1.3.6+中，你完全可以取消`截图识别快捷键`，将`截图联动`当成截图识别来用。这样做的效果和1.3.5是一样的。
