### ISSUE TITLE
开始任务后程序未响应

### ISSUE THREAD

**Issue by ljackie0318** [hiroi-sora/Umi-OCR#208]
你好，我在开始任务识别图片时，程序一直未响应，识别不成功后台paddle引擎已经在运行了，不知道什么原因，求大佬解答。笔记本CPU支持AVX
![image](https://github.com/hiroi-sora/Umi-OCR/assets/148438654/c0234d87-0fb5-4d88-aa01-d39966d9875e)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/148438654/f51eb09e-ee62-4317-8859-a38a36415083)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/148438654/c31150e2-1b0f-44e7-9be8-2bb5efbb7e48)

**Comment by hiroi-sora** [comment]
是不是图片比较大？大图可能识别较慢。从你的截图中，似乎软件是运行正常的。

`程序一直未响应` 指只是进度条不走，还是指整个软件都卡死了？可以切换到设置选项卡吗

**Comment by ljackie0318** [comment]
# 可以进入设置选项，但是功能都点不了。图片不大，很小的一个测试图片。截图功能也是同样的情况。点击开始任务后，进度条一直不走，联网和离线状态下都是这个情况

**Comment by ljackie0318** [comment]
大佬好，下载了rapid引擎能正常使用，然后该软件换到win7系统上，出现了以下错误（该版本在win11上能正常使用）。![IMG_20231022_141331.jpg](https://github.com/hiroi-sora/Umi-OCR/assets/148438654/576a1935-551d-45de-a437-6116cf0b4891)

**Comment by hiroi-sora** [comment]
请尝试下载安装VC运行库：
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by ljackie0318** [comment]
大佬您好，
   我电脑上之前已经装了VC_REDIST，目前您说的第三个步骤，成功运行软件。目前批量OCR和截图OCR均能正常使用。感谢！

**Comment by hiroi-sora** [comment]
这是修复版的启动器exe，将它放在原本 `Umi-OCR.exe` 相同的位置，可以代替`test_run.bat`强制启动程序。而且，它不会显示控制台窗口（可能会在启动时一闪而过），减少对正常使用的影响。

[umiocr.zip](https://github.com/hiroi-sora/Umi-OCR/files/13066400/umiocr.zip)

但是，这个修复版有一些缺陷请注意：
1. 不要删除或改名原本的启动器 `Umi-OCR.exe` 。
2. 不要使用软件自带的添加快捷方式（桌面/开始菜单。开机自启）。如果你需要添加快捷方式，请手动为修复版启动器 `umiocr.exe` 创建。
3. 修复版启动器对命令行模式的支持有限，比如不支持回传结果。

**Comment by ljackie0318** [comment]
感谢您的回复！我发现一个有意思的事情，就是我使用total commander这个软件进行文件管理，如果从这个软件启动Umi-OCR.exe会报错python3.dll，点击test_run.bat才能正常使用。
如果我从windows资源管理器启动Umi-OCR.exe程序能正常使用（启动时间大概3s）。
基于现在这个情况，我没有采用大佬的替换文件方法，而是从windows资源管理器直接启动就行。

**Comment by hiroi-sora** [comment]
在 [后续的版本中](https://github.com/hiroi-sora/Umi-OCR_v2/releases) ，如果再次遇到 `Umi-OCR.exe` 失效，可以用备用启动器：
```
UmiOCR-data/RUN_GUI.bat
```
它以最大兼容性启动软件，且不显示控制台窗口。
