### ISSUE TITLE
python 3.76 启动 点开始任务 就报错 批量任务启动引擎失败：'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by qqeip** [hiroi-sora/Umi-OCR#210]
INFO:Umi-OCR_log:命名管道\\.\pipe\umiocr等待连接
INFO:Umi-OCR_log:批量文本处理器初始化完毕！
INFO:Umi-OCR_log:启动引擎，参数：('PaddleOCR-json/PaddleOCR_json.exe', 'PaddleOCR_json_config_ch.txt', ' -limit_type=max -limit_side_len=960 -cpu_threads=10 -enable_mkldnn=True ')
INFO:Umi-OCR_log:引擎stop，停止任务！
ERROR:Umi-OCR_log:批量任务启动引擎失败：'str' object has no attribute 'decode'
INFO:Umi-OCR_log:msnB: onClose
INFO:Umi-OCR_log:任务close！

**Comment by hiroi-sora** [comment]
本项目最低支持3.8.10哦

**Comment by qqeip** [comment]
python 3.10又提示
config.py
 ModuleNotFoundError: No module named 'tkinter'

**Comment by hiroi-sora** [comment]
1. 有可能你使用的是miniconda之类的第三方python环境，标准库不全
2. 有可能你使用标准python环境，但安装时未勾选这个：

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/576b44ba-48a7-4420-bb0e-7dc313c51591)

解决方法：
1. 在已有的python环境中，安装tkinter模块。具体做法见百度。
2. 安装一个新的标准python环境，推荐3.8.10版本。

**Comment by qqeip** [comment]
好的 关了
