### ISSUE TITLE
PaddleOCR增加了表格识别的模块，Umi-OCR能否考虑进一步引入表格识别的功能？

### ISSUE THREAD

**Issue by xuxinliang** [hiroi-sora/Umi-OCR#211]
PaddleOCR增加了表格识别的模块，Umi-OCR能否考虑进一步引入表格识别的功能？

PaddleOCR新发版v2.2：开源版面分析与轻量化表格识别 - 知乎
https://zhuanlan.zhihu.com/p/397127928

**Comment by hiroi-sora** [comment]
主要问题是工作量太大。新版的paddle弃用了旧c++推理代码，新搞了一套 fast deploy 的框架。导致如果要更新引擎组件 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 的话，等于从头写个新项目。我是业余在维护项目，最近写Umi-OCR V2已经占用了全部个人时间，实在没有精力开新坑😂

次要问题是新的 fast deploy 框架的体积增大了。我测试过这个框架，它为了追求多功能，一股脑塞进了更多动态库，体积增长了几十MB。如果Umi-OCR体积过大，可能塞不进github release，使发布更困难。需要寻找一些精简的方法，或者等隔壁rapid团队出手，将之工程化。
