### ISSUE TITLE
有没有web端和api接口的想法？

### ISSUE THREAD

**Issue by lyhiving** [hiroi-sora/Umi-OCR#215]
docker化和支持linux？

**Comment by hiroi-sora** [comment]
V2支持linux理论可行，但可能依赖于桌面环境。

我个人的linux开发经验不充足，短期内没有适配计划。期待有经验的开发者参与。

**Comment by iszmxw** [comment]
可以的

**Comment by iszmxw** [comment]
> docker化和支持linux？

可以看看我封装的 docker 下的 linux 支持 [镜像操作文档](https://github.com/iszmxw/ocr)

**Comment by fishfree** [comment]
@iszmxw 你这个套娃好几层啊 :-) Dockerfile文件可否也分享一下？

**Comment by iszmxw** [comment]
> @iszmxw 你这个套娃好几层啊 :-) Dockerfile文件可否也分享一下？

没有 `dockerfile` 纯手动修改容器打包的镜像

**Comment by hiroi-sora** [comment]
最新测试版中，已实验性支持 Linux 平台。经测试，对 Debian 系发行版的兼容性较好。

有能力的用户，也可以根据我们文档，从源码构建Umi-OCR。然后打包docker。

https://github.com/hiroi-sora/Umi-OCR/releases
