### ISSUE TITLE
被人拿去卖钱了

### ISSUE THREAD

**Issue by Leonyar** [hiroi-sora/Umi-OCR#216]
闲鱼上一个叫 徽州白羊座法夏 的，拿了这个在卖钱呢

**Comment by hiroi-sora** [comment]
拿去卖的多了去了，不止这一家😂 我作为开发者似乎也确实没什么有效的反制手段。

**Comment by sixone-Jiang** [comment]
开源，但封装带UI的可执行文件的时候里面搞个时效性验证码机制，然后按一定周期发布嘛，一方面可以促进大家学习源码，一方面尽可能抑制这种那你打包好的文件去卖，一般这种贩子以及买家都懒得捣腾源码的

**Comment by songxing10000** [comment]
mac能用吗

**Comment by hiroi-sora** [comment]
> 封装带UI的可执行文件的时候里面搞个时效性验证码机制

我写这个项目的理想就是完全无限制，不给钱，不注册，不用安装，下好了就能用。爱用旧版本就用旧版本，爱用多久就用多久，不想用了随便删。

所以我也懒得/不愿意搞限制机制。

**Comment by hiroi-sora** [comment]
> mac能用吗

目前不能哦，我没有mac设备也没有开发经验。本项目代码本身支持跨平台，等以后有没有大佬来做平台运行环境适配吧。

**Comment by Leonyar** [comment]
应该不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月3日(周五) 上午10:01
收件人: ***@***.***&gt;;
抄送: "Xu ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 被人拿去卖钱了 (Issue #216)




 
mac能用吗

**Comment by songxing10000** [comment]
> > mac能用吗
> 
> 目前不能哦，我没有mac设备也没有开发经验。本项目代码本身支持跨平台，等以后有没有大佬来做平台运行环境适配吧。

我有设备M1，就是不知道如何编译你这项目

**Comment by barrierenergy** [comment]
> > mac能用吗
> 
> 目前不能哦，我没有mac设备也没有开发经验。本项目代码本身支持跨平台，等以后有没有大佬来做平台运行环境适配吧。



> 拿去卖的多了去了，不止这一家😂 我作为开发者似乎也确实没什么有效的反制手段。



> 拿去卖的多了去了，不止这一家😂 我作为开发者似乎也确实没什么有效的反制手段。

最好办法就是卖1分钱，扰乱他的市场，懒得管他的话，当我没说
