### ISSUE TITLE
双击exe运行识失败

### ISSUE THREAD

**Issue by FreedomXuanyuan** [hiroi-sora/Umi-OCR#223]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/61743153/6b018e09-35a2-445f-a0a7-bd16189015d3)

**Comment by hiroi-sora** [comment]
试试 [V2](https://github.com/hiroi-sora/Umi-OCR_v2/releases)

**Comment by FreedomXuanyuan** [comment]
可以了
