### ISSUE TITLE
双击exe之后的错误

### ISSUE THREAD

**Issue by talentscj0725** [hiroi-sora/Umi-OCR#224]
双击exe之后有以下报错：
OCR API 列表中不存在undefined
Global 处理配置项异常：
ocr.api枚举列表为空。
win7_x64_PaddleOCR-json: 动态导入包失败：cannot import name 'trLoad' from 'i18n' (unknown location)
win7_x64_RapidOCR-json: 动态导入包失败：cannot import name 'trLoad' from 'i18n' (unknown location)

**Comment by hiroi-sora** [comment]
请问你是从release下的压缩包，还是clone项目源码？

如果是源码，请确保主要代码、插件、运行环境，这三个部分（三个仓库）均更新到最新。

**Comment by hiroi-sora** [comment]
非常抱歉，经过检查，`cannot import name 'trLoad' from 'i18n'` 是我的插件Release没有及时更新所致。

现在我已经上传了新的 [Release](https://github.com/hiroi-sora/Umi-OCR_plugins/releases) 。当然，你可以不用下载，而是通过如下方法手动修正代码：

用记事本等文本编辑器，打开下述文件：
`win7_x64_PaddleOCR-json/paddleocr_config.py`
或
`win7_x64_RapidOCR-json/rapidocr_config.py`

开头有一行：
`from i18n import trLoad, tr`

将`i18n`改为`plugin_i18n`，即：
`from plugin_i18n import trLoad, tr`

保存并关闭文件。通过这个步骤，应该能修复无法导入插件的bug。
