### ISSUE TITLE
弹窗报错 Failed to create OpenGL context

### ISSUE THREAD

**Issue by MiManchiL** [hiroi-sora/Umi-OCR#225]
已经将两个dll放入文件夹中，但是报错依旧。还有其他方法吗？

**Comment by hiroi-sora** [comment]
如果你用的是v1版本，请尝试一下[v2版本](https://github.com/hiroi-sora/Umi-OCR_v2/releases)。

如果用的是v2，请给张报错截图看看。

**Comment by MiManchiL** [comment]
我更换成win11的另外台电脑不会有改错误了。但是目前报的是：
OCR API 列表中不存在undefined和Global 处理配置项异常：ocr.api枚举列表为空。
exe目前是可以打开了。
下面是我下载的信息：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/87927096/2c2b2abd-b5c5-42a3-a3cb-682cc14ea27e)

**Comment by MiManchiL** [comment]
hi 早上好，在win7系统上测试release插件和环境，其他未变情况下，在win7上只需要将两个dll补充下就可以打开了，无须在改.pre_settings了。
当我没有在plugins里复制win7_x64_PaddleOCR-json里的所有信息进去时，exe正常打开，但是复制进去后，就会报OCR API 列表中不存在undefined和Global 处理配置项异常：ocr.api枚举列表为空。
还有什么地方是我没注意到的吗？

**Comment by hiroi-sora** [comment]
非常抱歉，经过检查，`OCR API 列表中不存在undefined` 是我的插件Release没有及时更新所致。

你可以通过如下方法修正代码：

用记事本等文本编辑器，打开下述文件：
`win7_x64_PaddleOCR-json/paddleocr_config.py`
或
`win7_x64_RapidOCR-json/rapidocr_config.py`

开头有一行：
`from i18n import trLoad, tr`

将`i18n`改为`plugin_i18n`，即：
`from plugin_i18n import trLoad, tr`

保存并关闭文件。通过这个步骤，应该能修复无法导入插件的bug。
