### ISSUE TITLE
你好，我要怎么编译成EXE文件啊？

### ISSUE THREAD

**Issue by Epoch2022-iOS** [hiroi-sora/Umi-OCR#226]
提示这些信息：
PS C:\Users\Administrator\Desktop\AIScan> pyinstaller --onefile c:/Users/Administrator/Desktop/AIScan/AIScan/main.py  
185 INFO: PyInstaller: 6.2.0
185 INFO: Python: 3.8.5
186 INFO: Platform: Windows-10-10.0.19041-SP0
186 INFO: wrote C:\Users\Administrator\Desktop\AIScan\main.spec
188 INFO: Extending PYTHONPATH with paths
['c:\\Users\\Administrator\\Desktop\\AIScan\\AIScan']
317 INFO: checking Analysis
393 INFO: checking PYZ
449 INFO: checking PKG
513 INFO: Bootloader e:\python\python38\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
513 INFO: checking EXE
PS C:\Users\Administrator\Desktop\AIScan>

**Comment by hiroi-sora** [comment]
打包v1.3版：参考 [使用源代码](https://github.com/hiroi-sora/Umi-OCR#%E4%BD%BF%E7%94%A8%E6%BA%90%E4%BB%A3%E7%A0%81)

打包v2.0版：请阅读 [Umi-OCR_v2](https://github.com/hiroi-sora/Umi-OCR_v2) ，后部分介绍了开发环境部署流程。

关于你的日志，我估计是 `--onefile` 的参数不对。总之，请参照上述说明。

**Comment by Epoch2022-iOS** [comment]
好的 非常感谢，请问这个支持在MacOS上运行吗？

**Comment by hiroi-sora** [comment]
抱歉，暂不支持哦
