### ISSUE TITLE
批量识别任务异常

### ISSUE THREAD

**Issue by iewhz** [hiroi-sora/Umi-OCR#227]

**Comment by iewhz** [comment]
批量识别任务异常
[Error]OCR init fail.Argd：f'enable_mkldnn'：True，'cpu_threads'：10，'config_path'：'models/
config_chinese.txt'，'cls'：False，'use_angle_cls'：False，'limit_side_len'：999999）

**Comment by iewhz** [comment]
批量识别任务异常
[Error]OCR init fail.Argd：f'enable_mkldnn'：True，'cpu_threads'：10，'config_path'：'models/
config_chinese.txt'，'cls'：False，'use_angle_cls'：False，'limit_side_len'：999999）

**Comment by hiroi-sora** [comment]
大概率是CPU不兼容，请使用Rapid引擎版本。
