### ISSUE TITLE
可否升级到 python3.10，甚至是 3.11

### ISSUE THREAD

**Issue by FlyInWind1** [hiroi-sora/Umi-OCR#228]
我自己试了下 miniconda 的 3.10，相比于自带的 3.8，启动速度快了很多，体感很明显

**Comment by hiroi-sora** [comment]
> 可否升级到3.10以上？

当然是可以的。请按下列步骤操作：

1. 下载相应版本的Python **embeddable package** 包，解压放置到 `UmiOCR-data/runtime` 中。
https://www.python.org/downloads/windows/

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/c6d2de94-73d1-4ad4-933d-e5f37166b330)

2. Umi中有一些第三方库是绑定3.8的，你需要重新下载甚至编译它。已知需要更新的库有：

**Pillow**：需要下载 https://pypi.org/project/Pillow/#files
**zxing_cpp**：需要编译，参考 https://github.com/hiroi-sora/Umi-OCR_v2/issues/47
（如果嫌麻烦，可以先不管`zxing_cpp`。这会让二维码功能无法使用，但不会影响OCR相关的功能。）

将上述库的文件（`.whl`解压后的文件夹）放置到 `UmiOCR-data/site-packages` 即可。

个人实测，3.11是可以使用的。

> 为什么本项目不使用高版本Python？

因为 3.8 是官方最后一个支持win7的版本。考虑到本项目有很多win7用户，故选用兼容性最好的版本作为发行包。

不过，开发者当然可以自己调整和定制本项目的运行环境。

> 使用高版本Python的提升明显吗？

固然，新版py的运行速度有很大的提升，但对本项目的效率可能帮助不大。

Umi-OCR内部实际上有三个运行环境：跑OCR的C++推理引擎，跑UI界面的qml引擎，及跑业务逻辑的python解释器。前两者（C++和qml）已经是同类项目中最高效的了，python只是作为它们之间的胶水。故py速度再快，也难以影响到OCR的速度或前端的流畅度。

当然，**启动速度更快**可能是存在的，不过体感不明显。你可以试试~

**Comment by FlyInWind1** [comment]
谢谢解答。另外问一个其它的问题，python3.11的pySide2是在哪下的，我用3.11进行pip install pyside2，安装失败

**Comment by hiroi-sora** [comment]
首先请仔细了解 [构建项目](https://github.com/hiroi-sora/Umi-OCR#%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE) ，本项目导入第三方包一般不使用pip。

其次，3.8到3.11的pyside2应该是能通用的。我在3.11上测试，似乎当前版本的pyside2没有问题。

**Comment by FlyInWind1** [comment]
了解了

**Comment by FlyInWind1** [comment]
希望可以尝试一下 https://github.com/adang1345/PythonWin7
