### ISSUE TITLE
建议添加 MIT License 以方便 Scoop 收录

### ISSUE THREAD

**Issue by StudentWeis** [hiroi-sora/Umi-OCR#23]
首先感谢作者大大的作品，我很喜欢。

另外，[我正在向 Scoop 的 Extra 桶提交本应用](https://github.com/ScoopInstaller/Extras/pull/9270)，建议添加一份开源 License 以方便 Scoop 收录，我建议 MIT License。

**Comment by hiroi-sora** [comment]
感谢支持和建议~已加

**Comment by StudentWeis** [comment]
OK，目前已通过了 Scoop 的收录测试。
