### ISSUE TITLE
启动报错：Umi-OCR 异常退出 代码1 ，1.3.7版本启动正常

### ISSUE THREAD

**Issue by Chemicalform** [hiroi-sora/Umi-OCR#232]
运行test_speed.bat，提示如下文字
“翻译未加载。
QQmlApplicationEngine failed to load component
file:///E:/Desktop/Umi-OCR_Paddle_v2.0.0/UmiOCR-data/qt_res/qml/Main.qml:58:9: Type SystemTray unavailable
file:///E:/Desktop/Umi-OCR_Paddle_v2.0.0/UmiOCR-data/qt_res/qml/MainWindow/SystemTray.qml:7:1: plugin cannot be loaded for module "Qt.labs.platform": Cannot load library E:\Desktop\Umi-OCR_Paddle_v2.0.0\UmiOCR-data\site-packages\PySide2\qml\Qt\labs\platform\qtlabsplatformplugin.dll: ???????????????”

**Comment by Chemicalform** [comment]
paddle版本与rapid版本都无法启动，报错均为Umi-OCR 异常退出 代码1，
CPU为i5 7300HQ，支持AES、AVX、AVX2

**Comment by hiroi-sora** [comment]
感谢你提供的报错信息。

从信息上分析，这是pyside2库本身的兼容性问题，与OCR引擎无关（因此与CPU型号无关）。一个名为 `qtlabsplatformplugin.dll` 的动态库在你的电脑上无法加载。
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/7604a8f3-e6ea-420a-afb5-03c0c7486df5)

你可以尝试这个方法：
1. 下载完整版PySide2包：
https://hiroi-sora.lanzoul.com/iQUl31fosmfg
2. 将上述文件解压，放入该路径： `UmiOCR-data/site-packages` ，并覆盖原有文件。
3. 运行 `UmiOCR-data/RUN_CLI.bat` 看看是否还有报错。

以下是一些可能相关的帖子：
https://forum.qt.io/topic/132592/problem-with-colordialog-plugin-cannot-be-loaded-for-module-qt-labs-platform-using-qml/5
`https://github.com/Nuitka/Nuitka/issues/76`

**Comment by Chemicalform** [comment]
仍然报错，错误提示变成了
Qt plugins目录导入失败！
Qt plugins directory import failed！
DLL load failed while importing shiboken2：%1不是有效的Win32应用程序。

**Comment by hiroi-sora** [comment]
抱歉，可能误传了32位版。请再试试这个： https://hiroi-sora.lanzoul.com/iE6Ns1fra50j

**Comment by Chemicalform** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/34792518/0b88a7aa-e4be-403e-af41-7d6115f3f7a8)
放进去后又是
Umi-OCR 异常退出 代码1 
Umi-OCR exited abnormally.Code:1

**Comment by hiroi-sora** [comment]
看看 `UmiOCR-data/RUN_CLI.bat` 的运行结果是啥，是否还是和 `qtlabsplatformplugin.dll` 相关？

应该和本机的python版本无关，本项目是独立的嵌入式python环境。

**Comment by Chemicalform** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月23日(星期四) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hiroi-sora/Umi-OCR] 启动报错：Umi-OCR 异常退出 代码1 ，1.3.7版本启动正常 (Issue #232)





 
看看 UmiOCR-data/RUN_CLI.bat 的运行结果是啥，是否还是和 qtlabsplatformplugin.dll 相关？
 
应该和本机的python版本无关，本项目是独立的嵌入式python环境。

**Comment by hiroi-sora** [comment]
你可能上传了图片，但我这边看不到

**Comment by hiroi-sora** [comment]
如果你愿意的话可以做个实验：

在本机python（或者创一个py虚拟环境），`pip install PySide2` ，然后运行下面这段代码：

```python
import sys
from PySide2.QtGui import QGuiApplication
from PySide2.QtQml import QQmlApplicationEngine
from PySide2.QtCore import QCoreApplication, QUrl

qml_code = """
import QtQuick 2.0
import QtQuick.Controls 2.0
import Qt.labs.platform 1.1

ApplicationWindow {
    id: root
    visible: true
    title: "Hello World"
}
"""


app = QGuiApplication(sys.argv)
engine = QQmlApplicationEngine()
engine.addImportPath("./myvenv/Lib/site-packages/PySide2/qml")
engine.loadData(qml_code.encode(), QUrl())
app.exec_()
```

看看这段代码会不会报相同的错误。

**Comment by Chemicalform** [comment]
QQmlApplicationEngine failed to load component
<Unknown File>:4:1: plugin cannot be loaded for module "Qt.labs.platform": ????????C:\Users\12059\AppData\Local\Programs\Python\Python38\lib\site-packages\PySide2\qml\Qt\labs\platform\qtlabsplatformplugin.dll?????????????????

**Comment by hiroi-sora** [comment]
感谢测试。表明了这就是qt动态库的问题，与python无关（换用C++编译的qt，在你的电脑上大概率也会有相同问题。）

此问题非常稀有，网上难以找到相同症状的案例。最接近的是 [这个](https://forum.qt.io/topic/132592/problem-with-colordialog-plugin-cannot-be-loaded-for-module-qt-labs-platform-using-qml) ，这篇帖子最后的方案是导入 `Qt5Widgets.dll` 。但是对于pyside，原本就自带了 `Qt5Widgets.dll` ，所以也不适用于你的情况。

当然还有一种可能是 `Qt5Widgets.dll` 存在兼容问题，间接导致 `qtlabsplatformplugin.dll` 无法加载。但是按qt框架耕耘那么多年的底蕴，qt5.15也是兼容性最好的版本，理应很少会有兼容性问题吧……非常奇怪。

应该跟硬件无关，绝对是系统的问题，一些系统库可能改动过或不全，导致qt跑不起来。重装大概率可解，哈哈

总之抱歉，我对这个问题没有更多思路了。请先使用旧版，有新进展我会告知。

**Comment by Chemicalform** [comment]
谢谢，麻烦大佬了，其他电脑上软件运行都很正常，得空重装下系统试试

**Comment by 510457577** [comment]
Hi！ 您好
            借着本问题回复邮件跟您请教一些问题，冒昧的给你发邮件打扰您了。
            我这边最近接触到一个课题，正好用到了Umi-OCR的很多功能，想做一些定制化的发开发工作，不知道您是否有兴趣一起参与该项目。如果您愿意参与该项目具体需求我们详细聊聊，另外开发费用的事情，也可以一起沟通一下。谢谢
            以下是我的联系方式，盼复。谢谢
            微信：510457577        
            ***@***.***



***@***.***
 
发件人： hiroi-sora
发送时间： 2023-11-24 10:23
收件人： hiroi-sora/Umi-OCR
抄送： Subscribed
主题： Re: [hiroi-sora/Umi-OCR] 启动报错：Umi-OCR 异常退出 代码1 ，1.3.7版本启动正常 (Issue #232)
感谢测试。表明了这就是qt动态库的问题，与python无关（换用C++编译的qt，在你的电脑上大概率也会有相同问题。）
此问题非常稀有，网上难以找到相同症状的案例。最接近的是 这个 ，这篇帖子最后的方案是导入 Qt5Widgets.dll 。但是对于pyside，原本就自带了 Qt5Widgets.dll ，所以也不适用于你的情况。
当然还有一种可能是 Qt5Widgets.dll 存在兼容问题，间接导致 qtlabsplatformplugin.dll 无法加载。但是按qt框架耕耘那么多年的底蕴，qt5.15也是兼容性最好的版本，理应很少会有兼容性问题吧……非常奇怪。
应该跟硬件无关，绝对是系统的问题，一些系统库可能改动过或不全，导致qt跑不起来。重装大概率可解，哈哈
总之抱歉，我对这个问题没有更多思路了。请先使用旧版，有新进展我会告知。

**Comment by hiroi-sora** [comment]
@510457577 

抱歉，我本身学习工作比较繁忙，暂时没有精力参与您的项目。

本项目注释充足，设计易于拓展，二次开发工作会相对容易。如果你和你的团队遇到问题，可以在本项目Discussions或Issues提问，我会力所能及的提供解答。
