### ISSUE TITLE
用是什么ocr模型？ppocrv4?模型文件在哪

### ISSUE THREAD

**Issue by xinsuinizhuan** [hiroi-sora/Umi-OCR#233]

**Comment by hiroi-sora** [comment]
模型文件放在 `UmiOCR-data\plugins\……\models` 。

`Paddle` 插件用的模型库还是V3（因为V4有兼容性问题）。`Rapid` 插件用的是V4。

如果感兴趣，请了解 [插件仓库](https://github.com/hiroi-sora/Umi-OCR_plugins)
