### ISSUE TITLE
建议开发批量双层PDF制作

### ISSUE THREAD

**Issue by Marx-one** [hiroi-sora/Umi-OCR#236]
作者您好，本人是文科专业，书籍大多是扫描版本图书，写论文时看扫描图书最头疼的就是无法直接检索，能不能开发该软件，可以批量制作双层PDF，谢谢您！

**Comment by hiroi-sora** [comment]
嗯，PDF识别已有计划，双层PDF在考虑中。

**Comment by Marx-one** [comment]
感谢，如有可能，还请您考虑下双层PDF，这对文科生来说太有用了











                       
原始邮件
                       
                     

发件人："hiroi-sora"< ***@***.*** &gt;;

发件时间：2023/11/26 0:28

收件人："hiroi-sora/Umi-OCR"< ***@***.*** &gt;;

抄送人："LH"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [hiroi-sora/Umi-OCR] 建议开发批量双层PDF制作 (Issue #236)




 
嗯，PDF识别已有计划，双层PDF在考虑中。

**Comment by hiroi-sora** [comment]
v2.1.0 测试版 已支持PDF识别，并支持输出双层可搜索PDF。

https://github.com/hiroi-sora/Umi-OCR/releases
