### ISSUE TITLE
Title：Umi-OCR搭配Snipaste使用会出现快捷键失灵现象

### ISSUE THREAD

**Issue by xltx88** [hiroi-sora/Umi-OCR#244]

**Comment by xltx88** [comment]
使用Snipaste快捷键贴图后半秒内使用Umi-OCR快捷键会出现失灵现象。
复现步骤：
1、Snipaste使用F1快捷键截图，然后按F3贴图。
2、然后短时间内按Umi-OCR快捷键F2截屏发现无反应。
以上快捷键均为单键。

环境信息：
Snipaste2.7.2-Beta#
Umi-OCR v2.0.0
Windows10 LTSC 2019 企业版  版本号：1809

**Comment by hiroi-sora** [comment]
感谢测试。你可以试试给Umi管理员权限，应该就能避免Snipaste的影响。

未来Umi将优化快捷键机制或添加获取管理员权限的功能。

**Comment by xltx88** [comment]
> 谢谢。你可以尝试给Umi管理员权限，应该可以测试避免Snipaste的影响。
> 
> 未来Umi将优化快捷键或添加获取管理员权限的功能。

经过几天的实际使用，该问题已得到解决。感谢作者

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/402
