### ISSUE TITLE
运行这个工程时报OCR API列表不存在等问题，想着自己用源码运行一下这个应用，已经 按照Umi-OCR_runtime_windows拷贝了

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [hiroi-sora/Umi-OCR#245]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/28779327/adde50f5-e5b9-481c-a27d-c03f0b66ba5b)

**Comment by wangwenqiangGitHub** [comment]
想用qmlscene调试一下前端的界面，这个环境也不支持，需要配置什么?
想问下为什么没有采用python虚拟环境的形式开发呢

**Comment by hiroi-sora** [comment]
### 1. 当你用 qmlscene 试图调试Main.qml时，应该显示如下报错：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/49a2275c-0317-4433-ae41-9580cd9a34f6)
这是正常现象，表示 c++ / python 自定义模块未能加载。 qmlscene 是调试纯qml的工具，而本项目的qml中使用了大量的py自定义模块， qmlscene 是不能加载和调试这些模块的。
按照 [qt官方文档](https://doc.qt.io/qt-5/qtquick-qmlscene.html) 的说法，可以制作一些qml文件作为自定义模块的填充，在qml中提供与自定义模块相同的空接口（无实际功能）来让 qmlscene 跑起来。但我觉得这就没有必要了。
总之，本项目不太适合用 qmlscene 进行调试。

### 2. 没有采用python虚拟环境的形式开发呢？

因为虚拟环境的打包相对麻烦，尤其是对于Umi这样含有外部依赖（插件）和大体积库（pyside）的项目。我考虑过pyinstaller、Nuitka、QPT等打包工具，最终还是放弃了。目前选择的嵌入式环境方式，可以方便的管理插件、手动精简第三方库、提取打包为发行包，我感觉用起来不错。

当然，采用普通python解释器+虚拟环境的方式进行开发也是OK的，只是要修改一下 [main.py](https://github.com/hiroi-sora/Umi-OCR/blob/main/UmiOCR-data/main.py) 和 [run.py](https://github.com/hiroi-sora/Umi-OCR/blob/main/UmiOCR-data/py_src/run.py)  ，其它代码应该不用动。

### 3. OCR API列表不存在

你是否没有放置插件？请前往 [插件库](https://github.com/hiroi-sora/Umi-OCR_plugins) 下载任意一个OCR引擎插件，放置到 `UmiOCR-data\plugins` 目录下。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/9de0a73d-4f64-473c-9eb9-8585cb59d038)

**Comment by wangwenqiangGitHub** [comment]
感谢解答，根据操作已经可以顺利运行了，很好的开源项目，值得学习，希望出一个mac版
