### ISSUE TITLE
截图识别任务异常

### ISSUE THREAD

**Issue by TwinkleStarDust** [hiroi-sora/Umi-OCR#246]
[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 12, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
![Screenshot 2023-11-28 155550](https://github.com/hiroi-sora/Umi-OCR/assets/108475509/3c08896c-51fa-4c08-a72e-508e7bdc35ce)

**Comment by TwinkleStarDust** [comment]
> 可能是Paddle版本cpu不兼容，请下载Rapid版本尝试。

12600KF不兼容咩。。2.0之前还好好的，我看了一下还有一个弹窗您看看
![Screenshot 2023-11-28 155858](https://github.com/hiroi-sora/Umi-OCR/assets/108475509/b591625d-fc97-474e-9e4d-3e2d7ba0efeb)

**Comment by hiroi-sora** [comment]
这就有点奇怪。0xc0000142是指令集不兼容的显著特征。但12代iu肯定是兼容的，必不可能少指令集。

你试试直接运行 UmiOCR-data/plugins/paddle文件夹/paddleocr-json.exe ，看看有哪些报错弹窗。是不是只有0xc0000142这一个弹窗。

**Comment by TwinkleStarDust** [comment]
> 这就有点奇怪。0xc0000142是指令集不兼容的显著特征。但12代iu肯定是兼容的，必不可能少指令集。
> 
> 你试试直接运行 UmiOCR-data/plugins/paddle文件夹/paddleocr-json.exe ，看看有哪些报错弹窗。是不是只有0xc0000142这一个弹窗。

哈哈哈你说这个我就明白了，前几天超频去把bios里AVX 支持关了哈哈哈，刚去打开就没有报错正常运行了，作者辛苦了

**Comment by hiroi-sora** [comment]
哈哈哈哈哈，欢迎收看走进科学之：消失的指令集
