### ISSUE TITLE
Umi-OCR_Paddle_v2.0.0 截图OCR 中的 “记录” 标签页中的 “耗时 0.16 置信 0.91” 是不是应该为“执行”

### ISSUE THREAD

**Issue by dongshan3** [hiroi-sora/Umi-OCR#247]
帅哥，您好。我刚下载了 Umi-OCR_Paddle_v2.0.0，试用了 “截图OCR” 的功能。这个软件，挺棒的。

我在看识别文字的记录时，好像对其中的“耗时 0.16 置信 0.91” 有点理解不了。如果前边“耗时 0.16”指的是截图这个动作花了0.16秒，后边是不是理解为“执行 0.91”，文字识别这个动作花了0.91秒？

谢谢。
![umi-ocr_v2 0 0_typed](https://github.com/hiroi-sora/Umi-OCR/assets/9460409/0f85e40a-2987-47b7-b7e8-509771b86b9c)

**Comment by hiroi-sora** [comment]
不，这是“置信度”的意思哦。它是一个0~1的值，越接近1表示结果（理论上）越准确。

使用情景：比如在批量识别+输出json原始信息 的时候，使用者可以批量筛选出置信度较低的图片，进行人工校对。

**Comment by hiroi-sora** [comment]
我也感觉这个词可能有歧义，已经修改为“置信度”了。

**Comment by dongshan3** [comment]
> 不，这是“置信度”的意思哦。它是一个0~1的值，越接近1表示结果（理论上）越准确。
> 
> 使用情景：比如在批量识别+输出json原始信息 的时候，使用者可以批量筛选出置信度较低的图片，进行人工校对。

谢谢解答。
