### ISSUE TITLE
请问，【文本后处理】中的【段落合并】是使用什么方法实现的呢？

### ISSUE THREAD

**Issue by Thunderltx** [hiroi-sora/Umi-OCR#249]
想知道具体的方法，因为我现在用PP的OCR出来的文本只会划块儿，没有段落

**Comment by hiroi-sora** [comment]
[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 的Python API中有独立的段落合并模块，详见 [使用手册](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python) 。

这是从Umi-OCR中分离出来的模块。你可以直接拿去用哦~

**Comment by Thunderltx** [comment]
> [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 的Python API中有独立的段落合并模块，详见 [使用手册](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python) 。
> 
> 这是从Umi-OCR中分离出来的模块。你可以直接拿去用哦~

谢谢告知，感谢感谢
