### ISSUE TITLE
软件建议

### ISSUE THREAD

**Issue by lioArther** [hiroi-sora/Umi-OCR#25]
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22000 暂缺 Build 22000
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
系统制造商:       AZW
系统型号:         GTR
系统类型:         x64-based PC
处理器:           AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3301 Mhz

1. 在1.2.6的版本中，点击”录制按键“，软件会出现短暂的卡死。
2. 建议增加可以后台运行，当前点击关闭按键，软件就直接被关闭
3. 建议增加截图识别功能，可以截取选择需要识别的区域
4. 增加开机自动启动，虽然当前可以自己设置。

**Comment by hiroi-sora** [comment]
1. 点击录制按键卡死暂时是无解的，因为主线程在等待键盘按下。如果新开一个线程来维持主界面不卡死，会添加很多工作量和潜在的Bug，我暂时不愿意修改。当然，下版本会优化录制按键时的提示。
2. 关闭时收纳到托盘区（即后台运行）已经在做了。顺便问一下，你们喜欢按“关闭”时收到托盘，还是按“最小化”时收到托盘？
3. 截图识别在做了在做了😂
4. 将快捷方式扔到 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` 就能开机自启。软件内自动设置的话可能有点麻烦，我调查一下。

**Comment by lioArther** [comment]
2. 我个人的话，其实都无所谓。但是按照较多软件，“关闭”是最小化吧。

**Comment by hiroi-sora** [comment]
`v1.3.0` 已更新后台运行和内置截图。
