### ISSUE TITLE
V2快捷键无法捕捉当鼠标移入才能显示的提示框

### ISSUE THREAD

**Issue by jocksliu** [hiroi-sora/Umi-OCR#251]
浏览器、桌面、各类软件等有很多区域有这样一种类型的提示框
：当鼠标移入时显示
：当鼠标移出时隐藏
提示框类似如下效果
![image](https://github.com/hiroi-sora/Umi-OCR/assets/94985963/94afdda9-4a7a-4523-9c46-dfea6d3f4db3)

在V1.3.7版本中，当出现这个提示框时，按下快捷键，截图区域的画面可以捕捉这个提示框文本。
在V2.0版本中，当出现这个提示框时，按下快捷键，截图区域的画面这个提示文本消失，导致无法捕捉。

该问题对于用户影响较大，个人猜测截图定格画面优先级太低或者定格延迟太大导致，建议大佬优化。

**Comment by jocksliu** [comment]
另外提一句，软件很好用，但没找到打赏入口

**Comment by hiroi-sora** [comment]
> 无法鼠标悬停提示框

这是因为v2默认启用了`截图前隐藏主窗口`的功能，所以截图会延迟0.2s以等待主窗口关闭的动画。该功能在v1.3是默认关闭的。

当然，v2也可以关闭该功能：全局设置→截图→`截图前隐藏主窗口`，将✅︎取消勾选即可。

这样，截图不会有延迟，悬浮提示窗也是可以截取到的。

> 打赏

本项目暂时不开设打赏渠道。用户点个⭐︎就是对我的支持啦~

**Comment by jocksliu** [comment]
谢谢大佬，完美解决我的问题，已加星。
