### ISSUE TITLE
如何知道OCR识别一行文本已结束

### ISSUE THREAD

**Issue by Fred2998** [hiroi-sora/Umi-OCR#252]
在调用OCR接口时，能不能增加一个功能：就是标识一下一行中的最后一个文本。如果一行文本中有多种大小不一的字体，确实不好知道当前文本是这一行还是下一行，但这种情况毕竟是少数，也许你有更好的办法。谢谢

**Comment by hiroi-sora** [comment]
了解你的需求了，考虑一下。

对了，同一行中的字体都是相同大小的哦。

**Comment by Fred2998** [comment]
是的，同一行的字体基本都是相同大小的，这种情况点了99%，还有1%不好处理可以忽略不计。

**Comment by Fred2998** [comment]
我想问一下，这个什么时候更新？

**Comment by Fred2998** [comment]
不是啊，在调用OCR接口识别的数据里面标识每行的末尾。比如我要识别一张火车票

**Comment by Fred2998** [comment]
或者你在每行的末尾增加一个字段作为标识也行：islast：true / false

**Comment by hiroi-sora** [comment]
明白。其实OCR引擎本身是无法识别段落的，Umi-OCR依赖自己写的一套方案进行段落识别。你的需求涉及到该方案的调整和优化，已有计划，但可能没有那么快更新。

**Comment by Fred2998** [comment]
是的，如果图片是一张表格，没有最后行的标识，将很难复原。。。

**Comment by Fred2998** [comment]
问下，这个功能什么时候可以用？

**Comment by hiroi-sora** [comment]
抱歉，年末事情多，可能得1月份了。

段落识别的更新，可能需要一些启发式算法或聚类算法的研究，有一定难度和工作量。

**Comment by Fred2998** [comment]
问下，这个功能现在好了吗

**Comment by hiroi-sora** [comment]
目前的话，其实你可以使用`多行-代码段`的段落合并方案（http接口参数`"tbpu.merge": "MergeParaCode"`），它返回的结果是以行为单位的，同一行的不同部分以空格分隔。你可以先从结果列表中获取每一行，然后用空格来划分不同语句。

**Comment by Fred2998** [comment]
看了下，新版确实有这个功能。后续功能最好有PDF及表格识别，这两个功能使用也很广泛。

**Comment by hiroi-sora** [comment]
嗯，PDF识别正在开发，已取得较大进展。快的话月底能出

**Comment by hiroi-sora** [comment]
在 v2.1.0 正式版中，HTTP接口返回的字典中会额外包含一个 ["end"] 项，表示该文本块结尾的间隔符。你可以通过 end == "\n" 来快速判断这行文本是否结束。

详见 [HTTP接口手册](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_HTTP.md#data-%E6%A0%BC%E5%BC%8F) 。
