### ISSUE TITLE
请问后续有没有计划添加别的引擎版本？

### ISSUE THREAD

**Issue by zhangqian1229** [hiroi-sora/Umi-OCR#255]
比如calamari之类的，感谢

**Comment by hiroi-sora** [comment]
Umi添加新引擎是非常容易的，我刚刚就添加了一个支持公式识别的[Pix2Text引擎插件](https://github.com/hiroi-sora/Umi-OCR/issues/254)。

有一定开发经验的用户，也可以自己编写/适配OCR插件。请见 [插件开发手册](https://github.com/hiroi-sora/Umi-OCR_plugins/blob/main/demo_AbaOCR) 。

不过，Umi-OCR项目本身，是否会采用新引擎插件，取决于：
- 是否具有特色（如公式识别）
- 性能优秀（尤其是充分利用CPU性能）
- 识别精度高
- 体积足够小
- 兼容多种系统
