### ISSUE TITLE
报错：[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 8, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 999999}

### ISSUE THREAD

**Issue by Thinking2018** [hiroi-sora/Umi-OCR#256]
[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 8, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 999999}

**Comment by yisuixinq** [comment]
> [Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 8, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 999999}

遇到一样的问题了，在paddle版本中出现, Rapid 版没有

**Comment by yisuixinq** [comment]
> 大概率是CPU不兼容。Paddle引擎不支持 奔腾、赛扬、凌动 CPU，它们缺乏AVX指令集。
> 
> 请使用Rapid引擎版本，对CPU没有特殊要求。

Intel(R) Core(TM) i7-1065G7 CPU

**Comment by Thinking2018** [comment]
真的诶！用Rapid版就成功了😂。感谢感谢🙏🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 晚上8:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 报错：[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 8, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 999999} (Issue #256)




 
大概率是CPU不兼容。Paddle引擎不支持 奔腾、赛扬、凌动 CPU，它们缺乏AVX指令集。
 
请使用Rapid引擎版本，对CPU没有特殊要求。

**Comment by yisuixinq** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/40953718/44017f0e-82a8-44e2-97a4-f8509eea7e94)

BIOS没看

**Comment by hiroi-sora** [comment]
@yisuixinq 

看来应该不是指令集的问题。那么运行OCR报错的时候，有没有出现`0xc0000142`的弹窗呢？

即，是否为两个弹窗，一个是Windows弹出的`0xc0000142`，一个是软件内弹出的 `[Error] OCR init fail` ？

**Comment by yisuixinq** [comment]
只有一个软件内弹出的 [Error] OCR init fail，没有Windows下弹窗

另外两个版本的软件在我这台电脑下都不能双击运行，只能在命令行运行`umi-ocr`命令才能跑起来

![image](https://github.com/hiroi-sora/Umi-OCR/assets/40953718/b6976a58-f1e7-4a60-8e62-a221cbc0b9ce)

**Comment by hiroi-sora** [comment]
@yisuixinq 

了解。那么尝试直接运行该文件：
```
UmiOCR-data\plugins\win7_x64_PaddleOCR-json\PaddleOCR-json.exe
```
正常情况下，应该打开一个命令行窗口，最终输出`OCR init completed`。如果它有任何异常情况请告诉我。

**Comment by yisuixinq** [comment]
@hiroi-sora 
![image](https://github.com/hiroi-sora/Umi-OCR/assets/40953718/72af20d4-2340-41c3-8443-88528892b4d4)

**Comment by hiroi-sora** [comment]
哦哦，很有用的情报！

这是本项目中首次发现这种报错`MFPlat.DLL was not found`。所幸，网上有很多相关情况可以参考。

你可参考下述网页，尝试修复此问题。
https://zhuanlan.zhihu.com/p/596229445
https://www.partitionwizard.com/partitionmanager/fix-mfplat-dll-missing.html
https://blog.csdn.net/gggiweeq/article/details/133485462
https://thegeekpage.com/fix-mfplat-dll-missing-on-windows-10/
