### ISSUE TITLE
error: UI 错误

### ISSUE THREAD

**Issue by dnslin** [hiroi-sora/Umi-OCR#259]
全局设置界面下 UI超出容器 
![image](https://github.com/hiroi-sora/Umi-OCR/assets/49158572/46fe64c1-2da0-4e76-9572-8925498c7c9d)

**Comment by hiroi-sora** [comment]
请问你是什么显卡（or核显）？

全局设置，将 **渲染器** 改为 `Desktop OpenGL` 或 `关闭硬件加速` 试试。

**Comment by dnslin** [comment]
修改为Desktop OpenGL 可以了
