### ISSUE TITLE
添加文本排版或合并功能

### ISSUE THREAD

**Issue by jabberwockyr** [hiroi-sora/Umi-OCR#26]
非常感谢您的这个软件，长图识别正确率很高，但是在段落较长、屏幕宽度小于文本长度时时会出现文本断行的情况，所以想问您考虑增加一个文本排版功能吗？类似于PandaOCR的[这个功能](https://github.com/miaomiaosoft/PandaOCR/wiki/%E6%96%87%E6%9C%AC%E6%8E%92%E7%89%88%E6%88%96%E5%90%88%E5%B9%B6)

**Comment by hiroi-sora** [comment]
是的，早有计划。[开发中~](https://github.com/hiroi-sora/Umi-OCR/tree/main/ocr/tbpu)

我主要采用文本块的坐标位置信息来合并，理论上准确度会比单纯依靠字符来分块要高。

目前的效果预览：

![文本合并预览](https://user-images.githubusercontent.com/56373419/192543071-957ff6d0-095b-4f0d-9720-dc92e3e2c22a.png)
