### ISSUE TITLE
cannot find runtime/pythonw.exe windows 10 系统

### ISSUE THREAD

**Issue by zhumingyu** [hiroi-sora/Umi-OCR#261]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/10820548/be5d6322-8869-4832-8c5d-2efabe3679d0)
你好，请问这个提示是缺少哪个依赖库？谢谢

**Comment by hiroi-sora** [comment]
工作路径错误。你是调用`RUN_GUI.bat`吗？它必须在`UmiOCR-data`目录下调用或启动，才能正确地识别相对路径。你应该是直接在cmd默认位置（即`WINDOWS\system32`）调用，因此脚本无法识别相对路径。

**Comment by AquaHarp** [comment]
> 工作路径错误。你是调用`RUN_GUI.bat`吗？它必须在`UmiOCR-data`目录下调用或启动，才能正确地识别相对路径。你应该是直接在cmd默认位置（即`WINDOWS\system32`）调用，因此脚本无法识别相对路径。

可能是直接右键管理员运行了。在某些时候,右键管理员运行会把工作目录变成`WINDOWS\system32`导致出问题,在批处理文件的第一行加上
`pushd %~dp0`
或
`cd /d "%~dp0"`
可以解决

**Comment by hiroi-sora** [comment]
@AquaHarp 感谢~
