### ISSUE TITLE
2.0.0和1.3.7都用不了

### ISSUE THREAD

**Issue by yipmanho** [hiroi-sora/Umi-OCR#262]
![1701798529701](https://github.com/hiroi-sora/Umi-OCR/assets/153013326/a058df80-00c6-46b3-8401-ccecbbe2f813)
![1701798533430](https://github.com/hiroi-sora/Umi-OCR/assets/153013326/13856530-13a6-4c70-bcca-84e3b25c1b09)

**Comment by yipmanho** [comment]
![1](https://github.com/hiroi-sora/Umi-OCR/assets/153013326/48327dc0-8bb5-44f7-b310-80dbb46f319e)

**Comment by hiroi-sora** [comment]
啊？这也太奇怪了，Rapid引擎的兼容性是相当好的，还没见过跑不起来的。

请试试单独运行这个程序：
```
UmiOCR-data\plugins\win7_x64_RapidOCR-json\RapidOCR-json.exe
```

正常情况下，它应该显示`OCR init completed`。如果有报错，贴上来我看看

**Comment by yipmanho** [comment]
是显示OCR init completed  还是不行

**Comment by hiroi-sora** [comment]
OK，看来引擎没有问题，那么可能是接口与引擎的通信存在问题。结合1.3的报错弹窗来看，可能是进程交互时，无法识别路径的。

请尝试以下操作：
1. 用记事本打开 v2.0 Rapid版的以下文件：
```
UmiOCR-data\plugins\win7_x64_RapidOCR-json\api_rapidocr.py
```

2. 第10行，原本是：
```
ExePath = os.path.dirname(os.path.abspath(__file__)) + "/RapidOCR-json.exe"
```
将它改为`RapidOCR-json.exe`的绝对路径，比如：
```
ExePath = "C:/Users/Administrator/Desktop/工具/Umi-OCR_Rapid_v2.0.0/UmiOCR-data/plugins/RapidOCR-json.exe"
```

3. 第60行，原本是：
```python
            return f"[Error] OCR init fail. Argd: {tempConfigs}"
```
改为：
```python
            return f"[Error] OCR init fail. Argd: {tempConfigs} / {e}"
```

保存关闭此文件，重试OCR，看看有何变化。如果仍有`[Error] OCR init fail`的报错，其中会包含更多信息。请重新截图给我看看。

**Comment by yipmanho** [comment]
重装了一下系统 都能用了 应该是缺少了什么系统文件  谢谢大佬
