### ISSUE TITLE
作者，您好，您的软件很好用，我有两点小建议

### ISSUE THREAD

**Issue by lizuidie** [hiroi-sora/Umi-OCR#264]
第一，可以在设置上加入左侧图片默认不在图片上面显示文字识别结果的选项吗？因为这样便于校对，每次识别后再点击一次文字那个√有时占用时间，不如直接设置一个这个选项，喜欢看原图来校对的可以利用这个选项设置一下，就不用每次都点那个文字的√了。
第二，可以对识别结果的文字进行放大吗？比如我在那个识别后的文本框中按ctrl和鼠标滚动就可以调整识别文字的大小。因为有时如果识别的字有错误而字太小，会很费眼。

**Comment by hiroi-sora** [comment]
> 默认不在图片上面显示文字识别结果的选项

当然可以，我之后会加这个选项。
目前你可以这样修改来实现 默认不显示文字：
1. 用记事本打开 `UmiOCR-data\qt_res\qml\Widgets\ImageViewer\ImageWithText.qml`
2. 第11行有个 `    property bool showOverlay: true // 显示叠加层`
3. 将它改为  `    property bool showOverlay: false`

> 对识别结果的文字进行放大

你指的是哪里的文字？左侧图片预览面板的话，现在是支持鼠标滚轮放大的。右侧**记录**面板的话，可以修改 **全局设置 → 界面和外观 → 界面与文字大小** 。

**Comment by lizuidie** [comment]
感谢作者，您的软件很好使用。感谢您的回复。
就是目前的话，字体大小和界面大小的调整是合在一起的，但是有的时候识别结果出来校对的话，即使放大150%，识别结果的字体还是有点小，如果这个字体能在编辑框里像左边的图片一样自行调节就好啦，因为有时150%还是不够用，所以要是能达到跟左边图片那种调整方式就非常棒！
我发现一个问题，就是识别结果在编辑框中无法选中把光标定位在第一个字之前，可以定位在第一个字之后，但是之前却怎么也没法用鼠标把光标定位在第一个字之前，但是用键盘的左右键却可以，不知道是什么原因。









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiroi-sora/Umi-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月10日(星期天) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiroi-sora/Umi-OCR] 作者，您好，您的软件很好用，我有两点小建议 (Issue #264)





  
默认不在图片上面显示文字识别结果的选项
  
当然可以，我之后会加这个选项。
 目前你可以这样修改来实现 默认不显示文字：
  
用记事本打开 UmiOCR-data\qt_res\qml\Widgets\ImageViewer\ImageWithText.qml
 
第11行有个     property bool showOverlay: true // 显示叠加层
 
将它改为      property bool showOverlay: false
   
对识别结果的文字进行放大
  
你指的是哪里的文字？左侧图片预览面板的话，现在是支持鼠标滚轮放大的。右侧记录面板的话，可以修改 全局设置 → 界面和外观 → 界面与文字大小 。

**Comment by hiroi-sora** [comment]
OK，明白你的需求了。

> ctrl+滚轮，调整右侧 **记录** 栏中的字体大小

技术上可行，之后有空弄弄。

> 无法把光标定位在第一个字之前

感谢报bug，已复现，确实是个问题。

其实，Umi中的 “可跨多个文本框选中多段文字” 的特性，原本UI框架并不具备，是我魔改出来的功能。所以难以避免的引入一些bug。我之后会调查一下该bug。

**Comment by lizuidie** [comment]
哈哈，作者汝真神人也！技术太厉害了，这个ocr非常好用，加油！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 作者，您好，您的软件很好用，我有两点小建议 (Issue #264)




 
OK，明白你的需求了。
  
ctrl+滚轮，调整右侧 记录 栏中的字体大小
  
技术上可行，之后有空弄弄。
  
无法把光标定位在第一个字之前
  
感谢报bug，已复现，确实是个问题。
 
其实，Umi中的 “可跨多个文本框选中多段文字” 的特性，原本UI框架并不具备，是我魔改出来的功能。所以难以避免的引入一些bug。我之后会调查一下该bug。

**Comment by hiroi-sora** [comment]
出于维护性考虑，暂时不会添加滚轮调整字号的操作。其余问题已解决。
