### ISSUE TITLE
pdf to word好像很火，这个搞pdf to word难吗？

### ISSUE THREAD

**Issue by basicbh** [hiroi-sora/Umi-OCR#265]
每页pdf搞成图片，扫描，然后拼接成pdf，是这样搞吗？

**Comment by hiroi-sora** [comment]
pdf转txt或者文本pdf都相对容易，在本项目的未来计划之内。

转word更难，需要额外对word格式进行解析和写入，要考虑各种字体、编码、排版等。本项目暂时没有转word的计划。

**Comment by hiroi-sora** [comment]
v2.1.0 测试版 已支持PDF识别。（暂不支持转为word）

https://github.com/hiroi-sora/Umi-OCR/releases
