### ISSUE TITLE
在后台paddle版运行时，速度明显会变慢

### ISSUE THREAD

**Issue by HAM2506** [hiroi-sora/Umi-OCR#266]
windows环境下，paddle版，使用客户端的http服务，当客户端缩小至任务栏，需要1秒以上。

点击任务栏展开客户端至桌面，再执行同样的命令调用http服务，则速度明显变快到0.5秒左右。

同样的图片，使用PaddleOCR-json离线识别，也是在1秒多，不知道是不是同样的问题？

**Comment by hiroi-sora** [comment]
你是什么cpu，会不会是大小核调度的问题？程序在后台是转到小核运行了？

尝试设个高优先级或者优先大核？（网上有方法）

**Comment by HAM2506** [comment]
> 你是什么cpu，会不会是大小核调度的问题？比如程序在后台时，被转到小核运行了。
> 
> 尝试设个高优先级或者优先大核？（网上有方法）

intel 12700，刚试了一下，应该是大小核的问题，感谢回复！
