### ISSUE TITLE
关于scoop包管理

### ISSUE THREAD

**Issue by dahehua** [hiroi-sora/Umi-OCR#267]
请问可以加入scoop库，通过scoop管理吗

**Comment by hiroi-sora** [comment]
以前有热心用户 @StudentWeis  帮忙将本项目加到 [chawyehsu/dorado](https://github.com/chawyehsu/dorado) 里。

不过我更新v2.0版之后，更改了发布链接格式（`releases/tag/release%2F2$version`）和发布形式（自解压包），所以原有的更新机制失效了，最新只有 v1.3.7 版本。

我对 scoop 的安装脚本机制不熟悉，短期内无法更改该错误。以后有空再研究一下，或者请哪位大佬协助一下。

**Comment by StudentWeis** [comment]
我可以重新更改一下

**Comment by StudentWeis** [comment]
由于 Umi-OCR 添加了英文主页，所以我尝试将它添加在了 scoop 官方的 [Extras](https://github.com/ScoopInstaller/Extras/pull/12616) 包里，可以不需要添加额外的桶就直接安装。

```sh
scoop install Umi-OCR
scoop install Umi-OCR-Paddle
```

**Comment by StudentWeis** [comment]
@hiroi-sora

**Comment by hiroi-sora** [comment]
OK，感谢，之后会写到Readme中
