### ISSUE TITLE
指定路径生成OCR结果文档无效

### ISSUE THREAD

**Issue by lhj5426** [hiroi-sora/Umi-OCR#269]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/30548000/a6238abf-7a95-4734-8ad8-88103c05952a)
大佬 如图 您看到的 
左边是我指定路径文件夹
和软件上设置的路径  右边 是图片的路径 和 TXT生成的位置
明明在软件里指定了生成路径 可还是会生成在图片的文件夹里

**Comment by hiroi-sora** [comment]
如果是保存为单独文件，目前的逻辑是强制保存到原文件路径下。

指定目录的选项，只在保存为其他形式时生效。

之后我会改一下逻辑，让单独文件也能应用保存到指定目录。

**Comment by lhj5426** [comment]
> 如果是保存为单独文件，目前的逻辑是强制保存到原文件路径下。
> 
> 指定目录的选项，只在保存为其他形式时生效。
> 
> 之后我会改一下逻辑，让单独文件也能应用保存到指定目录。

嗯嗯   谢谢大佬

**Comment by hiroi-sora** [comment]
代码已更新 √
