### ISSUE TITLE
功能建议：软件窗口置顶功能

### ISSUE THREAD

**Issue by SuChenUp** [hiroi-sora/Umi-OCR#27]
我在使用word文档时，用软件识别文字后，不想全部复制文字，需要多次复制文字到表格里。虽然有并排显示窗口功能，但是希望作者能把软件加上一个软件窗口置顶功能。

如下图：
![屏幕截图 2022-09-30 221442](https://user-images.githubusercontent.com/52001271/193291055-b68dc298-fc84-44ab-992b-ab6ab26f28bc.png)

**Comment by hiroi-sora** [comment]
OK，加了

小改动懒得发新版本了，直接加到1.3.0里，再下载一次即可

**Comment by SuChenUp** [comment]
> OK，加了
> 
> ![image](https://user-images.githubusercontent.com/56373419/193330751-08be5113-761c-4f0d-804a-7350ddef9b06.png)
> 
> 小改动懒得发新版本了，直接加到1.3.0 release里，再下载一次即可

非常感谢！
