### ISSUE TITLE
希望可以增加.pdf转文字的功能

### ISSUE THREAD

**Issue by VerySadPig** [hiroi-sora/Umi-OCR#271]
这个功能应该也时常用的。
现在要先转图片，再ocr，费二遍事。
麻烦得很

感谢。乌咪很棒！

**Comment by hiroi-sora** [comment]
在写了在写了 😂

不过12月了，年末是真的忙，没那么快搞定

**Comment by hiroi-sora** [comment]
v2.1.0 测试版 已支持PDF识别。

https://github.com/hiroi-sora/Umi-OCR/releases
