### ISSUE TITLE
咱们将来会做实时ocr识别吗？

### ISSUE THREAD

**Issue by immmor** [hiroi-sora/Umi-OCR#273]
如题

**Comment by hiroi-sora** [comment]
指的是调用摄像头，录制视频，实时识别吗？本项目没有该计划哦。

还是指实时录屏对固定区域识别？这种功能已经有很多优秀的开源项目了，比如 [团子翻译器](https://github.com/PantsuDango/Dango-Translator) 等。所以本项目短期内不会有类似计划。

**Comment by immmor** [comment]
> 指的是调用摄像头，录制视频，实时识别吗？本项目没有该计划哦。
> 
> 还是指实时录屏对固定区域识别？这种功能已经有很多优秀的开源项目了，比如 [团子翻译器](https://github.com/PantsuDango/Dango-Translator) 等。所以本项目短期内不会有类似计划。

但是那个没法识别中文耶

**Comment by immmor** [comment]
> 指的是调用摄像头，录制视频，实时识别吗？本项目没有该计划哦。
> 
> 还是指实时录屏对固定区域识别？这种功能已经有很多优秀的开源项目了，比如 [团子翻译器](https://github.com/PantsuDango/Dango-Translator) 等。所以本项目短期内不会有类似计划。

请问还有别的推荐吗~~

**Comment by hiroi-sora** [comment]
团子应该支持中文的，设置里找找。

类似的项目还有：

https://github.com/HIllya51/LunaTranslator

https://github.com/hanmin0822/MisakaTranslator
