### ISSUE TITLE
请教古籍的识别

### ISSUE THREAD

**Issue by 3815445** [hiroi-sora/Umi-OCR#275]
大量中华古籍原本流落海外，但目前可以弄到扫描电子版，原图类似以下二图，想转换成文本，尽量减少人工干预。寻求帮助。谢谢！
![35](https://github.com/hiroi-sora/Umi-OCR/assets/150584521/6ae8d99c-bf23-4fc4-a88c-b9f9065defb9)
![2023-12-19_084357](https://github.com/hiroi-sora/Umi-OCR/assets/150584521/e0e9ce55-04a1-4c68-aaa2-c6015636cd19)

**Comment by hiroi-sora** [comment]
这张场景需要专门针对性训练的模型库，通用模型库或者现代繁中库并不适用。以下是一些可能有用的工具或服务：

https://dzcj.unihan.com.cn/
https://guji.rushi-ai.net/
https://ocr.gj.cool/
https://ocr.ancientbooks.cn/
http://www.wenshengai.com/
https://ocr.ascdc.tw/

https://www.wenxianxue.cn/tag/OCR

具体使用体验我也不是很清楚，仅抛砖引玉。

**Comment by 3815445** [comment]
非常感谢！
