### ISSUE TITLE
[Error] MissionOCR: API object is None.

### ISSUE THREAD

**Issue by loufeiyang** [hiroi-sora/Umi-OCR#278]
运行报错为啥
[Error] MissionOCR: API object is None.
![1703153292852](https://github.com/hiroi-sora/Umi-OCR/assets/101849270/78152938-a161-4467-92f3-df30cbcb45a7)

**Comment by hiroi-sora** [comment]
你是跑的源码吗？有没有正确放置 [OCR引擎插件](https://github.com/hiroi-sora/Umi-OCR_plugins) ？

**Comment by loufeiyang** [comment]
佬，这个ocr插件仓库里是不是少exe呀，我搜了一个PaddleOCR-json.exe，放到plugins下面，然后行了

**Comment by hiroi-sora** [comment]
仓库本身是只放代码的哦，像exe和dll这些编译生成的二进制文件体积较大，git管理不方便，所以没有放在仓库里。

你需要在该仓库的 [Releases](https://github.com/hiroi-sora/Umi-OCR_plugins/releases) 中下载完整的插件压缩包（含所有二进制文件），而不是下载仓库源代码。

**Comment by FnTop** [comment]
> 你是跑的源码吗？有没有正确放置 [OCR引擎插件](https://github.com/hiroi-sora/Umi-OCR_plugins) ？

这个要放哪些插件，放了paddleocr-jsn插件还是无法进行截图识别

**Comment by hiroi-sora** [comment]
> 放了PaddleOCR-json.exe插件还是无法进行截图识别

请确保放置插件后，目录结构是这样的：

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/c88afc71-d5fa-4834-8b16-47251f269e39)

**Comment by FnTop** [comment]
就是这样的呀
![图片](https://github.com/hiroi-sora/Umi-OCR/assets/43026579/226be352-d2cc-4af3-96ce-b1a844118cf9)

**Comment by hiroi-sora** [comment]
应该不会吧……

你试试下载一个Release版本，将其中的plugins整个复制到源码版相同目录下。

如果还是不行，将Release版的所有文件复制到源码目录中（覆盖）。

（另外，[源码](https://github.com/hiroi-sora/Umi-OCR/branches)建议选择最后一个`release/`开头的分支的代码，以免引入开发中的问题。）

**Comment by FnTop** [comment]
2.1.1 Release 是可以的
