### ISSUE TITLE
2k屏幕电脑，在使用HDMI接口外接显示屏之后，点击截图键会出现蓝色的颜色块，影响截图

### ISSUE THREAD

**Issue by lzh1043060917** [hiroi-sora/Umi-OCR#279]
<img width="1129" alt="Snipaste_2023-12-22_14-55-33" src="https://github.com/hiroi-sora/Umi-OCR/assets/25424316/4d473397-ca37-41e3-8e61-c5efd702a9be">
我的电脑是天选4，屏幕2k屏，在使用HDMI接口外接显示屏之后，点击截图键会出现蓝色的颜色块，导致无法正常截图；但是我换了个1080p屏幕的笔记本电脑，外接显示屏之后，点击截图键就没有这个问题了。两种版本的umi-ocr都出现了这样的问题，不知道有人知道啥原因么？

**Comment by lzh1043060917** [comment]
我的天选4是win11系统，cpu是amd，屏幕刷新率较高，但是外接显示屏只有60hz，我不太清楚和这个有没有关系。另一台没问题的电脑屏幕是1080p，60hz刷新率，win10系统，cpu是英特尔，除此之外想不到有啥差别了......

**Comment by lzh1043060917** [comment]
补充一下，我的2k屏的笔记本电脑，如果不外接显示器，直接用截图功能，就不会出现蓝色的块。只有在使用HDMI外接显示器之后才会出现这个情况。

**Comment by hiroi-sora** [comment]
试下关闭硬件加速

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/24321d4a-845e-4f05-bfd7-d22464d55a80)

**Comment by lzh1043060917** [comment]
> 试下关闭硬件加速
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/292422603-24321d4a-845e-4f05-bfd7-d22464d55a80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjczNTMsIm5iZiI6MTcwMzQ2NzA1MywicGF0aCI6Ii81NjM3MzQxOS8yOTI0MjI2MDMtMjQzMjFkNGEtODQ1ZS00ZjA1LWJmZDctZDIyNDY0ZDU1YTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAxMTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNGU2MWQxYWZlNmEyOTI4OTEwODQ3YTRjZGNhZWUzMzRmOTllZjUxODFlZjAyNTc3MTdmMDY0YjA0MzhiODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSVDJGhyFMAYIvE46T7dtxfa9FyI6fkIU6GZQ21u7vI)

试了，没效果

**Comment by hiroi-sora** [comment]
请尝试下列操作：

1. 打开 `UmiOCR-data\py_src\image_controller\image_provider.py` ，将30行的requestPixmap函数替换为：
```python
    def requestPixmap(self, path, size=None, resSize=None):
        if "/" in path:
            compID, imgID = path.split("/", 1)
            self._delCompCache(compID)  # 先清缓存
            if imgID in self.pixmapDict:
                self.compDict[compID] = imgID  # 记录缓存
                return self.pixmapDict[imgID]
            print(f"[Error] imgID {imgID} not in pixmapDict")
        else:  # 清空一个组件的缓存
            self._delCompCache(path)
        return self._getNoneImg()  # 返回占位符
```

2. 打开 `UmiOCR-data\py_src\image_controller\screenshot_controller.py` ，将第16行的getScreenshot函数替换为：
```python
    def getScreenshot(self, wait=0):
        if wait > 0:
            time.sleep(wait)
        try:
            grabList = []
            screensList = QGuiApplication.screens()
            for screen in screensList:
                pixmap = screen.grabWindow(0)  # 截图
                imgID = PixmapProvider.addPixmap(pixmap)  # 存入提供器，获取imgID
                grabList.append(
                    {
                        "imgID": imgID,
                        "screenName": screen.name(),
                    }
                )
                print(imgID)
                print(screen.name())
                print(screen.devicePixelRatio())
                print(screen.virtualGeometry())
                print(screen.geometry())
            return grabList
        except Exception as e:
            return [f"[Error] Screenshot: {e}"]
```

然后，在命令行中运行Umi-OCR，也可以直接运行 `UmiOCR-data\RUN_CLI.bat` 。截图，将命令行输出的内容粘上来给我看看。

**Comment by lzh1043060917** [comment]
> 请尝试下列操作：
> 
> 1. 打开 `UmiOCR-data\py_src\image_controller\image_provider.py` ，将30行的requestPixmap函数替换为：
> 
> ```python
>     def requestPixmap(self, path, size=None, resSize=None):
>         if "/" in path:
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
>             if imgID in self.pixmapDict:
>                 self.compDict[compID] = imgID  # 记录缓存
>                 return self.pixmapDict[imgID]
>             print(f"[Error] imgID {imgID} not in pixmapDict")
>         else:  # 清空一个组件的缓存
>             self._delCompCache(path)
>         return self._getNoneImg()  # 返回占位符
> ```
> 
> 2. 打开 `UmiOCR-data\py_src\image_controller\screenshot_controller.py` ，将第16行的getScreenshot函数替换为：
> 
> ```python
>     def getScreenshot(self, wait=0):
>         if wait > 0:
>             time.sleep(wait)
>         try:
>             grabList = []
>             screensList = QGuiApplication.screens()
>             for screen in screensList:
>                 pixmap = screen.grabWindow(0)  # 截图
>                 imgID = PixmapProvider.addPixmap(pixmap)  # 存入提供器，获取imgID
>                 grabList.append(
>                     {
>                         "imgID": imgID,
>                         "screenName": screen.name(),
>                     }
>                 )
>                 print(imgID)
>                 print(screen.name())
>                 print(screen.devicePixelRatio())
>                 print(screen.virtualGeometry())
>                 print(screen.geometry())
>             return grabList
>         except Exception as e:
>             return [f"[Error] Screenshot: {e}"]
> ```
> 
> 然后，在命令行中运行Umi-OCR，也可以直接运行 `UmiOCR-data\RUN_CLI.bat` 。截图，如果出现异常颜色块的话，将命令行输出的内容粘上来给我看看。

![Uploading Snipaste_2023-12-29_09-37-11.png…]()

**Comment by lzh1043060917** [comment]
> 请尝试下列操作：
> 
> 1. 打开 `UmiOCR-data\py_src\image_controller\image_provider.py` ，将30行的requestPixmap函数替换为：
> 
> ```python
>     def requestPixmap(self, path, size=None, resSize=None):
>         if "/" in path:
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
>             if imgID in self.pixmapDict:
>                 self.compDict[compID] = imgID  # 记录缓存
>                 return self.pixmapDict[imgID]
>             print(f"[Error] imgID {imgID} not in pixmapDict")
>         else:  # 清空一个组件的缓存
>             self._delCompCache(path)
>         return self._getNoneImg()  # 返回占位符
> ```
> 
> 2. 打开 `UmiOCR-data\py_src\image_controller\screenshot_controller.py` ，将第16行的getScreenshot函数替换为：
> 
> ```python
>     def getScreenshot(self, wait=0):
>         if wait > 0:
>             time.sleep(wait)
>         try:
>             grabList = []
>             screensList = QGuiApplication.screens()
>             for screen in screensList:
>                 pixmap = screen.grabWindow(0)  # 截图
>                 imgID = PixmapProvider.addPixmap(pixmap)  # 存入提供器，获取imgID
>                 grabList.append(
>                     {
>                         "imgID": imgID,
>                         "screenName": screen.name(),
>                     }
>                 )
>                 print(imgID)
>                 print(screen.name())
>                 print(screen.devicePixelRatio())
>                 print(screen.virtualGeometry())
>                 print(screen.geometry())
>             return grabList
>         except Exception as e:
>             return [f"[Error] Screenshot: {e}"]
> ```
> 
> 然后，在命令行中运行Umi-OCR，也可以直接运行 `UmiOCR-data\RUN_CLI.bat` 。截图，如果出现异常颜色块的话，将命令行输出的内容粘上来给我看看。

![Uploading Snipaste_2023-12-29_09-37-11.png…]()

**Comment by lzh1043060917** [comment]
> 请尝试下列操作：
> 
> 1. 打开 `UmiOCR-data\py_src\image_controller\image_provider.py` ，将30行的requestPixmap函数替换为：
> 
> ```python
>     def requestPixmap(self, path, size=None, resSize=None):
>         if "/" in path:
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
>             if imgID in self.pixmapDict:
>                 self.compDict[compID] = imgID  # 记录缓存
>                 return self.pixmapDict[imgID]
>             print(f"[Error] imgID {imgID} not in pixmapDict")
>         else:  # 清空一个组件的缓存
>             self._delCompCache(path)
>         return self._getNoneImg()  # 返回占位符
> ```
> 
> 2. 打开 `UmiOCR-data\py_src\image_controller\screenshot_controller.py` ，将第16行的getScreenshot函数替换为：
> 
> ```python
>     def getScreenshot(self, wait=0):
>         if wait > 0:
>             time.sleep(wait)
>         try:
>             grabList = []
>             screensList = QGuiApplication.screens()
>             for screen in screensList:
>                 pixmap = screen.grabWindow(0)  # 截图
>                 imgID = PixmapProvider.addPixmap(pixmap)  # 存入提供器，获取imgID
>                 grabList.append(
>                     {
>                         "imgID": imgID,
>                         "screenName": screen.name(),
>                     }
>                 )
>                 print(imgID)
>                 print(screen.name())
>                 print(screen.devicePixelRatio())
>                 print(screen.virtualGeometry())
>                 print(screen.geometry())
>             return grabList
>         except Exception as e:
>             return [f"[Error] Screenshot: {e}"]
> ```
> 
> 然后，在命令行中运行Umi-OCR，也可以直接运行 `UmiOCR-data\RUN_CLI.bat` 。截图，如果出现异常颜色块的话，将命令行输出的内容粘上来给我看看。
<img width="865" alt="Snipaste_2023-12-29_09-37-11" src="https://github.com/hiroi-sora/Umi-OCR/assets/25424316/0f873c67-1c96-44be-87e2-ff9b89b82280">

**Comment by hiroi-sora** [comment]
啊？？太玄学了，截图对象已经缓存到字典里了怎么会莫名其妙的消失了呢……

麻烦再改一下，`UmiOCR-data\py_src\image_controller\image_provider.py` 

requestPixmap函数改为：
```python
    def requestPixmap(self, path, size=None, resSize=None):
        print(f"request: {path}")
        print("   ", list(k[-6:] for k in self.pixmapDict.keys()))
        if "/" in path:
            compID, imgID = path.split("/", 1)
            self._delCompCache(compID)  # 先清缓存
            if imgID in self.pixmapDict:
                self.compDict[compID] = imgID  # 记录缓存
                return self.pixmapDict[imgID]
            print(f"[Error] imgID {imgID} not in pixmapDict!")
        else:  # 清空一个组件的缓存
            self._delCompCache(path)
        return self._getNoneImg()  # 返回占位符
```

后面的 _delCompCache 函数改为：
```python
    def _delCompCache(self, compID):
        if compID in self.compDict:
            last = self.compDict[compID]
            if last in self.pixmapDict:
                print(f"___del: {compID} {last}")
                del self.pixmapDict[last]
            del self.compDict[compID]
```

**Comment by lzh1043060917** [comment]
> 啊？？太玄学了，截图对象已经缓存到字典里了怎么会莫名其妙的消失了呢……
> 
> 麻烦再改一下，`UmiOCR-data\py_src\image_controller\image_provider.py`
> 
> requestPixmap函数改为：
> 
> ```python
>     def requestPixmap(self, path, size=None, resSize=None):
>         print(f"request: {path}")
>         print("   ", list(k[-6:] for k in self.pixmapDict.keys()))
>         if "/" in path:
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
>             if imgID in self.pixmapDict:
>                 self.compDict[compID] = imgID  # 记录缓存
>                 return self.pixmapDict[imgID]
>             print(f"[Error] imgID {imgID} not in pixmapDict!")
>         else:  # 清空一个组件的缓存
>             self._delCompCache(path)
>         return self._getNoneImg()  # 返回占位符
> ```
> 
> 后面的 _delCompCache 函数改为：
> 
> ```python
>     def _delCompCache(self, compID):
>         if compID in self.compDict:
>             last = self.compDict[compID]
>             if last in self.pixmapDict:
>                 print(f"___del: {compID} {last}")
>                 del self.pixmapDict[last]
>             del self.compDict[compID]
> ```

<img width="865" alt="Snipaste_2024-01-02_09-20-45" src="https://github.com/hiroi-sora/Umi-OCR/assets/25424316/10d9ad04-be78-4c89-870e-d168f93ec6c5">
而且有个很迷的问题，在我用HDMI外接显示屏的时候会出现这问题，但是拔掉HDMI，只用笔记本电脑的屏幕，就没有异常颜色块。。。

**Comment by lzh1043060917** [comment]
> 啊？？太玄学了，截图对象已经缓存到字典里了怎么会莫名其妙的消失了呢……
> 
> 麻烦再改一下，`UmiOCR-data\py_src\image_controller\image_provider.py`
> 
> requestPixmap函数改为：
> 
> ```python
>     def requestPixmap(self, path, size=None, resSize=None):
>         print(f"request: {path}")
>         print("   ", list(k[-6:] for k in self.pixmapDict.keys()))
>         if "/" in path:
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
>             if imgID in self.pixmapDict:
>                 self.compDict[compID] = imgID  # 记录缓存
>                 return self.pixmapDict[imgID]
>             print(f"[Error] imgID {imgID} not in pixmapDict!")
>         else:  # 清空一个组件的缓存
>             self._delCompCache(path)
>         return self._getNoneImg()  # 返回占位符
> ```
> 
> 后面的 _delCompCache 函数改为：
> 
> ```python
>     def _delCompCache(self, compID):
>         if compID in self.compDict:
>             last = self.compDict[compID]
>             if last in self.pixmapDict:
>                 print(f"___del: {compID} {last}")
>                 del self.pixmapDict[last]
>             del self.compDict[compID]
> ```

刚刚我发的回复是按下截图按钮后的命令行输出，如果此时我在异常颜色块里面进行截图，那么命令行输出如下：
![Uploading Snipaste_2024-01-02_09-23-03.png…]()

**Comment by hiroi-sora** [comment]
Umi进行一次截图的流程是：

```
1. ScreenshotManager.qml 调用 screenshot 函数，开始截图流程
2. screenshot_controller.py 调用 getScreenshot 函数，返回所有N个屏幕的截图
3. ScreenshotManager.qml 生成N个 ScreenshotWindowComp 窗口，覆盖在N个屏幕上
4. 用户鼠标划选区域
5. ScreenshotManager.qml 调用 ssEnd 函数，销毁N个窗口，删除图片缓存
6. 裁切指定范围的图片，结束截图流程
```

而在你的截图日志中，看到这一行出现了两次： 
`request:Image__QMLTYPE_160(0x253586402b0)/……cf517c`
这是一个异常情况。在第3步，图片组件 `0x253586402b0` **重复请求** 了编号为`……cf517c`的缓存。第二次请求时，按照我的缓存自动清理机制，`……cf517c`已经被清理了，已经不存在了。所以只能返回`红-蓝-红`的缺省图片。（这个颜色是人为设定的缺省图片）。

按理说，图片组件是不会重复请求id相同的缓存的。不知道为什么在你的设备上出现了重复的情况。

不过，既然知道问题发生的直接原因，咱们就能想办法绕开它。请打开`UmiOCR-data\py_src\image_controller\image_provider.py`，大约34行，原本是这样的：

```python
            compID, imgID = path.split("/", 1)
            self._delCompCache(compID)  # 先清缓存
```

现在改动`self._delCompCache`这句，加个限制条件，防止重复请求时删除缓存：

```python
            compID, imgID = path.split("/", 1)
            if compID in self.compDict and self.compDict[compID] != imgID: # 判断不是重复请求
                self._delCompCache(compID)  # 再清缓存
```

改动后，你的电脑上应该能正常使用双屏截图了。

**Comment by lzh1043060917** [comment]
> Umi进行一次截图的流程是：
> 
> ```
> 1. ScreenshotManager.qml 调用 screenshot 函数，开始截图流程
> 2. screenshot_controller.py 调用 getScreenshot 函数，返回所有N个屏幕的截图
> 3. ScreenshotManager.qml 生成N个 ScreenshotWindowComp 窗口，覆盖在N个屏幕上
> 4. 用户鼠标划选区域
> 5. ScreenshotManager.qml 调用 ssEnd 函数，销毁N个窗口，删除图片缓存
> 6. 裁切指定范围的图片，结束截图流程
> ```
> 
> 而在你的截图日志中，看到这一行出现了两次： `request:Image__QMLTYPE_160(0x253586402b0)/……cf517c` 这是一个异常情况。在第3步，图片组件 `0x253586402b0` **重复请求** 了编号为`……cf517c`的缓存。第二次请求时，按照我的缓存自动清理机制，`……cf517c`已经被清理了，已经不存在了。所以只能返回`红-蓝-红`的缺省图片。（这个颜色是人为设定的缺省图片）。
> 
> 按理说，图片组件是不会重复请求id相同的缓存的。不知道为什么在你的设备上出现了重复的情况。
> 
> 不过，既然知道问题发生的直接原因，咱们就能想办法绕开它。请打开`UmiOCR-data\py_src\image_controller\image_provider.py`，大约34行，原本是这样的：
> 
> ```python
>             compID, imgID = path.split("/", 1)
>             self._delCompCache(compID)  # 先清缓存
> ```
> 
> 现在改动`self._delCompCache`这句，加个限制条件，防止重复请求时删除缓存：
> 
> ```python
>             compID, imgID = path.split("/", 1)
>             if compID in self.compDict and self.compDict[compID] != imgID: # 判断不是重复请求
>                 self._delCompCache(compID)  # 再清缓存
> ```
> 
> 改动后，你的电脑上应该能正常使用双屏截图了。

差不多能用了，不过还是有点小bug，我刚刚在截图的时候，外接屏幕的内容覆盖了一部分当前屏幕的内容。只能在笔记本电脑自身的屏幕这边截图，不能在外接屏幕那边截图。搞不好是设备哪里有问题，估计很难排查。如果太难搞就算了。谢谢了。现在也不是不能用
![Uploading Snipaste_2024-01-03_09-22-24.png…]()
