### ISSUE TITLE
快捷键修改

### ISSUE THREAD

**Issue by langphed** [hiroi-sora/Umi-OCR#28]
现在截图的快捷键是alt+win+c 能否将快捷键设置为调整模式，之前用天若的ORC是可以自己设置快捷键的（用的是F4)

**Comment by hiroi-sora** [comment]
![image](https://user-images.githubusercontent.com/56373419/194302125-6e42f022-5c24-4d39-8144-af408a1ac180.png)
点这个录制按钮，然后按下入你想要的快捷键（如F4）就行了

**Comment by wxyShine** [comment]
![wxy_2022-10-08_11-36-42](https://user-images.githubusercontent.com/42802152/194686315-f72e0bcf-b6ec-4c91-9326-161618e664fa.png)
录制按下F4  出现这一堆~~ 系统是win11

**Comment by wxyShine** [comment]
> ![wxy_2022-10-08_11-36-42](https://user-images.githubusercontent.com/42802152/194686315-f72e0bcf-b6ec-4c91-9326-161618e664fa.png) 录制按下F4 出现这一堆~~ 系统是win11

好了  我重启软件 正常了

**Comment by hiroi-sora** [comment]
嗯，本项目使用的开源库[keyboard](https://github.com/boppreh/keyboard)是有一堆Bug，而且它也没怎么维护了，考虑以后换掉。录制快捷键时出问题，可能是keyboard线程的队列积累了错误的键值，重启软件重置状态后一般都能恢复正常。

**Comment by hiroi-sora** [comment]
新版本将解决快捷键问题。👉[测试版](https://github.com/hiroi-sora/Umi-OCR/issues/43)
