### ISSUE TITLE
有好多PaddleOCR-json.exe进程，是什么原因导致的

### ISSUE THREAD

**Issue by Szhonghuajia** [hiroi-sora/Umi-OCR#280]
![a](https://github.com/hiroi-sora/Umi-OCR/assets/86312433/c0002e45-4df2-4634-9015-4b0c0933e677)
如图，目前有2个（我开启并使用了HTTP服务）有次我检查发现有8个进程

**Comment by Szhonghuajia** [comment]
使用的是v2.0.1版本，系统是win10专业版

**Comment by hiroi-sora** [comment]
这确实不正常。在代码中，每隔一段时间会重启引擎以释放内存。感觉你的情况像是重启引擎时，旧的进程没有被正确kill掉。

我在测试时未能复现该情况，不知是不是跟你的系统也有关系。暂时我想不出解决方案，建议你换用Rapid引擎版。

**Comment by Szhonghuajia** [comment]
感谢帮助调查问题，我也尝试再另一台机器上复现该问题，但并没成功。所以系统的问题概率很大

**Comment by Szhonghuajia** [comment]
close
