### ISSUE TITLE
运行RUN_CLI.bat报错

### ISSUE THREAD

**Issue by andikeke1223** [hiroi-sora/Umi-OCR#282]
双击运行后出现以下报错，请问作者这是什么原因啊
UmiOCR-data/qt_res/qml/Main.qml:7:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot load library E:\umi-ocr\Umi-OCR_Paddle_v2.0.1\UmiOCR-data\site-packages\PySide2\qml\QtQuick\Controls.2\qtquickcontrols2plugin.dll: ?w?????v???V?[?W?????????????????B

**Comment by hiroi-sora** [comment]
qtquickcontrols2plugin.dll 依赖一些外部dll，如：
```
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
```
