### ISSUE TITLE
识别双栏文字怎么设置？

### ISSUE THREAD

**Issue by yfz516** [hiroi-sora/Umi-OCR#283]
首先，感谢作者hiroi-sora大神的辛劳制作及慷慨分享！请问对于双栏，甚至三栏的文字识别怎么操作，没有找到相关的设置。谢谢解答！

**Comment by hiroi-sora** [comment]
多栏布局识别存在一定难度，相关算法正在测试开发中~

**Comment by hiroi-sora** [comment]
目前多栏算法 已取得突破性进展，将在下个版本嵌入到Umi中。

详见：

https://github.com/hiroi-sora/GapTree_Sort_Algorithm
