### ISSUE TITLE
Umi-OCR如何部署在局域网服务器上？

### ISSUE THREAD

**Issue by qiunlp** [hiroi-sora/Umi-OCR#286]
const url = 'http://127.0.0.1:1224/api/ocr';
const data = {
    base64: '',
    }
};
fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    })
    .then(response => response.json())
    .then(data => {
        console.log(data);
    })
   将Umi-OCR安装在局域网服务器上，启动后端口也设置1224，请问：这里的url写成什么？浏览器地址栏尝试输入我的局域网服务器ip:1224，没有出现Umi-OCR版本号。谢谢！！

**Comment by hiroi-sora** [comment]
首先，如下图所示，高级 → 主机 → 调为“任何可用地址” 。重启软件生效。
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/a619a5de-ae1e-4372-8c72-578138e00711)

然后，按win+R，输入cmd打开命令行窗口，输入`ipconfig`获取本机ip。如：

```
无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : fda0:285:3e92:7a4b:aa9b:f7cf:6417:8c9d
   临时 IPv6 地址. . . . . . . . . . : fca0:285:3e81:7a4e:b102:4ce4:afc:a81d
   本地链接 IPv6 地址. . . . . . . . : fc80::bd8b:56fd:ab0d:3ba3%6
   IPv4 地址 . . . . . . . . . . . . : 192.168.9.81
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.9.1
```

其中`IPv4 地址 . . . . . . . . . . . . : 192.168.9.81`是本机局域网ip，别的机器访问`192.168.9.81:1224`即可。

**Comment by qiunlp** [comment]
非常感谢您的及时回复，待元旦上班后我试试。祝您新年快乐！

**Comment by qiunlp** [comment]
还想请教您，Umi-OCR.exe双击、右键打开、右键以管理员运行，都不能运行,不在什么原因？
Umi-OCR_Paddle_v2.0.1

**Comment by PhyCoe** [comment]
> 首先，如下图所示，全局设置 → 高级 → 主机 → 调为“任何可用地址” 。重启软件生效。 ![image](https://private-user-images.githubusercontent.com/56373419/293486821-a619a5de-ae1e-4372-8c72-578138e00711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzExNTAsIm5iZiI6MTcyNTkzMDg1MCwicGF0aCI6Ii81NjM3MzQxOS8yOTM0ODY4MjEtYTYxOWE1ZGUtYWUxZS00MzcyLThjNzItNTc4MTM4ZTAwNzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAxMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZjNmMDQwNTAzYjdiY2M3ODQwOGIxNzNjMjZjNTQyZDg3YzMzMmE1YzkzOTc4NWIxZTJmODk1OGRhZTYzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEoaLdvdTLjQNW7L_y3eOpgh1AFbrI98HMGSAOxTp9k)
> 
> 然后，按win+R，输入cmd打开命令行窗口，输入`ipconfig`获取本机ip。如：
> 
> ```
> 无线局域网适配器 WLAN:
> 
>    连接特定的 DNS 后缀 . . . . . . . :
>    IPv6 地址 . . . . . . . . . . . . : fda0:285:3e92:7a4b:aa9b:f7cf:6417:8c9d
>    临时 IPv6 地址. . . . . . . . . . : fca0:285:3e81:7a4e:b102:4ce4:afc:a81d
>    本地链接 IPv6 地址. . . . . . . . : fc80::bd8b:56fd:ab0d:3ba3%6
>    IPv4 地址 . . . . . . . . . . . . : 192.168.9.81
>    子网掩码  . . . . . . . . . . . . : 255.255.255.0
>    默认网关. . . . . . . . . . . . . : 192.168.9.1
> ```
> 
> 其中`IPv4 地址 . . . . . . . . . . . . : 192.168.9.81`是本机局域网ip，别的机器访问`192.168.9.81:1224`即可。

大佬你好，我本地连接127.0.01:1224无法访问（游览器里无法打开），然后按照您说的调为“任何可用地址” ，重启软件，访问本机ip+端口的方式，游览器报错Error: 405 Method Not Allowed，想请问下是什么原因呀
