### ISSUE TITLE
ORC截图是能否取消绿色十字线条，识别结果通知能否设置到右下角

### ISSUE THREAD

**Issue by gougou139** [hiroi-sora/Umi-OCR#287]
ORC截图是能否取消绿色十字线条，识别结果通知能否设置到右下角

**Comment by gougou139** [comment]
是不是我自己可以通过简单的代码修改就行，理论上应该是这样，有PyCharm

**Comment by hiroi-sora** [comment]
是的，你可以自己改代码实现这些功能。

> 取消绿色十字线条

UmiOCR-data\qt_res\qml\ImageManager\ScreenshotWindowComp.qml

第105行，将 十字指示器 Item{} 部分注释掉或删掉。
```qml
    // 十字指示器， mouseStatus==0 时启用
    // Item {
    //     anchors.fill: parent
    //     ………… 删掉整个Item
    // }
```

> 识别结果通知设置到右下角

UmiOCR-data\qt_res\qml\Popup_\MessageSimple.qml

第121行有一句：
```qml
x = (screenWidth - width) / 2 // 水平居中
```

将它改成：
```qml
x = screenWidth - width - 20 // 靠右
```
其中20表示弹窗右侧距离屏幕边缘的空隙，你可自行调整。

**Comment by gougou139** [comment]
你说的方法我已经回了，非常感谢，然后还想知道ORC结果通知可以通过内容自动调整通知高度和宽度么，那样我可以通过通知反馈是否是我需要的内容有没有误，类似如图这种
![微信截图_20240101150017](https://github.com/hiroi-sora/Umi-OCR/assets/22148632/7e3b09db-6cff-46a6-a184-cc1d45248463)
![微信截图_20240101150111](https://github.com/hiroi-sora/Umi-OCR/assets/22148632/4f11314f-6d7f-432f-9cc7-c8e3fcbe529b)

**Comment by gougou139** [comment]
当然，距离右边和下边的距离是固定的，根据ORC结果向上或者向左自适应，直到可以完整展示结果

**Comment by gougou139** [comment]
截图ORC如果文字较多，时间会很漫长，有没有计划增加OCR网络接口

**Comment by hiroi-sora** [comment]
> 自动调整通知高度

UmiOCR-data\qt_res\qml\Popup_\MessageSimpleComp.qml

第108行，将 `maximumLineCount` 后面的数字调大一点即可。比如调到10就是最多显示10行文本。
```qml
            maximumLineCount: 10
```

---

> 增加OCR网络接口

你指的是使用百度等在线OCR接口吗？短期内我没有类似计划。但你可以参考 [插件开发文档](https://github.com/hiroi-sora/Umi-OCR_plugins/tree/main/demo_AbaOCR)，自己写一个使用在线OCR接口的插件。开发难度并不高，有python经验即可。

> 赞赏相关

我暂时不会开放赞赏。点个⭐或者向朋友推荐一下就是对我的支持啦~~
