### ISSUE TITLE
无法启动引擎

### ISSUE THREAD

**Issue by Prometheus798** [hiroi-sora/Umi-OCR#29]
无法启动引擎是哪里出了问题？

**Comment by hiroi-sora** [comment]
请问CPU型号、系统版本？单独启动 `软件目录/PaddleOCR-json/PaddleOCR-json.exe` 有没有报异常？

若CPU不支持AVX指令集，目前是用不了的，见[issue #11](https://github.com/hiroi-sora/Umi-OCR/issues/11)

**Comment by zhangsy5356127** [comment]
启动引擎失败，用不了，window 11  64位
【INFO】 批量文本处理器初始化完毕！
【INFO】 启动引擎，参数：('PaddleOCR-json/PaddleOCR_json.exe', 'PaddleOCR_json_config_ch.txt', ' -limit_type=max -limit_side_len=960 -cpu_threads=10 -enable_mkldnn=True ')
【INFO】 引擎stop，停止任务！
【ERROR】 批量任务启动引擎失败：[WinError 2] 系统找不到指定的文件。

**Comment by hiroi-sora** [comment]
> 启动引擎失败，[WinError 2] 系统找不到指定的文件。
@zhangsy5356127 

你好，这个问题是打包后没有将引擎组件放到生成的exe同目录下（或main.py同目录下）。
请将引擎组件 [PaddleOCR-json 整个文件夹](https://github.com/hiroi-sora/Umi-OCR/blob/main/PaddleOCR-json) 放置于exe同目录下。

**Comment by zhangsy5356127** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月23日(周日) 晚上7:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 无法启动引擎 (Issue #29)




  
启动引擎失败，[WinError 2] 系统找不到指定的文件。
 @zhangsy5356127
  
你好，这个问题是打包后没有将引擎组件放到生成的exe同目录下（或main.py同目录下）。
 请将引擎组件 PaddleOCR-json 整个文件夹 放置于exe同目录下。

**Comment by MonicaArnaud** [comment]
打包exe后，无法启动引擎，报错是：No module named 'winshell' 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "ui\win_main.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "utils\startup.py", line 8, in <module>
ModuleNotFoundError: No module named 'winshell'

我安装了winshell也不行，确认PaddleOCR-json文件放在了打包exe的同目录下了。

**Comment by hiroi-sora** [comment]
> 打包exe后，无法启动引擎，报错是：No module named 'winshell'
@MonicaArnaud 

你好，这个错误与引擎无关。`winshell`是指一个python第三方库，不是win应用，你缺了这个库才会报错。
我昨天刚把这个库引进项目里，忘了更新requirements.txt。现在已经更新了，你再Clone一次，安装 `pip install -r requirements.txt` 就行了。或者单独 `pip install winshell` 。

**Comment by evachxji** [comment]
![image](https://user-images.githubusercontent.com/36871584/201513585-1fc1dd78-7698-49eb-aa40-f914c0c6e430.png)

任务失败:无法启动引擎: OCR init timeout: 5s.
PaddleOCR-json/PaddleOCR_ json.exe

**Comment by hiroi-sora** [comment]
> 任务失败:无法启动引擎: OCR init timeout: 5s. PaddleOCR-json/PaddleOCR_ json.exe

麻烦运行一下  `PaddleOCR-json` 文件夹中的 `PaddleOCR-json.exe`  ，看看输出了啥。

**Comment by bosco08021** [comment]
![image](https://user-images.githubusercontent.com/128128465/226508065-8235d1c9-05d3-41be-a32a-945af5395208.png)   
运行就提示这个，这软件之前在这电脑用过，非常好用。但是重装系统后就这样了，因为是小白也不知道什么问题，望解答，谢谢！

**Comment by hiroi-sora** [comment]
> 但是重装系统后就这样了，因为是小白也不知道什么问题，望解答，谢谢！

看样子是配置文件有问题或者目录损坏。直接重新下载一个就行了。

**Comment by bosco08021** [comment]
> > 但是重装系统后就这样了，因为是小白也不知道什么问题，望解答，谢谢！
> 
> 看样子是配置文件有问题或者目录损坏。删了直接重新下载一个就行了。

你这个是绿色版啊，我重装几次了。我上午看到你更新，就删了以前的版本，下的最新的这个版本，还是无法启动。。。

**Comment by hiroi-sora** [comment]
@bosco08021 

关于`No such file or directory: 'nul'`，我又研究了下，这个报错大概率与我软件本身没有关系，重装软件并不能解决问题。

（以下分析，太长不看可跳到下一段）

这个报错大概率是由于 **输出重定向的默认空设备找不到** 引起。Python的subprocess库会在打开一个管道时，将未使用的stderr流 默认重定向到一个名为`nul`的特殊设备文件。`nul`用于接收和丢弃所有写入到它的无用数据。
但是，你在更新系统的过程中，出现了某些意外因素，导致`nul`不存在或不可访问了：

1. `nul`设备文件被删除或移动了：在更新系统时，可能会进行系统清理或升级操作，导致某些系统文件或目录发生变化，而恰好如果`nul`文件被删除或移动了。
2. 用户权限不足：系统更新后，可能某些安全措施升级，导致咱Umi-OCR没有足够的权限来访问 `nul`设备。

（结论，解决方案：）

以下是有可能有效的解决方案：

方法1. 系统更新未完成：静等一段时间，或者去设置→windows更新→检查更新，等待所有更新步骤完成，让`nul`文件自己回到原位。
方法2. 手动恢复`nul`文件：下载这个[null.zip](https://github.com/hiroi-sora/Umi-OCR/files/11026837/null.zip)，解压出来的`null.sys`扔到这两个路径下：`C:\Windows\System32\drivers` 和 `C:\Windows\WinSxS` ，然后重启系统。
方法3. 提高权限：以管理员身份运行Umi-OCR试试。

（由于这个报错非常稀有，我也是第一次遇到，只能推测成因；所以上述处理方案不一定有效。）

还有个必然有效的解决方案：重装系统。
