### ISSUE TITLE
新版本没有 [自动清空面板] 请勤劳的作者大大添加一下

### ISSUE THREAD

**Issue by qq0536** [hiroi-sora/Umi-OCR#290]
新版本没有 [自动清空面板] 请勤劳的作者大大添加一下

**Comment by hiroi-sora** [comment]
实际上这是故意的。旧版软件的文本输出面板较为简陋，所有记录混在一个文本框里，所以添加一个`自动清空面板`来让易于区分最新记录。

但新版软件已经让每个记录位于单独的文本框里，不太容易搞混。还能在图片上直接叠加显示文本。所以我认为`自动清空面板`功能已经不必要了。

该功能的实现上是很容易的。比如你可以打开 `UmiOCR-data\qt_res\qml\Widgets\ResultLayout\ResultsTableView.qml` ，在第22行，即addOcrResult函数的开头添加一行代码：
```qml
        tableMouseArea.selectAllDel()
```
就能实现自动清空。

你可以先自己修改试用一下，看看有无必要。

**Comment by qq0536** [comment]
谢谢 完美解决   好用
