### ISSUE TITLE
响应未返回旋转角度

### ISSUE THREAD

**Issue by lianzuo123** [hiroi-sora/Umi-OCR#291]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/70282596/aaec401c-4ee0-4249-9b7c-f97faad60af8)

参数中的options.ocr.cls为true,,但是响应数据内缺失了 旋转的角度

**Comment by hiroi-sora** [comment]
抱歉，`cls`是指 **让OCR能够处理方向不正的图片** ，而不能返回旋转角度。本软件所有兼容的OCR引擎插件，均不会返回角度。

**Comment by lianzuo123** [comment]
> 抱歉，`cls`是指 **让OCR能够处理方向不正的图片** ，而不能返回旋转角度。本软件所有兼容的OCR引擎插件，均不会返回角度。

好的,谢谢

**Comment by lianzuo123** [comment]
> 抱歉，`cls`是指 **让OCR能够处理方向不正的图片** ，而不能返回旋转角度。本软件所有兼容的OCR引擎插件，均不会返回角度。

有计划增加这个吗?

**Comment by hiroi-sora** [comment]
实际上，引擎内部并不会记录具体的角度值，只会记录一个“方向分类标签”。比如0代表正朝上，1代表旋转90°，2代表旋转180°……你需要这样的数值吗？

**Comment by lianzuo123** [comment]
> 实际上，引擎内部并不会记录具体的角度值，只会记录一个“方向分类标签”。比如0代表正朝上，1代表旋转90°，2代表旋转180°……
> 
> 让引擎返回方向分类标签需要改改引擎源码，稍微有点麻烦，短期内优先级不高。

收到
