### ISSUE TITLE
Umi-OCR.exe运行失败

### ISSUE THREAD

**Issue by qiunlp** [hiroi-sora/Umi-OCR#293]
双击Umi-OCR.exe没有反应，命令行中运行 Umi-OCR.exe ，出现如下信息，请问您缺了什么库？麻烦您了！
![1](https://github.com/hiroi-sora/Umi-OCR/assets/24563279/6ee9df92-f503-4301-90e5-6a2201fd6659)

**Comment by hiroi-sora** [comment]
看起来是系统不兼容。从你的图片中看，似乎是比win7更老的系统。本程序最低只提供至win7的支持。

**Comment by qiunlp** [comment]
谢谢您的及时回复。windows server 2008 r2 标准版是否支持？

**Comment by hiroi-sora** [comment]
它基于 Windows Vista ，是比win7更老的系统。有许多python第三方库已经停止了对它的支持，所以可能会存在一些难以解决的兼容性问题。

**Comment by qiunlp** [comment]
好的，非常感谢啦！！！
