### ISSUE TITLE
未来能否将快捷键改为键盘钩子模式

### ISSUE THREAD

**Issue by qq0536** [hiroi-sora/Umi-OCR#294]
环境Win11

比如win+a会打开下图
![1](https://github.com/hiroi-sora/Umi-OCR/assets/68144942/f229ccb2-a948-41d8-9970-6fc266f957d4)

**Comment by hiroi-sora** [comment]
主要是python没有什么靠谱的键盘钩子库。v1.3.1版本以前用过如 keyboard 等键盘库，在部分系统上会出现奇奇怪怪的问题，没有现在的全局键盘事件模式稳定可靠。
