### ISSUE TITLE
请问我用http的方式调用OCR功能，在调用几次后就调用不成功了，我看错误信息是urlopen error [WinError 10061]，这个有解决的办法吗？

### ISSUE THREAD

**Issue by zthly** [hiroi-sora/Umi-OCR#295]
请问我用http的方式调用OCR功能，在调用几次后就调用不成功了。然后我用命令行的方式调用OCR也是失败，我看错误信息是urlopen error [WinError 10061]，这个有解决的办法吗？

**Comment by hiroi-sora** [comment]
感觉上是端口占用问题。本项目目前的HTTP接口比较简陋，不支持并发。可能你在某一次调用完成后，并没有断开HTTP连接，导致端口始终被占用，所以后续的请求无法进行。

命令行调用本质上也依赖HTTP接口，所以会受到端口占用的影响。

请检查调用代码，是否在任务完成后及时断开连接。
