### ISSUE TITLE
快捷键经常失效

### ISSUE THREAD

**Issue by donkeyax** [hiroi-sora/Umi-OCR#296]
我设置的截图OCR快捷键。经常性的失效，然后再点开umi主页面，最小化又好了。

**Comment by donkeyax** [comment]
win11最新系统。12代英特尔。又给管理员权限

**Comment by hiroi-sora** [comment]
可以使用 [快捷键增强工具](https://github.com/hiroi-sora/Umi-OCR/issues/402) 。
