### ISSUE TITLE
快捷键兼容鼠标按键

### ISSUE THREAD

**Issue by wed257** [hiroi-sora/Umi-OCR#297]
例如鼠标中键   鼠标侧键

**Comment by hiroi-sora** [comment]
鼠标按键与键盘事件的处理流程较为不同，代码上兼容鼠标按键会比较麻烦。而且，该需求比较小众。

建议你使用外部方法实现该需求。比如鼠标宏软件或AutoHotkey脚本，将鼠标键映射为键盘按键。

比如，下列AHK脚本能用鼠标侧键1触发`win+alt+C`，侧键2触发`win+alt+V`，调用Umi-OCR的功能。将它保存为.ahk文件，用AHK打开即可使用。
```AutoHotkey
XButton1::#!c
XButton2::#!v
```

**Comment by wed257** [comment]
感谢 辛苦了

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/402

通过这个方式也可以实现鼠标控制功能。

例：
`XButton1 umi-ocr --screenshot`
