### ISSUE TITLE
【请求适配引擎】chineseocr_lite

### ISSUE THREAD

**Issue by qwedc001** [hiroi-sora/Umi-OCR#298]
（其实是我自己适配的时候遇到问题了hhhhh）
未经严格测试，但是在我个人使用chineseocr_lite引擎（https://github.com/DayBreak-u/chineseocr_lite ，访问方式为开启服务器并使用requests进行ocr提交，另有访问方式可以直接通过获取model.py下的OcrHandle进行直接predict）时对于批量OCR的效率要大于paddleOCR。
当然，我也注意到paddle可以自行调整使用核心数量等参数，所以我在考虑进一步进行测试。

**Comment by qwedc001** [comment]
同时我本人也在尝试对chineseocr进行适配，如果成功我也会提交pr。

**Comment by hiroi-sora** [comment]
我最近正忙于本项目PDF文档识别的工作，暂时开发排期已满。

如果你遇到任何问题，可以来问我，我会尽可能的帮你解答。我欢迎任何开发者 向本项目贡献新引擎插件~

将现有离线引擎项目封装成Umi插件的大概开发流程如下：
1. 本地建立一个独立的 python 3.8.10 x64 虚拟环境。
2. 在该环境中，部署一个引擎项目的最小demo，确保可以使用基础OCR功能。所有依赖库均要安装在虚拟环境中。
3. 依赖库在虚拟环境中的存放位置为： `环境venv\Lib\site-packages` 。将 `site-packages` 中的所有文件拷贝。
4. 创建一个Umi插件目录，将 `site-packages` 目录粘贴进去。
5. 插件开发参考 [开发文档](https://github.com/hiroi-sora/Umi-OCR_plugins/tree/main/demo_AbaOCR) 。在引擎启动方法`def start(self, argd)`中，使用如下语句加载依赖库：
```python
    def start(self, argd):
        if self.ocr:  # 如果引擎已启动，则跳过启动步骤。
            return ""
        site.addsitedir(SitePackages)  # 将依赖目录 ./site-packages 添加到python搜索路径
        try:
            from xxx import XXX  # 导入依赖库
            self.ocr = XXX()  # 使用依赖库，初始化引擎对象
```

除了开发文档，你也可以参考 [P2T插件的代码](https://github.com/hiroi-sora/Umi-OCR_plugins/blob/main/win7_x64_Pix2Text/p2t_api.py) 。

另外，如果可以的话尽量不要用服务器的交互模式，需要额外考虑端口占用、进程管理等问题。能在python内部解决交互就最好了。

**Comment by qwedc001** [comment]
明白。我会尝试使用内部交互完成封装，完成以后会提交pr

**Comment by qwedc001** [comment]
好的，我自己完成封装了
封装后同样测试条件下chineseocr占用略低一些，不过批量的速度比paddleOCR要慢，置信率也略低，可能是和项目本身模型追求极致轻量有关。我还没有来得及跟rapid进行比较
然后chineseocr要装numpy，还有一些其他的site-packages，我都已经放到我的项目里了，您可以先review一下，如果满足提交pr的条件，我就fork插件库提交pr了
https://github.com/qwedc001/chineseocr_umi_plugin

**Comment by hiroi-sora** [comment]
好，我检查一下

**Comment by hiroi-sora** [comment]
我进行了一些修改，给你PR了。
https://github.com/qwedc001/chineseocr_umi_plugin/pull/1

看看 api_chineseocr_lite.py 开头的注释，我提了一些未来优化的方向。

你先将 TODO 1 解决了，即优化git结构，移除不必要跟踪的二进制文件及第三方库，减小git体积。
然后PR到我的插件库。

TODO 2~4 在未来可以慢慢优化。

感谢你的贡献~

**Comment by qwedc001** [comment]
好的，谢谢啦
git结构是我上传的时候忘了写gitignore导致的，一会就改
作者大大辛苦了

**Comment by hiroi-sora** [comment]
然后PR给我的时候，也许可以使用 submodule 的模式。
先fork一份 `qwedc001/Umi-OCR_plugins` ，将 `qwedc001/chineseocr_umi_plugin` 连接为它的子模块。Readme也补充一下。

最后将 `Umi-OCR_plugins` PR给我。不需要提交 `chineseocr_umi_plugin` 本身。
这样你以后维护 `chineseocr_umi_plugin`这一个项目就行了，简单一点。

具体我也没试过，你可以研究一下哈
https://zhuanlan.zhihu.com/p/87053283

**Comment by qwedc001** [comment]
todo1 已完成。
2，3在路上。我打算先提交一个pr版本，确认submodule正常后再进行修改。
4的话，我刚刚去原repo看了一下，原项目chineseocr_lite是原作者基于chineseocr项目做的精简模型，可能是会存在这样的问题，我可能后续会再做一版原有chineseocr模型的适配。到时候现有项目会标识上一个Lite插件的标志。
原有chineseocr支持CPU和GPU推理，给出的示意图说是能稳定在半秒内出一张图，但是我还没有进行测试。加上pytorch等一系列部署相对比较麻烦，可能需要考察一下制作成插件的可行性再进行。
总之我一会去折腾pr，谢谢啦

**Comment by qwedc001** [comment]
折腾完了，没啥问题merge以后这个issue就可以close啦，谢谢啦
hiroi-sora/Umi-OCR_plugins#1

**Comment by hiroi-sora** [comment]
OK，完整插件包传到你仓库的release里

**Comment by hiroi-sora** [comment]
另外我想补充一下：
- 我个人不是特别看好 chineseocr 。它的语言库少（只支持中英），对cv2和numpy库强依赖（发行包体积大）。对比Paddle系引擎，似乎没有特别突出的优势。
- 当然还是感谢你的工作，拓展Umi插件生态总是好的。
---
- Paddle系中文模型库的精度较为优秀。但对于非中文语言，如日韩语等，则不太令人满意。本项目下就有一些issues吐槽日语精度不够好。
- 我比较看好 [tesseract-ocr](https://github.com/tesseract-ocr/tesseract) / [pytesseract](https://github.com/madmaze/pytesseract)，这个项目对于多国语言可能有更好的训练。
- tesseract核心推理组件是C++编写的，比纯python在性能和发行体积上会有优势，不依赖cv2。

你有足够经验和能力。可否尝试为Umi开发tesseract插件？

**Comment by qwedc001** [comment]
```
你有足够经验和能力。
```
有这句话就足够啦。
可以的，我本身接触到这个项目就是在和学长寻找OCR工具的时候看到的，我们当时手上使用的模型就是chineseocr，没有事先接触paddle，所以一开始的判断有误。
既然现在会写插件了，我还是很乐意加入插件开发的。

**Comment by hiroi-sora** [comment]
嗯嗯，不急，慢慢来~
