### ISSUE TITLE
如何打包

### ISSUE THREAD

**Issue by woqq111** [hiroi-sora/Umi-OCR#3]
十分感谢你提供的程序，我想要修改一些操作，但是-D打包后出现控制台，而且包很大，请问你是怎么用`pyinstaller -F -w -i icon/icon.ico -n "Umi-OCR 批量图片转文字" main.py`来打包的呢，这个应该只会把一个文件打包，如果修改spec导入其它文件后-F会出现文字识别卡死的情况

**Comment by woqq111** [comment]
算是解决问题了
修改了spec下面的部分

```spec
Analysis(['main.py','asset.py','callingOCR.py','config.py','selectAreaWin.py'],
datas=[('PaddleOCR-json','PaddleOCR-json')],

name='Umi-OCR 批量图片转文字',
console=False,
entitlements_file=None, icon='icon\\icon.ico' )
```

然后不用`os.system`（用这个是为了简化操作，识别后弹出记事本，但后果是出现控制台），用`subprocess.call('notepad ' + outPath, creationflags=0x08000000)`代替

最后`pyinstaller -D -w '.\Umi-OCR 批量图片转文字.spec'`出一个文件夹，里面有那个闪闪发光的exe文件

**Comment by hiroi-sora** [comment]
完成任务后打开文件，是个实用的功能~ 已加入正式版v1.2.2。

我用的是 `os.startfile( path )` 大法，通吃“打开记事本”和“打开资源管理器”两种功能；也不会弹出控制台。
