### ISSUE TITLE
提示 无法启动引擎 winError2 系统找不到指定文件

### ISSUE THREAD

**Issue by yinyinfeiqiao** [hiroi-sora/Umi-OCR#30]
点开始任务 按钮提示

**Comment by hiroi-sora** [comment]
1. 报错弹窗可以截图放上来么？
2. 系统版本？
3. 是否混搭了新旧UmiOCR版本的配置文件或语言扩展包？

**Comment by yinyinfeiqiao** [comment]
应该是没有识别到PaddleOCR_json.exe。把PaddleOCR-json文件夹和生成的转换工具.exe放在同一级 就可以了

**Comment by hiroi-sora** [comment]
是滴，引擎组件默认要放在python入口文件（或exe文件）的同目录下。如果你想放在别的地方，可以修改配置文件 `Umi-OCR_config.json` 中的`ocrToolPath`属性。（配置文件在初次启动时生成）
