### ISSUE TITLE
有没有考虑增加linux版本

### ISSUE THREAD

**Issue by shanguwei** [hiroi-sora/Umi-OCR#300]

**Comment by hiroi-sora** [comment]
原生支持linux：未来有计划，短期内开发排期已满暂时不考虑。

第三方提供的docker支持： https://github.com/iszmxw/ocr-docker

**Comment by EverythingGoesWithTheFlow** [comment]
> 原生支持linux：未来有计划，短期内开发排期已满暂时不考虑。
> 
> 第三方提供的docker支持： https://github.com/iszmxw/ocr-docker

这个试了，识别中文时返回904，json返回异常

**Comment by EverythingGoesWithTheFlow** [comment]
> 原生支持linux：未来有计划，短期内开发排期已满暂时不考虑。
> 
> 第三方提供的docker支持： https://github.com/iszmxw/ocr-docker

<img width="410" alt="报错返回" src="https://github.com/hiroi-sora/Umi-OCR/assets/54532769/06c5f042-eb8d-4294-8d36-a93eba32894f">

**Comment by Jxells** [comment]
希望能增加linux版本

**Comment by zzdboy** [comment]
也是希望能提供linux版本...ARM64版本 可以通过命令行操作OCR识别。。指定输出到txe文本里

**Comment by Mingxiangyu** [comment]
也是希望能提供linux版本

**Comment by hiroi-sora** [comment]
最新测试版中，已实验性支持 Linux 平台。经测试，对 Debian 系发行版的兼容性较好。

https://github.com/hiroi-sora/Umi-OCR/releases
