### ISSUE TITLE
为什么初始化失败呢

### ISSUE THREAD

**Issue by 178381807** [hiroi-sora/Umi-OCR#301]
[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 4, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
OCR init fail.
![image](https://github.com/hiroi-sora/Umi-OCR/assets/39585724/093f27c2-cac0-4efc-9114-04e004a26548)

**Comment by hiroi-sora** [comment]
可能是CPU指令集兼容问题，请尝试改用Rapid引擎版本。
