### ISSUE TITLE
http遍历post后出现错误An error occurred: RequestError: Error: connect ECONNREFUSED 127.0.0.1:1224

### ISSUE THREAD

**Issue by be1ongs** [hiroi-sora/Umi-OCR#303]
![微信截图_20240106145747](https://github.com/hiroi-sora/Umi-OCR/assets/33516111/ca74905e-4412-4df6-9c2e-7c588c85e511)

**Comment by be1ongs** [comment]
作者大大有空的时候帮忙看看，感谢！

**Comment by hiroi-sora** [comment]
`ECONNREFUSED` 表示连接被拒绝。有可能是连续调用过于频繁，后端的上一次连接尚未释放时就进入了下一次调用，导致端口占用等问题。

你可以尝试：
1. 两次调用之间，暂缓100ms。
2. 捕获到该错误时，重新调用一次。
