### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by OOOOccasionally** [hiroi-sora/Umi-OCR#304]
**1**单行合并的不够彻底，能不能添加一个强制单行的功能，把识别到的所有内容合并成一行，不要换行符。
**2**添加一个多次截图识别的功能。对两个以上不同位置进行截图，然后一次识别。

**Comment by hiroi-sora** [comment]
1. 强制单行

有道理。下个版本会优化段落合并功能，到时候加上`强制合并为单行`的选项。

2. 多次截图

引擎每次只能识别一张图片，多次截图只能分开多个任务进行提交。

如果先将多个图片拼成单个图片，虽然理论上只需一次任务，但是执行起来较麻烦，图像处理需要一定开销。

我不太认同这个做法的必要性。

**Comment by OOOOccasionally** [comment]
有比较旧点的win7电脑无法使用，重装win10也不行，安装的同版本win7系统，不同的电脑一共出现三个不同的问题：
1、打开没反应，盯着进程看也没反应试了bat启动也不行。
2、打开后程序只有一个框架，中间是黑屏，右击托盘图标可以进入截图功能，按鼠标截图软件就会闪退。
3、报错：
    Failed to create OpenGL context for format
    QSurfaceFormat(version 2.0,options
    QFlags<QSurfaceFormat:FormatOption>0,depthBufferSize 24,redBufferSize-1,greenBufferSize-1,blueBufferSize-1,
    alphaBufferSize 8,stencilBufferSize 8,samples -1,swapBehaviorQSurfaceFormat:DoubleBuffer,swapInterval 1,colorSpace
    QSurfaceFormat:DefaultColorSpace,profile
    QSurfaceFormat::NoProfile).
    This is most likely caused by not having the necessary graphicsdrivers installed.
    Install a driver providing OpenGL 2.0 or higher,or,if this is notpossible,make sure the ANGLE Open GL ES 2.0 emulation
    libraries (libEGL.dll,libGLESv2.dll and d3dcompiler_*.dll)areavailable in the application executable's directory or in a locationlisted in PATH.
运行bat时提示缺少什么模块，太快了一闪而过。
**这三个问题不知道是怎么回事，只是怀疑是硬件太落后，同样版本的系统有的电脑是可以用的，不知道能不能找到具体原因**

**Comment by hiroi-sora** [comment]
@OOOOccasionally 

确实，这是硬件落后或驱动缺失导致的问题，但是也有修复方法。请参考： https://github.com/hiroi-sora/Umi-OCR_v2/issues/22
