### ISSUE TITLE
建议优化部分功能。

### ISSUE THREAD

**Issue by cauzp** [hiroi-sora/Umi-OCR#307]
感谢作者提供如此优秀的软件。在7945hx的笔记本上有极佳的反应速度。
但是在使用中遇到两个不太方便地方，建议进行优化。
1. F4 + F4复制全部的快捷键无法修改，与Deepl 自动翻译冲突，建议允许自定义该操作的快捷键。
2. 提供取消开机自动弹出主页面的功能，在日常使用中该功能感觉意义不大，在开机时自动弹出与原本简洁优雅的风格略显冲突。

再次对作者团队做出的杰出贡献致敬！

**Comment by hiroi-sora** [comment]
### 1. F4 + F4复制全部的快捷键无法修改

软件中并没有设计与 `F4` 相关的快捷键哦。你说的是 `Ctrl+C 双击` 复制全部记录 吗？

这是一个组件绑定快捷键（而不是全局快捷键），是写死在前端代码里的。所以要像截屏那样 允许用户录制自定义按键的话，开发上会比较困难。未来我会考虑一下，让它可自定义。

当前，如果你熟悉 js 语法，可以尝试直接修改发行版软件中的代码来调整触发按键：

`UmiOCR-data\qt_res\qml\Widgets\ResultLayout\ResultTextContainer.qml` 第 144 行开始的`Keys.onPressed`键盘事件函数。

### 2. 取消开机自动弹出主页面

`全局设置 → 窗口 → 启动时缩小到任务栏` 勾选这个选项可以实现打开软件不弹主界面哦。

这个选项是抄 Clash for Windows 的，我觉得够用了。如果要区分软件是手动启动还是由系统自动启动的，虽然可行，就是代码会比较繁琐。

**Comment by cauzp** [comment]
感谢您的及时回复。我已解决相关问题！
