### ISSUE TITLE
Umi-OCR_Paddle_v2.0.1.7z 识别报错

### ISSUE THREAD

**Issue by Royal-zay** [hiroi-sora/Umi-OCR#308]
[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 4, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
OCR init fail.
![WeChat643e6322c2a9afcde08cc2e394484bf7](https://github.com/hiroi-sora/Umi-OCR/assets/66818654/81da6937-1b1e-4eef-b99d-1116b0774452)

**Comment by hiroi-sora** [comment]
你有个 `0xc0000142` 的报错弹窗，大概率是Paddle引擎的CPU兼容性问题（不支持没有AVX指令集的CPU，比如奔腾、赛扬、凌动等）。

请尝试换用 Rapid引擎 版本。
