### ISSUE TITLE
http识别报错

### ISSUE THREAD

**Issue by yangfei01** [hiroi-sora/Umi-OCR#310]
![95F6EEDD-2193-44d6-BB33-05578866D5AA](https://github.com/hiroi-sora/Umi-OCR/assets/39617449/7104ef5e-65f7-4a50-9e1e-91f3d4d7b02b)
第一个使用截图识别没有问题，第二个使用http识别报错

**Comment by hiroi-sora** [comment]
你的参数填错了哦。

你使用Paddle引擎，ocr.language的格式应该是类似`models/config_chinese.txt`。
但是你似乎填写的是`简体中文`，这是Rapid引擎的格式。

请再查阅一下 [文档中的Paddle引擎选项说明](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_HTTP.md#paddle%E5%BC%95%E6%93%8E%E6%8F%92%E4%BB%B6-%E9%80%89%E9%A1%B9) 。

**Comment by yangfei01** [comment]
好的，ok
