### ISSUE TITLE
在windows server2012中无法运行

### ISSUE THREAD

**Issue by 755678570** [hiroi-sora/Umi-OCR#311]
![666](https://github.com/hiroi-sora/Umi-OCR/assets/44051269/de7ee546-224b-471a-94d6-b8b9d3f010d3)
2个版本打开后都提示这个。

**Comment by hiroi-sora** [comment]
驱动不全，缺失了一些opengl软渲染依赖库。问题不大，参照下述链接即可修复：

https://github.com/hiroi-sora/Umi-OCR_v2/issues/22

**Comment by 755678570** [comment]
已成功启动，谢谢老板。
