### ISSUE TITLE
行驶证当中的0中间有一个斜杠的，无法识别0

### ISSUE THREAD

**Issue by 954224685** [hiroi-sora/Umi-OCR#318]
请参考全国统一行驶证格式，请问是否有解决办法？
![image](https://github.com/hiroi-sora/Umi-OCR/assets/112752918/cf7f9f23-928c-45e0-bc78-8a6f931483d1)
如上图所示

**Comment by hiroi-sora** [comment]
开源通用模型库，可能一般不会训练`斜杠0`这种较少见的情景。

非通用领域的任务需求，需要用专门的训练集来训练和微调模型。目前可用于行驶证识别的开源引擎较少，效果没有保证。

如果你有大量需求，建议使用付费的商业服务；百度、阿里云等服务商，都提供了成熟的证件识别（包括行驶证）的接口。

请参考：
https://cloud.baidu.com/product/ocr_cars/vehicle_license
https://help.aliyun.com/document_detail/442298.html
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/img-ocr/ocr/vehicleLicenseOCR.html
https://support.huaweicloud.com/api-ocr/ocr_03_0034.html

**Comment by 954224685** [comment]
> 通用领域的任务需求，需要用专门

感谢回复，是否有其他方式解决呢，我理解的目前的识别也是训练支持的，那是否可以单独加入这个0的训练，比如说我单独训练一下这个0，然后加资源库加到现在的系统里面？再次感谢

**Comment by hiroi-sora** [comment]
PaddleOCR支持自己训练/微调模型库，然后将自己的模型库导入Umi-OCR。

训练模型的要求：

- 拥有大量训练数据，比如一批行驶证图片及对应标签（人工识别结果）。
- 较好的电脑，最好拥有支持CUDA的高配显卡
- 有一定Python使用经验

训练步骤：

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/recognition.md
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/training.md

训练完成后，模型导入Umi的步骤：

可参考 https://github.com/hiroi-sora/Umi-OCR/issues/316#issuecomment-1890462301

**Comment by MoshiLL** [comment]
how large of a dataset of annotated driving license images is needed
