### ISSUE TITLE
Github发行版下载页面显示404

### ISSUE THREAD

**Issue by TC999** [hiroi-sora/Umi-OCR#319]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/88823709/c5e90643-9d19-4820-994a-87217c51c80a)
在发行版内点击下载压缩包会跳转到这个页面

**Comment by hiroi-sora** [comment]
1. 开科学上网
2. 如果使用了专门为github加速的一些服务，请尝试关掉，它们可能错误重定向
3. 在蓝奏云下载发行版： https://hiroi-sora.lanzoul.com/s/umi-ocr
