### ISSUE TITLE
有交流群吗

### ISSUE THREAD

**Issue by CCCpan** [hiroi-sora/Umi-OCR#321]
有交流群吗有交流群吗有交流群吗有交流群吗

**Comment by hiroi-sora** [comment]
没有😂

这个项目，目前是我单人用业余时间在开发和维护。个人时间精力有限，维护一个交流群等社区会对我产生更多压力。

各位用户有任何建议请在 Github 提 Issue ，我均会尽快查看和回复。从Umi-OCR创建至今，已经实现了众多的建议。之后也会继续满足用户提出的需求。

**Comment by acracker** [comment]
@hiroi-sora  你好, 我想截取指定位置 指定大小的 图片,然后进行识别, 有比较好的方法吗?

**Comment by hiroi-sora** [comment]
@acracker 

你可以用python进行指定范围的截图，然后调用Umi-OCR或者 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 进行识别。
