### ISSUE TITLE
长截图识别失败（约3w像素高

### ISSUE THREAD

**Issue by tinydoot** [hiroi-sora/Umi-OCR#325]
这个要求会不会太过分，但是手机里的长截图需要识别一下~~T T

**Comment by hiroi-sora** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/740f4252-9367-4f6c-b760-21d2ed74600c)

限制图片bian'chang边长 调成 `无限制` 即可。
