### ISSUE TITLE
图片转文字中许多颜表情或者是省略号符号一类的不是显示不出就是乱的，希望能改一下

### ISSUE THREAD

**Issue by 2321881815** [hiroi-sora/Umi-OCR#328]

**Comment by hiroi-sora** [comment]
中文模型库本身没有用颜表情做过训练，其字典中也没有存储表情的编码，所以表情确实是识别不出来的。此时，OCR引擎会拿出一个与表情较为相似的汉字来充数。这就造成了乱码。

至于省略号、破折号这类长符号的识别，一直是OCR技术的难点之一。目前没有很好的方法能解决这个问题。

本项目未来将继续关注并适配各种开源OCR组件，提升软件准确度和使用体验。。
