### ISSUE TITLE
建议高DPI支持

### ISSUE THREAD

**Issue by liuchanghuaX1** [hiroi-sora/Umi-OCR#33]
![image](https://user-images.githubusercontent.com/40064819/196212753-ffdf994e-87e7-479c-9e3b-a5303351b596.png)
2K屏下显示模糊不清。

**Comment by Freddd13** [comment]
@hiroi-sora +1 2k下我感觉截图时屏幕定格那个画面十分模糊

**Comment by Freddd13** [comment]
![image](https://user-images.githubusercontent.com/50367552/198820161-eb3dfbdd-310e-4b1a-8cf0-b64d3023ebeb.png)

**Comment by hiroi-sora** [comment]
@Freddd13 

> 截图时屏幕定格那个画面十分模糊

很遗憾，目前这是一个feature。截图定格的画面只能以逻辑分辨率显示，假如2k物理分辨率开200%系统缩放就变成了1280p，因此变糊。

不过只是画面显示会糊，实际截出来的图还是2k物理分辨率，不会影响OCR准确率，请放心。若仍不能接受，可以切换为系统截图模式。

如果再增加一个“透明模式”，启动截图时不冻结画面，而是在透明层上绘制瞄准线UI，等待鼠标拖拽结束时才截取画面。可以保持原分辨率显示，缺点是截取视频等动态画面会比较麻烦。你觉得这个功能怎么样？

**Comment by Freddd13** [comment]
@hiroi-sora 透明模式其实感觉意义有限hh，我刚才看到还能从剪贴板读就想着用snipaste截图送剪贴板，结果快捷键有问题b38...

**Comment by zhengqwe** [comment]
右键exe->属性->兼容性->更改高DPI设置->勾选最下面的框，在下面的下拉框里选应用程序，确定

**Comment by hiroi-sora** [comment]
[v2版本](https://github.com/hiroi-sora/Umi-OCR_v2) 已全面适配高分屏。
