### ISSUE TITLE
图片转文字无法匹配自动换行的功能

### ISSUE THREAD

**Issue by 2321881815** [hiroi-sora/Umi-OCR#331]
在字数过长，原先图片就是换行的情况下，转换之后就会被分段，字与字之间会被强制断开，在阅读器上观看的时候，自动换行只能换行同一行的文字，强制断开的那一部分不能连上，希望能以句子符号结尾断开

**Comment by 2321881815** [comment]
![Uploading IMG_20240124_214729.jpg…]()

**Comment by hiroi-sora** [comment]
收到。下个版本就会有更优化的**排版解析模块**以整理各种文本。
