### ISSUE TITLE
安卓什么时候可以支持下呢? 安卓本地接口这种

### ISSUE THREAD

**Issue by diuchouni** [hiroi-sora/Umi-OCR#332]
安卓什么时候可以支持下呢? 安卓本地接口这种

**Comment by hiroi-sora** [comment]
本项目是针对桌面平台开发的。Linux和MacOS的适配都在可行范围内，但要适配安卓等移动平台，估计会非常困难。另外，本人对安卓开发也并不了解。

如果你有在安卓使用本地OCR的需求，可以了解一下 [Paddle Lite](https://github.com/PaddlePaddle/PaddleOCR/blob/0525f6bb01bfed401f767894619f6a25ee750892/deploy/lite/readme_ch.md) 。
