### ISSUE TITLE
错误] Umi-OCR Error 主程序启动失败! gbk' codec can't encode character yu2022' in position 1718: illegalmutibte segwence ........ .......... .......sss.

### ISSUE THREAD

**Issue by xiahan4956** [hiroi-sora/Umi-OCR#336]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/22903427/46aba856-7a46-4e9b-9739-cfab5ebe97e4)

背景是批量的识别图片,用CLI,出现了这个错误

**Comment by hiroi-sora** [comment]
请问你是使用命令行指令，比如 `Umi-OCR.exe --path="xxx"` 的时候出现了该报错吗？如果是，那么使用的是什么指令？

如果某一张图片能稳定触发该bug，请将这张图片也传上来，我研究下。

**Comment by xiahan4956** [comment]
cmd = f'"{ocr_tool}" --path "{image_path}" -->"{text_path}"'
            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=True)
            
            
           就是你所说的,加了-->

图片我还没有找到,因为发现报错了也可以通过ahk的脚本跳过 - - 回头找到了发出来

**Comment by hiroi-sora** [comment]
1. 你的指令 `-->"{text_path}"` 中，是不是漏了一个空格？
2. 如果不加 `-->` ，识别同一张图片，仍会有报错吗？
