### ISSUE TITLE
Umi-OCR在设置里加“在后台运行”或者“隐藏托盘图标”功能

### ISSUE THREAD

**Issue by Doraemon0611** [hiroi-sora/Umi-OCR#338]
朋友您好，因为我设置它启动不显示主窗口，但是它图标还在托盘，可不可以在开启Umi-OCR的时候不让它的图标出现在托盘里啊！我想让它完全在后台中运行然后我就可以使用CMD命令来控制它了。或者您在设置里加一个“在后台运行”的功能。
![无标题](https://github.com/hiroi-sora/Umi-OCR/assets/132356061/9fe31264-b2ef-4601-a6af-4dfb0ad2bc4f)

**Comment by hiroi-sora** [comment]
你可以简单地修改一下代码实现：

1. 用编辑器或记事本打开 `UmiOCR-data\qt_res\qml\MainWindow\SystemTray.qml`
2. 第72行 `    visible: true` ，改为 `    visible: false`

**Comment by Doraemon0611** [comment]
嗯，谢谢。

**Comment by hiroi-sora** [comment]
下个版本中，即可在全局设置中找到隐藏托盘图标的高级选项了。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/0fb1c8ba-6d5b-4256-9039-07ad3117f5c3)
