### ISSUE TITLE
在使用PaddleOCR-json.exe的问题

### ISSUE THREAD

**Issue by Doraemon0611** [hiroi-sora/Umi-OCR#339]
在使用PaddleOCR-json.exe时，我使用 PaddleOCR-json.exe -port=64535 给它设置了 64535 的端口，我使用TCP调试助手与它进行连接，连接成功后，发送任何消息它都不响应(不返回值，在CMD面板也没信息)，我想知道，使用TCP与它连接后，我怎么实现使用TCP发送指令的方式来控制它？
![无标题123](https://github.com/hiroi-sora/Umi-OCR/assets/132356061/702f83ea-7f70-456b-880a-8192d6a6a013)

**Comment by hiroi-sora** [comment]
请仔细阅读 [PaddleOCR-json的详细使用说明](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md#%E4%BC%A0%E5%85%A5%E6%8C%87%E4%BB%A4%E5%B9%B6%E8%8E%B7%E5%8F%96%E8%BF%94%E5%9B%9E%E5%80%BC) 哦，其中提到：所有指令必须以 `\n` 为结尾，程序才能识别出这是一次完整的指令。

示例：

```
{"image_base64": "iVBORw0KGgoAAAANSUhEUgAAAC4AAAAXCAIAAAD7ruoFAAAACXBIWXMAABnWAAAZ1gEY0crtAAAAEXRFWHRTb2Z0d2FyZQBTbmlwYXN0ZV0Xzt0AAAHjSURBVEiJ7ZYrcsMwEEBXnR7FLuj0BPIJHJOi0DAZ2qSsMCxEgjYrDQqJdALrBJ2ASndRgeNI8ledutOCLrLl1e7T/mRkjIG/IXe/DWBldRTNEoQSpgNURe5puiiaJehrMuJSXSTgbaby0A1WzLrCCQCmyn0FwoN0V06QONWAt1nUxfnjHYA8p65GjhDKxcjedVH6JOejBPwYh21eE0Wzfe0tqIsEkGXcVcpoMH4CRZ+P0lsQp/pWJ4ripf1XFDFe8GHSHlYcSo9Es31t60RdFlN1RUmrma5oTzTVB8ZUaeeYEC9GmL6kNkDw9BANAQYo3xTNdqUkvHq+rYhDKW0Bj3RSEIpmyWyBaZaMTCrCK+tJ5Jsa07fs3E7esE66HzralRLgJKp0/BD6fJRSxvmDsb6joqkcFXGqMVVFFEHDL2gTxwCAaTabnkFUWhDCHTd9iYrGcAL1ZnqIp5Vpiqh7bCfua7FA4qN0INMcN1+cgCzj+UFxtbmvwdZvGIrI41JiqhZBWhhF8WxorkYPpQwJiWYJeA3rXE4hzcwJ+B96F9zCFHC0FcVegghvFul7oeEE8PvHeJqC0w0AUbbFIT8JnEwGbPKcS2OxU3HMTqD0r4wgEIuiKJ7i4MS16+og8/+bPZRPLa+6Ld2DSzcAAAAASUVORK5CYII="}\n
```

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/780da07a-77e7-4321-a60b-327e8f102176)

**Comment by Doraemon0611** [comment]
嗯，感谢！
