### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yshumy** [hiroi-sora/Umi-OCR#340]
win 11:
<img width="798" alt="截屏2024-02-03 19 20 56" src="https://github.com/hiroi-sora/Umi-OCR/assets/103359913/238713db-62ee-46f7-81f5-fb685a726d54">

**Comment by hiroi-sora** [comment]
你的CPU不兼容Paddle引擎，请使用Rapid版本。

**Comment by yshumy** [comment]
> 你的CPU不兼容Paddle引擎，请使用Rapid版本。

忘了说是苹果虚拟机win 11 了。
