### ISSUE TITLE
点适应窗口后图片消失

### ISSUE THREAD

**Issue by yshumy** [hiroi-sora/Umi-OCR#341]
原图：

<img width="513" alt="截屏2024-02-03 19 06 18" src="https://github.com/hiroi-sora/Umi-OCR/assets/103359913/06463071-eb89-4af4-927a-b0683242726e">

点适应窗口后：

<img width="769" alt="截屏2024-02-03 23 54 05" src="https://github.com/hiroi-sora/Umi-OCR/assets/103359913/86112bc8-e6a7-480d-bd93-6773db53d319">

**Comment by hiroi-sora** [comment]
这个bug是由于图片组件未加载完毕时提前调用某些函数，导致除0错误。我已经改正了一些代码，避免了此问题。

但是，正常情况下，图片组件的加载是一瞬间的事情，提前调用函数的几率微乎其微。如果你是在虚拟机环境下运行，也许环境因素也导致了组件状态的一些异常。

如果你能稳定复现该bug，请告诉我更多信息。

以及， **在图片已经显示的前提下，点击适应窗口，是否会出现该bug？**
