### ISSUE TITLE
本地客户端使用局域网服务器

### ISSUE THREAD

**Issue by GoldBro233** [hiroi-sora/Umi-OCR#342]
我根据 Issue #286 在我的服务器上部署了服务器
但是我不知道如何在本地客户端上使用
我只在当前接口中看到了PaddleOCR 选项
请问能给予指导嘛？

**Comment by hiroi-sora** [comment]
目前的设计中，“服务器模式” 是为轻度开发者提供一个简便的接口，可以用自己的程序来调用Umi的功能。

暂时不支持第二台Umi客户端访问服务器模式，未来可能开发该功能。
