### ISSUE TITLE
关于输出内容的问题

### ISSUE THREAD

**Issue by AlvinPPP** [hiroi-sora/Umi-OCR#343]
批量任务输出信息中能否加上一列“状态”；就是左侧列表中“耗时”、“状态”那个“状态”；
我发现这个状态有点像置信区间或者识别效果的意思，通常在0.9以上就比较好，但有时候也会出现比较低的情况。
由于输出的信息里没有保留“状态”信息，在后续对已识别数据进行清洗的时候发现，状态值低的数据通常没有价值；
所以我寻思，如果输出信息里保留有“状态”信息，那在后续清洗的时候就能比较有效地鉴别和挑选了。
谢谢。

**Comment by hiroi-sora** [comment]
如果你想后续对数据进行二次加工，强烈建议先输出为jsonl格式，然后再用自己的代码逐行读入进行检查。

jsonl文件中包含了所有OCR原始信息，包括置信度。你可以根据这些信息进行处理。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/de8de1a6-9509-4336-8056-d0aac8e9ff07)
