### ISSUE TITLE
Windows服务器2012,系统版本8.1运行不了，opengl版本低

### ISSUE THREAD

**Issue by neauxty** [hiroi-sora/Umi-OCR#344]
![Uploading WX20240204-211521@2x.png…]()

**Comment by neauxty** [comment]
Failed to create OpenGL context for formatQSurfaceFormat(version 2.0, optionsQFlags<QSurfaceFormat::FormatOption>0, depthBufferSize 24.redBufferSize -1, greenBufferSize -1, blueBufferSize -1,alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehaviorQSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpaceQSurfaceFormat::DefaultColorSpace, profileOSurfaceFormat::NoProfile).This is most likely caused by not having the necessary graphicsdrivers installed..
Install a driver providing OpenGL 2.0 or higher, or, if this is notpossible, make sure the ANGLE Open GL ES 2.0 emulation libraries(libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in theapplication executable's directory or in a location listed in PATH.

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR_v2/issues/22

**Comment by neauxty** [comment]
感谢作者，刚刚也搜到了，我试试
