### ISSUE TITLE
关于图片被旋转或者干脆就是竖着的图(90度或者270°)

### ISSUE THREAD

**Issue by neauxty** [hiroi-sora/Umi-OCR#345]
要是用户上传的是被旋转过得图，有exif写着旋转角度还好处理些，有的干脆就是竖着的，基本上识别不出来

**Comment by hiroi-sora** [comment]
如果你使用服务器模式，请在上传参数中将 **进行图像旋转校正** 设为 true 。具体参数名称请看 [文档](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_HTTP.md) 。

**Comment by neauxty** [comment]
> 如果你使用服务器模式，请在上传参数中将 **图像旋转校正** 设为 true 。具体参数名称请看 [文档](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_HTTP.md) 。

收到，感谢大佬！
