### ISSUE TITLE
有点疑惑：识别率低于十年前的一款离线OCR软件

### ISSUE THREAD

**Issue by yshumy** [hiroi-sora/Umi-OCR#347]
用这张图测试，旮旯二字只识出一个：
<img width="749" alt="截屏2024-02-04 00 03 02" src="https://github.com/hiroi-sora/Umi-OCR/assets/103359913/e37bddf7-e4ab-4498-b2ce-66c029669526">

**Comment by hiroi-sora** [comment]
受限于模型大小、训练数据集的选择等，OCR引擎对于部分不常见文字的识别率低是正常的，如`旯`。另外，测试图片的大小、背景颜色、字体等因素也会影响识别效率。你可以用更多样本进行测试对比，在更大的范围上统计或体验识别率。

本项目使用的Paddle系列模型，已经是当前开源领域中，简体中文OCR精度最好的文字识别模型之一。十年来神经网络技术的发展日新月异，精度和效率会远优于老的技术。

如果各位用户发现有更优秀的OCR项目可以告诉我。Umi-OCR支持将各种离线引擎或在线服务制作成插件，载入软件中使用。

如果免费的开源项目无法满足你的精度需求，你应该寻求商用付费的高精度OCR服务，百度阿里等云服务商都有提供类似服务。

**Comment by yshumy** [comment]
[千百OCR3.1.7β绿色版.zip](https://github.com/hiroi-sora/Umi-OCR/files/14181111/OCR3.1.7.zip)

**Comment by yshumy** [comment]
> 受限于模型大小、训练数据集的选择等，OCR引擎对于部分不常见文字的识别率低是正常的，如`旯`。另外，测试图片的大小、背景颜色、字体等因素也会影响识别效率。你可以用更多样本进行测试对比，在更大的范围上统计或体验识别率。
> 
> 本项目使用的Paddle系列模型，已经是当前开源领域中，简体中文OCR精度最好的文字识别模型之一。十年来神经网络技术的发展日新月异，精度和效率会远优于老的技术。
> 
> 如果各位用户发现有更优秀的OCR引擎项目可以告诉我。Umi-OCR支持将各种离线引擎或在线服务制作成插件，载入软件中使用。
> 
> 如果免费的开源项目无法满足你的精度需求，你应该寻求商用付费的高精度OCR服务，百度阿里等云服务商都有提供类似服务。

另外，请问是否支持完整的Unicode码字符集？

**Comment by hiroi-sora** [comment]
1. 千百OCR并非离线，而是要申请或购买百度在线接口。5MB的软件包也塞不下离线模型库。

百度接口是个一直在更新的商业服务，识别准确率比开源、离线组件好是正常的。

2. Unicode集含有超过100k字符。哪怕是世界上最强大的人工智能服务，如大语言模型gpt-4，没有“学会”如此多字符的相关知识，更别提本地小模型了。

PaddleOCR的简体中文字典中包含了约6.6k个常用汉字及符号。
