### ISSUE TITLE
为什么返回值都是原始输入的结果，经过函数处理的结果都没有返回和处理，一直的是原始的，这逻辑是否有错？

### ISSUE THREAD

**Issue by cqray1990** [hiroi-sora/Umi-OCR#350]
def run(self, textBlocks):
        textBlocks = linePreprocessing(textBlocks)  # 预处理
        textBlocks = self.gtree.sort(textBlocks)  # 构建间隙树
        nodes = self.gtree.get_nodes_text_blocks()  # 获取树节点序列
        # 段内分析
        for tbs in nodes:
            self.pp.run(tbs)  # 预测结尾分隔符
            for tb in tbs:
                del tb["normalized_bbox"]
        return textBlocks

    def run(self, textBlocks):
        textBlocks = linePreprocessing(textBlocks)  # 预处理
        # 整版分析
        self.pp.run(textBlocks)  # 预测结尾分隔符
        for tb in textBlocks:
            del tb["normalized_bbox"]
        return textBlocks

**Comment by hiroi-sora** [comment]
没有错的哦，经过函数处理的结果已经写入 textBlocks 变量了

**Comment by cqray1990** [comment]
> 没有错的哦，经过函数处理的结果已经写入 textBlocks 变量了

我调试之后发现没变

 self.pp.run(textBlocks)  # 预测结尾分隔符
这个函数之后的：

    def run(self, text_blocks: list):
        """
        对属于一个区块内的文本块列表，进行段落分析，预测每个文本块结尾的分隔符。

        :param text_blocks: 文本块对象列表
        :return: 排序后的文本块列表
        """
        # 封装块单元
        units = self._get_units(text_blocks, self.get_info)
        # 执行分析
        self._parse(units)
        return text_blocks
 self._parse(units)中解析的段落paras变量才有变化，后又把units返回了

**Comment by hiroi-sora** [comment]
哈哈，你观察得很仔细，我解释一下。

1. 关于 `linePreprocessing` ：此步骤中，根据旋转角度等信息，为每个元素构建标准化包围盒`tb["normalized_bbox"]` 。过程中产生的其余中间量无需返回。
2. 关于 `self.pp.run(textBlocks)` ：此步骤中，向列表的每个元素写入结尾间隔符 `tb["end"]` 。只需改变每个元素的内容，而不需要改变列表的结构（比如增加、删除元素）。

总之，传入列表（的引用），在子模块内根据引用修改原始列表的元素内容，不需要返回值。
