### ISSUE TITLE
识别后的行顺序错位

### ISSUE THREAD

**Issue by StrollStars** [hiroi-sora/Umi-OCR#353]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/10942225/1b8838fd-1e31-4e18-ab02-3418fe65a446)
如图，识别后的第二行和第三行与实际的相反，RapidOCR 2.0.2

**Comment by hiroi-sora** [comment]
试一下 [2.1.0版](https://github.com/hiroi-sora/Umi-OCR/releases/tag/alpha%2F2.1.0)

**Comment by StrollStars** [comment]
@hiroi-sora 对比测试后发现，问题是出在设置的段落合并中，2.0.2版中的单行存在这个问题，但是2.1.0版不再有这个选项，所以没有这个问题了。不过我发现了另外个问题，2.1.0版我直接运行Umi-OCR.exe没有成功，是通过RUN_GUI.bat启动的程序。

**Comment by StrollStars** [comment]
@hiroi-sora 对比测试后发现，问题是出在设置的段落合并中，2.0.2版中的单行存在这个问题，但是2.1.0版不再有这个选项，所以没有这个问题了。不过我发现了另外个问题，2.1.0版我直接运行Umi-OCR.exe没有成功，是通过RUN_GUI.bat启动的程序。

**Comment by StrollStars** [comment]
测试2.1.0版的排版方案，没发现此问题。
