### ISSUE TITLE
截图OCR时可以选定屏幕上一个固定区域进行连续截图么？

### ISSUE THREAD

**Issue by ryanwrz** [hiroi-sora/Umi-OCR#357]
是近几年用过的体验最佳OCR工具，内网神器，给up点赞！

请问截图OCR时可以选定屏幕上一个固定区域进行连续截图么？不用每次重复框选这样的？

也期待未来版本的直接导入excel，将绝杀！
(•̀ᴗ•́)و ̑̑(•̀ᴗ•́)و ̑̑(•̀ᴗ•́)و ̑̑

**Comment by hiroi-sora** [comment]
感谢支持~

固定区域OCR，已经有一些现成的、成熟的项目了，比如 [团子翻译器](https://github.com/PantsuDango/Dango-Translator) 。因此，本项目进行这类重复工作的优先级不高。

不过，近期我打算添加一个类似的简单功能，按下快捷键 可以获取上一次的屏幕区域并进行OCR（无需重复手动框选）。这样也能简化你的操作。
