### ISSUE TITLE
能否保留原pdf的名字

### ISSUE THREAD

**Issue by shimaoyu** [hiroi-sora/Umi-OCR#358]
在转双层pdf时最好能保留原pdf名的文件格式和路径
左侧的pdf的页数区间能否导出excel表格出来
左侧的选择文件夹可以多层级文件夹选pdf

**Comment by hiroi-sora** [comment]
### 1. 保留原pdf名的文件格式和路径

在标签页内的设置面板中，勾选高级，然后将 `文件名格式`  改为 `%name` 。此时新生成的文件的前缀就能与原文件一致，不过后缀为 `.layered.pdf` 。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/f072133f-0f2d-4adc-9acd-45a822474e6a)

如果你连后缀都想与原来一致（即为.pdf），需要自己修改代码。请用记事本打开`UmiOCR-data\py_src\ocr\output\output_pdf_layered.py`，第15行为：
```python
        self.outputPath = f"{self.dir}/{self.fileName}.layered.pdf"  # 输出路径
```
修改为以下即可：
```python
        self.outputPath = f"{self.dir}/{self.fileName}.pdf"  # 输出路径
```

### 2. 左侧的pdf的页数区间能否导出excel表格出来

暂时没有做这个功能的打算

### 3. 左侧的选择文件夹可以多层级文件夹选pdf

在设置中，勾选 **递归读取子文件夹** 即可，见上图的蓝色框框。

**Comment by shimaoyu** [comment]
左侧那个文档和状态，范围
能增加个导出表格这个功能吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月18日(周日) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)




 
1. 保留原pdf名的文件格式和路径
 
在标签页内的设置面板中，勾选高级，然后将 文件名格式  改为 %name 。此时新生成的文件的前缀就能与原文件一致，不过后缀为 .layered.pdf 。
 
image.png (view on web)
 
如果你连后缀都想与原来一致（即为.pdf），需要自己修改代码。请用记事本打开UmiOCR-data\py_src\ocr\output\output_pdf_layered.py，第15行为：
         self.outputPath = f"{self.dir}/{self.fileName}.layered.pdf"  # 输出路径
 
修改为以下即可：
         self.outputPath = f"{self.dir}/{self.fileName}.pdf"  # 输出路径
 
2. 左侧的pdf的页数区间能否导出excel表格出来
 
暂时没有做这个功能的打算
 
3. 左侧的选择文件夹可以多层级文件夹选pdf
 
在设置中，勾选 递归读取子文件夹 即可，见上图的蓝色框框。

**Comment by hiroi-sora** [comment]
抱歉，该功能看起来比较小众，我暂时不会考虑。

如果您有编程基础，可以尝试自己实现。大致思路：

在`UmiOCR-data\qt_res\qml\Widgets\FilesTableView.qml`中，获取`headers`和`dataModel`的值，以csv等方式打印或保存。

**Comment by shimaoyu** [comment]
1这个功能也不算小众，如果是大量pdf要统计页数，比如档案数字化加工时就能用着
2还有一个问题比如有一个pdf是占用的内存是2M
用咱这个Umi-OCR双层pdf后保存的pdf变成1M多，是给压缩了吗（不应该比2M多才是吗？多加了一层文字）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)




 
抱歉，该功能看起来比较小众，我暂时不会考虑。
 
如果您有编程基础，可以尝试自己实现。大致思路：
 
在UmiOCR-data\qt_res\qml\Widgets\FilesTableView.qml中，获取headers和dataModel的值，以csv等方式打印或保存。

**Comment by hiroi-sora** [comment]
1. 了解，后续会考虑该功能。如果有更多用户有类似需求，会提高开发优先级。
2. 是的，默认启用了压缩。一方面，对图片内容进行无损压缩。另一方面，对字体文件进行了裁切，即删除字库中未被使用的文字。我认为尽量节约存储空间是好文明~~

**Comment by shimaoyu** [comment]
pdf功能能不启用压缩功能吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月21日(周三) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)




  
了解，后续会考虑该功能。如果有更多用户有类似需求，会提高开发优先级。
 
是的，默认启用了压缩。一方面，对图片内容进行无损压缩。另一方面，对字体文件进行了裁切，即删除字库中未被使用的文字。我认为尽量节约存储空间是好文明~~

**Comment by hiroi-sora** [comment]
> 不启用压缩功能

可以。请用记事本或编辑器打开 `UmiOCR-data\py_src\ocr\output\output_pdf_layered.py`。

第85行，原本是：
```
            self.pdf.ez_save(self.outputPath)
```
将`ez_`删掉，也就是改为：
```
            self.pdf.save(self.outputPath)
```

**Comment by shimaoyu** [comment]
这个软件单层转双层pdf一次性只能转200多个pdf，能修改吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)




 
抱歉，该功能看起来比较小众，我暂时不会考虑。
 
如果您有编程基础，可以尝试自己实现。大致思路：
 
在UmiOCR-data\qt_res\qml\Widgets\FilesTableView.qml中，获取headers和dataModel的值，以csv等方式打印或保存。

**Comment by shimaoyu** [comment]
单层pdf转双层pdf一次性最多可以拖多少个pdf,
我拖进去500个pdf，为啥只能200个pdf，这个参数能改成，想拖进去多少个就显示多少个吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月21日(周三) 晚上6:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)




  
不启用压缩功能
  
可以。请用记事本或编辑器打开 UmiOCR-data\py_src\ocr\output\output_pdf_layered.py。
 
第85行，原本是：
             self.pdf.ez_save(self.outputPath)  
将ez_删掉，也就是改为：
             self.pdf.save(self.outputPath)

**Comment by shimaoyu** [comment]
能换成office识别吗？现在我看有win7和win10识别库。这个识别快





------------------ 原始邮件 ------------------
发件人: hiroi-sora ***@***.***&gt;
发送时间: 2024年2月21日 17:58
收件人: hiroi-sora/Umi-OCR ***@***.***&gt;
抄送: shimaoyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)





  
了解，后续会考虑该功能。如果有更多用户有类似需求，会提高开发优先级。
 
是的，默认启用了压缩。一方面，对图片内容进行无损压缩。另一方面，对字体文件进行了裁切，即删除字库中未被使用的文字。我认为尽量节约存储空间是好文明~~

**Comment by hiroi-sora** [comment]
> 单层pdf转双层pdf一次性最多可以拖多少个pdf, 我拖进去500个pdf，为啥只能200个pdf，这个参数能改成，想拖进去多少个就显示多少个吗

这个可能跟系统有关，一次不能拖太多文件。可以尝试分批拖进，或者将父文件夹拖进来。程序里是没有限制任务数量上限的，一次几百个文档我也测试过，在我这边是没有问题的。

**Comment by shimaoyu** [comment]
识别精度还可以我看着



------------------ 原始邮件 ------------------
发件人: hiroi-sora ***@***.***&gt;
发送时间: 2024年6月3日 21:15
收件人: hiroi-sora/Umi-OCR ***@***.***&gt;
抄送: shimaoyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)





  
能换成office识别吗？现在我看有win7和win10识别库。这个识别快
  
你指的是 Windows 自带的 OCR 吗？它的精度并不高，配置起来也不算简单（可能需要在系统设置中下载目标语言的识别包），所以 Umi 目前并没有使用该接口。
 
不过，有需要的开发者可以用它自行开发 Umi-OCR 插件 。

**Comment by shimaoyu** [comment]
您有微信吗？想加您微信





------------------ 原始邮件 ------------------
发件人: hiroi-sora ***@***.***&gt;
发送时间: 2024年6月3日 21:15
收件人: hiroi-sora/Umi-OCR ***@***.***&gt;
抄送: shimaoyu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hiroi-sora/Umi-OCR] 能否保留原pdf的名字 (Issue #358)





  
能换成office识别吗？现在我看有win7和win10识别库。这个识别快
  
你指的是 Windows 自带的 OCR 吗？它的精度并不高，配置起来也不算简单（可能需要在系统设置中下载目标语言的识别包），所以 Umi 目前并没有使用该接口。
 
不过，有需要的开发者可以用它自行开发 Umi-OCR 插件 。

**Comment by hiroi-sora** [comment]
> 您有微信吗？想加您微信

不好意思哈，我暂不会提供微信联系方式。如有需要，可以邮件联系我：

hiroi-sora@qq.com
