### ISSUE TITLE
能否提供高级指令的调用示例，感谢！

### ISSUE THREAD

**Issue by jingkanghou** [hiroi-sora/Umi-OCR#359]
抱歉，对python的命令行调用知识了解不多，能否提供高级指令调用示例？非常感谢！

比如：BatchOCR模块中有msnPaths函数，但是该函数的定义如下：
def msnPaths(self, paths, argd):
在命令行中如何调用该函数，如何传入self,如果传入paths？

**Comment by hiroi-sora** [comment]
高级指令是一个实验性质的功能。一般而言，只推荐通过它调用无参函数（self不算参数）；调用有参函数会非常麻烦。

比如说msnPaths需要两个参数，paths要求传入列表，argd要求传入一些参数字典。但高级指令只支持传入字符串类型，无法传入列表和字典，因此无法实现调用msnPaths。

如果你有批量识别图片路径的需求，建议在在自己的代码中，循环调用`Umi-OCR.exe --path "D:/xxx.png"`接口，一次只识别一张图片。

**Comment by jingkanghou** [comment]
好的，谢谢！
如果能支持批量ocr的指令就更好了，比如ocr指定路径下的所有图像文件。
