### ISSUE TITLE
想问下大佬，pdf文档识别有没有命令行或者说http调用的方法呢？

### ISSUE THREAD

**Issue by Mingxiangyu** [hiroi-sora/Umi-OCR#362]
@hiroi-sora 大佬新年快乐，拜个晚年，麻烦解答下

**Comment by hiroi-sora** [comment]
新年快乐~

2.1.0版本暂时没有该功能的计划。接口调用可能涉及到文件上传下载/临时存储的问题，有一定工作量。

不过在2.1.1或之后的版本，可能会添加该功能。

**Comment by Mingxiangyu** [comment]
> 新年快乐~
> 
> 2.1.0版本暂时没有该功能的计划。接口调用可能涉及到文件上传下载/临时存储的问题，有一定工作量。
> 
> 不过在2.1.1或之后的版本，可能会添加该功能。

可以给个文档处理相关的文件位置吗，我可以尝试写写然后贡献出来，这样能减少大佬你这边开发量

**Comment by hiroi-sora** [comment]
### 文档任务接口

UmiOCR-data\py_src\mission\mission_doc.py

`addMission` 方法用于提交一个文档任务。`msnInfo` 参数比较复杂，要求传入回调函数和任务控制参数字典。可以参考 `UmiOCR-data\py_src\tag_pages\BatchDOC.py` 第58行左右的代码。

### 命令行接口

UmiOCR-data\py_src\server\cmd_server.py

可以在第203行，判断paths是图片还是文档（ 可通过`utils.utils`模块的findImages和findDocs来判断 ）。如果是图片则继续执行后续流程，如果是文档则跳出并转到文档处理的流程。

（当然，现在整个 quick_ocr 函数有点臃肿繁杂，也许要先优化一下）

### HTTP接口

如果想添加一个新的HTTP接口，可以在 `UmiOCR-data\py_src\server\ocr_server.py` 的第75行后添加一个路由函数，如：

```
    @UmiWeb.route("/api/pdf", method="POST")
    def _pdf(): .....
```

然后进行文件上传、保存、识别、清理缓存的流程。（注意，原则上HTTP接口只允许处理上传的文件，不允许加载本地路径。否则恶意用户能通过局域网获取本机文件内容。）

**Comment by Mingxiangyu** [comment]
> ### 文档任务接口
> UmiOCR-data\py_src\mission\mission_doc.py
> 
> `addMission` 方法用于提交一个文档任务。`msnInfo` 参数比较复杂，要求传入回调函数和任务控制参数字典。可以参考 `UmiOCR-data\py_src\tag_pages\BatchDOC.py` 第58行左右的代码。
> 
> ### 命令行接口
> UmiOCR-data\py_src\server\cmd_server.py
> 
> 可以在第203行，判断paths是图片还是文档（ 可通过`utils.utils`模块的findImages和findDocs来判断 ）。如果是图片则继续执行后续流程，如果是文档则跳出并转到文档处理的流程。
> 
> （当然，现在整个 quick_ocr 函数有点臃肿繁杂，也许要先优化一下）
> 
> ### HTTP接口
> 如果想添加一个新的HTTP接口，可以在 `UmiOCR-data\py_src\server\ocr_server.py` 的第75行后添加一个路由函数，如：
> 
> ```
>     @UmiWeb.route("/api/doc", method="POST")
>     def _doc(): .....
> ```
> 
> 然后进行文件上传、保存、识别、清理缓存的流程。（注意，原则上HTTP接口只允许处理上传的文件，不允许加载本地路径。否则恶意用户能通过局域网获取本机文件内容。）



> ### 文档任务接口
> UmiOCR-data\py_src\mission\mission_doc.py
> 
> `addMission` 方法用于提交一个文档任务。`msnInfo` 参数比较复杂，要求传入回调函数和任务控制参数字典。可以参考 `UmiOCR-data\py_src\tag_pages\BatchDOC.py` 第58行左右的代码。
> 
> ### 命令行接口
> UmiOCR-data\py_src\server\cmd_server.py
> 
> 可以在第203行，判断paths是图片还是文档（ 可通过`utils.utils`模块的findImages和findDocs来判断 ）。如果是图片则继续执行后续流程，如果是文档则跳出并转到文档处理的流程。
> 
> （当然，现在整个 quick_ocr 函数有点臃肿繁杂，也许要先优化一下）
> 
> ### HTTP接口
> 如果想添加一个新的HTTP接口，可以在 `UmiOCR-data\py_src\server\ocr_server.py` 的第75行后添加一个路由函数，如：
> 
> ```
>     @UmiWeb.route("/api/doc", method="POST")
>     def _doc(): .....
> ```
> 
> 然后进行文件上传、保存、识别、清理缓存的流程。（注意，原则上HTTP接口只允许处理上传的文件，不允许加载本地路径。否则恶意用户能通过局域网获取本机文件内容。）

好的好的，我看一看，后续如果能开发出来提个pr

**Comment by hiroi-sora** [comment]
最新测试版中，已支持HTTP PDF接口。

https://github.com/hiroi-sora/Umi-OCR/releases
