### ISSUE TITLE
启动umi-ocr报错

### ISSUE THREAD

**Issue by hegdog** [hiroi-sora/Umi-OCR#364]
双击应用后弹出如下内容：
Qt plugins目录导入失败！
Qt plugins directory import failed! 

DLL load failed while importing shiboken2:找不到指定的模块。

点击确定后就是：
Umi-OCR异常退出。代码:1 
Umi-OCR exited abnormally. Code:1

问问大佬怎么办，是单位里的电脑，64位的windows7系统 处理器是i5 7500 两个版本都是这个报错情况  o(╥﹏╥)o

**Comment by hiroi-sora** [comment]
试试直接将软件解压放在D盘根目录下，能否运行

**Comment by hegdog** [comment]
> 试试直接将软件解压放在D盘根目录下，能否运行

试了一下还是失败了，两个版本都是和上次相同的报错，我还试过c盘或者其他盘（有个盘还是完全空的），也有试过把文件夹中的一个文件夹和exe文件取出来放在根目录，结果还是一样
是因为单位电脑缺了什么组件吗？或者有没有错误我可以贴出来

**Comment by hiroi-sora** [comment]
嗯……我知道了，既然与路径无关，那么99%的概率是用的比较早期的win7系统，缺失一些组件。

可以这样排查：

1. 下载DLL依赖查询工具（一个很小的绿色软件）： https://dependencywalker.com/depends22_x64.zip
2. 打开 depends22_x64
3. 将Umi-OCR中的这个文件拖入工具界面：  `UmiOCR-data\site-packages\shiboken2\shiboken2.pyd`
4. 等待一段时间。工具上如果有标红的条目，比如 `API-MS-XXXXX.DLL | Error opening file.系统找不到指定的文件。` ，那么就是缺少这个DLL。
5. 你可以上网搜索缺失的DLL并补充。注意，应该补充安装整个套件（如VC运行库），而不是仅仅下载单个DLL放到电脑里。

ex. 如果确实难以解决该问题，你可以换用更早的 [Umi-OCR v1.3.7](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v1.3.7) 版本。

**Comment by hegdog** [comment]
试了一下还是很遗憾失败了，不管是老版本还是新版本，检测了一下缺少大量dll文件，由于单位是局域网，常规联网修复软件也不太好用，以下分别是老版本启动报错情况、老版本检测缺失、新版本（paddle）检测缺失情况
![老版本报错](https://github.com/hiroi-sora/Umi-OCR/assets/40329211/21960a16-6afd-4017-be42-c1b19051ee09)
![老版本检测](https://github.com/hiroi-sora/Umi-OCR/assets/40329211/00a9cb44-e287-4dff-b83a-a416e045e517)
![最新版本Paddle](https://github.com/hiroi-sora/Umi-OCR/assets/40329211/b674dc29-42bf-47fc-99fc-243bb62dc2b7)

**Comment by hiroi-sora** [comment]
尝试下载VC运行库，拷贝到目标电脑上安装：

 https://aka.ms/vs/17/release/vc_redist.x64.exe
