### ISSUE TITLE
能否实现API请求后过滤字符功能

### ISSUE THREAD

**Issue by liuyan814** [hiroi-sora/Umi-OCR#365]
场景：一个图片中，有中文，有字母，有标点符号。返回结果只想返回中文，其他的字符不要。
就是说识别后，在返回结果之前，支持请求配置设置，可设置如： 识别全部、识别中文、识别字母之类。

**Comment by hiroi-sora** [comment]
如果只想识别字母，可以在参数里指定使用英文识别库。

如果想更精细的过滤指定内容，建议在调用方代码中实现。我认为该功能超出了Umi API的职责范围。调用方拿到结果后再做，应该更好。
