### ISSUE TITLE
大佬请问一下这个项目怎么集成到java项目中

### ISSUE THREAD

**Issue by zhangxianbao** [hiroi-sora/Umi-OCR#367]
想在java项目中通过 cmd命令行调用返回ocr结果，但结果不返回

**Comment by hiroi-sora** [comment]
如果你只需要通过cmd调用本地路径识图，那么 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 提供了现成的 [java-api](https://github.com/jerrylususu/PaddleOCR-json-java-api) ，开发起来会更容易。

**Comment by zhangxianbao** [comment]
感谢
