### ISSUE TITLE
大佬，打包之后exe报错

### ISSUE THREAD

**Issue by PinelliaLogic** [hiroi-sora/Umi-OCR#371]
![Snipaste_2024-02-26_17-20-12](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/5f88db20-5567-48c1-9582-4d5b6ec41d1a)

**Comment by hiroi-sora** [comment]
我这边测试，打包是正常的哦。

请确保：
1. 未打包时，直接在工程目录中使用 Umi-OCR.exe 运行，是否正常？
2. 是否使用脚本 release.py 进行打包？
3. 打包后，程序目录中是否存在 `UmiOCR-data\py_src\imports\plugin_i18n.py` ？

**Comment by PinelliaLogic** [comment]
我把它打包成了单个exe，`pyinstaller -F -w -i 图标路径 启动程序py`，运行之后报错。没用release.py 进行打包

**Comment by hiroi-sora** [comment]
本项目使用了`嵌入式python运行环境`的开发和发布方式，因此不适用于传统的 pyinstaller 打包。

请使用本项目中附带的一键打包脚本 release.py 。

**Comment by FnTop** [comment]
打包失败
![图片](https://github.com/hiroi-sora/Umi-OCR/assets/43026579/9076e44c-333f-449a-95a7-171a0576b5ff)

**Comment by hiroi-sora** [comment]
> 打包失败

请尝试，添加一个参数： `--path_7z "7zr.exe的完整绝对路径"`

`7zr.exe` 一般在 `Umi-OCR\dev-tools\7z\7zr.exe` ，你也可以在电脑上单独安装7z、使用它的7zr的路径。

如果这一步还是失败也没关系，软件包其实已经打包好了，在 `./release/Umi-OCR_Paddle_v2.1.1`。这个文件夹可以手动打个压缩包，移到别的电脑上可运行。

**Comment by FnTop** [comment]
Umi-OCR上没有7zr.exe ，windows项目上找到了,使用路径参数后可正常打包
[ Umi-OCR_runtime_windows\dev-tools\7z\7zr.exe](https://github.com/hiroi-sora/Umi-OCR_runtime_windows/tree/main/dev-tools)
