### ISSUE TITLE
Umi-OCR_Rapid_v2.0.2 报错

### ISSUE THREAD

**Issue by 154687650156** [hiroi-sora/Umi-OCR#373]
一个奇怪的现象，我在虚拟机中使用ocr，一开始正常，运行几个小时以后，就出现以下报错，之后无论怎么排查问题，都无法解决。
然而，我再次克隆原来的虚拟机使用，又正常运行几个小时，之后又是报错。
cpu支持avx，物理机是e5-2696 v4
![sdasd](https://github.com/hiroi-sora/Umi-OCR/assets/161430069/3a4cdf0c-5bab-4414-8680-b6f17a37241a)
[Error] OCR init fail. Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx', 'cls': 'ch_ppocr_mobile_v2.0_cls_infer.onnx', 'rec': 'rec_ch_PP-OCRv4_infer.onnx', 'keys': 'dict_chinese.txt', 'doAngle': 1, 'mostAngle': 1, 'maxSideLen': 2048, 'numThread': 2}
OCR init fail.

**Comment by 154687650156** [comment]
“再次克隆原来的虚拟机使用”，不是克隆已经报错的虚拟机，是原本有一个母虚拟机，每个来自这个虚拟机的克隆运行几小时后都会报错。

**Comment by hiroi-sora** [comment]
1. 出现问题时，虚拟机的CPU和内存占用 是否在正常范围内？是否试过重启系统？
2. 你的虚拟化软件是什么？换用别的版本或别的软件有无问题？

你的截图上，Rapid命令行中提示”SSE指令集不可用“，但是CPU-Z中看到SSE是存在的，非常奇怪。

SSE本身是个标准配置的指令集，一般不可能缺失的。另外我翻遍了opencv的Issue也没找到同类报错，说明在正常使用环境中不可能出现这种非常底层的问题的。我觉得就两种可能：1.资源耗尽（如内存吃满）导致。2.虚拟化的bug导致。

**Comment by 154687650156** [comment]
> 1. 出现问题时，虚拟机的CPU和内存占用 是否在正常范围内？是否试过重启系统？
> 2. 你的虚拟化软件是什么？换用别的版本或别的软件有无问题？
> 
> 你的截图上，Rapid命令行中提示”SSE指令集不可用“，但是CPU-Z中看到SSE是存在的，非常奇怪。
> 
> SSE本身是个标准配置的指令集，一般不可能缺失的。另外我翻遍了opencv的Issue也没找到同类报错，说明在正常使用环境中不可能出现这种非常底层的问题的。我觉得就两种可能：1.资源耗尽（如内存吃满）导致。2.虚拟化的bug导致。

1，系统启动后cpu内存各方面数据都正常，多次重启系统测试是肯定有的。
2，VMware12，正在换系统测试。
我尝试过最新的2.1.0到1.3.4全部不行，各种缺少dll和应用错误。
主要困惑点是虚拟机运行一段时间后才报错，之后再也不能正常运行。
不过要感谢你的开发，物理机的w7 w10都正常运行。

**Comment by hiroi-sora** [comment]
此问题引发条件窄，正常用户不会遇到，复现和修复也较难。先close了。
