### ISSUE TITLE
win 7电脑批量2个及以上pdf时每次都中途退出

### ISSUE THREAD

**Issue by idealkindom** [hiroi-sora/Umi-OCR#375]
如题，不管是rapid还是paddle版，Win 7上都有这个问题。换了文件也依然如故。

**Comment by hiroi-sora** [comment]
会不会是某个PDF有问题？

单独识别任意一个PDF，可以正常结束吗？如果不行，将出问题的那个文件，上传上来给我看看。

**Comment by idealkindom** [comment]
> 会不会是某个PDF有问题？
> 
> 单独识别任意一个PDF，可以正常结束吗？如果不行，将出问题的那个文件，上传上来给我看看。

我也测试了一次只识别一个文件，但是还是会崩退。
晚上我在Win 10的机子上测试了相同的两个pdf文件批量识别，没有问题，顺利识别完成。因此，排除了是文件的原因，是不是Win 7系统的锅呢？
[爆炸危险性及其评估（上册）.PDF](https://github.com/hiroi-sora/Umi-OCR/files/14435228/default.PDF)

**Comment by idealkindom** [comment]
> 会不会是某个PDF有问题？
> 
> 单独识别任意一个PDF，可以正常结束吗？如果不行，将出问题的那个文件，上传上来给我看看。

下册超过了25MPa,无法上传。总之在Win 10机子上上下册两个文件顺利批量识别了。Win 7上不知道中间哪里就崩退了，并且没有保存一个ocr过的pdf文件

**Comment by idealkindom** [comment]
> 会不会是某个PDF有问题？
> 
> 单独识别任意一个PDF，可以正常结束吗？如果不行，将出问题的那个文件，上传上来给我看看。

下册超过了25MPa,无法上传。总之在Win 10机子上上下册两个文件顺利批量识别了。Win 7上不知道中间哪里就崩退了，并且没有保存一个ocr过的pdf文件

**Comment by idealkindom** [comment]
所以就是系统兼容性问题

在 2024-02-29 04:27:41，hiroi-sora ***@***.***> 写道：


是的，经过测试，文档识别功能在Win7上兼容性确实有问题。

系统A：一个刚创建的win7虚拟机，缺很多驱动和运行库，使用文档识别时基本都会出现软件崩溃。

系统B：我用过一段时间的win7系统，与系统A是同一个镜像，但是打过不少驱动和运行库。使用文档识别时，只有很小概率会出现异常情况。

基本可以确定是驱动或运行库的缺失引起的，与PDF文件本身没有关系。

但这个Bug调起来非常麻烦，我甚至很难定位到是哪一段代码引起的，似乎多个不同组件的协同作用下才会导致问题……非常玄学。

所以暂时，win7用户只要两种办法：

尝试补充常用运行库、驱动，更新系统补丁。
换用win10及以上的系统。

**Comment by hiroi-sora** [comment]
新版本已解决该问题。如果还有异常，可参考 [Win7 常见问题](https://github.com/hiroi-sora/Umi-OCR/issues/447) 。
