### ISSUE TITLE
希望可以返回每个字符的坐标和置信度

### ISSUE THREAD

**Issue by xudaisong** [hiroi-sora/Umi-OCR#385]
希望可以返回每个字符的坐标和置信度

**Comment by hiroi-sora** [comment]
目前只有很少的OCR引擎采用单字模型结构，即以**单个字符**为单位进行识别。单字模型能原生支持输出字符坐标。

更多的主流OCR引擎，使用的是 `编码器+解码器` 的模型结构。它们以**行/文本块**为单位进行识别。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/b71e51da-6255-4a50-a876-df040af9aafc)

`编码器+解码器` 结构原生不一定支持输出单个字符的坐标，或者需要一定的转换步骤才能提取到。 

Umi-OCR 为了支持多种引擎插件，选择了最通用的接口格式，即以**行/文本块**为最小单位。因此，暂时无法支持输出单字坐标。

**Comment by hiroi-sora** [comment]
据我所知，似乎没有开源/离线组件支持单字分割。

以下两个在线商业服务支持：
[阿里云OCR](https://ai.aliyun.com/ocr/general)
[腾讯云OCR](https://cloud.tencent.com/document/product/866/33527)
