### ISSUE TITLE
存放目录问题

### ISSUE THREAD

**Issue by xzlosats111** [hiroi-sora/Umi-OCR#388]
win10，不论是将软件放在D:\Program Files，还是D:\Program Files (x86)，都会报错
两个目录都试过了报错都一样，放在D盘根目录可以正常运行
Paddle_v2.1.0版本报错信息为
[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 16, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
Rapid_v2.1.0版本报错信息为
[Error] OCR init fail. Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx', 'cls': 'ch_ppocr_mobile_v2.0_cls_infer.onnx', 'rec': 'rec_ch_PP-OCRv4_infer.onnx', 'keys': 'dict_chinese.txt', 'doAngle': 0, 'mostAngle': 0, 'maxSideLen': 1024, 'numThread': 16}
[WinError 193] %1 不是有效的 Win32 应用程序。
1.3.7版本是放在D:\Program Files可以正常运行

**Comment by hiroi-sora** [comment]
我这边没有复现相同情况。我在 `Program Files` 中运行，只会提示权限不足无法记录配置文件，OCR还是能正常工作。

不过，我觉得你的问题也有可能是由权限引起。请尝试以管理员身份运行，或者移到其他权限限制较少的目录下。

**Comment by xzlosats111** [comment]
又去试了一下，甚至放在c盘的软件目录都可以正常运行，在D盘软件目录手动右键管理员模式运行也不行，比较玄学，算了
