### ISSUE TITLE
老大 什么时候出Linux版的

### ISSUE THREAD

**Issue by FunnyRyan** [hiroi-sora/Umi-OCR#389]
Linux就不受人待见吗

**Comment by LET19** [comment]
+1

**Comment by hiroi-sora** [comment]
软件本体（纯前端）适配Linux的难度应该不大，qt本身支持跨平台，我的代码里也预留了跨平台API的接口。

难在OCR引擎插件。PaddleOCR 和 RapidOCR 插件可能都要重新调整通信方式、调试编译C++代码，有点头大。

我打算下个版本（v2.1.1）加入在线OCR API模块。使得Umi就算无法使用离线OCR插件，也能调用在线服务。然后开始软件本体的Linux适配工作。

至于Linux平台的离线OCR插件，我可以先搞一些不依赖C++代码的插件（[Tesseract](https://github.com/qwedc001/tesseractOCR_umi_plugin)之类），然后再慢慢适配 Paddle 和 Rapid 。

总之，预计可能最早在 v2.1.2 版本，能提供初步的原生 Linux 平台支持。（不保证，看实际情况）

目前，可以用这个第三方的方案， [在Docker中跑Umi-OCR](https://github.com/iszmxw/ocr-docker) 。

**Comment by hiroi-sora** [comment]
新的测试版已发布，实验性支持 Linux 平台。

https://github.com/hiroi-sora/Umi-OCR/releases
