### ISSUE TITLE
Umi-OCR_20231105版的二维码识别比新版本的强

### ISSUE THREAD

**Issue by mmwew** [hiroi-sora/Umi-OCR#390]
试了一下，Umi-OCR_20231105版时识别较强，之后的版本不及这个版本。

**Comment by hiroi-sora** [comment]
20231105版 跟后续所用的，是两款不同的二维码识别库，识别准度会有所差异。可能在某些情境下，旧库的准确率更好，而对另一些图片时新库更好。

新库在功能上有一些优势，并且能应对大多数情景，我认为时适合采用的。
