### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by boredwithnaming** [hiroi-sora/Umi-OCR#392]
我之前使用其他OCR的习惯是使用F1识图，换成这个后，在Chrome浏览器中使用此快捷键并不能覆盖Chrome的快捷键，弹出Google Chrome帮助，希望能解决

**Comment by hiroi-sora** [comment]
收到。我已经有一些优化思路，待后续研究。

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/402
