### ISSUE TITLE
出现PDF未启动引擎就完成识别的现象，wdf

### ISSUE THREAD

**Issue by qwedc001** [hiroi-sora/Umi-OCR#394]
hiroi-sora/RapidOCR-json/issues/16 的伴生issue。
PDF样本已上传：
[心血管－中药新药临床研究指导原则.pdf](https://github.com/hiroi-sora/Umi-OCR/files/14472277/default.pdf)

在执行完显示引擎后，在执行批量识别文档的时候偶然发现此文档识别速度极快，并且没有弹出引擎开启的黑框。

我之前执行过此文档的OCR识别，Umi会保存之前的识别记录吗？好像不会吧

很怪

**Comment by hiroi-sora** [comment]
> 文档识别速度极快，并且没有启动引擎

检查一下 设置 → 文档处理 → 内容提取模式 。你可能设为了 `仅拷贝原有文本` ，该选项下不会调用引擎。

我测试了你的样本。当上述选项不为 `仅拷贝……` 时，是可以正常调用引擎的。

**Comment by qwedc001** [comment]
我这里的软件行为是只有设置选项打到“整页强制OCR”会调用引擎，其他三个选项均为0.2秒出结果并且精度很差

**Comment by hiroi-sora** [comment]
你用的还是 alpha1 版本，我后来应该修过这个bug，更新到v2.1.0正式版试试？

**Comment by qwedc001** [comment]
忘了关issue了，这个问题已经解决
