### ISSUE TITLE
Http接口如何调用识别pdf等文件呢？

### ISSUE THREAD

**Issue by PlanckLength** [hiroi-sora/Umi-OCR#397]
小白用户，pdf读取base64调用时出错，是不是pdf格式文件不能用base64？可以给个pdf调用例子吗？

**Comment by hiroi-sora** [comment]
嗯，当前版本HTTP接口暂不支持文档识别，待后续版本补充。

**Comment by xjxqd** [comment]
谢谢这个功能太需要了,坐等更新

**Comment by iris2jane** [comment]
能否支持识别pdf指定页码指定位置（矩形坐标）

**Comment by hiroi-sora** [comment]
> pdf指定页码指定位置（矩形坐标）

指定页码是可以支持的，但指定坐标有点麻烦。

不过，接口返回值里会包含坐标，调用方可以自己根据坐标过滤一下结果。

**Comment by aceliuchanghong** [comment]
QAQ,等大神更新*2

**Comment by steven0081** [comment]
当前最新的2.1.1的版本支持HTTP接口了吗？

**Comment by hiroi-sora** [comment]
> 当前最新的2.1.1的版本支持HTTP接口了吗？

抱歉，还没，我最近比较忙。此外，这项工作的优先级不高，还有一些排在前面的开发计划等待处理。

**Comment by dandaaan** [comment]
急需这个功能

**Comment by habacat** [comment]
希望能够支持Linux版http接口pdf文档识别调用。想用自己的服务器搭建一个服务。

**Comment by zhangwanshen** [comment]
坐等大佬出http接口pdf文档识别❤

**Comment by hiroi-sora** [comment]
此功能开发中，将在下版本实现。

**Comment by hiroi-sora** [comment]
新的测试版已发布，支持 Linux 和 http PDF识别接口。

https://github.com/hiroi-sora/Umi-OCR/releases
