### ISSUE TITLE
启动截图后截图识别任务异常[Error] MissionOCR: APl object is None.

### ISSUE THREAD

**Issue by sgyhl18** [hiroi-sora/Umi-OCR#399]
启动截图后截图识别任务异常[Error] MissionOCR: APl object is None.

**Comment by hiroi-sora** [comment]
你是通过源码搭建的吧？

请务必 [根据搭建流程指南](https://github.com/hiroi-sora/Umi-OCR_runtime_windows?tab=readme-ov-file#1-%E6%94%BE%E7%BD%AE%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83) ，在 [插件仓库](https://github.com/hiroi-sora/Umi-OCR_plugins) 下载至少1个OCR引擎插件，根据提示放置在指定目录下。

**Comment by sgyhl18** [comment]
我想本地运行源码，是缺少key吗？

**Comment by hiroi-sora** [comment]
不是，目前本项目所有OCR插件均是离线的，不需要填key。

当前仓库 【https://github.com/hiroi-sora/Umi-OCR】 只存放了软件主框架代码，不含OCR引擎。如果要本地运行源码，必须去插件仓库【https://github.com/hiroi-sora/Umi-OCR_plugins】 下载至少一个OCR引擎，才行。
