### ISSUE TITLE
功能建议：增加读取剪贴板功能

### ISSUE THREAD

**Issue by AlphatoBeta** [hiroi-sora/Umi-OCR#4]
希望增加粘贴图片功能，这样就可以调用系统截图，然后粘贴进来直接识别了。

**Comment by AlphatoBeta** [comment]
另外，是否会考增加对飞浆V3模型的支持（官网说V3的英文场景提升11%，对于批量识别英文书籍，速度提升应该是可感知的） ：）

**Comment by hiroi-sora** [comment]
> 功能建议：增加读取剪贴板功能

如 你 所 愿 。

（其实我一直也想这个功能。但主要是咱家PaddleOCR-json只支持读硬盘中的图片，而我希望截图能直接读内存，优雅一点……）

嘛算了，现在是先缓存到硬盘再调用识别。凑合凑合😂

**Comment by hiroi-sora** [comment]
> 另外，是否会考增加对飞浆V3模型的支持

看了一下，V3模型和V2在使用上是通用的，`PaddleOCR-json`可以直接升级。但是实测效果没有想象中好。

在耗时上，虽然官方说`中文场景效果相比于PP-OCRv2再提升5%`。但是经多次测试，都是v3时间更长。见下图，左为v3，右为v2。

![image8b0cdefc2599dc4a.png](https://tupian.li/images/2022/05/31/image8b0cdefc2599dc4a.png)

在识别精度上，v3的优点是对小字的识别率更高，部分v2忽略的小字也会检测出来。见下图，左为v3，素材中“快速存档”“快速读档”等字也被框住了；而v2没有。（推测，就是因为v3增加了对小字的检测率，所以要花费更长时间来识别更多内容。）

![imagefbbaa438605d43c4.png](https://tupian.li/images/2022/05/31/imagefbbaa438605d43c4.png)

但是，对于常规大小的文字段落，v3的识别率反而更差：错字、漏字比v2显著增加。简单挑了几个段落：

| v3               | v2                   |
| ---------------- | -------------------- |
| 支配耆           | 支配者               |
| 七传说           | 七夕传说             |
| 冉于轻微的动     | 由于轻微的晃动       |
| 集中真的很强     | 集中力真的很强       |
| 不知廉的孩子     | 不知廉耻的孩子       |
| 星也会点点地移动 | 星星也会一点点地移动 |

所以，我感觉v3现在还不太稳定，不打算换~

**Comment by AlphatoBeta** [comment]
已经更新，识别剪贴板**十分好用**

**Comment by hiroi-sora** [comment]
@ranqianchen 
> 是否能新增一个“自动复制识别内容”的功能

小意思，已加

**Comment by hiroi-sora** [comment]
> 另外，是否会考虑增加对飞浆V3模型的支持（官网说V3的英文场景提升11%，对于批量识别英文书籍，速度提升应该是可感知的） ：）

`v1.2.6` 已支持并默认附带V3版模型。

新版本的速度确实比前代有明显提升，不管识别哪种语言，都有20%以上的耗时减少。但这似乎不是V3模型的功劳，而是Paddle团队优化 C++ 识别引擎的结果，代码做了相当多的调整（~~搞得我也要跟着重构😂~~）。新版引擎对V2模型依然有同样的提速效果~

V3模型最大的优势是准确度提高了，很多V2认不出来的小字、扭曲字形，V3可以搞定。

**Comment by AlphatoBeta** [comment]
已经推荐到小众软件了https://www.appinn.com/umi-ocr/

**Comment by Evezerest** [comment]
> 但是，对于常规大小的文字段落，v3的识别率反而更差：错字、漏字比v2显著增加。简单挑了几个段落：

你好，我是PaddleOCR的PM，对于v3效果的疑问我们可以再深入交流一下，可以进一步改善你的程序体验。方便的话可以微信扫描下方二维码，进群后a一下群主；或者通过邮件paddleocr@outlook.com联系

![image](https://user-images.githubusercontent.com/50011306/190969347-835ea8c3-c12f-4e34-a994-d74df339165c.png)

**Comment by LDOUBLEV** [comment]
@hiroi-sora 
> 看了一下，V3模型和V2在使用上是通用的，PaddleOCR-json可以直接升级，替换模型文件即可。但是实测效果没有想象中好。

> 在耗时上，虽然官方说中文场景效果相比于PP-OCRv2再提升5%。但是经多次测试，都是v3时间更长。见下图，左为v3，右为v2。

hello，关于V3性能的问题，请教下，在打包exe的时候预测的时候有没有设置enable_mkldnn=true，设置这个参数在比较好的intel硬件上会提升比较明显，官方说的『PP-OCRv2再提升5%』也是开启mkldnn后测试的结果；如果可以，麻烦提供下你的硬件和系统版本，我们也会尽快验证性能变慢问题的原因。

**Comment by hiroi-sora** [comment]
> 对于v3效果的疑问我们可以再深入交流一下，可以进一步改善你的程序体验。

哈哈，欢迎PP官方的回复！ @Evezerest 

当时我测出“V3模型效果比V2差”，是使用 PPOCR-**v2.1** 版的c++引擎。现在我的项目已经跟进升级为了 **v2.6** 版引擎，这个版本对V3的适配性没有任何问题，V3不会弱于V2。相反，V3 模型的识别率在各个方面(det,rec)都显著强于V2。感谢PP团队的工作！

> 在打包exe的时候预测的时候有没有设置enable_mkldnn=true

 @LDOUBLEV 

这个项目使用的是C++引擎，我已经设了 enable_mkldnn 的默认值为true。经过测试，它确实有极大的加速效果。

在 v2.6 引擎下，无论V2还是V3模型的速度都远胜于 v2.1 引擎。但是，内存占用也比前代有显著提高（代码里已开启了内存优化 `config.EnableMemoryOptim()` ）。尤其是 v3 slim 模型，在  v2.6 引擎下占用内存极高，可能存在问题。

两位可以看一下我的 [效率测试](https://github.com/hiroi-sora/Umi-OCR#%E6%95%88%E7%8E%87%E6%B5%8B%E8%AF%95--%E5%BC%80%E5%8F%91%E8%AF%B4%E6%98%8E)
