### ISSUE TITLE
有mac可以运行的吗？可以部署到centos系统吗？

### ISSUE THREAD

**Issue by sgyhl18** [hiroi-sora/Umi-OCR#401]
有mac可以运行的吗？可以部署到centos系统吗？

**Comment by hiroi-sora** [comment]
先搜一下已有Issues嘛。暂时没有原生 MacOS 和 Linux 版本。可以通过第三方docker尝试部署在Linux上。

**Comment by hiroi-sora** [comment]
新的测试版已发布，初步支持 Linux 系统。

https://github.com/hiroi-sora/Umi-OCR/releases

**Comment by hiroi-sora** [comment]
Umi-OCR 本体已支持 Docker 部署，在 CentOS 7 中测试通过。 👉 [文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md)
