### ISSUE TITLE
大佬,会更新识别的结果只提取数字的功能吗

### ISSUE THREAD

**Issue by kyon777** [hiroi-sora/Umi-OCR#403]
因为想配合宏使用,截图某一区域,但是这个区域的数字位置不固定(左右有偏移),所以想截图的区域大一点,但是自动复制的结果只提取数字.大佬会考虑更新筛选吗

**Comment by hiroi-sora** [comment]
我暂时不会更新此功能，建议自己修改代码实现。

示例：

打开 `UmiOCR-data\qt_res\qml\TabPages\ScreenshotOCR\ScreenshotOCR.qml`

找到 `const resText = resultsTableView.addOcrResult(res)`

修改为：

```js
        let resText = resultsTableView.addOcrResult(res)
        resText = resText.replace(/\D/g, '') // 删除非数字的字符
```

**Comment by sagasm** [comment]
如要增加此功能, 可转为支持正则筛选功能

**Comment by kyon777** [comment]
谢谢大佬,改了代码,问题得到完美解决

**Comment by kyon777** [comment]
大佬,这个代码只能筛选 截图或者粘贴图片的结果.  如果 我本身复制的结果是 文字(21156一二三四),然后想通过 粘贴图片的功能 筛选出21156.请问是修改哪一段的代码
