### ISSUE TITLE
想请问升级底层识别模型的方法

### ISSUE THREAD

**Issue by PopsGitHub21** [hiroi-sora/Umi-OCR#405]
大佬，想问一下如果想用PaddleOCR新的版本（PP-OCRv4）识别，计算速度和准确度是否会提高点？
目前有些文件识别时错别字较多，请问下如果想自己测试的话应该要怎么操作么？

**Comment by hiroi-sora** [comment]
你可以下载个 [win7_x64_RapidOCR-json](https://github.com/hiroi-sora/Umi-OCR_plugins/releases) 的插件，里面自带 PP-OCRv4 模型。不过我实测，准确度提升有限。

**Comment by PopsGitHub21** [comment]
感谢大佬，我测试一下
