### ISSUE TITLE
一个页面内只能用一个DoubleColumnLayout或DoubleRowLayout控件

### ISSUE THREAD

**Issue by PinelliaLogic** [hiroi-sora/Umi-OCR#406]

**Comment by PinelliaLogic** [comment]
引入两个DoubleColumnLayout或DoubleRowLayout，第二个参数设置不起作用

**Comment by hiroi-sora** [comment]
感谢反馈。其实不是一个页面内只能用一个`Double_Layout`的问题，而是`DoubleColumnLayout`组件本身有Bug。

这个控件之前没有在项目中被使用，所以我没有发现Bug。

现在已经修复了，请拉取最新main分支。一页内使用多个`Double_Layout`应该是正常的。

**Comment by PinelliaLogic** [comment]
> 嵌套使用问题1：上下布局消失
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/b9dbe7d1-416d-485c-97ee-bd1e731a683c)
![question2](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/95669e3f-6bb9-4d14-9430-e1085911bc57)

> 问题2：设置initSplitterX没有作用
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/f07559f5-73a4-4474-a1c3-ebd59e019501)
![question1](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/d9502e6c-0117-417a-9e41-d36b80b07659)

**Comment by PinelliaLogic** [comment]
1. 上下布局消失
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/96336013-a833-44e3-a47c-e81b915580a0)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/5cbba4ba-aba8-4ed8-bc60-3ce2b3ea8d20)
2. initSplitterX不起作用
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/252964ce-5ede-421b-ab6e-4cd3d8431d97)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/c9aac7f4-1f13-474c-9658-e5c59a8c1cfe)

**Comment by hiroi-sora** [comment]
你的代码中没有定义锚点或者元素宽高，所有元素都是0像素，所以看起来什么东西都没有。

如下图，给所有元素都设个 `anchors.fill: parent` （锚点填满父元素），就正常了。你也可以用别的锚点设定方式。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/1dcc1d27-444c-4d2f-a78c-4b196fba3ba8)

另外，如果左右/上下两个区块的初始比例与 `initSplitterX` 的设定值不一致，这可能是屏幕缩放比例导致的Bug。对使用影响不大，暂时未修复。

**Comment by PinelliaLogic** [comment]
谢谢👍
