### ISSUE TITLE
有几率快捷键失效 & 录制不正确 10.29

### ISSUE THREAD

**Issue by lioArther** [hiroi-sora/Umi-OCR#41]
操作系统：Microsoft Windows 11 操作系统名称：
10.0.22000 缺Build 22000
操作系统制造版本：微软公司
操作系统配置：独立工作站专业版操作系统制造商
类型：多处理器自由
系统制造商：AZW
系统型号：GTR
系统类型：x64-based PC
处理器：AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3301 Mhz

Umi-OCR版本：1.3

![image](https://user-images.githubusercontent.com/27990398/198814524-1e92fdef-5bb0-48ae-b4bc-7b05c1281cec.png)

1. 截图功能有时候会失效（好像是因为长时间没有使用就会这样），只有重新录制快捷键才可以正常使用
2. 有时候录制结果显示是多个按键组合。案例：录制F2截图，显示F2+F9，但按F2还是生效

**Comment by hiroi-sora** [comment]
反馈收到，快捷键相关问题正在修Bug中。

如果 `重新录制快捷键` 能正常使用，那就 `禁用启用（点两次复选框）` 吧，比录制方便一点，效果一样的。

**Comment by Freddd13** [comment]
@hiroi-sora  
我这里也有快捷键的问题，我使用`snipaste` F1截图后，使用ctrl+C 保存到剪贴板，然后使用我设定好的快捷键，这时绑定的所有快捷键都会失效，我的测试：

> snipaste F1 + Ctrl-C: 失效
snipaste F1 + 手动点复制：失效
snipaste 手动点应用图标截图 + Ctrl-C/手动复制：成功

如果发生了失效，那这时我再去设快捷键，会变成`新key+F1`，不管怎么设都带这个F1，然后居然还能用，下次再开就用不了了。
 
刚才调了下，发现这个新key+F1是直接从keyboard库给出来，不知道是库的问题还是这里多线程写法的问题，没时间研究了= =。

**Comment by hiroi-sora** [comment]
@Freddd13 

好滴好滴，感谢测试。我打算之后替换成pynput库试下。keyboard的毛病确实不好弄 b39

**Comment by hiroi-sora** [comment]
新版本将解决快捷键问题。👉[测试版](https://github.com/hiroi-sora/Umi-OCR/issues/43)
