### ISSUE TITLE
请问大佬,后续会更新后台截图功能吗

### ISSUE THREAD

**Issue by kyon777** [hiroi-sora/Umi-OCR#410]
目前搭配宏使用,一直只截图某一个区域不变!
现在截图整个屏幕要闪一下,而且给了一个1000MS的延迟脚本才能跑起来.
有没办法能让延迟降低到100MS左右,持续监控也可以.
截一下屏幕就闪一下(3个屏幕一起闪),有点影响感官.

**Comment by hiroi-sora** [comment]
只截图某个区域的话，可以用 v2.1.0 版本的 “重复截图” 功能，它会重复获取上一次截图的区域而无需框选。

“截图整个屏幕闪一下” 可能与显卡驱动有关。在 全局设置 → 渲染器 ，切换为另一个渲染器，或者关闭硬件加速，即可。

“延迟” 你指的是什么的延迟呢？

**Comment by kyon777** [comment]
是我表达错误了,“截图整个屏幕闪一下”是因为脚本过快导致的
正常情况按下截图快捷键不是会弹出截图工具么.

脚本的流程是,  按下快捷键- 延迟1000MS -鼠标选取截图区域.

如果把1000MS改为2000,就是正常的弹出截图工具(屏幕变色).
我是改为了500MS,没有弹出截图工具,导致的感官错觉是屏幕闪一下.
------------------
但是,我现在用了你说的那个重复截图,已经能无须框选了.**所以完美了我的问题,**

感谢大佬,功能真强大. 最牛的是微信截图等其他工具截图是不会覆盖 重复截图的记录值的.
