### ISSUE TITLE
其他组件调用截图方法报错

### ISSUE THREAD

**Issue by PinelliaLogic** [hiroi-sora/Umi-OCR#411]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/3daad26e-5b04-45a3-aa2d-baecab0c7ad2)

**Comment by hiroi-sora** [comment]
请给出详细的代码截图，上图 我看不出问题所在。

**Comment by PinelliaLogic** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/694bfa3e-986f-4c97-b391-97172d9abe35)
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/d6e45138-ce83-4aba-9aac-7229a435af09)

**Comment by hiroi-sora** [comment]
我大概懂了，你是不是另外创了一个 .qml 文件，然后在其中创建了 `ScreenshotOCR` 组件？

这是不可行的，`ScreenshotOCR.qml` 本身是一个 `TabPage` 。`TabPage`相当于一个标签页的根，必须由 `PagesManager.qml` 进行管理，自动生成、销毁，不能作为别的页面的子组件。

这里报错 callPy of undefined，本质上是 `connector` 未定义。该属性是由 `PagesManager` 自动初始化的。如果你手动创建一个 `TabPage` ，那么该属性未被定义。

如果你想在别处调用 `ScreenshotOCR` 标签页的截图方法，可以通过全局事件来调用：（需要先确保截图OCR标签页处于打开状态）

```
qmlapp.pubSub.publish( "<<screenshot>>" ) // 发送名为 <<screenshot>> 的全局事件
```

如果你想在自己的标签页内，进行截图并获取图片（不进行OCR），可以参照ScreenshotOCR的screenshot方法，调用全局函数`qmlapp.imageManager.screenshot` 。

**Comment by PinelliaLogic** [comment]
好的，感谢
