### ISSUE TITLE
关于双层PDF的建议

### ISSUE THREAD

**Issue by OOOOccasionally** [hiroi-sora/Umi-OCR#412]
测试了一下双层PDF功能，发现只能选中PDF文件进行识别。能否增加添加文件夹的功能，然后遍历文件夹，将识别结果按照源文件夹目录结构进行保存。

**Comment by hiroi-sora** [comment]
这功能一直都支持的，将文件夹 **拖进软件页面** 即可。

还可以在页面设置 → 勾选【高级】 → 下面勾选【递归读取子文件夹】，搜索目录中所有的文件。

**Comment by OOOOccasionally** [comment]
我今天试了啊，拖文件夹进去没反应

**Comment by OOOOccasionally** [comment]
不好意思我好像搞错了，明天再试试

**Comment by OOOOccasionally** [comment]
文件夹无法拖入，显示🚫

**Comment by hiroi-sora** [comment]
我这边拖入文件夹是正常的。

如果你无法使用此功能，请检查：软件是否存放在权限要求严格的目录下？如果放在权限一般的目录下，如桌面或D盘根目录，能否正常使用？

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/b45113ec-453b-40dc-bc6a-e116bb73b4b0)

**Comment by OOOOccasionally** [comment]
软件和图片都在D盘，所有拖入功能都不可用

**Comment by hiroi-sora** [comment]
这可能不是Umi的问题，是系统问题。

你可以尝试这些方法：
https://www.zhihu.com/question/25366899
https://www.bilibili.com/read/cv6924395

**Comment by OOOOccasionally** [comment]
我直接重装了个系统，可以用了
