### ISSUE TITLE
很长的图片的话无法识别吗

### ISSUE THREAD

**Issue by 1411430556** [hiroi-sora/Umi-OCR#415]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/67215517/058dc2df-0396-4584-b0ca-a1e7adbe5fdf)
上面是一个很长的截图，似乎识别不出来

**Comment by 1411430556** [comment]
> > #325
> 
> Yes~ 将 `限制图片边长` 调大一些，或者干脆无限制，就行。

谢谢

**Comment by Xmug** [comment]
可以将图片分割后再进行批量识别，不过我试过一次，无论是哪个引擎，批量识别后都会出现十五分之一左右的错别字

**Comment by qd-dcd** [comment]
yes
&nbsp;


381854460
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月13日(星期三) 凌晨5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [hiroi-sora/Umi-OCR] 很长的图片的话无法识别吗 (Issue #415)





 
可以将图片分割后再进行批量识别，不过我试过一次，无论是哪个引擎，批量识别后都会出现十五分之一左右的错别字
