### ISSUE TITLE
使用SpinBox，数字变成了藏文

### ISSUE THREAD

**Issue by PinelliaLogic** [hiroi-sora/Umi-OCR#417]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/9b6b4448-87b0-47d6-98fe-e47036fc645c)

**Comment by hiroi-sora** [comment]
或许是字体问题。如果要添加自定义组件，建议将所有字体设为 Umi-OCR 内指定的字体全局变量`theme.fontFamily`：
```qml
组件 {
    font.family: theme.fontFamily
}
```

**Comment by PinelliaLogic** [comment]
已经设置为系统字体了，无效
![image](https://github.com/hiroi-sora/Umi-OCR/assets/95219163/1aee2996-890a-41c1-8ca5-ce29b0deb2d6)

**Comment by hiroi-sora** [comment]
先指出一些你的代码错误：
- 设置了 `anchors.fill` ，就不能再设置 `anchors.verticalCenter` 及 `anchors.horizontalCenter` 。
- `theme.dataFamily` 是不存在的，Umi只有两个字体全局变量：`theme.fontFamily` 和 `theme.dataFontFamily` 。它们对应于**全局设置 → 修改字体**中的`界面` 和 `内容` 。（如果你自定义了dataFamily，无视这条）

然后，在我这边测试，显示数字是正常的。哪怕字体设为默认的 `undefined` ，也不会出现数字显示错误。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/7b39c873-7266-4e50-9d98-9a3370d6af3d)

如果你还是没有找出问题，可以试一下 [官方文档](https://doc.qt.io/qt-5/qml-qtquick-controls2-spinbox.html) 中，`Custom Values` 的那段示例代码，看看显示字符串 `["Small", "Medium", "Large"]` 是否正常。

**Comment by PinelliaLogic** [comment]
好的，谢谢
