### ISSUE TITLE
无法正常开机自启

### ISSUE THREAD

**Issue by CreeperAWA** [hiroi-sora/Umi-OCR#419]
运行了`echo %ProgramData%`返回正常，程序也在启动文件夹中，但开机不会自启
我又尝试删掉启动文件夹中的程序，使用注册表启动，依旧不行

**Comment by hiroi-sora** [comment]
看起来是系统问题概率较大。你电脑上其他程序可以开机自启吗？可以通过手动放置快捷方式到启动文件夹 的方式自启吗？

**Comment by eAtmApp** [comment]
可以尝试用计划任务加上延迟来启动

**Comment by CreeperAWA** [comment]
> 看起来是系统问题概率较大。你电脑上其他程序可以开机自启吗？可以通过手动放置快捷方式到启动文件夹 的方式自启吗？

可以的
