### ISSUE TITLE
希望支持记住窗口状态

### ISSUE THREAD

**Issue by fcwys** [hiroi-sora/Umi-OCR#420]
希望能记住窗口和标签的状态，个人习惯直接使用识别结果和记录页面，要是能记住窗口和标签状态（或支持锁定）就好了，另外希望清除全部识别记录支持快捷键，这样识别记录过多时方便清理，谢谢！
如图：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/28641034/b0bd3495-3f4c-4999-b0c1-5ca02fa8d1a6)

**Comment by hiroi-sora** [comment]
> 记住标签页双栏布局的位置状态

OK，写了。如果分割条拖动到最左或最右，则下次启动时恢复相同状态。

> 清除全部识别记录的快捷键

设为 `Ctrl+Del 双击` ，你觉得如何？

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/20b6ed3f-458c-4d8f-83c2-26176f30618c)

**Comment by fcwys** [comment]
可以的，因为是生产力工具，非常感谢！

**Comment by hiroi-sora** [comment]
OK，那么你建议的两个功能都搞定了，可以拉取main分支体验。
