### ISSUE TITLE
使用文档识别时电脑会自动重启

### ISSUE THREAD

**Issue by Nriako** [hiroi-sora/Umi-OCR#421]
重复试了几次都这样 刚识别几页就直接重启了
其他功能倒是没问题
请问应该如何解决？谢谢

**Comment by hiroi-sora** [comment]
啊？那么神奇……

问一下：

1. 是正常的关机重启，还是蓝屏那种故障的重启？
2. 只对特定的文件有这种现象，还是所有的文件？
3. 出问题时页数有没有规律？比如固定在第3页出问题。
4. 如果 `保持文件类型` 不勾选 `双层可搜索文档` 的话，是否还会出问题？

**Comment by Nriako** [comment]
> 啊？那么神奇……
> 
> 问一下：
> 
> 1. 是正常的关机重启，还是蓝屏那种故障的重启？重启前，有没有其他异常现象，比如软件卡死？
> 2. 只对特定的文件有这种现象，还是所有的文件？
> 3. 出问题时页数有没有规律？比如固定在第3页出问题。
> 4. 如果 `保持文件类型` 不勾选 `双层可搜索文档` 的话，是否还会出问题？

1 是正常的关机重启（电脑直接黑屏 然后开始重启）没有出现蓝屏 也没有出现卡死等现象
2 我试了几个文件 都出现了这种情况
3 没有规律 都是在识别几页或几十页重启
4 如果勾选 **双层文档** 那么会很快重启 如果没有勾选而是输出txt 那么会在几十页后才会重启

**Comment by Nriako** [comment]
破案了 换rapid版就行了 应该是我配置不够吧

**Comment by hiroi-sora** [comment]
你的配置是啥？

进行批量任务时，Paddle引擎会尽量让CPU满载，以加快任务速度。如果是长期没有维护的老电脑，确实有可能导致CPU过热或者核心电压不稳，使得系统重启。Rapid引擎对CPU的压力则低一些。

**Comment by Nriako** [comment]
> 你的配置是啥？
> 
> 进行批量任务时，Paddle引擎会尽量让CPU满载，以加快任务速度。如果是长期没有维护的老电脑，确实有可能导致CPU过热或者核心电压不稳，使得系统重启。Rapid引擎对CPU的压力则低一些。

amd 5500

**Comment by Nriako** [comment]
完了 换了rapid版还是出问题了 不过是到几百页之后才重启 我往上拉了点电压也没用

**Comment by hiroi-sora** [comment]
监控一下cpu温度和内存占用，我估计可能是过热或者内存满。

**Comment by Nriako** [comment]
又试了几个文件 都没有出现问题 cpu和内存占用 温度也很正常

**Comment by Cronoes** [comment]
我今天也遇到这个问题了，我是5900X。。
