### ISSUE TITLE
新版本可以加上清理历史记录功能吗

### ISSUE THREAD

**Issue by brisk21** [hiroi-sora/Umi-OCR#427]
### Expected behavior 预期的功能

和旧版本一样，可以快速清理历史的截图、历史的识别，用右键也行

### Approximate reference (optional) 近似的参考（可选）

![image](https://github.com/hiroi-sora/Umi-OCR/assets/17331991/0ca5c6d0-368d-4886-b169-2dccf92e4200)

**Comment by hiroi-sora** [comment]
在右栏的`记录`面板中，是可以右键清理历史记录的。（Ctrl+Del的快捷键在下版本实装）

你是想在左栏的图片预览面板，也支持清除预览吗？

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/4199d24a-2019-472f-ba90-d717cceb02e2)

**Comment by brisk21** [comment]
> 在右栏的`记录`面板中，是可以右键清理历史记录的。（Ctrl+Del的快捷键在下版本实装）
> 
> 你是想在左栏的图片预览面板，也支持清除预览吗？
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/313568693-4199d24a-2019-472f-ba90-d717cceb02e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjI0NTMsIm5iZiI6MTcxMTYyMjE1MywicGF0aCI6Ii81NjM3MzQxOS8zMTM1Njg2OTMtNDE5OWQyNGEtMjAxOS00NzJmLWJhOTAtZDcxN2NjZWIwMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwMzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YWQ0MTM5OWZjNjRmMTk1ZWI3NWY2MTIwMWM5NzMyNjQ1MmQ0ZjZlMDM4ZGJlYzZmMWUzZjYzNGQ4NWI3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXdaC6V8dYyyfIhAFgLeYiyGo_91EckxtCDjRXgM8ng)

是的，图片也想清理掉，以前的版本可以的，很清爽，用习惯了

**Comment by hiroi-sora** [comment]
搞定了，下版本即支持。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/8aca032d-14bf-48b0-9439-f7998507b66a)

**Comment by hiroi-sora** [comment]
新版本已发布。
