### ISSUE TITLE
HTTP argv调用返回[Error] Paths is empty.

### ISSUE THREAD

**Issue by 2Niu** [hiroi-sora/Umi-OCR#431]
### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

看README_HTTP.md最后一部分
```
方法：`POST`

参数：`json` `list`

传入一个列表，列表中记录命令行参数。

- 如：命令行调用 `Umi-OCR.exe --path "D:/xxx.png"`
- 等价于向argv接口发送： `["--path", "D:/xxx.png"]`
```

启动Umi-OCR.exe后
python调用:
```
>>> os.path.exists('D:/2.png')
True
>>> 
>>> 
>>> url = 'http://127.0.0.1:1224/argv'
>>> r = requests.post(url, json={'--path':"D:/2.png"})
>>> r.text
'[Error] Paths is empty.'
```

一直返回Paths is empty,这个地方看不懂了,命令行执行倒是正常：
C:\Users\Administrator\Downloads\Umi-OCR_Paddle_v2.1.0\Umi-OCR_Paddle_v2.1.0>Umi-OCR.exe --path D:/2.png

C:\Users\Administrator\Downloads\Umi-OCR_Paddle_v2.1.0\Umi-OCR_Paddle_v2.1.0>08:25
744

**Comment by hiroi-sora** [comment]
指令写错了。json指令要求传入一个列表，如 `["--path", "D:/2.png"]` 。你代码里写成了字典。

**Comment by 2Niu** [comment]
改成列表就行了，多谢！
