### ISSUE TITLE
大佬，关于软件识别对于竖排的日语文字识别容易识别错误

### ISSUE THREAD

**Issue by kevinfkw** [hiroi-sora/Umi-OCR#434]
### Expected behavior 预期的功能

我在使用软件的时候，横排文字识别都还是有很高的正确率，但是竖排文字就非常容易识别错误，请问这部分的弱点能够调整吗？
![识别差异](https://github.com/hiroi-sora/Umi-OCR/assets/164173323/6c67ce97-c3f5-40d6-9e9a-874decaafa6f)

**Comment by hiroi-sora** [comment]
很抱歉，在 Umi-OCR 已经支持的5款开源OCR引擎中，`日文+竖排` 情景的识别率都不太如人意。

你可以尝试这个项目： [manga-ocr](https://github.com/kha-white/manga-ocr) 。对 **竖排漫画** 特攻。

未来，Umi也考虑引入manga-ocr的识别库作为可选插件。

**Comment by qwedc001** [comment]
> 未来，Umi也考虑引入manga-ocr的识别库作为可选插件。
好的收到这就去做（？）

能否提供一些样本图片，发在这里或者发送到邮箱2364319479@qq.com都可
