### ISSUE TITLE
vscode 调试报错：No module named 'frontend'

### ISSUE THREAD

**Issue by Kengson** [hiroi-sora/Umi-OCR#436]
### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

vscode debug的时候报错：
---------------------------
【错误】 Umi-OCR Error
---------------------------
主程序启动失败 !

No module named 'frontend'
但看了下没有引用frontend的代码啊，这个有解决方案么，感谢！！

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![image](https://github.com/hiroi-sora/Umi-OCR/assets/35826488/19a1ef5f-9a20-4ccc-87d9-e4d5d5fa4b8d)

**Comment by hiroi-sora** [comment]
1. 关于运行环境`Umi-OCR_runtime_windows`，请使用/更换为Github自动打包的最新包：
https://github.com/hiroi-sora/Umi-OCR_runtime_windows/archive/refs/heads/main.zip

2. 部署完后，检查能否通过 `Umi-OCR.exe` 运行。如果 exe 可以运行，vscode调试报错，多半是Vscode的项目配置问题。
3. 请确保使用项目目录下的 `.vscode\Umi-OCR_v2.code-workspace` 作为Vscode项目工作区，它已经配好了所需的参数。
