### ISSUE TITLE
TeesseractOCR插件错误

### ISSUE THREAD

**Issue by dajuzi2011** [hiroi-sora/Umi-OCR#437]
### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR, TesseractOCR, Pix2Text

### Reproduction steps 复现步骤

使用TeesseractOCR插件时错误，尝试过删除其中一个，上百度搜过，没解决
<img width="421" alt="PixPin_2024-03-22_19-59-27" src="https://github.com/hiroi-sora/Umi-OCR/assets/148550453/415825a2-551a-4de4-97b3-ccca4939478e">

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

<img width="421" alt="PixPin_2024-03-22_19-59-27" src="https://github.com/hiroi-sora/Umi-OCR/assets/148550453/ba11ac37-8068-43f3-9b62-bbb9ad6a6b08">

**Comment by xmp4660** [comment]
这个是由于文件夹后缀造成的，删除文件夹名称里的 `.` 就可以解决

**Comment by dajuzi2011** [comment]
谢谢，解决了

**Comment by dajuzi2011** [comment]
能更新一下Releases吗，下载下来就带
![Uploading PixPin_2024-03-22_20-16-54.png…]()
点

**Comment by hiroi-sora** [comment]
主插件库 `Umi-OCR_plugins/releases` 的文件昨天已经更新过了。你是从 `qwedc001/tesseractOCR_umi_plugin` 下载的吗？

我去催下修改。

**Comment by dajuzi2011** [comment]
都没改啊？还有从github上下载最新版软件会403，我从sourceforge上下载了半个小时
<img width="1280" alt="PixPin_2024-03-22_21-58-31" src="https://github.com/hiroi-sora/Umi-OCR/assets/148550453/faf7c751-8d07-4239-8adc-d2123e7341f2">
<img width="1280" alt="PixPin_2024-03-22_21-59-12" src="https://github.com/hiroi-sora/Umi-OCR/assets/148550453/be03fa7d-c3d2-4ba0-a4e0-ee0b0620da93">
<img width="1280" alt="PixPin_2024-03-22_21-56-53" src="https://github.com/hiroi-sora/Umi-OCR/assets/148550453/b404d50c-af7f-4fed-a448-47fdda73c4bb">

**Comment by hiroi-sora** [comment]
主插件库中， `win7_x64_TesseractOCR_fast_v1.1.0.7z` 的内部文件夹 `win7_x64_TesseractOCR_fast` 已经不带 `.` 

将内部文件夹放到 `plugins` 目录下即可。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/4e79e9aa-d2f2-4888-8c87-a31f8f0db24f)

至于网络问题，请配合科学上网工具使用Github和sourceforge。国内用户从蓝奏云下载也是OK的，没有限速。

https://hiroi-sora.lanzoul.com/s/umi-ocr

**Comment by qwedc001** [comment]
抱歉我因为忙了一些别的事情造成了拖延，现在我这侧的release也已经完成文件夹修改。
