### ISSUE TITLE
添加额外语言报错 11.1

### ISSUE THREAD

**Issue by lioArther** [hiroi-sora/Umi-OCR#44]
OS 名称: Microsoft Windows 11 专业版
OS 版本: 10.0.22000 暂缺 Build 22000
OS 制造商: Microsoft Corporation
OS 配置: 独立工作站
OS 构建类型: Multiprocessor Free
系统制造商: AZW
系统型号: GTR
系统类型: x64-based PC
处理器: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3301 Mhz

软件版本：1.3.1 alpha1

额外添加英文，在使用的过程中会报错。

![image](https://user-images.githubusercontent.com/27990398/199263440-ba001f9b-5b8a-499e-8613-00b07f47cf71.png)

**文件一：**
PaddleOCR_json_config_en.txt
![image](https://user-images.githubusercontent.com/27990398/199265106-7f3bb84c-a6df-4e16-8031-d122b43fc98a.png)

**文件二：**
en_dict.txt
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/dict/en_dict.txt

**文件三：**
![image](https://user-images.githubusercontent.com/27990398/199264088-b254f271-85b4-4630-b204-1da73b4706f3.png)

**文件四：**
![image](https://user-images.githubusercontent.com/27990398/199264221-7119d417-d094-4b9a-a92b-06b133e14e15.png)

切换为其他语言后，还是可以正常使用。

请帮忙看看是哪里的故障呢？切换为英文就报错。

**Comment by hiroi-sora** [comment]
字典错了，你下载的是V2旧版的字典，不兼容V3模型库。（官方文档也没有提示，我研究了一会才发现的）

V2的英文库是纯英文+数字。V3在此基础上额外增加了常见符号，所以加载旧版字典会因长度不足导致越界，进程崩溃。
V3库对应的字典地址：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/en_dict.txt

实测换了字典后可以跑。效果比简中库好很多，基本没发现空格丢失现象

![image](https://user-images.githubusercontent.com/56373419/199280014-164222c2-6625-4cb1-847c-16c2d574bc0d.png)

**Comment by lioArther** [comment]
替换后，可以正常使用了。感谢。
