### ISSUE TITLE
正在尝试进行在线插件开发，有些问题需要请教

### ISSUE THREAD

**Issue by qwedc001** [hiroi-sora/Umi-OCR#441]
### Expected behavior 预期的功能

[off topic] GPU侧暂时推进不下去，详见 hiroi-sora/Umi-OCR/discussions/440，所以看了一眼短期计划里我能帮上忙的捡了这个事
[off topic] 网络波动吃了我一次issue提交，写的东西全没了
读了一下百度关于OCR的文档，尝试实现了一下，遇到几个问题
1.用户的API Key和Secret Key一类隐私内容，Umi的处理方式应该是填写一次后消失不再展示（允许通过特定按钮修改），或者是放在localOptions里和其他选项一致？
2.百度OCR里提供了普通识别和高精度识别。造成了一些需要差异化的设置处理。高精度识别里有些选项是普通识别没有的，对于这部分选项，现有的框架和写法能不能支持监测模式切换动态更改列表？还是需要将两种OCR模式分割成两个插件？
3.注意到百度OCR里提供了一个PDF识别手段，但是对于文件本身的要求比较高（base64编码小于10M），这个手段需要实现吗，还是按照原先umi的处理方式就好

**Comment by hiroi-sora** [comment]
1. `API Key` 和 `Secret Key` 放在 `globalOptions` 里。配置文件本身是明文存储，不具备加密的条件。前端也没有必要做遮挡，直接显示即可。同类 调API的项目都是明文存储，对于本地应用而言不必太担心安全性。
2. 我觉得没有必要区分，普通和高精度的参数可以写在一起，高精度的参数给个提示（只有高精度模式下才生效）。
3. 没必要用百度的PDF接口。插件仅提供基础的OCR功能即可，PDF解析交给Umi。

另外，我接下来（v2.1.1发布后）准备重写插件构架，修补现有结构存在一些缺点。你可以先不急着写新的插件。

更多信息，发了个邮件给你。

**Comment by qwedc001** [comment]
理解了，那基于现有情况该issue先close掉了，等着时机成熟了再加入到task
:D
