### ISSUE TITLE
win7 通过exe及bat均无法启动

### ISSUE THREAD

**Issue by User1596025356** [hiroi-sora/Umi-OCR#444]
### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win7

### Reproduction steps 复现步骤

单位电脑win7通过exe及bat打开均无反应。后用另一电脑在虚拟机中安装全新win7 64位（vc运行库已安装），双击exe及bat同无反应，通过命令行启动exe报以下错误。
![111](https://github.com/hiroi-sora/Umi-OCR/assets/47137868/68185c17-f3e0-47cb-bb1a-a4a92d0e873d)

**Comment by hiroi-sora** [comment]
感谢你提供的报错截图。跟 ( #293 ) 类似，是`pynput`和`ctypes`这两个库报错。不过在win7上不兼容是首次发现。

我怀疑跟win7小版本有关，能否再截图/拍照，看看 **系统信息** ？

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/b9a42ed5-456f-4249-bf86-95e6c7a75876)

**Comment by hiroi-sora** [comment]
另外，你虚拟机iso如果有下载地址也请发我，我可以帮测试一下。

**Comment by User1596025356** [comment]
麻烦了，公司电脑系统信息如下：
![a90c39eaaa301ccc87f654348e65b82d](https://github.com/hiroi-sora/Umi-OCR/assets/47137868/90a8d326-d9bf-4da6-ad75-c9d503861542)

虚拟机win7测试iso下载地址：
https://www.alipan.com/s/utUwfyjY52d

**Comment by hiroi-sora** [comment]
测试完毕，该iso缺失了 `KB2533623` 补丁，导致 Python 3.8 无法运行。

请安装一个 KB2533623 补丁： `Windows6.1-KB2533623-x64.msu`

（微软官网已经关闭了该补丁的下载。如果要在第三方网站下，请注意安全。）

**Comment by User1596025356** [comment]
非常感谢！安装此补丁后可正常打开，但点击截图OCR程序会出现“未响应”。后经过windows updates更新到最新后可正常使用。
