### ISSUE TITLE
非使用期间也会占用CPU资源

### ISSUE THREAD

**Issue by xmokay** [hiroi-sora/Umi-OCR#446]
### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

WIN 10

### OCR plugins Used 使用的OCR插件

RapidOCR

### Reproduction steps 复现步骤

打开Umi-OCR，什么都不做。观察CPU使用率，发现Umi-OCR会持续占用2%左右的CPU资源（可能不同电脑略有差异），这个状态一一直持续无论打开多久。

**Comment by qwedc001** [comment]
你好，我无法复现issue所说情况。我的电脑Umi在执行完OCR以后CPU占用率迅速跌至0。
如果可以，请进一步提供截图/系统版本加以说明。
Umi-OCR在执行过一次OCR识别后，后台会开启一个常驻的OCR引擎，你看到的**有可能**是引擎的占用。但是，我电脑上没有这种情况。

**Comment by hiroi-sora** [comment]
并不是引擎的占用，OCR引擎在非活动期间是不占用CPU的。

你看到的应该是前端UI的占用。如果进行过截图OCR等操作，前端正在显示图片的话，就会产生1%~2%的占用。测试如下：

|  情景 | CPU占用稳定值 |
|----|----|
| 打开截图标签页，未显示图片 | 0.3% |
| 打开截图标签页，正在显示图片 | 2% |
| 截图，然后关闭窗口（放到托盘） | 0% |
| 一直放在托盘，进行截图操作 | 0% |

未来我可能对图片渲染组件的性能进行优化，但优先级不高。当前，对性能敏感的用户可以：
- 截图OCR后，手动清空图片（下版本支持）
- 长期将Umi-OCR放在后台使用（建议在设置中关闭`识图后弹出主窗口`，开启`自动复制结果`）。

**Comment by xmokay** [comment]
> 并不是引擎的占用，OCR引擎在非活动期间是不占用CPU的。
> 
> 你看到的应该是前端UI的占用。如果进行过截图OCR等操作，前端正在显示图片的话，就会产生1%~2%的占用。测试如下：
> 情景 	CPU占用稳定值
> 打开截图标签页，未显示图片 	0.3%
> 打开截图标签页，正在显示图片 	2%
> 截图，然后关闭窗口（放到托盘） 	0%
> 一直放在托盘，进行截图操作 	0%
> 
> 未来我可能对图片渲染组件的性能进行优化，但优先级不高。当前，对性能敏感的用户可以：
> 
>     * 截图OCR后，手动清空图片（下版本支持）
> 
>     * 长期将Umi-OCR放在后台使用（建议在设置中关闭`识图后弹出主窗口`，开启`自动复制结果`）。

对。应该就是UI渲染对资源的消耗，可能有UI内容在不停重绘。我这没有截图的情况下，界面不最小化的话，使用率就在1-2%的样子。

**Comment by hiroi-sora** [comment]
经过调查，此问题应该是加载动画【OCR......】造成的异常资源占用，已修复。

你可以尝试：将软件目录中的`UmiOCR-data\qt_res\qml\Widgets\Loading.qml`替换为[新的内容](https://github.com/hiroi-sora/Umi-OCR/blob/3bcd4e6025c67c74459c81af4b2b627d36a5186a/UmiOCR-data/qt_res/qml/Widgets/Loading.qml)。此时，空闲状态下应该不会占用CPU了。
