### ISSUE TITLE
【功能请求】命令行 --screenshot 能设定参数，截取全屏或指定屏幕范围进行OCR，无需鼠标框选。

### ISSUE THREAD

**Issue by Twist110** [hiroi-sora/Umi-OCR#452]
### Expected behavior 预期的功能

执行Umi-OCR.exe --screenshot --output test.txt命令行后, 后台能自动截取当前屏幕全屏，或者指定屏幕范围。

**Comment by hiroi-sora** [comment]
我考虑一下该功能。

有相同需求的小伙伴可以点个表情或者回帖，人数会影响开发优先级。

**Comment by Twist110** [comment]
这个功能很有必要，对在Windows系统后台每隔一段时间自动截取屏幕主界面，并通过OCR识别出其中的文字内容，把结果保留到文档里。

**Comment by hiroi-sora** [comment]
此功能基本开发完毕，欢迎测试。（后续将发布到新版本）

拉取main分支代码进行测试：

https://github.com/hiroi-sora/Umi-OCR/archive/refs/heads/main.zip

1. 从上述链接下载zip包
2. 解压其中的`UmiOCR-data`目录
3. 粘贴到 **Umi-OCR v2.1.1** 版本的`UmiOCR-data`目录中（即覆盖原有同名目录）

范围截图指令：
```
umi-ocr --screenshot screen=0 rect=x,y,w,h
```
控制参数：（注意，前面无需加`--`）
- `screen`: 要截图的显示器编号（多个显示器时有效），从0开始。缺省为0。
- `rect`: 截图范围矩形框，`x坐标,y坐标,w宽度,h高度`。缺省为全屏。

示例1：截取第1个显示器的全屏
```
umi-ocr --screenshot screen=0
```

示例2：截取第2个显示器，从左上角[50,100]开始，大小为 300x200 的矩形
```
umi-ocr --screenshot screen=1 rect=50,100,300,200
```

**Comment by Twist110** [comment]
已验证成功，非常感谢，希望尽快加入正式版里。





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiroi-sora/Umi-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月24日(星期五) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiroi-sora/Umi-OCR] 【功能请求】命令行 --screenshot 能设定参数，截取全屏或指定屏幕范围进行OCR，无需鼠标框选。 (Issue #452)





 
此功能基本开发完毕，欢迎测试。（后续将发布到新版本）
 
拉取main分支代码进行测试：
 
https://github.com/hiroi-sora/Umi-OCR/archive/refs/heads/main.zip
  
从上述链接下载zip包
 
解压其中的UmiOCR-data目录
 
粘贴到 Umi-OCR v2.1.1 版本的UmiOCR-data目录中（即覆盖原有同名目录）
  
范围截图指令：
 umi-ocr --screenshot screen=0 rect=x,y,w,h  
控制参数：（注意，前面无需加--）
  
screen: 要截图的显示器编号（多个显示器时有效），从0开始。缺省为0。
 
rect: 截图范围矩形框，x坐标,y坐标,w宽度,h高度。缺省为全屏。
  
示例1：截取第1个显示器的全屏
 umi-ocr --screenshot screen=0  
示例2：截取第2个显示器，从左上角[50,100]开始，大小为 300x200 的矩形
 umi-ocr --screenshot screen=1 rect=50,100,300,200

**Comment by hiroi-sora** [comment]
[v2.1.2 正式版](https://github.com/hiroi-sora/Umi-OCR/releases/latest) 已发布
