### ISSUE TITLE
Win10系统内使用Umi-OCR v2.1版本报错

### ISSUE THREAD

**Issue by frederic89** [hiroi-sora/Umi-OCR#453]
### CPU  

Intel Core（TM）2 Duo CPU

### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

国产VDI虚拟云桌面登入后，v2.1.0解压桌面使用Umi-OCR，提示报错。
在使用截图功能后，步入自动识别文字时PaddleOCR-json.exe弹出错误窗口，“应用程序无法正常启动（0xc0000142）”。随后，Umi-OCR同样报错。
具体详见图片。Citrix虚拟桌面Workspace平台未测试。

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

<img width="645" alt="bug1" src="https://github.com/hiroi-sora/Umi-OCR/assets/16588101/6bf121d0-7ab3-426c-9401-44eee829ca1b">
<img width="389" alt="bug2" src="https://github.com/hiroi-sora/Umi-OCR/assets/16588101/6d6b4d5e-1ab7-463d-8bcd-04a639d831d8">

**Comment by hiroi-sora** [comment]
明显是该云环境缺乏AVX指令集。换用Rapid版本即可。

**Comment by frederic89** [comment]
> 明显是该云环境缺乏AVX指令集。换用Rapid版本即可。

感谢指导 换用后Rapid版本后可正常使用
