### ISSUE TITLE
求增加截图取消不显示主程序画面的需求

### ISSUE THREAD

**Issue by BaseenHolmes** [hiroi-sora/Umi-OCR#454]
### Expected behavior 预期的功能

现状：“截图成功“ 或 ”截图过程中按esc退出“ 都会自动显示主程序画面，虽然有“识图后弹出主程序”的选项，但如果关闭了该选项，则“截图成功“ 或 ”截图过程中按esc退出“ 这两种情况都不显示主程序画面。
需求：当 **“截图过程中按esc退出”则不显示主程序框**；而当**“截图成功”则显示主程序框**

**Comment by hiroi-sora** [comment]
可以，我之后优化一下整体逻辑。

目前你可以简单修改代码实现：

1. 打开 `UmiOCR-data\qt_res\qml\TabPages\ScreenshotOCR\ScreenshotOCR.qml`
2. 第31行的`screenshotEnd`函数，将 `popMainWindow()` 移到 `if` 语句块的后面，即：
```
    // 截图完毕
    function screenshotEnd(clipID) {
        if(!clipID) { // 截图取消
            tabPage.callPy("ocrImgID", undefined, undefined)
            return
        }
        popMainWindow()
        // ……其余步骤
```
