### ISSUE TITLE
软件启动识图失败

### ISSUE THREAD

**Issue by bhjg** [hiroi-sora/Umi-OCR#456]
### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

Windows 11 专业版 23H2

### Reproduction steps 复现步骤

[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 16, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}

每次启动都这样

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![20244394910](https://github.com/hiroi-sora/Umi-OCR/assets/79200621/c766b8f4-d5d7-4e1a-a626-a030244cf34d)
![20244394933](https://github.com/hiroi-sora/Umi-OCR/assets/79200621/6bb2bfd2-d6e2-4f76-be8f-8ac620ad3079)
![20244394957](https://github.com/hiroi-sora/Umi-OCR/assets/79200621/686c5346-83a9-456f-ad5a-c22d38fe7c17)

**Comment by hiroi-sora** [comment]
看起来是虚拟机环境，模拟的CPU不支持AVX指令集。请换用Rapid版本。
