### ISSUE TITLE
功能建议：OCR结果输出到每个图片同名的单独txt文件

### ISSUE THREAD

**Issue by githubmango0509** [hiroi-sora/Umi-OCR#46]
之前一直对离线OCR工具不抱任何希望，直到找到这个开源软件。测试下来识别率真的很高，感谢作者无私奉献！不支持win7略有点遗憾。还有一点小希望，如果后续版本能加入输出OCR结果到txt文件时，可以一个图片一个txt文件，以每个图片的主名为文件名，那就更棒了！

**Comment by hiroi-sora** [comment]
### 蟹蟹支持！❤

> 输出到每个图片同名的单独txt文件

写好了，从main分支打包即可，或者下载我打包的临时版 `Umi-OCR v1.3.2 Dev.exe`：
https://hiroi-sora.lanzoul.com/s/umi-ocr-test
（不含引擎组件，请扔进v1.3.1的文件夹中使用）

![image](https://user-images.githubusercontent.com/56373419/200184967-c63d31fb-0260-40d0-aae5-32f9c6325d43.png)

**Comment by githubmango0509** [comment]
愿望实现了,感谢作者神速更新!

**Comment by githubmango0509** [comment]
新版本收到,已下载,感谢!
















在 2022-12-01 19:29:25，"hiroi-sora" ***@***.***> 写道：

Closed #46 as completed.
