### ISSUE TITLE
如何向site-packages添加opencv。

### ISSUE THREAD

**Issue by enxion** [hiroi-sora/Umi-OCR#462]
### Expected behavior 预期的功能

大佬你好。我想在程序加入摄像头,需要引入opencv.试着从conda env中复制了cv2和opencv_python,还有numpy.但是在main.py中加入imopr cv2后一直提示找不到multiarry_umath.大佬能指点一下如何正确的添加python库吗？万分感谢。也希望大佬能在后续更新中能加入摄像头功能
![360截图20240407151114649](https://github.com/hiroi-sora/Umi-OCR/assets/14361584/5d34bf73-cb8c-4957-8c9f-e67b803a1fd2)

**Comment by hiroi-sora** [comment]
### 摄像头功能

是的，我也有考虑调用设备相机来拍照OCR，不过此功能优先度不高。等以后有空吧。

### 导入外部库

建议不要在本项目内用conda的库，少数情况下可能会有坑。请用原生python虚拟环境。

1. 确保基于 python 3.8.10 x64 ，创建一个虚拟环境。在虚拟环境内pip安装所需的库。
2. 将虚拟环境的 `.venv\Lib\site-packages` 内的文件，复制到 `UmiOCR-data\site-packages` 中。或者：

为了便于调试，防止误动原本的库，创建一个 `UmiOCR-data\site-packages-2`

- 在 `UmiOCR-data\main.py` 第110行的for循环中，将 `site-packages-2` 加入搜索路径，即：
```
    for n in [".", "site-packages", "site-packages-2"]:
```

最后，在任意py文件中 import cv2 。

**Comment by hiroi-sora** [comment]
另外，你似乎是直接在发行版上进行开发？部署一个 [开发环境](https://github.com/hiroi-sora/Umi-OCR_runtime_windows) ，调试起来更轻松哦。

**Comment by enxion** [comment]
感谢大佬。我在PyStand项目和Numpy里面看见了相同的提问，成功的解决了提问。我不是专业的程序员，看到这个项目挺有趣的，想加个摄像头功能玩一下。但我发现这不是一件简单的事情。之前并没有接触过QML，也不清楚项目的架构。都不知道从哪入手呢，估计要花一点时间才能摸清楚。也希望大佬能尽快推出摄像头功能。我感觉这个功能还是很有用的。
再次感谢大佬！

**Comment by enxion** [comment]
感谢大佬。我在PyStand项目和Numpy里面看见了相同的提问，成功的解决了提问。我不是专业的程序员，看到这个项目挺有趣的，想加个摄像头功能玩一下。但我发现这不是一件简单的事情。之前并没有接触过QML，也不清楚项目的架构。都不知道从哪入手呢，估计要花一点时间才能摸清楚。也希望大佬能尽快推出摄像头功能。我感觉这个功能还是很有用的。
再次感谢大佬！
