### ISSUE TITLE
在 Parallels Desktop 的 win11 虚拟机中，打开 Umi-OCR.exe，没有反应

### ISSUE THREAD

**Issue by yksalun** [hiroi-sora/Umi-OCR#465]
### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

在 Parallels Desktop 的 win11 虚拟机中，打开 Umi-OCR.exe，没有出现图形化界面，但是进程是存在的，用命令行启动也是一样的情况。

**Comment by yksalun** [comment]
是虚拟机连接外接盘的问题，将外接盘链接到虚拟机上就没问题了。

**Comment by qwedc001** [comment]
还以为是Apple M芯片的问题，刚刚编辑消息到一半
解决了就好（

**Comment by yksalun** [comment]
您好，您的邮件我已收到，我会尽快回复。

**Comment by harvey-1993** [comment]
在 Parallels Desktop 的 win10 虚拟机中，也出现了打开 Umi-OCR.exe，没有出现图形化界面，但是进程是存在的，用命令行启动也是一样的情况。没有外接盘
