### ISSUE TITLE
希望批量识别文档可以有暂停功能

### ISSUE THREAD

**Issue by tcmtom** [hiroi-sora/Umi-OCR#469]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

如题

前面识别了一个900多页的文档，从头开始太麻烦而且费时间，就只能端着电脑从办公室走到宿舍来的，所以希望能有此功能

**Comment by hiroi-sora** [comment]
好建议，会做

**Comment by hiroi-sora** [comment]
[v2.1.2 正式版](https://github.com/hiroi-sora/Umi-OCR/releases/latest) 已发布
