### ISSUE TITLE
能否实现维吾尔语识别？

### ISSUE THREAD

**Issue by moys1778** [hiroi-sora/Umi-OCR#470]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

我想实现对图片上维吾尔语的提取

**Comment by hiroi-sora** [comment]
参考 [常见问题](https://github.com/hiroi-sora/Umi-OCR/issues/447#issuecomment-2025245747) ，目前没有开源OCR引擎拥有维吾尔语的识别库。（技术上可以实现，但是需要自己训练模型。）

未来会接入在线OCR接口，届时可使用国内厂商提供的小语种识别服务。
