### ISSUE TITLE
Rapid和Paddle都无法正确识别瘪字

### ISSUE THREAD

**Issue by Xmug** [hiroi-sora/Umi-OCR#475]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR

### Reproduction steps 复现步骤

Paddle会识别成别的字，Rapid则干脆不识别。
另外Rapid有时能识别出憋字，有时不能。
![QQ截图20240416101258](https://github.com/hiroi-sora/Umi-OCR/assets/7780332/444555e8-e51d-40c7-a54c-b76fea1778bf)
![QQ截图20240416101108](https://github.com/hiroi-sora/Umi-OCR/assets/7780332/2f884cd4-66c2-4c4b-9b26-3626c036fba1)

**Comment by qwedc001** [comment]
你好，经过对于 paddle 和 rapid 本身的命令行测试，得出的结论为 #447 FAQ issue中的`“某种语言识别准确率低”`。
例： paddle 测试用命令行： 
```bash
paddleocr --image_dir ./test.png --use_angle_cls true --use_gpu false
````
命令行返回结果：
![image](https://github.com/hiroi-sora/Umi-OCR/assets/14366166/8269b540-fbea-4172-80d4-e4be203d2c78)

我对 paddle 的词典文件查找了一下，词典文件中是有“憋”字的，可能识别的优先级比较低。这个问题并非 Umi 所能解决的的 issue 范围之内，请前往 [PaddleOCR 开源项目](https://github.com/PaddlePaddle/paddleocr) 和 [RapidOCR开源项目](https://github.com/rapidAI/RapidOcrOnnx) 进行反馈。我们会在模型文件更新后使用最新的离线模型作为 Umi 的内置模型。或者您也可以等待我们后续对于在线 OCR API 的适配。
