### ISSUE TITLE
[BUG]无法同时提交超过255个pdf文件进行扫描

### ISSUE THREAD

**Issue by kylincaster** [hiroi-sora/Umi-OCR#476]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

同时在window文件浏览器中选中超过255个pdf文件，然后拖入Umi-OCR中，这样Umi-OCR就会失去一部分组件功能的作用，也无法再添加或删除待扫描的pdf文件，只能扫描已有的前255个pdf文件。

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

我是在将整个pdf文件以页为单位进行拆分扫描时发现的。主要是Umi-OCR对pdf文件进行扫描时没有暂停功能，因此，本人将大的pdf文件拆散进行处理，然后再合并已扫描的文件。因此，希望Umi-OCR添加暂停功能，或临时保存能力。

**Comment by butitsblue** [comment]
> 暂停功能在开发中。
> 
> 我这边测试（Win11），拖入超过800个文件是正常的哦，虽然拖入的瞬间会因为预处理而卡一下。
> 
> 另外在我的程序设计上，按理说不会有数量上限或者遇到性能上限。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/322902089-7b871adc-ad85-41f0-983c-e0a324e2704d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjk3NjgsIm5iZiI6MTcxNjQyOTQ2OCwicGF0aCI6Ii81NjM3MzQxOS8zMjI5MDIwODktN2I4NzFhZGMtYWQ4NS00MWYwLTk4M2MtZTBhMzI0ZTI3MDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxNTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDNkOGZkOTFmYTQyYjQwNjM1NWY0Y2ZjZTdmMmY1ZjZlZGU2MTMwY2I0MzJjYWRkOTQ2NDQzZTUxNWE4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mG-pigZNT_FLV3_RYfVCcv2CSqB8ShstM7KccZfi5w)
> 
> 你的问题，我估计有几个可能：
> 
> 1. 拖入瞬间的卡顿状态下，因为点击鼠标或者别的原因，使得预处理中断，只有前255个文件被导入。
> 2. 操作系统限制，一次只能拖拽255个文件。
> 
> 你可以做这些尝试：
> 
> 1. 拖入、松开左键的瞬间，确保不要继续碰鼠标或键盘。
> 2. 不要全选所有文件拖入，而是拖入单个父文件夹。
> 3. 不拖入，而是点打开文档的按钮，Ctrl+A全选→导入多个文件。

同样遇到类似问题，拖入超过255个文件没问题，点击开始任务就会弹出错误提示，255个文件往后的所有文件都是初始化输出器失败，无法加载文档

**Comment by hiroi-sora** [comment]
> 同样遇到类似问题，拖入超过255个文件没问题，点击开始任务就会弹出错误提示，255个文件往后的所有文件都是初始化输出器失败，无法加载文档

你是输出 什么文件？双层PDF吗？

**Comment by butitsblue** [comment]
@

> > 同样遇到类似问题，拖入超过255个文件没问题，点击开始任务就会弹出错误提示，255个文件往后的所有文件都是初始化输出器失败，无法加载文档
> 
> 你是输出 什么文件？双层PDF吗？

对，批量双层pdf

**Comment by hiroi-sora** [comment]
> 对，批量双层pdf

好的，大概知道问题在哪了，正在修复。

**Comment by butitsblue** [comment]
> > 对，批量双层pdf
> 
> 好的，大概知道问题在哪了，正在修复。

谢谢，期待

**Comment by butitsblue** [comment]
> [v2.1.2 版本](https://github.com/hiroi-sora/Umi-OCR/releases/latest) 发布，优化了大批文件加载的性能，理论上能避免此 Bug 。
> 
> 如果还有此问题复现，可能是系统限制一次拖入的数量，可尝试分批拖入文件，或者拖入单个 父文件夹。

感恩
