### ISSUE TITLE
ui界面乱码白屏

### ISSUE THREAD

**Issue by sexchen** [hiroi-sora/Umi-OCR#477]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win7

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR

### Reproduction steps 复现步骤

win7环境，打开应用后，鼠标移动到程序上后ui界面就会变成空白乱码，搜索没有历史提问，不知道是少了什么组件。1.X版本无此问题。

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![IMG_20240412_084545](https://github.com/hiroi-sora/Umi-OCR/assets/17498101/d5a68afa-9536-4a6b-9e08-6bc2270ce0af)
![IMG_20240412_085641](https://github.com/hiroi-sora/Umi-OCR/assets/17498101/5d3639c6-d752-4802-ad30-3d37f316a25a)
![IMG_20240412_084554](https://github.com/hiroi-sora/Umi-OCR/assets/17498101/2c0a2051-984c-451b-aa86-81a0d3f9c27d)
![IMG_20240412_085318](https://github.com/hiroi-sora/Umi-OCR/assets/17498101/d61a705f-837f-4ecc-83c3-80cb98bf1adc)

**Comment by sexchen** [comment]
> 你好，看起来是系统文本解码库的问题。请尝试更新一下系统：
> 
> 控制面板 → 系统和安全 → Windows 更新 → 检查更新

我的电脑无法连接到网络，能告诉我我需要安装什么补丁吗

**Comment by hiroi-sora** [comment]
抱歉，因为此问题无法复现，所以我没有办法研究它并知道具体的错误原因。

但是，Win7上大多数已知问题，都与系统缺失更新相关。网上有一些“离线整合补丁包”，可能对你的设备有效。
