### ISSUE TITLE
能不能把GPU也给它用上

### ISSUE THREAD

**Issue by msjsc001** [hiroi-sora/Umi-OCR#478]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

开发者你好，我的电脑是中高配，AMD3700X + RTX3060 在使用PDF 的OCR时目前只能用到CPU，后边能不能把GPU也支持上？让它效率更高？（目前CPU也只能跑到50%左右）
以下是运行环境信息：
```
{
  "cpu": "AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD | 8C16T",
  "home": "C:\\Program Files\\Uim-OCR\\Umi-OCR_Paddle_v2.1.1",
  "path": "C:\\Program Files\\Uim-OCR\\Umi-OCR_Paddle_v2.1.1\\Umi-OCR.exe",
  "platform": "Windows-10-10.0.22631",
  "python": "3.8.10",
  "ram": "31.9 GB"
}
```

### Approximate reference (optional) 近似的参考（可选）

![image](https://github.com/hiroi-sora/Umi-OCR/assets/93178788/a7be4f63-91f7-4ae3-8abc-0767fef6cb7b)

**Comment by qwedc001** [comment]
Duplicate of #447 .
你好，此问题已经在常见问题中回答。

**Comment by msjsc001** [comment]
> Duplicate of #447 . 你好，此问题已经在常见问题中回答。

好，看了，既然是长线计划这个需求就先关闭了。
