### ISSUE TITLE
低版本cpu问题，换Umi-OCR_Rapid解决了

### ISSUE THREAD

**Issue by lforlgg** [hiroi-sora/Umi-OCR#480]
### Umi-OCR version 程序版本

Umi-OCR_Paddle_v2.1.1

### Windows version 系统版本

Windows 10 企业版 LTSC 21H2 19044.4046

### OCR plugins Used 使用的OCR插件

_No response_（原版解压即用）

### Reproduction steps 复现步骤

截图OCR，截图后，弹出错误提示：
![2024-04-20_120257](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/c175961a-2d17-48c2-b10b-fa84b91e1784)

---------------------------
PaddleOCR-json.exe - 应用程序错误
---------------------------
应用程序无法正常启动(0xc0000142)。请单击“确定”关闭应用程序。 
---------------------------
确定   
---------------------------

点确定后，继续提示：
![2024-04-20_120310](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/f26f41aa-9e8d-4a78-ae29-9b7f27882b9f)

[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 2, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}

谢谢。不知是否跟系统精简有关。office等大型软件运行没问题。

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![2024-04-20_win](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/2b9b6bf3-53c8-44fc-a554-079b4bf6d4d6)
![2024-04-20_120356](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/45177e8a-fe36-438f-8cef-5b71dd7d6368)

**Comment by hiroi-sora** [comment]
哈哈，[【FAQ】 常见问题](https://github.com/hiroi-sora/Umi-OCR/issues/447) 第一条就是。
