### ISSUE TITLE
[已解决]某些pdf识别后文本层每页都有一定程度的错位（附样本）

### ISSUE THREAD

**Issue by lforlgg** [hiroi-sora/Umi-OCR#483]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

Windows10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

pdf识别后文本层有错位问题。
Umi-OCR_Paddle_v2.1.1.7z.exe
Umi-OCR_Rapid_v2.1.1.7z.exe
都测试过，都有此问题。

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

{
  "cpu": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel | 6C6T",
  "home": "D:\\AI\\UmiOCR_Paddle",
  "path": "D:\\AI\\UmiOCR_Paddle\\Umi-OCR.exe",
  "platform": "Windows-10-10.0.17763",
  "python": "3.8.10",
  "ram": "47.9 GB"
}
[错位样本P24-28.pdf](https://github.com/hiroi-sora/Umi-OCR/files/15050502/P24-28.pdf)

**Comment by hiroi-sora** [comment]
好的，已确认默认模式下有文本错位的问题，后续会尝试修复。

因为PDF内容格式比较灵活，有一些生成器（扫描仪）又不按规范写入，所以解析时会有预料以外的情况发生，见谅。

目前，你可以将内容提取模式改为`整页强制OCR`，如下图。可以避免文本错位问题。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/e67b3a4a-ec2b-44e3-bb71-e19db09b3c91)

**Comment by lforlgg** [comment]
谢谢大佬，我懂了。试了一下，用您说的选项，完美解决！👍️❤️

那些选项的确有点专业，没接触过的，不敢随意更改默认选项。
如果方便，可以在鼠标移向选项时，给点tips提示：
![tips_ziped](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/d540bd37-bb56-4696-8dbe-8764d564952a)
😋

**Comment by hiroi-sora** [comment]
收到，好建议

**Comment by lforlgg** [comment]
> 好的，已确认 默认模式下有文本错位的问题，后续会尝试修复。
> 
> 因为PDF内容格式比较灵活，有一些生成器（扫描仪）又不按规范写入，所以解析时会有预料以外的情况发生，见谅。
> 
> 目前，你可以将内容提取模式改为`整页强制OCR`，如下图。可以避免文本错位问题。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/324220803-e67b3a4a-ec2b-44e3-bb71-e19db09b3c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzE4MjQsIm5iZiI6MTcxMzg3MTUyNCwicGF0aCI6Ii81NjM3MzQxOS8zMjQyMjA4MDMtZTY3YjNhNGEtZWMyYi00NGUzLWJiNzEtZTE5ZGIwOWIzYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTllNjVjOGJmYWQ5NTg1ODkxNGIyNzJhNmRjNWQwNzQwODI4MDJiNTA0M2Q0ZDhmNDkxMWIwNTczNzc4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8rj6Uemr6CoL3DcvNRCWk3htPX9rxnc6bVopCQb27w)
@hiroi-sora 叨扰大佬，帮看看。
又有一个批量文档ocr错位的样本，这次结果有点惨不忍睹。重置默认设置和用你的设置办法，都差不多结果。
截图ocr倒是还好。
这种类似目录这样排版的，umi-ocr似乎总是喜欢把页码放在一堆，它不是每个条目一行一行。abbyy这块表现比较正常。
[排版会错位的OCR样本.pdf](https://github.com/hiroi-sora/Umi-OCR/files/15076010/OCR.pdf)

考虑到类似问题集中，我要么不开新帖避免占用更多资源。

**Comment by lforlgg** [comment]
> 好的，已确认 默认模式下有文本错位的问题，后续会尝试修复。
> 
> 因为PDF内容格式比较灵活，有一些生成器（扫描仪）又不按规范写入，所以解析时会有预料以外的情况发生，见谅。
> 
> 目前，你可以将内容提取模式改为`整页强制OCR`，如下图。可以避免文本错位问题。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/324220803-e67b3a4a-ec2b-44e3-bb71-e19db09b3c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzE4MjQsIm5iZiI6MTcxMzg3MTUyNCwicGF0aCI6Ii81NjM3MzQxOS8zMjQyMjA4MDMtZTY3YjNhNGEtZWMyYi00NGUzLWJiNzEtZTE5ZGIwOWIzYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTllNjVjOGJmYWQ5NTg1ODkxNGIyNzJhNmRjNWQwNzQwODI4MDJiNTA0M2Q0ZDhmNDkxMWIwNTczNzc4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8rj6Uemr6CoL3DcvNRCWk3htPX9rxnc6bVopCQb27w)
@hiroi-sora 叨扰大佬，帮看看。
又有一个批量文档ocr错位的样本，这次结果有点惨不忍睹。重置默认设置和用你的设置办法，都差不多结果。
截图ocr倒是还好。
这种类似目录这样排版的，umi-ocr似乎总是喜欢把页码放在一堆，它不是每个条目一行一行。abbyy这块表现比较正常。
[排版会错位的OCR样本.pdf](https://github.com/hiroi-sora/Umi-OCR/files/15076010/OCR.pdf)

考虑到类似问题集中，我要么不开新帖避免占用更多资源。

**Comment by hiroi-sora** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/78bd3b69-2e22-467b-9236-1e44dd39084b)

你这份样本，OCR出来的文本位置是没有错的。可能你指的是文本顺序错误，先左边的标题，后右边的页码。

这是因为，Umi默认将PDF当成 **多栏排版** ，左边的标题和右边的页码被识别成了 **两栏** ，因此先左后右。

你可以在设置里，将排版解析方案改为任意的 `单栏` ，即可应付这种情景。

当前Umi的算法没办法识别是单栏目录还是双栏正文，所以必须手动选择排版方案。未来可能会引入专门的排版识别AI模型，类似ABBYY那样，支持智能排版。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/194fd904-104e-4f9f-848c-be1e0304145b)

**Comment by lforlgg** [comment]
比较困惑，我同样设置得不到您那有的排版结果（识别结果如附件）。
[OCR样本_识别后的排版.pdf](https://github.com/hiroi-sora/Umi-OCR/files/15077093/OCR._.pdf)
![cor2_ziped](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/4f188b9f-974a-43f7-9008-5faf07002143)
![cor_ziped](https://github.com/hiroi-sora/Umi-OCR/assets/105794681/61a77908-1296-4d03-ae7a-4933d7adb84c)

**Comment by hiroi-sora** [comment]
哦哦，懂了，v2.1.1确实存在这个问题。我拿最新main分支做的测试，已经修复了这个问题。

你可以拉取一下main分支（或者github主页下载zip包），直接将 `UmiOCR-data` 整个目录，覆盖粘贴到v2.1.1的相同目录。

**Comment by hiroi-sora** [comment]
👍 收到
