### ISSUE TITLE
Add an option to generate one layer PDF file output

### ISSUE THREAD

**Issue by tonyho** [hiroi-sora/Umi-OCR#487]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

Except the 2 layered PDF, can you kindly to add an one layer pdf export option?  Or can I extract the OCRed(text) PDF layer using other free tools?

### Approximate reference (optional) 近似的参考（可选）

None

**Comment by hiroi-sora** [comment]
I've just added this feature; you can pull from the main branch to test it. (Alternatively, you can copy the `UmiOCR-data` directory from the main branch and overwrite the same directory in the `Release v2.1.1` .)

In the `Batch Documents OCR` tab, check the `Advanced` option in settings. Now, the `Output file format` will have an additional option: `.pdf One-layer plain text document`. This allows for the output of a single-layer PDF containing only the OCR results, without the original image layers.

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/84d77e2c-4d31-4704-85d6-e0c4a52afb95)
