### ISSUE TITLE
文字与向量公式混排的时候，向量识别有误。

### ISSUE THREAD

**Issue by wuaijiepo** [hiroi-sora/Umi-OCR#493]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

Pix2Text

### Reproduction steps 复现步骤

单独识别向量准确，但是文字与向量公式混排的时候，向量识别有误。
![360截图20240410084424889](https://github.com/hiroi-sora/Umi-OCR/assets/168254053/21e637af-b0e7-4450-8c76-4bfa2ab9e3d8)

![360截图20240427114719561](https://github.com/hiroi-sora/Umi-OCR/assets/168254053/7ae51b45-f34d-4718-b96a-f83997df2547)

**Comment by hiroi-sora** [comment]
这是 Pix2Text 插件，**检测模型** 的精度问题。它对于行内公式的检测能力比较有限。

见： https://github.com/breezedeus/Pix2Text/issues/70

例图这种较复杂的情景，还是不要用混合识别了，手动一个个框选吧。（在设置里仅勾选 `启用数学公式` ，可以提高纯公式识别的精度。）

**Comment by wuaijiepo** [comment]
非常感谢。
