### ISSUE TITLE
作者大牛。可以把pdf识别http接口先上吗 

### ISSUE THREAD

**Issue by dandaaan** [hiroi-sora/Umi-OCR#495]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

文字版pdf识别率 非常高。但是目前只能将pdf转成图片 在调用接口。识别率打折扣。希望能加上pdf识别接口。希望作者大佬能考虑一下。先上这个功能。

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/397

**Comment by hiroi-sora** [comment]
最新测试版中，已支持PDF识别接口。

https://github.com/hiroi-sora/Umi-OCR/releases
