### ISSUE TITLE
不支持Win7，验证所有版本无法运行

### ISSUE THREAD

**Issue by 976465669** [hiroi-sora/Umi-OCR#496]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

问题：Win7所有版本无法运行，测试未通过，希望直接沟通
公司预赞助定制解决，请联系15319419526

**Comment by hiroi-sora** [comment]
你好。

1. 请提供一个你们的邮箱。
2. 你们最常用的Win7版本，请将镜像打包一下，之后发给我，我可以帮你们调查一下。

**Comment by 976465669** [comment]
您好。

1、邮箱976465669@qq.com
2、常用操作系统如下（镜像文件地址已附，烦请调查，不胜感激）
#windows_server_2008_r2
ed2k://|file|cn_windows_server_2008_r2_standard_enterprise_datacenter_and_web_with_sp1_x64_dvd_617598.iso|3368839168|D282F613A80C2F45FF23B79212A3CF67|/

#windows7旗舰版6.1.7601
ed2k://|file|cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso|3420557312|B58548681854236C7939003B583A8078|/

**Comment by hiroi-sora** [comment]
OK，我已在下载。

我可能需要数日来调查，请耐心等待。如果得到了具体的解决方案，我会在这个Issue中回复你。如果需要进一步交流，我再会通过邮件联系你。

**Comment by 976465669** [comment]
您好，非常感谢，以上两个镜像，升级补丁已正常使用，验证如下
-Windows 7 旗舰版：VC+KB2533623
-Womdws Server 2008 SP2：VC+KB2533623+opengl32sw_64

**Comment by 976465669** [comment]
您好，非常感谢，以上两个镜像，升级补丁已正常使用，验证如下
-Windows 7 旗舰版：VC+KB2533623
-Womdws Server 2008 SP2：VC+KB2533623+opengl32sw_64
效果如下
![server2008sp2](https://github.com/hiroi-sora/Umi-OCR/assets/33680852/bbe92b64-8eac-419f-8056-955053646171)
![win7u](https://github.com/hiroi-sora/Umi-OCR/assets/33680852/3cbcf5ca-9c78-4cf2-b1dd-e811e23c150c)
