### ISSUE TITLE
windows 2008 各种dll补丁打完后报错提示

### ISSUE THREAD

**Issue by paulizam** [hiroi-sora/Umi-OCR#499]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

windows 2008r2

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

![图片](https://github.com/hiroi-sora/Umi-OCR/assets/18679484/8568de17-331f-4db1-871d-f7089f5f0ea7)

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![图片](https://github.com/hiroi-sora/Umi-OCR/assets/18679484/3940ae14-9ece-4d53-94e5-07dcafcbfa4d)

**Comment by hiroi-sora** [comment]
CPU不兼容，请换用[Rapid版本](https://github.com/hiroi-sora/Umi-OCR/releases/tag/v2.1.1)。
