### ISSUE TITLE
全屏长图怎么处理？

### ISSUE THREAD

**Issue by lwstudy** [hiroi-sora/Umi-OCR#5]
![image](https://user-images.githubusercontent.com/58960791/178916688-f3e8acbc-764a-406d-9fb0-fa83d8706b43.png)
全屏长图怎么办？这放进来，分辨率直接没法识别

**Comment by hiroi-sora** [comment]
> 全屏长图怎么处理

实际上应该拆分为两个问题：超大分辨率图片如何添加忽略区域？超大分辨率图片如何准确地识别？

### 1. 超大分辨率图片如何添加忽略区域？

答：很遗憾，忽略区域窗口的UI不支持滚动，所以目前可能难以操作。未来有可能改善这个功能。

### 2. 超大分辨率图片如何准确地识别文字？

可能你也发现了，直接将超大图片扔处理列表转文字，效果奇差，甚至一个文字都转不出来。这是因为 为了提高效率，PaddleOCR预先将长度超标的图片进行压缩，再执行文字识别。想临时关闭这个功能，只需将`PaddleOCR_json_config.txt`中的`max_side_len  960`改写到比较大的数（要处理的图片的高度）即可。不过，处理完图片后，最好将参数改回来，否则以后处理正常尺寸图片时会很慢。

或者可以参照下面的步骤生成一个专门应对大图片的识别器：

1. 复制一份PaddleOCR_json.exe，重命名为`PaddleOCR_json_大分辨率.exe`。复制一份PaddleOCR_json_config.txt，重命名为`PaddleOCR_json_大分辨率_config.txt`。
2. 将`PaddleOCR_json_大分辨率_config.txt`中的max_side_len一行改为`max_side_len  7000`。
3. 打开Umi-OCR软件，转到设置，将识别器路径改为`PaddleOCR-json\PaddleOCR_json_大分辨率.exe`。
4. 正常导入大分辨率图片并识别即可。

![16577831063401.png](https://tupian.li/images/2022/07/14/16577831063401.png)

![1657783221440.png](https://tupian.li/images/2022/07/14/1657783221440.png)

**Comment by lwstudy** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/5#issuecomment-1184088016
