### ISSUE TITLE
orc里面没有output_separate_txt文件

### ISSUE THREAD

**Issue by XUE-ZHI-JUN** [hiroi-sora/Umi-OCR#50]
![image](https://user-images.githubusercontent.com/61927351/200466254-28bd0adc-c75c-4257-a7b0-5737c73157aa.png)

**Comment by hiroi-sora** [comment]
抱歉，忘了git add
现在已经补上了。

**Comment by XUE-ZHI-JUN** [comment]
![image](https://user-images.githubusercontent.com/61927351/200484138-cb41aa3c-4494-47f5-abc9-d76c912277a6.png)
请问一下，我如何传入一张图片进去，而不是图片地址了？

**Comment by hiroi-sora** [comment]
> 如何传入一张图片进去

你是指直接从内存传一份图像数据进去么？

目前引擎只支持两种读取图片方式：读本地文件，读剪贴板。如果你想不经过硬盘，直接内存传图，可以用剪贴板作为中转。

见 https://github.com/hiroi-sora/PaddleOCR-json

**Comment by XUE-ZHI-JUN** [comment]
是的。我看剪贴板好像传递的是clipboard字符串。目前我想通过内存去传入图片

**Comment by XUE-ZHI-JUN** [comment]
你好。请问一下方向判别的返回值在哪里呀？我似乎没有找到

**Comment by hiroi-sora** [comment]
识别出的文字的方向吗？引擎组件的接口没有这个返回值。只有设置是否启用方向分类器的接口。
