### ISSUE TITLE
批量OCR功能识别PNG图片报错203提示

### ISSUE THREAD

**Issue by liubeisi** [hiroi-sora/Umi-OCR#501]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11

### Reproduction steps 复现步骤

上传了这两张图片
![公文写作金句0](https://github.com/hiroi-sora/Umi-OCR/assets/31694555/6ff4f62b-997d-4a17-8244-c913a39a20d1)
![公文写作金句1](https://github.com/hiroi-sora/Umi-OCR/assets/31694555/a99d180b-a773-4ec8-b36f-ce9387de4eec)使使用批量OCR功能报错203

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![image](https://github.com/hiroi-sora/Umi-OCR/assets/31694555/948ea9dc-f931-487b-9ce4-0e6a1b9aa750)

**Comment by hiroi-sora** [comment]
我测试了一下，这两张图片的编码并不是png，可能是webp的一种变体，引擎无法解码。

你可以用第三方工具，比如 [这个](https://convertio.co/zh/) ，将所有图片转换为标准png编码，再进行OCR。

**Comment by liubeisi** [comment]
感谢大佬回复！

已经解决了。后面还有同学遇到这个问题，请强制把看起来是PGN格式的换成PGN，可以解决这个问题。

再次谢谢开发者
