### ISSUE TITLE
OCR init fail

### ISSUE THREAD

**Issue by Luohui109** [hiroi-sora/Umi-OCR#509]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

WIN10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

下载，解压，运行，投入图片，执行

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 2, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}
![微信截图_20240508163352](https://github.com/hiroi-sora/Umi-OCR/assets/50389484/579d685a-5c1a-4301-979d-6c03066fb38a)

**Comment by hiroi-sora** [comment]
可能是CPU兼容性问题，请换用 Rapid版本 。

https://github.com/hiroi-sora/Umi-OCR/releases/tag/v2.1.1

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/dcd934b0-7035-4f42-8678-3aa2e93d6242)

**Comment by STARS7yao** [comment]
重置设置
