### ISSUE TITLE
哪位大佬开发一下HTTP功能

### ISSUE THREAD

**Issue by liuyunfei666** [hiroi-sora/Umi-OCR#51]
我想服务器上调用,不会PC语言太痛苦了!!!

**Comment by hiroi-sora** [comment]
你是想部署到自己服务器的话，不妨了解一下隔壁的：
[TrWebOCR](https://github.com/alisen39/TrWebOCR)
[RapidOCR/ocrweb](https://github.com/RapidAI/RapidOCR/tree/main/ocrweb)
[RapidOCRServer](https://github.com/Physton/RapidOCRServer)

**Comment by liuyunfei666** [comment]
> 你是想部署到自己服务器的话，不妨了解一下隔壁的： [TrWebOCR RapidOCR](https://github.com/alisen39/TrWebOCR)[/ocrweb](https://github.com/RapidAI/RapidOCR/tree/main/ocrweb) [RapidOCRServer](https://github.com/Physton/RapidOCRServer)

感谢感谢!
