### ISSUE TITLE
无法使用python main.py启动环境

### ISSUE THREAD

**Issue by FnTop** [hiroi-sora/Umi-OCR#514]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

lastest

### Windows version 系统版本

win11

### Reproduction steps 复现步骤
已经安装了PySide2

![图片](https://github.com/hiroi-sora/Umi-OCR/assets/43026579/67fb41fe-e2d8-4202-9c09-cdb419f7f36b)
![图片](https://github.com/hiroi-sora/Umi-OCR/assets/43026579/2256d2da-56bb-46a8-b5f7-0ad1623347d4)

**Comment by hiroi-sora** [comment]
你好，请仔细阅读Readme-[构建项目](https://github.com/hiroi-sora/Umi-OCR?tab=readme-ov-file#%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE)。
