### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Fan-Xiao1** [hiroi-sora/Umi-OCR#518]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11、

### Reproduction steps 复现步骤

[Error] OCR init fail. Argd: {'enable_mkldnn': True, 'cpu_threads': 16, 'config_path': 'models/config_chinese.txt', 'cls': False, 'use_angle_cls': False, 'limit_side_len': 960}

**Comment by hiroi-sora** [comment]
有没有伴随着 `0xc0000142` 的报错弹窗？如果有的话，见 [FAQ](https://github.com/hiroi-sora/Umi-OCR/issues/447) 。

或者，更换使用 [Umi-OCR_Rapid](https://github.com/hiroi-sora/Umi-OCR/releases) 试试。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/0df90a17-f531-4817-a000-bbf680e114a8)
