### ISSUE TITLE
{"code": 902, "data": "子进程已崩溃。", "time": 0.0, "timestamp": 1716539054.833477}

### ISSUE THREAD

**Issue by peng-poso2o** [hiroi-sora/Umi-OCR#519]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

Umi-OCR_Paddle_v2.1.1

### Windows version 系统版本

win server 2022

### Reproduction steps 复现步骤

CPU和内存性能差会容易出现！有没有相关日志可查？

**Comment by hiroi-sora** [comment]
Paddle版是会占用大量CPU和内存资源的。而 Rapid 版对性能要求没那么高，内存占用会保持在较低的水平。

对于低配置电脑，请更换使用 [Umi-OCR_Rapid](https://github.com/hiroi-sora/Umi-OCR/releases) 试试。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/0df90a17-f531-4817-a000-bbf680e114a8)

**Comment by Xmug** [comment]
建议用Rapid引擎，paddle最大的缺点是支持的图片长度没Rapid长

**Comment by zyjdmmm** [comment]
渣机受害者，啊
