### ISSUE TITLE
能否添加OCR扫描版pdf文档功能

### ISSUE THREAD

**Issue by githubmango0509** [hiroi-sora/Umi-OCR#52]
现实操作中，除了直接操作图片外，也有不少扫描过的pdf文档，不能直接提取文字。需要先转化成图片再OCR。如果能在打开文件夹选取图片时多加一个pdf类型，并在开始任务时自动先转化成临时同名图片文件，任务完成后再自动删除临时图片文件，那就厉害了！这个建议可能有点过高，作者量力而行就是了，谢谢！

**Comment by hiroi-sora** [comment]
已有识别pdf的计划，预计在未来的大版本中作为开发重点。当前大版本还待解决一些历史遗留问题。我近期也比较忙，暂时没有开发大型新功能的精力。

> 开始任务时自动先转化成临时同名图片文件

这样处理最简单，甚至在当前大版本的框架内加上也未尝不可。
我是希望做的话做得更好，内存传图，输出还原排版的word/pdf，忽略水印，都安排上。

**Comment by githubmango0509** [comment]
支持作者的思路，期待更完美的作品，辛苦了！

**Comment by jusanyuan** [comment]
太期待了，'这样处理最简单，甚至在当前大版本的框架内加上也未尝不可。
但我是希望做的话做得更好，内存传图，输出还原排版的word/pdf，忽略水印，都安排上。"

**Comment by jusanyuan** [comment]
太期待了

**Comment by hiroi-sora** [comment]
v2.1.0 测试版 已支持PDF识别。

https://github.com/hiroi-sora/Umi-OCR/releases
