### ISSUE TITLE
文字识别时，电脑画面瞬间变模糊

### ISSUE THREAD

**Issue by mmdg1314** [hiroi-sora/Umi-OCR#521]
作者大大，不知道是我电脑的原因还是怎么回事，只要一截图，屏幕就会自动变模糊，文字识别完成以后又恢复正常了

**Comment by hiroi-sora** [comment]
请问你用的是 Umi-OCR 什么版本？截图屏幕模糊是 v1 版本的毛病，按理说 v2 不存在该问题。

**Comment by mmdg1314** [comment]
嗯嗯是的，我下载了一下新版本，没有这个问题了，感谢哈，大大辛苦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月26日(星期天) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hiroi-sora/Umi-OCR] 文字识别时，电脑画面瞬间变模糊 (Issue #521)














 
请问你用的是 Umi-OCR 什么版本？截图屏幕模糊是 v1 版本的毛病，按理说 v2 不存在该问题。
