### ISSUE TITLE
启动程序时弹窗报错：ModuleNotFoundError: No module named 'py_src.tag_pages.QRCode'

### ISSUE THREAD

**Issue by blackandwhite996** [hiroi-sora/Umi-OCR#522]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

解压后运行有该报错，改为2.1.0版本正常

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

<img width="340" alt="Snipaste_2024-05-27_01-26-00" src="https://github.com/hiroi-sora/Umi-OCR/assets/131672144/f80d1c45-73a3-42e0-a5a1-71902925c6c9">

**Comment by AlexS0914** [comment]
2尝试了一下，2.0+版本解压后双击exe无反应，打不开。但是1.+版本可以正常打开。不知是何原因？
是否是CPU兼容性的原因，2.0+版本在intel的电脑可以打开，但是在国产cpu如兆芯开先打不开（paddle和rapid都打不开）

**Comment by hiroi-sora** [comment]
> 但是在国产cpu如兆芯开先打不开（paddle和rapid都打不开）

很有可能是CPU兼容性问题。v2.0+版本使用了很多新的第三方库，它们的运行库可能是平台敏感的，在不同平台上需要重新编译。或者它们依赖于一些系统组件，在国产CPU平台上默认没有安装，导致了依赖缺失的问题。

您可以尝试安装 python 3.8.10 （下方链接），看看安装过程中是否会出现报错。据我的经验，如果 Umi-OCR 打不开（没有任何反应、报错都没有），可能是卡在第一步：连python解释器都没能跑起来。那么，很可能安装 python 3.8 时会报错。根据报错修复问题后， Umi 也能正常运行了。

https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe

**Comment by blackandwhite996** [comment]
> > 启动程序时弹窗报错：ModuleNotFoundError： No module named 'py_src.tag_pages.QRCode'启动程序时弹窗报错：ModuleNotFoundError：没有模块名为'py_src.tag_pages.二维码'
> 
> 此问题似乎是二维码 QRCode 模块或者标签页控制连接器引起的。不过我重新审查了 v2.1.1 和 v2.1.0 相关代码，暂时没有发现不妥当的地方。也有可能是别的相关模块或第三方库存在问题，间接导致了该报错。
> 
> 这错误感觉比较玄学，也只有你这一例报错，目前我无法判断具体原因。如果别的用户有类似情况，请在本Issue下回复，补充更多信息。
> 
> 你可以尝试：
> 
> * 确保下载的 v2.1.1 压缩包是正确的。检查sha256是否为 。`53e144b07c3ddfc1038e16926912de75c8212840c84cd56713f9e93ecc22e753`
> * 如果 v2.1.0 可以运行，那么在相同路径下解压放置 v2.1.1 ，尝试能否运行。
> * 如果 v2.1.0 可以运行，那么下载 v2.1.1 的纯源码包（下面链接），将 其中的 目录，解压、覆盖粘贴到 v2.1.0 的相同路径下，即增量更新为 v2.1.1 。看看增量更新后能否正常运行。`UmiOCR-data`
> 
> https://github.com/hiroi-sora/Umi-OCR/archive/refs/heads/release/2.1.1.zip

已尝试，上述方法，运行依旧显示
![image](https://github.com/hiroi-sora/Umi-OCR/assets/131672144/5557e5ef-60d5-41a1-8934-f2ba2be3e511)

**Comment by AlexS0914** [comment]
> > 但是在国产cpu如兆芯开先打不开（paddle和rapid都打不开）
> 
> （这个问题与楼主的 QRCode 问题无关）
> 
> 很有可能是CPU兼容性问题。v2.0+版本使用了很多新的第三方库，它们的运行库可能是平台敏感的，在不同平台上需要重新编译。或者它们依赖于一些系统组件，在国产CPU平台上默认没有安装，导致了依赖缺失的问题。
> 
> 您可以尝试安装 python 3.8.10 （下方链接），看看安装过程中是否会出现报错。据我的经验，如果 Umi-OCR 打不开（没有任何反应、报错都没有），可能是卡在第一步：连python解释器都没能跑起来。那么，很可能安装 python 3.8 时会报错。根据报错修复问题后， Umi 也能正常运行了。
> 
> https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe

Python竟然安装成功了，神奇。。但是2.0+还是打不开

**Comment by hiroi-sora** [comment]
@AlexS0914 如果2.0+运行`UmiOCR-data`目录中的`RUN_CLI.bat`，有反应吗

**Comment by blackandwhite996** [comment]
> > 启动程序时弹窗报错：ModuleNotFoundError: No module named 'py_src.tag_pages.QRCode'
> 
> 此问题似乎是二维码 QRCode 模块或者标签页控制连接器引起的。不过我重新审查了 v2.1.1 和 v2.1.0 相关代码，暂时没有发现不妥当的地方。也有可能是别的相关模块或第三方库存在问题，间接导致了该报错。
> 
> 这错误感觉比较玄学，也只有你这一例报错，目前我无法判断具体原因。如果别的用户有类似情况，请在本Issue下回复，补充更多信息。
> 
> ---
> 
> 你可以尝试：
> - 确保下载的 v2.1.1 压缩包是正确的。检查sha256是否为 `53e144b07c3ddfc1038e16926912de75c8212840c84cd56713f9e93ecc22e753` 。
> - 如果 v2.1.0 可以运行，那么在相同路径下解压放置 v2.1.1 ，尝试能否运行。
> - 如果 v2.1.0 可以运行，那么下载 v2.1.1 的纯源码包（下面链接），将 其中的`UmiOCR-data` 目录，解压、覆盖粘贴到 v2.1.0 的相同路径下，即增量更新为 v2.1.1 。看看增量更新后能否正常运行。
> 
> https://github.com/hiroi-sora/Umi-OCR/archive/refs/heads/release/2.1.1.zip

我最近试了最新版的版本，报错情况相同，不过使用另外的rapid版本可以正常运行出来

**Comment by hiroi-sora** [comment]
> 我最近试了最新版的版本，报错情况相同，不过使用另外的rapid版本可以正常运行出来

你的意思是，用 v2.1.2 Rapid 版本可以正常运行吗？

**Comment by blackandwhite996** [comment]
> > 我最近试了最新版的版本，报错情况相同，不过使用另外的rapid版本可以正常运行出来
> 
> 你的意思是，用 v2.1.2 Rapid 版本可以正常运行吗？

是啊，另外那个版本报的还是同样的错，我系统是Win11的，系统安装的Python是3.12的

**Comment by xianggithubli** [comment]
2.10可以运行，但2.11和2.12 paddle版本都不能运行 rapid版本没试过

**Comment by hiroi-sora** [comment]
在最新发布的 [v2.1.3 beta.1](https://github.com/hiroi-sora/Umi-OCR/releases) 版本，我用了以前 v2.1.0 相同的第三方库来打包，理论上兼容性与 v2.1.0 是一样的。大家可以尝试一下，新版本是否还会有 ModuleNotFoundError 的问题。

**Comment by blackandwhite996** [comment]
> 在最新发布的 [v2.1.3 beta.1](https://github.com/hiroi-sora/Umi-OCR/releases) 版本，我用了以前 v2.1.0 相同的第三方库来打包，理论上兼容性与 v2.1.0 是一样的。大家可以尝试一下，新版本是否还会有 ModuleNotFoundError 的问题。

确实可以运行出来了

**Comment by masterjian** [comment]
@hiroi-sora 
我来说几句。
之前一直都是覆盖安装，从2.1.0升级到2.1.4的时候，再次覆盖安装，然后就出现了这个issue中的一样的错误。
然后，重新解压到新文件夹，直接双击运行。没有问题。

所以，是不是覆盖安装时，某些被移除的模块被“残留”了下来导致的。
