### ISSUE TITLE
希望HTTP接口中加入忽略区域或者指定识别的区域

### ISSUE THREAD

**Issue by wahsonG** [hiroi-sora/Umi-OCR#525]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

在/api/ocr接口中，加入指定识别的区域参数，在识别的时候只识别该区域。

**Comment by hiroi-sora** [comment]
建议收到 √

**Comment by wahsonG** [comment]
能否加上去除水印功能？作者大大

**Comment by hiroi-sora** [comment]
如果你指的是对图片操作、抹除图片中的水印，这并不在Umi的设计范围以内，还是使用别的专业图像编辑软件比较好呢。

**Comment by wahsonG** [comment]
了解，谢谢大佬回复

**Comment by wahsonG** [comment]
作者大大，HTTP协议里面，要确定指定识别区域，参数说明有吗？

**Comment by wahsonG** [comment]
有没有可能优化一下？

**Comment by hiroi-sora** [comment]
> 有没有可能优化一下？

Umi-OCR 项目本身不训练和微调模型库。我们提供一个OCR引擎到用户的桥梁。

目前，Paddle系列模型库已经是开源领域内精度最好的OCR模型（尤其对简体中文）。我们会持续跟踪Paddle的更新，并寻找更多优秀的开源OCR项目，让其作为 Umi 的识别引擎组件。

未来，我们也会支持腾讯、百度等商业在线OCR服务，它们在复杂情景中也许能提供更好的精度。

**Comment by wahsonG** [comment]
谢谢大佬的答复
