### ISSUE TITLE
作者声称永久免费，可是我看好像有人倒卖收费呢

### ISSUE THREAD

**Issue by bairihai** [hiroi-sora/Umi-OCR#526]
我在b站看到视频介绍，被引流到[某网站](https://buyanbuyan.com/thread-3698.htm)，发现要收费注册。

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/216

首先，作者不是跟它们一伙的哈，Umi是真的不收费。

利用开源项目盈利的人太多了。独立开发者个人很难有限制手段。

不过，大家的行动可以助力净化网络环境。二道贩子利用了信息差。大家可以在合适的地方（评论区/弹幕）宣传一下正确的下载使用渠道，打破信息差。（当然，有些贩子也会删评。那也没有办法）

Umi-OCR 蓝奏云免注册下载： https://hiroi-sora.lanzoul.com/s/umi-ocr
