### ISSUE TITLE
可以过滤图片中的文本吗？只需要文字周边是空白的！

### ISSUE THREAD

**Issue by peng-poso2o** [hiroi-sora/Umi-OCR#527]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

![image](https://github.com/hiroi-sora/Umi-OCR/assets/47685488/b242f7ca-477d-4ede-b9b8-7abe0df7343f)

**Comment by hiroi-sora** [comment]
如果你指的是在OCR得到的识别结果中，不出现 指定范围内的文字，那么可以使用我们的`忽略区域功能。详见Readme的说明。

如果你指的是对图片操作、抹除图片中的文字，这并不在Umi的设计范围以内，还是使用别的专业图像编辑软件比较好呢。
