### ISSUE TITLE
很好的软件！作者大大可以增加一个“直接替换原目录文件”的功能吗？

### ISSUE THREAD

**Issue by Kichony** [hiroi-sora/Umi-OCR#528]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

您好！出于工作要求，我们需要将双层转换过后的新PDF直接替换掉原来的单层旧PDF，之前我们是使用的破解版的福昕PDF，不仅破解过程繁琐，并且双层转换操作繁杂且有bug，并且也不能直接转换多个文件夹内的所有pdf，今天在52看到了作者大大的软件，使用后OCR准确率可以完全达到预期！唯一美中不足的就是只能生成layered后缀的新文件，请问作者大大是否可以增加一个“替换原同名文件”的功能，如果可以的话，作者大大是否可以留个联系方式，帮我们单位单独定制OCR的软件，我的微信是oyoyoy0730，费用不是问题，都可以直接开票报销，谢谢作者大大

**Comment by hiroi-sora** [comment]
简单的小功能，帮你写了。

[Umi-OCR v2.1.1 定制组件：双层PDF允许覆盖原文件.zip](https://github.com/hiroi-sora/Umi-OCR/files/15496614/Umi-OCR.v2.1.1.PDF.zip)

该版本中，双层PDF不会带有 `layered` 的后缀，并且覆盖原文档时不会出现占用冲突错误。

使用方法：
1. 下载、解压 上述压缩包，将 `UmiOCR-data` 整个文件夹 粘贴到 Umi-OCR v2.1.1 目录中，覆盖原本的内容。
2. 【建议】 批量文档标签页的设置中，选择 **保存到**、**指定目录** ，以免原文档被覆盖。（或者，在操作之前，自己手动备份好原文档。）

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/506320e6-76f1-4bac-93a0-37ebc7b62df9)

**Comment by Kichony** [comment]
好的，感谢大大！

**Comment by Kichony** [comment]
好的，感谢大大！因为我们单位所有数据已经被备份至移动硬盘且都已异地备份，所以我们在服务器端只需要直接双层转换pdf替换服务器上的数据即可，再次感谢啦~

**Comment by OOOOccasionally** [comment]
作者大大，保存到指定目录，可以让PDF按照图片的目录结构保存吗
