### ISSUE TITLE
大佬请教一下如何提高英文识别效果

### ISSUE THREAD

**Issue by Fern43nd0** [hiroi-sora/Umi-OCR#53]
目前正在使用1.3.0版本配合纯英v3 rec模型，目前识别的格式较为单一，以英文、符号为主，偶有数字，目前效果不错。
但是有个问题是在单个识别的情况下容易漏字符，比如逗号容易识别不到、“&”识别成“8”之类的错误比较常见，但是批量识别的情况下错误几率会低很多。
想请教下这种情况怎么可以改善一下？麻烦大佬有时间帮忙解答一下我的疑惑，谢谢。

**Comment by Fern43nd0** [comment]
[https://imgse.com/i/xzoj2Q](url)
这里上传不了图片，只好用图床了。
左侧是单个识别结果，右侧是批量识别的效果。

**Comment by hiroi-sora** [comment]
> 单个识别的情况下容易漏字符，但是批量识别的情况下错误几率会低很多

单个识别是指截屏吗？如果对**同一个图像**，截屏和导入批量识别的准确度不一致；是不是截屏的选区太小了（刚刚好框住文本）？尝试适当加大选区范围，文字边缘多留一些空白。

> 逗号容易识别不到

毕竟OCR是有局限的，机器不能像人一样从上下文推断，仅从图像本身不容易区分一个小点是符号还是污渍，所以对点状符号的缺漏会多一些。

> “&”识别成“8”之类

如果大批量识别 有这个问题的话，可以考虑把结果的文本再处理一下，高亮出所有 [字母+8] 的组合查找替换。或者上正则表达式。

**Comment by Fern43nd0** [comment]
> > 单个识别的情况下容易漏字符，但是批量识别的情况下错误几率会低很多
> 
> 单个识别是指截屏吗？如果对**同一个图像**，截屏和导入批量识别的准确度不一致；是不是截屏的选区太小了（刚刚好框住文本）？尝试适当加大选区范围，文字边缘多留一些空白。
> 
> > 逗号容易识别不到
> 
> 毕竟OCR是有局限的，机器不能像人一样从上下文推断，仅从图像本身不容易区分一个小点是符号还是污渍，所以对点状符号的缺漏会多一些。
> 
> > “&”识别成“8”之类
> 
> 如果大批量识别 有这个问题的话，可以考虑把结果的文本再处理一下，高亮出所有 [字母+8] 的组合查找替换。或者上正则表达式。

刚刚测试了一下，的确如您所说，单个识别时截屏选区太小导致准确度低，留白多了之后跟批量检测的效果一致了，感谢！
