### ISSUE TITLE
固定区域OCR和其他OCR

### ISSUE THREAD

**Issue by Oplay66** [hiroi-sora/Umi-OCR#532]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

请问可以添加固定区域OCR和添加windowsOCR吗？

**Comment by hiroi-sora** [comment]
> 固定区域OCR

目前，可通过 **重复截图** 功能（截图OCR标签页 → 设置 → 快捷键 → 重复截图）来实现简单的固定区域OCR。触发该快捷键时，会重复截取上一次截图的区域进行识别。

下个版本，将可以通过命令行传入屏幕坐标进行固定区域识别。

> Windows OCR

Windows 自带的 OCR 的精度并不高，配置起来也不算简单（可能需要在系统设置中下载目标语言的识别包），所以 Umi 目前并没有使用该接口。

有需要的开发者可以使用它 自行开发 [Umi-OCR 插件](https://github.com/hiroi-sora/Umi-OCR_plugins) 。
