### ISSUE TITLE
Umi-OCR_Rapid版，没有内存清理功能？

### ISSUE THREAD

**Issue by xiaolongzhuanshi** [hiroi-sora/Umi-OCR#533]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

请问Umi-OCR_Rapid版，没有内存清理功能吗？如果想要和Paddle版一样定时清理需要怎么做？

**Comment by hiroi-sora** [comment]
PaddleOCR 引擎在 mkldnn加速库启用的情况下有缺陷，引擎本身不会回收内存，会越占越多。所以我在外部写了一套内存管理机制，根据空闲时间和占用量，强制释放当前进程占用的内存，保障用户正常使用。

而Rapid引擎，本身的内存管理功能是正常的，会自动释放内存，因此无需外部控制的手段。此外，Rapid的内存占用量也比Paddle低很多，识别速度比Paddle慢一点。如果是低配置电脑的用户，建议选择Rapid版本。

**Comment by xiaolongzhuanshi** [comment]
好的谢谢回答，我是因为想放后台调用，不想平时没事就有个占200多M的服务放在那里。
现在的话，我就在外面做个监控服务然后用python直接调用[RapidOCR-json](https://github.com/hiroi-sora/RapidOCR-json)的接口，有调用的时候就实例化这个引擎。闲时就关闭这个引擎，这样就能实现我的需求。
非常感谢大佬的OCR-json引擎封装，很好用
