### ISSUE TITLE
无法识别文本框内的数字

### ISSUE THREAD

**Issue by WMMWW** [hiroi-sora/Umi-OCR#534]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

1.打开软件
2.截图OCR（请查看附件）
3.识别
4.查看结果（内容缺失）

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![issue](https://github.com/hiroi-sora/Umi-OCR/assets/90370680/b33e11fe-3fd0-47df-9542-7b272d62da9d)

**Comment by hiroi-sora** [comment]
你好。当文本周围有外框时，会干扰通用OCR模型的提取和识别。对于这种特殊情景，需要针对性的训练OCR模型。

如果您有大批量的该类图片识别需求，并且具有一定技术和硬件，可参考 [https://github.com/PaddlePaddle/PaddleOCR](PaddleOCR) 仓库，自行训练模型并导入 Umi-OCR 中使用。
