### ISSUE TITLE
OCR API 列表中不存在

### ISSUE THREAD

**Issue by wendingming** [hiroi-sora/Umi-OCR#537]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.0

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

下载了源代码以后运行时错误，请问是什么情况

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![111](https://github.com/hiroi-sora/Umi-OCR/assets/35925537/7c5fb8fb-474d-45a6-85c9-cd2d94515522)

**Comment by hiroi-sora** [comment]
## OCR API列表不存在

你的部署流程漏了一步：放置OCR引擎插件。请前往 [插件库](https://github.com/hiroi-sora/Umi-OCR_plugins) 下载任意一个OCR引擎插件，放置到 `UmiOCR-data\plugins` 目录下。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/9de0a73d-4f64-473c-9eb9-8585cb59d038)

请确保目录结构如下图所示。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/6739a0e8-29d0-49d9-bfad-85031c49cd0e)
