### ISSUE TITLE
截图后闪退

### ISSUE THREAD

**Issue by cherub0507** [hiroi-sora/Umi-OCR#541]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2

### Windows version 系统版本

win 11 pro 23H2

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

启动程序，截图识别，转两个圈就闪退，进程中已经没有程序

请教如何解决

**Comment by cherub0507** [comment]
https://github.com/hiroi-sora/Umi-OCR/assets/58015207/1915b357-b83d-4996-a335-0470cf9a0fe5

**Comment by hiroi-sora** [comment]
请问截图以外的方式，比如粘贴图片、拖入图片、PDF识别等，可以正常使用吗？

**Comment by cherub0507** [comment]
> 请问：
> 
> 1. 截图以外的方式，比如粘贴图片、拖入图片、PDF识别等，可以正常使用吗？
> 2. 您电脑有几个显示器？

点醒我了……果然是外接显示器的原因

移除后一切功能正常

感谢感谢！！！

**Comment by hiroi-sora** [comment]
> 果然是外接显示器的原因，移除后一切功能正常

Umi-OCR 是支持多显示器的，我平时也挂着3个显示器在使用。

不过，如果显示器存在一些 非标准的属性或硬件信息，有可能导致 Umi 截图时调用出错。

如果有能力的用户，遇到了类似问题，可尝试 [通过源码部署](https://github.com/hiroi-sora/Umi-OCR?tab=readme-ov-file#%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE) 本项目，并重点检查以下的函数：
- `UmiOCR-data\py_src\image_controller\screenshot_controller.py` - `def getScreenshot(self, wait=0)`
- `UmiOCR-data\qt_res\qml\ImageManager\ScreenshotManager.qml` - `function getGrabList()`

如果有人发现了问题根源或解决了本问题，欢迎交流或发PR，谢谢~

**Comment by cherub0507** [comment]
> > 果然是外接显示器的原因，移除后一切功能正常
> 
> Umi-OCR 是支持多显示器的，我平时也挂着3个显示器在使用。
> 
> 不过，如果显示器存在一些 非标准的属性或硬件信息，有可能导致 Umi 截图时调用出错。
> 
> 有能力的用户，遇到了类似问题，可尝试 [通过源码部署](https://github.com/hiroi-sora/Umi-OCR?tab=readme-ov-file#%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE) 本项目，并重点检查以下的函数：
> 
> * `UmiOCR-data\py_src\image_controller\screenshot_controller.py` - `def getScreenshot(self, wait=0)`
> * `UmiOCR-data\qt_res\qml\ImageManager\ScreenshotManager.qml` - `function getGrabList()`
> 
> 如果有人发现了问题根源或解决了本问题，欢迎交流或发PR，谢谢~

![微信截图_20240604153944](https://github.com/hiroi-sora/Umi-OCR/assets/58015207/07740b76-0dcc-4568-88fd-5a49da201535)

![微信截图_20240604153927](https://github.com/hiroi-sora/Umi-OCR/assets/58015207/c1044298-6f52-4841-a898-cfd7257821e0)

显示器信息供参考

我尝试调整主显示器的刷新率为60Hz，但是一样闪退

猜测是不是外接显示器分辨率低于主显示器的原因

**Comment by hiroi-sora** [comment]
看起来，你是笔记本内屏通过核显转接，外屏独显直连，也许跟这个有关系。

你试试单独使用任意一个显示器（Win+P，选择仅电脑或仅第二屏幕），是否能正常截图

**Comment by cherub0507** [comment]
Win+P，选择 仅电脑屏幕 或 仅第二屏幕，都正常

全局设置改为 关闭硬件加速，所有功能测试正常

非常感谢耐心解答！

祝好！
