### ISSUE TITLE
可以设置为win系统服务方式启动吗？不需要进入桌面启动，只需要HTTP！

### ISSUE THREAD

**Issue by peng-poso2o** [hiroi-sora/Umi-OCR#548]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

可以设置为win系统服务方式启动吗？不需要进入桌面启动，只需要HTTP！

**Comment by xiaolongzhuanshi** [comment]
他有全局设置的，里面有个隐藏托盘图标，关闭后最小化到系统托盘，设置完后，把软件快捷键放到开机启动的文件夹下就可以实现你想要的效果

**Comment by hiroi-sora** [comment]
> 可以设置为win系统服务方式启动吗？不需要进入桌面启动，只需要HTTP！

可以实现开机自启、静默启动不显示主窗口，在全局设置里能看到。

> 把软件快捷键放到开机启动的文件夹下

全局设置里点一下开关就能设置开机启动了，无需手动放置快捷方式。
