### ISSUE TITLE
umi程序作为api调用过程中出现：PaddleOCR-json.exe-应用程序错误

### ISSUE THREAD

**Issue by lgl8023** [hiroi-sora/Umi-OCR#552]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

UMI-OCR.exe运行正常。只是使用了umi 的 HTTP功能，但会不定时弹出异常

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![企业微信截图_17177566548516](https://github.com/hiroi-sora/Umi-OCR/assets/54259926/878b6f50-ec81-4458-8ea0-2fb27db93d9d)

**Comment by hiroi-sora** [comment]
也许是连续调用次数过多，电脑内存不足。内存＜4g的设备建议使用 Umi-OCR Rapid版本。

如果您仍要使用 Paddle 版本，可以取全局设置→左下角勾选**高级** → 右边拉到最下 → PaddleOCR板块 → 有个大概是“限制内存上限”的选项，将它设为你电脑总内存的2/3。这样可以确保内存不会爆满。

**Comment by lgl8023** [comment]
谢谢您！我的性能在32G, 所以暂时先考虑尝试限制内存上限。
