### ISSUE TITLE
自动截图

### ISSUE THREAD

**Issue by Oplay66** [hiroi-sora/Umi-OCR#553]
你好，请问范围自动截图是如何运作的？屏幕出现文字自动截图？小白如何使用？

**Comment by hiroi-sora** [comment]
1. 对于小白而言，使用“**重复截图**”功能更简单快捷。

如下图，请先设定一个重复截图快捷键，如 `win+alt+x` 。

然后，先按 `win+alt+c` 进行一次**常规截图**。后续再按 `win+alt+x` 时，就会**重复**上次截图的范围，进行自动截图识别。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/4a7bc826-a24c-416c-9066-11f54bb41258)

2. 命令行中的 [范围截图](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_CLI.md#ocr%E6%8C%87%E4%BB%A4) ，是给有经验的用户，通过命令行指令传入指定范围、自动进行截图识别。这样可以跟外部第三方软件或自己编写的脚本进行联动控制。需要用户熟悉命令行的操作。

3. Umi-OCR暂未支持 “屏幕出现文字自动截图” 的功能，必须手动触发截图（通过快捷键或命令行）。如果您确实需要这种功能，可以使用别的开源项目，如 [团子翻译机](https://github.com/PantsuDango/Dango-Translator) 。
