### ISSUE TITLE
win arm版本点击exe无反应

### ISSUE THREAD

**Issue by jiaokuniu** [hiroi-sora/Umi-OCR#555]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2

### Windows version 系统版本

win11

### Reproduction steps 复现步骤

win arm上运行rapid版本，解压后点击exe后鼠标转了一下圈然后就没反应了。

有看到说是x64系统，但微软应该会对基于x64的软件进行转译。

不知道是我的windows系统缺乏了什么库，还是目前仍不兼容win arm呢？

**Comment by hiroi-sora** [comment]
请尝试：运行 `UmiOCR-data`目录中的`RUN_CLI.bat` ，有什么反应？

如果没反应，回到上一级 `Umi-OCR` 目录，在此处打开终端或Powershell，输入`./umi-ocr` 回车。有什么反应？

**Comment by jiaokuniu** [comment]
感谢回复！

运行RUN_CLI.bat时候，提示Windows cannot find 'runtime/python.exe'. Make sure you typed the name correctly, and then try again.

在Umi-OCR目录终端输入./umi-ocr时，点击回车似乎没什么反应

**Comment by hiroi-sora** [comment]
请尝试：直接运行 `UmiOCR-data/runtime` 目录中的 `python.exe` ，有什么反应？

正常情况下，应该展开一个控制台可交互界面，显示如下内容：

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
>>>
```

如果没有看到这样的内容，说明 Python 3.8.10 x86-64 解释器无法在 Win11 ARM 系统中运行。可能需要从源码重新编译解释器，或者换用更新、原生支持ARM的Python发行包来适应。

另外，本项目依赖的一些第三方库，如 PySide2、PyMuPDF 等，也不一定兼容ARM系统，需要一些迁移调整工作。

**Comment by jiaokuniu** [comment]
hi, 运行python.exe后，正常展开了控制台：
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
>>>

**Comment by hiroi-sora** [comment]
> 运行python.exe后，正常展开了控制台

OK，那么在 UmiOCR-data 目录下，打开终端，输入下列指令，应该可以手动启动 Umi-OCR 。你试试：

```sh
runtime/python.exe main.py
```

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/f22c5c51-e7f6-47ab-94d6-6fe923d14f9b)

**Comment by jiaokuniu** [comment]
hi感谢！输入指令后，提示如下：
<img width="1181" alt="image" src="https://github.com/hiroi-sora/Umi-OCR/assets/77779310/9d05bb23-9bc8-4f63-a8e7-d2a874a629c8">
我按照终端提示的，输入.\runtime/python.exe，然后又跳出了控制台：
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
>>>
之后就没反应了

**Comment by hiroi-sora** [comment]
只是输入 `.\runtime/python.exe` 不够，后面要加上 `main.py` 哦。

尝试以下几个命令，总有一个是对的：
```sh
./runtime/python.exe main.py
```

```sh
./runtime/python.exe ./main.py
```

**Comment by jiaokuniu** [comment]
感谢回复！我在terminal里输了您提供的这两条指令，都是同样的问题：点击回车之后就没任何反应了

**Comment by hiroi-sora** [comment]
> 感谢回复！我在terminal里输了您提供的这两条指令，都是同样的问题：点击回车之后就没任何反应了

那么应该就是第三方库（如QT等）可能存在较严重的不兼容，导致运行时闪退。我手上没有 ARM 设备，无法测试和定位问题，抱歉。建议还是在 x86-64 平台上使用本软件。

如果您有一定的动手能力，可尝试 [Windows 开发环境部署](https://github.com/hiroi-sora/Umi-OCR_runtime_windows) ，这样可以检测得到更详细的信息（比如执行到哪一行代码时出错）。

**Comment by jiaokuniu** [comment]
好的，谢谢您耐心的回复！感谢开发这么优秀的工具
