### ISSUE TITLE
能否像python库一样引入umiOrc的功能

### ISSUE THREAD

**Issue by luoysuan** [hiroi-sora/Umi-OCR#556]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

大佬，希望将orc功能整合进程序中，就像python中引入一个依赖库一样就好，不想单独的再重新启动一个程序。这种能实现吗

### Approximate reference (optional) 近似的参考（可选）

如java的Tesseract，不过识别度感觉比较差

**Comment by hiroi-sora** [comment]
你要的功能，请移步隔壁 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 。
