### ISSUE TITLE
关于can't find python3.dll和任务异常弹窗后软件无法操作的问题

### ISSUE THREAD

**Issue by Kichony** [hiroi-sora/Umi-OCR#559]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.1

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

第一个问题是，在进行批量文档OCR时，会出现如图的异常弹窗，弹窗内的文档不会被OCR识别，且多个弹窗点击确认之后整个软件表面变黑，且后续无法进行操作，只能退出软件后才能重新操作，使用场景是在 OCR局域网内共享的文件，且已经设置可读可写的权限，目前几百个文档会有几个是这样的，不是很清楚原因
![IMG_9978](https://github.com/hiroi-sora/Umi-OCR/assets/49964525/4a76179e-b710-41ed-82f3-87e3daf54b97)
![IMG_9979](https://github.com/hiroi-sora/Umi-OCR/assets/49964525/d801ee50-ffd4-47bd-aa82-2a970ce3d3c7)

第二个问题是，本来打算在服务器上使用本软件，然后一解压就出现这个提示，但是看了文件夹内是有这个文件的，服务器的系统是windows server2019，是因为系统问题没法用这个软件嘛？
![IMG_9977](https://github.com/hiroi-sora/Umi-OCR/assets/49964525/5fe6e056-62be-483d-b2aa-a50095771b23)

谢谢作者大大啦，麻烦您！

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

主要问题如上

**Comment by Kichony** [comment]
并且关于python3.dll问题，通过尝试安装VC运行库提示安装失败，无法安装

**Comment by hiroi-sora** [comment]
# 问题1：

> 会出现如图的异常弹窗，弹窗内的文档不会被OCR识别，且多个弹窗点击确认之后整个软件表面变黑，且后续无法进行操作，只能退出软件后才能重新操作，使用场景是在 OCR局域网内共享的文件，且已经设置可读可写的权限，目前几百个文档会有几个是这样的

按照弹窗中的信息，实际上已经成功跑完OCR识别了，但是识别后的内容 **无法保存** 。可能是文件共享引起的问题。、

建议您可以：使用共享的远程文件进行OCR，但是 **保存到本地路径** 。设置方法如下图。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/a26a2d4f-5cee-490d-8124-55b1fbee5b29)

# 问题2：

> Cannot find Py_Main() in: python3.dll

这个问题的主要原因是 Python 解释器没能跑起来，底层原因可能是缺失VC运行库。

相关： https://github.com/hiroi-sora/Umi-OCR_v2/issues/21

如果 `安装VC运行库提示安装失败` ，那么请上网搜下相关问题。必须要安装该库才能跑得动Python解释器。
