### ISSUE TITLE
合并为自然段时能否在每行的末尾多加一个空格呀,谢谢

### ISSUE THREAD

**Issue by RuiYu2021** [hiroi-sora/Umi-OCR#56]
这样整段的英文单词就不会粘在一起了.

**Comment by RuiYu2021** [comment]
或者引入Notepad中 "宏" 的概念,这样可以适配更多需求?

在此先%%%大佬为敬.

**Comment by hiroi-sora** [comment]
> 整段的英文单词粘在一起

要不这样，[合并自然段-英文模式]：当半角英文符号后面没有空格时，补充一个空格

**Comment by RuiYu2021** [comment]
极好的! 可惜我现在才高二, 学校超级基础的python课不太可能学这些. 大佬若有空可改改, 非常感谢 Thanks♪(･ω･)ﾉ
