### ISSUE TITLE
谢谢这么好用的Umi,强烈请求加入罗马数字等特别字符识别！

### ISSUE THREAD

**Issue by cukkk** [hiroi-sora/Umi-OCR#560]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

谢谢这么好用的Umi,强烈请求加入罗马数字等特别字符识别！

**Comment by qwedc001** [comment]
你好，经过测试，RapidOCR和PaddleOCR的中文模型原生支持对罗马数字的识别，您可以自行测试准确性。
<img width="406" alt="cba38f916123c178383b7cea5bbd91e" src="https://github.com/hiroi-sora/Umi-OCR/assets/14366166/e38106b5-f49e-4646-8824-aac7cd94bcfc">
