### ISSUE TITLE
UMI-OCR V2.1.2 needs more funciton

### ISSUE THREAD

**Issue by FS655556** [hiroi-sora/Umi-OCR#566]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

There is a very good and new function which is called "screenshot again", However, it can be improved better, that is "screenshot again + copy", in this way, it is more convinient for the users.

We are looking forward to the upgrade and more useful functions.

Just go ahead, we like the sofeware a lot.

Thank you a lot.

**Comment by FS655556** [comment]
Welcome to give more good advice, thank you a lot.

**Comment by hiroi-sora** [comment]
Thank you so much for your suggestion!

If what you are looking for is "screenshot again and OCR, then automatically copy the OCR result," we already have this feature. You can enable it by checking the "Copy result" option in the settings.

However, if you are looking for a feature that automatically copies the image after taking a screenshot again, this is a more niche request. We don't plan to officially develop this feature at the moment. That said, if you need it, I can provide you with some guidance on how to modify the code to achieve this.

If your request doesn't fall into either of the above categories, please provide more details about your needs.
