### ISSUE TITLE
【安卓】可否集成到安卓上，在移动端非常需要！armv7、arm64、x86、x86_64，飞桨官方的只有arm，但考虑到很多机器CPU无法转义执行，建议所有abi都支持一下

### ISSUE THREAD

**Issue by sd3970566** [hiroi-sora/Umi-OCR#567]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

【安卓】可否集成到安卓上，在移动端非常需要！armv7、arm64、x86、x86_64，飞桨官方的只有arm，但考虑到很多机器CPU无法转义执行，建议所有abi都支持一下

### Approximate reference (optional) 近似的参考（可选）

【安卓】可否集成到安卓上，在移动端非常需要！armv7、arm64、x86、x86_64，飞桨官方的只有arm，但考虑到很多机器CPU无法转义执行，建议所有abi都支持一下

**Comment by hiroi-sora** [comment]
OCR引擎后端的话想找还是能找到一些方案的。至于前端，本项目的前端基于python+qml，并且按照桌面端的使用习惯设计。移植移动端，我估计工程量会很大，不亚于重新开发一款软件。因此，短期内，我们不会有移动端的相关计划。
