### ISSUE TITLE
能否增加一个选项，截图时屏幕是否变暗

### ISSUE THREAD

**Issue by daming0086** [hiroi-sora/Umi-OCR#568]
### Issues

- [x] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

特殊场景需要截图时屏幕不变暗（或者暗的不那么明显），不知道能否实现

**Comment by hiroi-sora** [comment]
当然可以实现。

请用记事本打开 `UmiOCR-data/qt_res/qml/ImageManager/ScreenshotWindowComp.qml` ，第21行代码为：
```qml
property color darkLayerColor: "#73000000" // 深色背景层的颜色
```
改小前两个数字，就能减少屏幕变暗的幅度。比如改成 #00000000 ，就是完全不变暗。

修改完后，请保存文件，重启Umi-OCR。

**Comment by daming0086** [comment]
给力，秒回
