### ISSUE TITLE
跪求linux命令行版

### ISSUE THREAD

**Issue by ywh-my** [hiroi-sora/Umi-OCR#569]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

希望可以在linux使用把，谢谢

**Comment by Gavin1937** [comment]
你好，Umi-OCR的很多命令行功能都是和前端UI绑定的，也就是说你很难在一个无头的Linux服务器上使用Umi-OCR命令行。

你可以参考一下下面这几个方案：
1. 如果你使用的是一个带有桌面环境的Linux，可以参考[Umi-OCR_runtime_linux仓库里的文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux)来搭建Umi-OCR Linux环境，之后就可以在Linux上使用命令行了。
2. 如果你使用的是一个无头的Linux，可以考虑直接使用Umi-OCR的后端OCR引擎：[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json)。
3. 如果你使用的是一个无头的Linux，并且必须要用Umi-OCR。你可以研究一下搭建Umi-OCR Linux环境后使用[Xpra](https://github.com/Xpra-org/xpra)来启动Umi-OCR

请注意，现阶段Umi-OCR的Linux版本还在开发中。PaddleOCR-json的Linux版本已经写完了主要功能，正在测试阶段。

**Comment by ywh-my** [comment]
非常感谢，我需要的是纯命令行式的ocr，我先试试您说的方案二。后面再打赏！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月20日 13:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hiroi-sora/Umi-OCR] 跪求linux命令行版 (Issue #569) |

你好，Umi-OCR的很多命令行功能都是和前端UI绑定的，也就是说你很难在一个无头的Linux服务器上使用Umi-OCR命令行。

你可以参考一下下面这几个方案：

如果你使用的是一个带有桌面环境的Linux，可以参考Umi-OCR_runtime_linux仓库里的文档来搭建Umi-OCR Linux环境，之后就可以在Linux上使用命令行了。
如果你使用的是一个无头的Linux，可以考虑直接使用Umi-OCR的后端OCR引擎：PaddleOCR-json。
如果你使用的是一个无头的Linux，并且必须要用Umi-OCR。你可以研究一下搭建Umi-OCR Linux环境后使用Xpra来启动Umi-OCR

请注意，现阶段Umi-OCR的Linux版本还在开发中。PaddleOCR-json的Linux版本已经写完了主要功能，正在测试阶段。
