### ISSUE TITLE
忽略区域编辑器中无法框选图片角落部分

### ISSUE THREAD

**Issue by Fern43nd0** [hiroi-sora/Umi-OCR#57]
在使用编辑器的时候，框选了右下角的无用文字，但貌似有些角落部分没有选到，依然会识别到文字。
然后我尝试了删除忽略区域，并添加一个识别区域，区域内不包含右下角无用文字，开始识别后依然会识别出右下角无用文字。
麻烦您有时间看看您那边能不能复现，我这边使用了1.3.0、1.3.1、1.3.2 dev版均有这个问题。

**Comment by hiroi-sora** [comment]
## 有些角落部分没有选到：

框选角落区域时，鼠标应该从画面内部向外部拖拽，就可以覆盖到边缘。

![忽略区域覆盖边缘位置](https://user-images.githubusercontent.com/56373419/201504956-2c1232bc-4717-447f-91aa-7dc8b6e09d2b.jpg)

---

## 添加一个识别区域，开始识别后依然会识别出右下角无用文字：

需要理解，识别区域仅仅是起到一个**判断**的作用，真正**能删除文字**的是忽略区域A跟B。

```
if ( 未添加识别区域 或 识别区域内不存在文字 ) {
    删除 忽略区域A
} else if ( 识别区域内有文字 ) {
    删除 忽略区域B
}
```

**Comment by Fern43nd0** [comment]
您好，我在框选时就是按您说的方法做的，但角落还是无法选中，麻烦您看下方截图的示意，我在框选区域时，除了左上，别的都会留下黑边。
关于第二个问题的逻辑现在明白了，感谢。

![1](https://user-images.githubusercontent.com/39207992/201514254-fd712c62-b40d-4f48-b1be-0a21344c4419.gif)

四角示意：![222](https://user-images.githubusercontent.com/39207992/201513687-ae49b7e6-2ceb-4e21-838f-17fe396fd417.jpg)

**Comment by hiroi-sora** [comment]
留下黑边只是UI绘制的精度问题，不代表实际处理时，选区未覆盖到角落。

如果你那边依然会识别到文字，我怀疑也是浮点数精度问题导致的。不过我测试了一些类似的图片，没有复现该情况。可否把你的例图发来看看？

**Comment by Fern43nd0** [comment]
可以，我这边有相同格式的四张不同内容长度的图，下载地址：https://www.123pan.com/s/9v6RVv-YeGj （不需要注册登录就可以下载）
我这边测试情况是，只设置忽略区域A为右下角邮件通知，除了内容最多的那张图正常以外，别的三张图片都会出现依然识别出文字的情况，使用的是您这个项目release里下载的多语言包简体中文预设，同时英文预设也会出现这个情况。麻烦您费心看下了。

**Comment by hiroi-sora** [comment]
我设置了忽略右下角邮件区域。4张例图的右下角文字均被成功忽略，比如`VIHR.png`这张图就所有文字都没了，输出为空。
![image](https://user-images.githubusercontent.com/56373419/201537904-be8f0452-b4d1-4e3f-87b8-ea5b2b3f0ec6.png)
我又试了用四个区域把整个图形都包括在内，如下方对比图。4张例图的所有文字均被成功忽略，输出全部为空。似乎并未复现区域失效的问题。

---

不过，我依然重新检查了程序，优化了一些坐标系缩放的逻辑；通过减少一次除法，提高了0.001的浮点精度（换算整数大概是1像素）。还对UI加了额外的偏移补正，使绘制的矩形更准确，如下图，右为更改后。

![image](https://user-images.githubusercontent.com/56373419/201538427-6527867c-f9b7-481c-9035-83a73f8af098.png)

可以试试`dev 3`版是否解决了你的问题：https://hiroi-sora.lanzoul.com/s/umi-ocr-test

**Comment by Fern43nd0** [comment]
使用dev3测试了，现在已经完全没问题了，框选右下角之后已经不会出现任何文字了，非常感谢您！
