### ISSUE TITLE
跪求支持韓文OCR功能!

### ISSUE THREAD

**Issue by sahiya0w0** [hiroi-sora/Umi-OCR#572]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

Umi-OCR真的很優勢!!很感謝作者大大的辛勞...如果可以的話希望也能支持韓文啊!!

**Comment by qwedc001** [comment]
对于某种特定语言的识别，请参考 FAQ issues/447#issuecomment-2025245747 的内容。

对于该内容的进一步解释： Umi-OCR 本身并不负责识别，它只是将识别的任务发送给了目前已经适配的开源引擎上，而要想添加某个特定语言的支持，是需要在引擎上添加支持，而不是 Umi 软件本身。
现在，已经支持韩文识别的开源引擎有 PaddleOCR（需要在[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/models_list.md)下载韩文模型），TesseractOCR（参照我的 repo，需要在[此处](https://github.com/tesseract-ocr/tessdata_fast)下载韩文模型），你可以自行添加。

**Comment by hiroi-sora** [comment]
Umi-OCR 的两个发行版中（Paddle，Rapid）都是默认附带了韩文语言库的哦。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/49b1205b-aa3c-4734-9412-26c1a7dfdbb8)

**Comment by sahiya0w0** [comment]
> 对于某种特定语言的识别，请参考 FAQ [/issues/447](https://github.com/hiroi-sora/Umi-OCR/issues/447) 的内容。
> 
> 对于该内容的进一步解释： Umi-OCR 本身并不负责识别，它只是将识别的任务发送给了目前已经适配的开源引擎上，而要想添加某个特定语言的支持，是需要在引擎上添加支持，而不是 Umi 软件本身。 现在，已经支持韩文识别的开源引擎有 PaddleOCR（需要在[此处](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/models_list.md)下载韩文模型），TesseractOCR（参照我的 repo，需要在[此处](https://github.com/tesseract-ocr/tessdata_fast)下载韩文模型），你可以自行添加。

啊啊啊好的謝謝!!

> Umi-OCR 的两个发行版中（Paddle，Rapid）都是默认附带了韩文语言库的哦。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/341966967-49b1205b-aa3c-4734-9412-26c1a7dfdbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNTkxODgsIm5iZiI6MTcxOTA1ODg4OCwicGF0aCI6Ii81NjM3MzQxOS8zNDE5NjY5NjctNDliMTIwNWItYWEzYy00NzM0LTk0MTItMjZjMWE3ZGZkYmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEyMjEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MGZhZDczYWZmZjJmNTkwZDI3ZjgxMzY0NDA0MmU5OGRlZTBlNTMyMGUzYTU0MmYyNTU4YzUwN2NhZGE3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b68BMlBRyIdUb8gsZ8-f6fwtokOpM13fyiaRSVb_JQA)

我眼瞎了......不好意思打擾了!!!謝謝謝謝!!
