### ISSUE TITLE
全新部署的WIN10 LTSC 2021系统上启动报错：Cannot load python3.dll

### ISSUE THREAD

**Issue by parafox25** [hiroi-sora/Umi-OCR#574]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2

### Windows version 系统版本

win10 LTSC 2021(21H2

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR

### Reproduction steps 复现步骤

两个版本都尝试过了，都报了同样的错误，装了VC运行库和.net runtime，机型是surface pro 8（1135G7）
---------------------------
ERROR
---------------------------
Cannot load python3.dll from:

C:\PE\Umi-OCR\Umi-OCR_Rapid_v2.1.2\UmiOCR-data\runtime
---------------------------
确定   
---------------------------

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![QQ图片20240626124446](https://github.com/hiroi-sora/Umi-OCR/assets/76649347/7e60d590-6419-4c4e-8fb4-46cf40933518)

**Comment by hiroi-sora** [comment]
你好，请安装 [VC运行库](https://aka.ms/vs/17/release/vc_redist.x64.exe) 。

如果已安装后仍有相同报错，可尝试手动安装一下 [python 3.8.10 x64](https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe) ，看看安装Python的过程中有没有报错。如果有，则按照报错内容去网上查找解决方法，一般都能找到。

**Comment by parafox25** [comment]
> 你好，请安装 [VC运行库](https://aka.ms/vs/17/release/vc_redist.x64.exe) 。
> 
> 如果已安装后仍有相同报错，可尝试手动安装一下 [python 3.8.10 x64](https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe) ，看看安装Python的过程中有没有报错。如果有，则按照报错内容去网上查找解决方法，一般都能找到。

非常感谢你的回复，确实是因为VC运行库未正确安装的问题，修复并重启后问题就解决了。
