### ISSUE TITLE
作者老师，能不嗯加上ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ

### ISSUE THREAD

**Issue by popop123** [hiroi-sora/Umi-OCR#576]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

强烈希望作者大大能增加对ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ这些圈内字母的识别，虽然插件库，有部分插件能支持识别这类字符，但是准确度和稳定性与项目本体相差太大了

**Comment by hiroi-sora** [comment]
抱歉，我们暂时没有资源和精力进行模型库训练。这类带圈字符，不仅rec文本识别库需要调整，det检测库也需要针对性的微调，有一定工程难度，我估计不太容易实现 低误差的识别。

**Comment by popop123** [comment]
好吧，作者大大辛苦了
