### ISSUE TITLE
【功能建议】文字底部有水印也会被识别出来，能不能不识别水印

### ISSUE THREAD

**Issue by dododcdc** [hiroi-sora/Umi-OCR#58]

**Comment by hiroi-sora** [comment]
给个样例？

**Comment by dododcdc** [comment]
> 是指这种吗？ ![image](https://user-images.githubusercontent.com/56373419/201834650-43582b46-3eaf-40bb-ade9-3ff537008648.png)
> 
> 如果水印字号大的话，本身不会被识别出来。如果字号小，又不容易与正文区分开，是比较难处理。我会再考虑一下

就是这种

**Comment by clipsheep6** [comment]
@hiroi-sora  
是否考虑增加类似如下链接中的简单水印去除方法？ 对于字体相近的水印去除效果还不错
https://cloud.tencent.com/developer/article/1894330

**Comment by hiroi-sora** [comment]
> 是否考虑增加类似如下链接中的简单水印去除方法？ 对于字体相近的水印去除效果还不错

有两个问题：
1. numpy和opencv库太重了，会使软件体积增大上百MB。
2. 对于不同的图片，需要调节参数来适应，增加了操作难度和繁琐度。

或许可以先用外部脚本或第三方工具来先对图片预处理，再导入Umi中识别。
