### ISSUE TITLE
希望能在linux上运行并允许接口调用

### ISSUE THREAD

**Issue by magicendaver** [hiroi-sora/Umi-OCR#580]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

你好，作者大大，我这边有个需求是要让该项目能在linux系统上跑起来，然后能通过调用接口的方式使用其中的pdf文字识别功能，请问目前有什么方法吗？

**Comment by hiroi-sora** [comment]
Linux平台 / PDF http接口，这两个功能都正在开发（基本搞定了），下个版本提供。

**Comment by xzm123456** [comment]
> Linux平台 / PDF http接口，这两个功能都正在开发（基本搞定了），下个版本提供。

等待作者大大更新，哈哈哈哈哈哈哈

**Comment by hiroi-sora** [comment]
有能力的开发者可以尝试通过源码部署，来使用 Linux 版本 / PDF http 功能了。

详细说明：

- https://github.com/hiroi-sora/Umi-OCR_runtime_linux
- https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md

**Comment by xzm123456** [comment]
好的，感谢博主。
________________________________
发件人: hiroi-sora ***@***.***>
发送时间: 2024年7月10日 16:35
收件人: hiroi-sora/Umi-OCR ***@***.***>
抄送: xzm123456 ***@***.***>; Comment ***@***.***>
主题: Re: [hiroi-sora/Umi-OCR] 希望能在linux上运行并允许接口调用 (Issue #580)


有能力的用户可以尝试通过源码部署，来使用 Linux 版本 / PDF http 功能了。

详细说明：

  *   https://github.com/hiroi-sora/Umi-OCR_runtime_linux
  *   https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md

―

**Comment by hiroi-sora** [comment]
新的测试版已发布，可下载试用：

https://github.com/hiroi-sora/Umi-OCR/releases
