### ISSUE TITLE
一识别就提示：OCR init fail Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx

### ISSUE THREAD

**Issue by hui945** [hiroi-sora/Umi-OCR#582]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2

### Windows version 系统版本

WIN10专业版21H1

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR

### Reproduction steps 复现步骤

打开软件后直接截图就报错，我试过用另一台同样系统，同样处理器的电脑就不会出现这个问题
CPU:5800X
显卡：3060TI 8G
主板：七彩虹B550M

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

[Error] OCR init fail. Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx', 'cls': 'ch_ppocr_mobile_v2.0_cls_infer.onnx', 'rec': 'rec_ch_PP-OCRv4_infer.onnx', 'keys': 'dict_chinese.txt', 'doAngle': 0, 'mostAngle': 0, 'maxSideLen': 1024, 'numThread': 16}
OCR init fail.

**Comment by hui945** [comment]
这个处理器算是中高端的了，应该不会是CPU太低级引起的

**Comment by hiroi-sora** [comment]
你当前用的是 Rapid 版本。请问尝试过 Paddle 版本吗？你这个处理器兼容 Paddle 的，可以试试。

**Comment by hui945** [comment]
两个版本都有试过，后来重装系统后就恢复了，但是还是不知道是怎么引起的这个问题




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hiroi-sora/Umi-OCR] 一识别就提示：OCR init fail Argd: {'models': 'models', 'ensureAscii': 1, 'det': 'ch_PP-OCRv3_det_infer.onnx (Issue #582)




 
你当前用的是 Rapid 版本。请问尝试过 Paddle 版本吗？你这个处理器兼容 Paddle 的，可以试试。
