### ISSUE TITLE
功能建议：更便捷地更换识别语言

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [hiroi-sora/Umi-OCR#59]
我最常用的使用场景是：用其他软件快捷键截图，然后快捷键呼出`Umi-OCR`识别。

现在，如果需要多语言识别：比如这次想识别日语，但上一次识别的是英文（软件内的`识别语言`设置成了英文），需要：

0. 截完屏后触发`快捷识图-粘贴图片`快捷键，`Umi`窗口弹出，并显示`识别内容`页
1. 点击`设置`页
2. 在最下面选择并更换`识别语言`到日语
3. 再触发一次`快捷识图-粘贴图片`快捷键

期望的操作：

0. 截完屏后触发`快捷识图-粘贴图片`快捷键，`Umi`窗口弹出，并显示`识别内容`页
1. 在这一页上（比如下图这里）的下拉菜单里选择并更换`识别语言`
2. 自动重新识别上一次识别的图片，并输出结果

![图片](https://user-images.githubusercontent.com/63943573/201851538-0f66c3cd-2a49-4e60-9b69-e81df2032c5a.png)

**Comment by MaxHasBeenUsed** [comment]
好快！感谢！！确实是很方便了！

不过还又有两个新bug；；
1. 主界面勾选了`窗口置顶`之后，弹出的`更改语言`窗口也应该自动置顶。我试了一下`更改语言`会被挡在主窗口后面。
2. 两种方法（`识别内容`和托盘）都无法唤出`更改语言`界面。好像是打开一次`更改语言`之后关掉主界面，就无法再次唤起了。重开主程序恢复。

**Comment by hiroi-sora** [comment]
> 又有两个新bug

嗯，小问题，已修复，见上面链接的`Dev 5`。
1：改成了 子窗口跟随主窗的置顶状态。启用/关闭置顶后，请重新打开子窗口来应用状态。
2：忘了接管默认退出事件导致单例对象被意外销毁😂已修复。
