### ISSUE TITLE
允许在界面中直接选择 TesseractOCR traineddata 模型

### ISSUE THREAD

**Issue by fangquinlan** [hiroi-sora/Umi-OCR#591]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

![屏幕截图 2024-07-12 115417](https://github.com/user-attachments/assets/f8152500-81e7-40a5-8824-d50476fdd8fc)
现在使用这些`traineddata`必须改成标准命名格式，比如`deu.traineddata`，才能在Umi中识别。但是这样很麻烦，如果我想要测试哪个模型效果好，必须不停的改名。能不能直接选择文件？

**Comment by qwedc001** [comment]
建议收到

**Comment by qwedc001** [comment]
@fangquinlan 功能已经写好了，挺简单的一个patch
你可以clone一份最新的Tesseract 插件库代码然后直接覆盖现有内容。Release可能稍晚点发
