### ISSUE TITLE
docker部署

### ISSUE THREAD

**Issue by jaychoubaby** [hiroi-sora/Umi-OCR#596]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

希望增加一个纯api功能的docker部署方式，在linux上部署只需要api能正常使用即可，docker部署干净便捷

**Comment by Gavin1937** [comment]
你好，如果需要docker部署的话可以考虑直接部署Umi-OCR的后端OCR引擎：[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/README-docker.md#%E4%BD%BF%E7%94%A8-docker-%E9%83%A8%E7%BD%B2)。部署后可以用[它的API](https://github.com/hiroi-sora/PaddleOCR-json/tree/main?tab=readme-ov-file#api%E5%88%97%E8%A1%A8)调用。

**Comment by jaychoubaby** [comment]
> 你好，如果需要docker部署的话可以考虑直接部署Umi-OCR的后端OCR引擎：[PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/README-docker.md#%E4%BD%BF%E7%94%A8-docker-%E9%83%A8%E7%BD%B2)。部署后可以用[它的API](https://github.com/hiroi-sora/PaddleOCR-json/tree/main?tab=readme-ov-file#api%E5%88%97%E8%A1%A8)调用。

好的 谢谢

**Comment by hiroi-sora** [comment]
Umi-OCR 本体已支持 Docker 部署。 👉 [文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md)
