### ISSUE TITLE
功能建议: 拖入文件夹能递归下面所有子文件夹

### ISSUE THREAD

**Issue by lqzhgood** [hiroi-sora/Umi-OCR#6]
目前拖入文件夹仅读取当前文件夹的图片 
希望拖入文件夹能递归到所有子文件夹的图片

谢谢

**Comment by hiroi-sora** [comment]
🉑，下版本安排

**Comment by hiroi-sora** [comment]
[v1.2.5](https://github.com/hiroi-sora/Umi-OCR#%E4%B8%8B%E8%BD%BD) 已更新该功能，需要在设置里开启

**Comment by lqzhgood** [comment]
谢谢
