### ISSUE TITLE
请问用命令行的方式，如何返回json形式带坐标的dict类数据

### ISSUE THREAD

**Issue by dojia** [hiroi-sora/Umi-OCR#602]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

现在用命令行的方式，返回的是识别文本。不知道如何能返回跟http返回格式一样，dict模式，json，带有坐标数据的那种。

**Comment by hiroi-sora** [comment]
如果你想用命令行模式获取json原始数据，建议直接调用引擎：

https://github.com/hiroi-sora/PaddleOCR-json
