### ISSUE TITLE
用过其他插件后换回自带的截图OCR不会翻译了

### ISSUE THREAD

**Issue by aiken2132** [hiroi-sora/Umi-OCR#603]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

用过TesseractOCR插件后换回自带的截图OCR不会翻译了，我把TesseractOCR整个文件夹删了还是一样翻译不了

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![QQ_1721382002334](https://github.com/user-attachments/assets/4c772474-5629-48d2-8adb-d251ea8ea099)
![QQ_1721382018642](https://github.com/user-attachments/assets/474d7288-f7b7-44ca-a194-861647b9e970)

**Comment by hiroi-sora** [comment]
我们目前没有截图翻译功能哦，“语言”选项是调节要识别的图片中的语言。

**Comment by aiken2132** [comment]
> 我们目前没有截图翻译功能哦，“语言”选项是调节要识别的图片中的语言。

语言设置了英文还是一样
![QQ_1721383056820](https://github.com/user-attachments/assets/42039f20-70a9-4278-88c0-cf298665e9c6)
![QQ_1721383080123](https://github.com/user-attachments/assets/d70f66b7-43fd-4329-8606-dc49170e69aa)

**Comment by hiroi-sora** [comment]
这个有什么问题吗，图片中是英文，识别出来的文字也是英文。

我们目前还没有“将英文翻译为中文”的功能哦。

**Comment by aiken2132** [comment]
> 这个有什么问题吗，图片中是英文，识别出来的文字也是英文。
> 
> 我们目前还没有“将英文翻译为中文”的功能哦。

好吧 我的
