### ISSUE TITLE
增加docker方式的部署

### ISSUE THREAD

**Issue by xzm123456** [hiroi-sora/Umi-OCR#607]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

希望增加docker方式的部署，自己尝试过多次，都没有成功。但是docker方式部署很方便、直接，希望增加

**Comment by hiroi-sora** [comment]
已基本实现Docker部署，见文档：

[Docker部署文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md)

**Comment by xzm123456** [comment]
> 已基本实现Docker部署，见文档：
> 
> [Docker部署文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md)

已部署，win下docker没问题，非常感谢博主。在linux遇到一些问题，linux版本项目下已经提交了。

**Comment by izturn** [comment]
@hiroi-sora 在ubuntu22.04下,打包这类前置操作均成功执行,但最后运行不成功:

1. docker run
```
➜  Umi-OCR-Docker docker run -d --name umi-ocr \
    -e HEADLESS=true \
    -p 1224:1224 \
    umi-ocr-paddle
0311a8ca395740af31ee01f8aeb9f091e837733e9c27783b18b3911304ea0fd7
```
2. curl:
```
➜  Umi-OCR-Docker curl http://127.0.0.1:1224/api/ocr/get_options                     
curl: (7) Failed to connect to 127.0.0.1 port 1224 after 0 ms: 连接被拒绝
```
3.
```
➜  Umi-OCR-Docker docker exec -it umi-ocr sh    
Error response from daemon: container 0311a8ca395740af31ee01f8aeb9f091e837733e9c27783b18b3911304ea0fd7 is not running
```
