### ISSUE TITLE
功能建议：支持使用命令行选项进行功能调用

### ISSUE THREAD

**Issue by CudtMFrag** [hiroi-sora/Umi-OCR#61]
不想占用快捷键，去任务栏点图标太麻烦，希望可以用命令行进行功能调用方便配合其它软件（quicker）

**Comment by hiroi-sora** [comment]
建议收到。以后有空研究下。

**Comment by hiroi-sora** [comment]
命令行调用开发完毕，欢迎体验 [v1.3.3 测试版](https://github.com/hiroi-sora/Umi-OCR/issues/96) 。
