### ISSUE TITLE
Windows Server 2016 保存PDF时 “已停止工作”

### ISSUE THREAD

**Issue by qwedc001** [hiroi-sora/Umi-OCR#613]
> # 保存PDF时 “已停止工作”
> 文档识别，能识别出文字，能保存为txt等文件。但如果选择保存为`双层可搜索PDF`，则最后导出文件时弹窗报错：
> 
> ```
> Umi-OCR.exe 已停止工作
> 
> 查看问题详细信息：
> 
> 问题事件名称：BEX64
> 故障模块名称：ucrtbase.DLL
> 故障模块版本：10.0.10240.16390
> 异常偏移：00000000064399
> 异常代码：c0000417
> ```
> 
> ![](https://private-user-images.githubusercontent.com/56373419/318039422-93de1169-44bb-46fb-bf2e-a424400b7267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzcyMjMsIm5iZiI6MTcyMjE3NjkyMywicGF0aCI6Ii81NjM3MzQxOS8zMTgwMzk0MjItOTNkZTExNjktNDRiYi00NmZiLWJmMmUtYTQyNDQwMGI3MjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE0Mjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NjVhYjg1YzI4YTVmOGFkODBkZDk1NDk2YzYyN2JiMWE4NmY4OWE3MWQ1NDRiYzcwZTYyMzBlZGFlNDRlMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jKD24ZMqk-ctu301_2cNS5lK_GTGVmho-C0hYa5JoCo)
> 
> # 可能的发生条件：
> win7早期版本，缺少系统补丁（尤其是 `KB4534310`、`KB3042058`）
> 
> # 修复方法：
> 注意！由于 `KB4534310` 依赖前置补丁，因此 **不能** 单独下载安装该补丁。
> 
> 您必须使用系统检查更新（`控制面板 → 系统和安全 → Windows Update → 检查更新`），安装所有缺失的更新，直到这个项目安装完毕：
> 
> ```
> 2020-01 适用于基于 x64 的系统的 Windows 7 月度安全质量汇总 （KB4534310）
> ```
> 
> 温馨提示，如果自动升级的过程中出现 `80092004` 的安装错误，实测 [这个做法](https://jingyan.baidu.com/article/acf728fd25a1e3b9e510a3f2.html) 有效。
> 
> 如下图，直到安装了这些更新，就能解决PDF无法保存的问题。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/318044484-e302610d-756d-499e-909b-cf3243a9a25a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzcyMjMsIm5iZiI6MTcyMjE3NjkyMywicGF0aCI6Ii81NjM3MzQxOS8zMTgwNDQ0ODQtZTMwMjYxMGQtNzU2ZC00OTllLTkwOWItY2YzMjQzYTlhMjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE0Mjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZTBlZjQxMjI5NTdiZGJmMjQwNjM0MzhiZmZiMTQ5MGRkMmQ4YTMwZmQ0N2JhODBkNzNhY2U4NmFmYWQ3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKmaFNQqH49cVaFTp-yr7e-4x5ERjdN2oDR26y0NYqk)

请问W10也出现这个问题要咋办啊，两个版本都试过不行

_Originally posted by @zhizhilin in https://github.com/hiroi-sora/Umi-OCR/issues/447#issuecomment-2254546339_

**Comment by qwedc001** [comment]
@zhizhilin 请不要在FAQ下直接开启评论（
请先提供一下更具体的系统信息和报错弹窗方便故障排查

**Comment by zhizhilin** [comment]
不好意思，评论已经删除，其他详细信息如下：
问题：文档识别，能识别出文字，能保存为txt等文件。但如果选择保存为双层可搜索PDF，则最后导出文件时弹窗报错“已停止工作”
系统版本：搞错了，不是w10，查了一下是windows service 2016 standard 1607；我试了一下Paddle和Rapid版本都不行，因为有权限管控，也没办法尝试安装补丁。
问题日志：
错误应用程序名称: Umi-OCR.exe，版本: 0.0.0.0，时间戳: 0x6530e6f2
错误模块名称: ucrtbase.dll，版本: 10.0.14393.1770，时间戳: 0x59bf2b6f
异常代码: 0xc0000409
错误偏移量: 0x000000000006d658
错误进程 ID: 0x6c9c
错误应用程序启动时间: 0x01dae186df84257f
错误应用程序路径: C:\xx\Umi-OCR_Paddle_v2.1.3\Umi-OCR.exe
错误模块路径: C:\Windows\System32\ucrtbase.dll

**Comment by hiroi-sora** [comment]
应该就是补丁问题。保存文件时崩溃，bug是发生在PyMuPDF库内部。 ucrtbase.dll `0xc0000409` 一般是内存异常，如堆栈溢出或分配了错误的内存。 PyMuPDF 项目并没有相关 Issue ，我感觉大概率不是代码问题，而是调用系统API时出错，我们难以修复此问题。

这种问题与 Paddle 或 Rapid 版本无关，因为是发生在两个版本都通用的组件内。暂时只能换一台机器来使用此功能了。

**Comment by zhizhilin** [comment]
好的，谢谢大佬。

**Comment by rogerccdi** [comment]
大佬你好，我的win11也出现这样的问题，是双层可搜索文档的转换过程中耗时很长（半小时就有txt，但是快一个小时了双层pdf是0字节），之后就报错卡死了，事件查看器的描述如下：程序Umi-OCR.exe版本0.0.0.0停止与 Windows 交互并已关闭。若要查看有关此问题的详细信息是否可用，请查看安全性与维护控制面板中的问题历史记录。
问题事件名称:	AppHangB1
Application Name:	Umi-OCR.exe
Application Version:	0.0.0.0
Application Timestamp:	6530e6f2
Hang Signature:	a0bb
Hang Type:	134217728
OS 版本:	10.0.22621.2.0.0.768.101
区域设置 ID:	2052
win11没能找到和上面类似涉及到哪一个dll导致错误的报告，谢谢大佬！
