### ISSUE TITLE
有个java调用cmd导出pdf的路径拼接疑问

### ISSUE THREAD

**Issue by 793536325** [hiroi-sora/Umi-OCR#614]
谢谢作者提供了这么好的功能。我在win10命令行中完整的跑通了https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_CLI.md 中的例子。
现在我想在java中复现下，但是拼接路径的时候一直报错

![微信截图_20240731174407](https://github.com/user-attachments/assets/e9a18cea-b946-458f-a5fa-e856800b4566)

我拼接好的参数  umi-ocr --call_qml BatchDOC --func addDocs "[\"E:/pdf/0117/2010/001/0117-2010-001-0004.pdf\"]"
是可以在命令行直接执行的，但是在java中就不行提示如下：
Your argv: ['umi-ocr', '--call_qml', 'BatchDOC', '--func', 'addDocs', '["E:/pdf/0117/2010/001/0117-2010-001-0004.pdf"]']
[Error]: 2
usage: Umi-OCR --help
问问这个应该怎么处理 
谢谢了

**Comment by hiroi-sora** [comment]
你好。

这个在 CLI 跑 BatchDOC 的例子只是个参考。在实际应用中，如果你想通过接口来调用PDF识别，强烈建议使用HTTP接口：

https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md#/api/doc

**Comment by 793536325** [comment]
谢谢
