### ISSUE TITLE
使用截图ocr功能会黑屏两次

### ISSUE THREAD

**Issue by wjhg** [hiroi-sora/Umi-OCR#619]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.13

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

使用截图后ocr屏幕会黑屏两次。

**Comment by hiroi-sora** [comment]
全局设置 → 渲染器 → 关闭硬件加速

![image](https://github.com/user-attachments/assets/e70264d2-433a-4e52-96a9-f5601b7d51d9)
