### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by panxiuwen** [hiroi-sora/Umi-OCR#62]
能否发布一个命令行版
能否添加CUDA的支持，毕竟paddleocr是可以支持cuda的

**Comment by hiroi-sora** [comment]
> CUDA：

以后会考虑，现在我手头没显卡。

> 命令行版：

是需要什么功能呢，可否描述一下？

**Comment by panxiuwen** [comment]
我想把后端部署到Linux服务器上，如果能给个接口的话，也方便封装
如果您写的前端也能连接到服务器上对接到后端的话就更好了
当然我也做过封装到网页版前端之类的工作，比如https://github.com/panxiuwen/waifu2x-webui

**Comment by hiroi-sora** [comment]
因为本项目的初衷是纯本地，所以框架设计就没有考虑到远程，引擎模块（paddleocr封装后）也不太容易移植到Linux平台。要做的话，工作量跟新开一个项目差不多了。
你是想部署到自己服务器，隔壁已经有不少同类项目，不妨了解一下：
[TrWebOCR](https://github.com/alisen39/TrWebOCR)
[RapidOCR/ocrweb](https://github.com/RapidAI/RapidOCR/tree/main/ocrweb)
[RapidOCRServer](https://github.com/Physton/RapidOCRServer)

**Comment by panxiuwen** [comment]
非常感谢您的提醒
到后面我也会尝试把您写的前端和他们的后端封装在一起的

**Comment by hiroi-sora** [comment]
命令行调用开发完毕，欢迎体验 [v1.3.3 测试版](https://github.com/hiroi-sora/Umi-OCR/issues/96) 。
