### ISSUE TITLE
Bug & 解决方法：打开软件时弹窗报错 process PID not found (pid=*****)

### ISSUE THREAD

**Issue by hiroi-sora** [hiroi-sora/Umi-OCR#63]
这个Bug仅在`v1.3.1`版本极低概率出现；表现为打开软件时弹窗报错，无法正常启动软件，如下图：
![image](https://user-images.githubusercontent.com/56373419/202861407-b111a16d-ecab-4281-9f0c-bcbbd1dea91e.png)

# 此Bug已在v1.3.2修复。

# 如果v1.3.1的用户遇到了此问题，可参考以下步骤快速解决：
1. 打开软件目录下的配置文件 `Umi-OCR_config.json` 。
2. 将其中 `"processID": ****, ` 的一行**删掉**。
3. 问题解决，重新打开软件即可。
![image](https://user-images.githubusercontent.com/56373419/202861617-1f34f235-bbde-4b63-8773-8947679c6741.png)

**Comment by hiroi-sora** [comment]
Bug出现原因：

v1.3.1 加入了多开检测的功能，检查是否已有Umi-OCR正在运行，其中有一步是查询历史进程的信息。
先用 `psutil.pid_exists` 检查该进程号是否存在，是，则用 `psutil.Process` 生成对象并提取其信息。

我偶然遇到了这个现象： `pid_exists` 返回True，即进程存在；而 `Process` 报异常 `NoSuchProcess` ，即进程不存在。这似乎前后矛盾。
暂时没有搞清这个Bug触发的机制，但加了异常处理来规避它，程序可以在此情形下保持正常运行。

**Comment by haima3** [comment]
> Bug出现原因：
> 
> v1.3.1 加入了多开检测的功能，检查是否已有Umi-OCR正在运行，其中有一步是查询历史进程的信息。 先用 `psutil.pid_exists` 检查该进程号是否存在，是，则用 `psutil.Process` 生成对象并提取其信息。
> 
> 我偶然遇到了这个现象： `pid_exists` 返回True，即进程存在；而 `Process` 报异常 `NoSuchProcess` ，即进程不存在。这似乎前后矛盾。 暂时没有搞清这个Bug触发的机制，但加了异常处理来规避它，程序可以在此情形下保持正常运行。

正常来讲Windows的PID是顺序分配吧，会不会有运行时间长了之后PID有重新分配的情况？？这只是个猜测，没有实际遇见过。

**Comment by hiroi-sora** [comment]
> 运行时间长了之后PID有重新分配的情况

这种常见情况当然有考虑到，多开检测的重要一环就是检验历史pid当前对应的进程，是umi 还是系统分配给的其它不相关程序。应该与此bug妹有关系
