### ISSUE TITLE
怎么识别意大利拉丁文？

### ISSUE THREAD

**Issue by i990049** [hiroi-sora/Umi-OCR#64]
搞了一些意大利剧的图形字幕，想要转换一下

**Comment by hiroi-sora** [comment]
1. 下载模型库&字典：[ppocr-latin.zip](https://github.com/hiroi-sora/Umi-OCR/files/10051863/ppocr-latin.zip)

2. 扔到软件目录下 `PaddleOCR-json` 文件夹

3. 上一级目录，打开`Umi-OCR_config.json`，在`ocrConfig`中粘贴：
```
        "拉丁文": {
            "path": "PaddleOCR_json_config_latin.txt"
        },
```

**Comment by WhiteSKing** [comment]
你好，有两个问题想请教下：
1、我想多扩展一些越南语、泰语、印尼语等一些语种，哪里有字典模型库吗？
2、想看下“initStr = self.ret.stdout”这里面的源码，想了解下识别过程，哪里可以看吗？

**Comment by hiroi-sora** [comment]
> 哪里有字典模型库

请看 [进阶操作](https://github.com/hiroi-sora/Umi-OCR#%E8%BF%9B%E9%98%B6%E6%93%8D%E4%BD%9C--%E5%B0%8F%E6%8A%80%E5%B7%A7) 的添加多国语言。

> 识别引擎相关

请见 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 。
