### ISSUE TITLE
图片超过10mb识别异常

### ISSUE THREAD

**Issue by xiaotao-xiaotao** [hiroi-sora/Umi-OCR#647]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

Linux

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

docker部署的最新版本，通过接口调用，我这边有一批图片都识别不了，也没有任何的响应信息，接口一直卡住不动，很长时间也没有响应信息

测试文件如下所示：
链接: https://pan.baidu.com/s/1CHKzWWRX05SwwUZqkeUwFQ 
提取码: veyk

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![image](https://github.com/user-attachments/assets/c77be858-3397-4532-b050-cad54ecd11c8)

**Comment by hiroi-sora** [comment]
进入docker命令行，修改 `app/UmiOCR-data/py_src/server/web_server.py` ，第22行的代码：
```python
BaseRequest.MEMFILE_MAX = 10485760  # 设置单次请求大小上限：10MB
```

将这个数值改大一点。

**Comment by xiaotao-xiaotao** [comment]
好滴，感谢

**Comment by xiaotao-xiaotao** [comment]
> 进入docker命令行，修改 `app/UmiOCR-data/py_src/server/web_server.py` ，第22行的代码：
> 
> ```python
> BaseRequest.MEMFILE_MAX = 10485760  # 设置单次请求大小上限：10MB
> ```
> 
> 将这个数值改大一点。

好滴，感谢

**Comment by xiaotao-xiaotao** [comment]
还有个建议问题，期望能把docker的镜像体积大小给缩减下，我看tika-server上边集成的TesseractOCR才720mb呢
