### ISSUE TITLE
关于PDF与JPG在输出txt和csv时的异常问题。

### ISSUE THREAD

**Issue by AlvinPPP** [hiroi-sora/Umi-OCR#654]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win 10

### OCR plugins Used 使用的OCR插件

PaddleOCR, RapidOCR

### Reproduction steps 复现步骤

背景：PDF文件（经测试在单页也存在问题），该类PDF文件的特征是一种经复印近扫描形成的（不会特别整齐，且有不可预见的使用痕迹）
测试过程：
直接放入PDF文件进行识别，并输出cvs和txt结果。
![image](https://github.com/user-attachments/assets/08be5f4a-819f-45de-b76b-d3be1a6056a5)
上述这个识别结果可见在软件界面的记录是带有乱码的（这种乱码，经输出layered.pdf后，可知悉是上面的一个指纹）
在cvs和txt的异常表现为：
txt上是按照软件界面的记录输出的；
![image](https://github.com/user-attachments/assets/02eaccc2-b61f-466d-be77-ae63c9dd39b8)
cvs则没有按软件界面的记录输出；（认为是异常点）
![image](https://github.com/user-attachments/assets/22c15a86-97de-41eb-b320-f9ffc17a2f88)
对比两边的文本，似乎这种情况下，中文部分会变成乱码。

另外就是，将PDF文件导出为JPG后使用批量OCR识别输出CVS时，则是正常的，且也不会受“指纹”痕迹的影响。
![image](https://github.com/user-attachments/assets/e564aa0f-4e0f-4451-a5f6-80ae910b616d)

希望能修复识别PDF文件时对其中文输出CSV结果异常的问题。（该问题在使用内容提取模式为“仅OCR图片”时似乎是可避免的，正常情况下都使用“混合OCR/原文本”的模式，多数文件都可以正常识别，个别文件会出现上述问题，但事后再发现就要换模式重新跑一遍批量了）

**Comment by hiroi-sora** [comment]
1. 指纹问题

**内容提取模式** 就是用来处理不同情况的文档的。如果想排除无意义的文本元素， `整页强制 OCR` 或 `仅 OCR 图片` 都可以解决。

2. CSV乱码问题

Office Excel 打开CSV时，默认会采用本地编码（比如`GB2312`）而不是更通用的 `utf-8` 。这使得 Umi 需要根据识别内容，猜测它属于哪种本地编码，进行保存。如果识别内容中出现了特殊字符（比如指纹中可能含有的特殊符号），就有可能让 Umi 猜错编码， Office 打开为乱码。

为解决这个问题，可以优先让 Umi 保存为 `utf-8` ，然后使用特定的方法转换为Excel：
1. 用文本编辑器打开 `UmiOCR-data\py_src\ocr\output\output_csv.py`，开头有一段代码：
```
        self.encodings = [  # 保存编码优先级
            "ansi",  # Windows系统本地编码
            "ascii",  # 纯英
            "gbk",  # 简中
            "big5",  # 繁中
            "shift_jis",  # 日文
            "euc-kr",  # 韩文
            "utf-8",
        ]
```
2. 将这段代码改为如下：
```
        self.encodings = [  # 强制设为 utf-8
            "utf-8"
        ]
```
3. 重启Umi-OCR，进行任务，得到csv文件。
4. 将csv导入excel（而不是直接打开）。 [参考](https://zhuanlan.zhihu.com/p/643376582)
5. 当然，也可以直接用WPS打开csv，一般不会乱码。用WPS保存为excel就可以换成Office打开了。

**Comment by AlvinPPP** [comment]
我是那种不太懂代码，更倾向软件使用的用户类型。
由于我试过将PDF导出为图片再进行批量识别，这种情况下是不产生猜错编码的问题的，所以是否可以理解为通过内容提取模式改为“仅OCR图片”时，其效果是等同于批量识别JPG类型因此就不产生猜错编码问题？

此外，我按你提示的第4点，使用导入excel而非直接打开，对第1、2点是否改代码似乎没关系，我通过excel导入昨天出异常的结果和今天改了代码后再输出的结果（昨天和今天结果都是直接打开是乱码的状态），但导入时界面都如下图所示，这引起我的疑惑，这个界面描述的文件原始格式都是UTF-8，则是否与Umi猜错编码无关呢？是否有我能进一步做的测试供你参考？

![image](https://github.com/user-attachments/assets/53422ca7-0105-443d-9f65-3b902cb910eb)
