### ISSUE TITLE
有计划支持wayland协议吗?

### ISSUE THREAD

**Issue by zzqayy** [hiroi-sora/Umi-OCR#659]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

随着nvidia对linux的驱动支持,现在大部分发行版本都开始准备切换到wayland,有计划支持wayland下操作吗?

**Comment by hiroi-sora** [comment]
你好。 Umi-OCR 在 wayland 协议中唯一不支持的功能是截图，因为 Umi 调用 QT 的跨平台截图接口 `grabWindow` ，该接口在 wayland 下无法获取真实截图。

解决此问题的方法有：

1. 等待QT修复此接口。
2. Umi-OCR 中，检测到 wayland 环境时，调用第三方接口进行截图。

短期内，我没有方法2的开发计划。也许未来有空了再看看吧……

**Comment by zzqayy** [comment]
好的,感谢你的回复.我有时间自己尝试一下2方案看是否成功
