### ISSUE TITLE
内存占用有点大，请问是什么情况

### ISSUE THREAD

**Issue by yyh296996761** [hiroi-sora/Umi-OCR#66]
![image](https://user-images.githubusercontent.com/26431893/203488469-8d4148c1-ff70-4ddd-a493-c41cea5dacc9.png)

我在一个电子书中用snipaste截屏，然后用umi-ocr 粘贴图片的功能，截屏了两次，内存占用增加了很多

**Comment by hiroi-sora** [comment]
PPOCR引擎是占内存比较多，回收策略不积极。一般来说，不会因此导致崩溃或严重问题，占用的越多，回收越频繁，增长的越慢。
（你这2g似乎不太正常，我这边刚启动识别几张图的话不会超过1g。也许是不同平台硬件的区别……）

如果你介意，可以调整以下两个选项：
1. 关闭MKLDNN加速
2. 引擎策略换为**按需关闭**（勾选底部高级选项重启软件后才有此选项）

调整其中任意一个就能大幅降低内存占用，无需两个都关。但降低内存的同时也会降低识别速度。

![image](https://user-images.githubusercontent.com/56373419/203495112-d926980e-117f-4e29-982f-007998d72132.png)
