### ISSUE TITLE
对中文文字支持不完全，比如【祂】

### ISSUE THREAD

**Issue by huanshiwushuang** [hiroi-sora/Umi-OCR#667]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win10专业版 22H2 19045.4780

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

![screenshots](https://github.com/user-attachments/assets/a3398b42-3a26-4134-9797-d0d156cbe3b1)

**Comment by qwedc001** [comment]
请见 https://github.com/hiroi-sora/Umi-OCR/issues/447#issuecomment-2025245747
Umi 并非实际识别方，生僻字识别效果差是 Umi 本身调用引擎 Paddle 对生僻字训练较少导致的。

**Comment by huanshiwushuang** [comment]
> 请见 [#447 (comment)](https://github.com/hiroi-sora/Umi-OCR/issues/447#issuecomment-2025245747) Umi 并非实际识别方，生僻字识别效果差是 Umi 本身调用引擎 Paddle 对生僻字训练较少导致的。
> 
> 不知道什么时候插件系统重写好，重写好接入在线API这种情况可能会有所改善，不过目前没办法搞定。

感谢，明白了
