### ISSUE TITLE
OCR引擎后台运行会掉线

### ISSUE THREAD

**Issue by LanRenLan** [hiroi-sora/Umi-OCR#67]
![QQ截图20221126093829](https://user-images.githubusercontent.com/112599739/204101874-d6594195-3c38-4c72-820e-4cbe0e514462.png)
![QQ截图20221126093945](https://user-images.githubusercontent.com/112599739/204101880-f2e7389b-18d8-40f3-bf2c-39f14d1e0dfd.png)
![QQ截图20221126094152](https://user-images.githubusercontent.com/112599739/204101936-80399236-939b-4482-ba85-aa8ed0234f9d.png)
软件版本1.3.1，winver Windows 11 21H2(OS内部版本22000.1281)，单显示器；引擎管理设置的是后台常驻，启用MKLDNN加速，没有自动清内存的软件。软件的图标会莫名其妙的消失，在任务栏里找不到，但是任务管理器里面是有的。快捷键是f6，平时有托盘图标的时候可以正常运行 没有冲突，但是图标没了以后就用不了了。双开，启动引擎，再退出就可以正常使用，虽然依旧没有图标，倒也不算啥大问题

**Comment by hiroi-sora** [comment]
确实看上去比较奇怪，不像任何已知的问题。从任务管理器的图来看内存占用明显不正常，只打开前端的话应该占用26m，启动引擎组件则占用130+m；你这里才0.7m，python解释器都没在跑。

- 请问这问题一般发生在启动软件多长时间后呢？
- 出现这问题时是否处于后台托盘模式？即叉掉软件窗口，留在托盘运行。
    - 试试如果不叉掉，只最小化，还会出现这问题吗？
    - 如果还会出现，试试设置里`显示托盘图标 取消勾选`，然后重启软件并最小化放着，看看还会出现问题吗？

**Comment by LanRenLan** [comment]
我笔记本长时间不关机，偶尔休眠，上一次出这个bug的时候，CPU运行时间大概24小时，以前遇到这个问题也是运行时间比较长才有
下面是我的设置，我平时不开窗口，一直把他后台运行的。您说的方法我也会试一下，等一段时间再来反馈
![QQ截图20221126224337](https://user-images.githubusercontent.com/112599739/204122873-3b860648-2c1c-48be-aec0-335dd1ca5add.png)

**Comment by LanRenLan** [comment]
搞不明白了，我当时连续遇到了两次这个bug才来报错的，结果后来我无论怎么设置都再也没遇到过了。 前天电脑去送修，现在只能用旧电脑，i5 6200 8G内存，也没遇到OCR掉线的情况。总之谢谢大大开发软件了。
