### ISSUE TITLE
可否添加模型识别速度切换

### ISSUE THREAD

**Issue by lsqm01** [hiroi-sora/Umi-OCR#674]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

感谢您的开发！这个软件是我用过最好的软件
我本人使用的是Rapid 引擎插件版，机器是办公轻薄本，尽管如此仍然CPU占用过高（60-70上下），影响机器在扫描的同时使用其他功能
想问在您预期的GPU扫描版本推出之前，可否推出模式切换功能
即：低速模式：可将模型的运行扫描速率降低至60-80%性能（或更低？），这样扫描速度慢，但是对机器负载可以降低，更适合办公轻薄本使用
常速模式：即默认正常模型运行速度
非常期待您的答复，谢谢！

**Comment by hiroi-sora** [comment]
你好，目前版本支持所谓“低速模式”。请在全局设置标签页→文字识别→RapidOCR，将 **线程数** 设得低一点就行啦！比方说你是4核8线程的轻薄本，可以设为2线程，这样最多占满1个物理核心，机器仍有足够冗余性能。

**Comment by lsqm01** [comment]
感谢您的回复！
之前也看到了这个设置但是没搞明白，感谢答疑解惑！
