### ISSUE TITLE
语种选择空白

### ISSUE THREAD

**Issue by Teto314** [hiroi-sora/Umi-OCR#676]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win11 23H3 22631.4169

### Reproduction steps 复现步骤

翻译语种中的朝鲜语变成空白了，是最近才发现的问题
更改字体、重启、重装ocr问题依旧

但是另一台相同win11的电脑就没有这个问题
不清楚原因，是我windows的问题吗

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![屏幕截图 2024-09-28 224326](https://github.com/user-attachments/assets/a02abd99-5945-4f39-bc79-a7342bde5699)

**Comment by hiroi-sora** [comment]
可能是系统字体渲染异常。首先，请尝试在 全局设置标签页→ 修改字体→ **界面** 一栏，改为别的字体试试。

如果仍不行，请尝试：

打开此文件： `Umi-OCR\UmiOCR-data\plugins\win7_x64_PaddleOCR-json\models\configs.txt`

这个文件保存了语言库参数到语种名称的映射，其中有一行是：
```
config_korean.txt 한국어
```

将 `한국어` 改为 `Korean` 、 `朝鲜语/韩语` 之类，可避免系统渲染字符的异常。

**Comment by Teto314** [comment]
configs.txt暂时没改
但在安装支持朝鲜语的字体batang后，尝试把界面语言切换，后可以batang字体正常显示，再之后即使切换回雅黑这种不支持韩文的界面语言也可正常显示了，估计是我windows的问题
