### ISSUE TITLE
UMI -OCR 对表格的识别太弱了，简直不像个成熟产品，怎么和微信识别一个水平，谁还用这个。。。。连个表格都识别不好，格式错乱

### ISSUE THREAD

**Issue by john19820** [hiroi-sora/Umi-OCR#677]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

如题

### Approximate reference (optional) 近似的参考（可选）

1111111111111111111111111

**Comment by john19820** [comment]
真是令人惊讶，表格格式识别能力都接近零了，怎么还会有热度，也真是神奇。随便一个中国产的手机自带的识别都比这个项目好一万倍，不知道这个项目存在的意义在哪

**Comment by qwedc001** [comment]
你好，首先，本项目的表格格式识别能力主要受限于所使用的开源引擎 PaddleOCR以及RapidOCR，其表格识别方案在今年七月才上线主 repo 并且根据其[文档](https://paddlepaddle.github.io/PaddleOCR/algorithm/table_recognition/algorithm_table_slanet.html#42-c)所写，C++推理暂时不支持表格识别，我们这侧无法对接其功能。
针对表格识别，您所指的“国产手机自带的识别”一般采用的是手机厂商内置的闭源商用模型，是需要你购买厂商手机才能获得的附加服务，和本软件采用的开源免费引擎是两回事。本软件当前版本的所有内容并不会花费您的任何钱财。
最后，Umi-OCR 目前仍在进行插件系统重构，在重构完成后我会帮助适配在线OCR平台，如果您对开源引擎的识别效果不满意，还请您等待在线OCR功能上线后，自行创建API Key调用商业厂商的接口以达成您期望的效果。
