### ISSUE TITLE
Rapid版本中 Http服务不可用的问题

### ISSUE THREAD

**Issue by jumpywin** [hiroi-sora/Umi-OCR#683]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

windows11、windows10

### OCR plugins Used 使用的OCR插件

RapidOCR

## 文档识别：上传

使用HTTP服务`http://127.0.0.1:1224/api/doc/upload`上传PDF文件，json参数为

```json
{
    "ocr.language": "models/config_chinese.txt",
    "ocr.cls": true,
    "ocr.limit_side_len": 999999,
    "tbpu.parser": "single_none",
    "pageRangeStart": 1,
    "pageRangeEnd": -1,
    "doc.extractionMode": "mixed"
}
```

通过`http://127.0.0.1:1224/api/doc/result`获取结果时偶发http无响应。

***

## 文档识别：获取下载链接

`http://127.0.0.1:1224/api/doc/download`，参数如下

```json
{
    "id": "01103b11-b306-493b-9dff-b5a4837a28ce",
    "ingore_blank": false,
    "file_types": ["txtPlain"]
}
```

获取到的txt文件为空，且偶发性无响应。多次测试不同文件都是如此。

- 获取`pdfLayered`时，拿到的PDF文件只有底层的原文档，没有上层的可搜索复制文本

***

## 其他

- 使用软件UI内`批量文档`的功能来识别同样的PDF文件时，没有出现任何问题。

- 出现问题的版本为Umi-OCR_Rapid_v2.1.4，同时多次测试过Umi-OCR_Paddle2.1.4版本，没有出现过上述问题

测试机器有两台，问题完全一致：

- intel PentiumG6400 windows10 1809 X64 企业版LTSC
- intel core i5-13500 windows11 23H2 X64 家庭中文版

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

[未命名.pdf](https://github.com/user-attachments/files/17336948/default.pdf)

**Comment by hiroi-sora** [comment]
这个问题有点奇怪，理论上OCR插件不会影响http模块的稳定性。

可否尝试下：Rapid版本，通过 `Umi-OCR/UmiOCR-data/RUN_CLI.bat` 启动程序。此时会打开一个命令行日志窗口。当http请求出现问题时，看看日志中是否有报错。

（下版本会更新日志保存到文件功能，方便调试）

**Comment by jumpywin** [comment]
![QQ20241014-084403](https://github.com/user-attachments/assets/86c48701-532f-42e5-be65-c609493a1c22)

**Comment by jumpywin** [comment]
下载文件后，不清理临时文件，拿到txtPlain下载链接使用浏览器访问。此时HTTP服务就无响应了。
![QQ20241014-085209](https://github.com/user-attachments/assets/db434da0-4af4-46cb-95fd-0844801ba2d3)
![QQ20241014-085222](https://github.com/user-attachments/assets/7e7cc4c4-1e6c-4145-aff3-800dadce42cb)

**Comment by hiroi-sora** [comment]
从报错来看，是你的参数 `language` 错误。你填的 `models/config_chinese.txt` 是 Paddle 引擎的参数格式。对于别的引擎（比如Rapid），你应该先用 [api/doc/get_options](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md#0-%E6%96%87%E6%A1%A3%E4%B8%8A%E4%BC%A0%E5%8F%82%E6%95%B0%E6%9F%A5%E8%AF%A2) 接口查询参数，如下，能看到language应该填写 `简体中文` 、`繁體中文` …………这种格式。

![image](https://github.com/user-attachments/assets/9bee9390-5043-4482-8573-54d474b32e55)

**Comment by jumpywin** [comment]
> 从报错来看，是你的参数 `language` 错误。你填的 `models/config_chinese.txt` 是 Paddle 引擎的参数格式。对于别的引擎（比如Rapid），你应该先用 [api/doc/get_options](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md#0-%E6%96%87%E6%A1%A3%E4%B8%8A%E4%BC%A0%E5%8F%82%E6%95%B0%E6%9F%A5%E8%AF%A2) 接口查询参数，如下，能看到language应该填写 `简体中文` 、`繁體中文` …………这种格式。
> 
> ![image](https://private-user-images.githubusercontent.com/56373419/376120581-9bee9390-5043-4482-8573-54d474b32e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTA5MzMsIm5iZiI6MTcyODg5MDYzMywicGF0aCI6Ii81NjM3MzQxOS8zNzYxMjA1ODEtOWJlZTkzOTAtNTA0My00NDgyLTg1NzMtNTRkNDc0YjMyZTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA3MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDkzNmE5ODBhNWU0ZmQ2OTJmOTY2NzkxZTUxMTQ5MTdmYjY4NDJiMGQ2MDNlMTg1OTRlMWI1Y2Y3NTkyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-yIe-hCrKF5NM-gSlOG9PL4R7ajATwGMmJHsT3SZ-nQ)

非常感谢您的认真回复，我对于我先入为主的认为参数一致的行为感到抱歉。
