### ISSUE TITLE
pdf文档内容识别错误

### ISSUE THREAD

**Issue by llm163520** [hiroi-sora/Umi-OCR#685]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

1、用批量文档识别
2、点击开始任务

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![image](https://github.com/user-attachments/assets/d9e2d670-244a-4764-be8d-01615e3bbb76)
[20240729185649698-6421.pdf](https://github.com/user-attachments/files/17348843/20240729185649698-6421.pdf)

**Comment by llm163520** [comment]
![image](https://github.com/user-attachments/assets/adfbb5e2-213c-4da5-a56e-2a4f9d99fc4b)
其识别结果内容不对，识别结果内容参考上图

**Comment by hiroi-sora** [comment]
试试： 内容提取模式 → 整页强制OCR

**Comment by llm163520** [comment]
> 试试： 批量文档标签页→设置→内容提取模式 → 整页强制OCR

尝试过不行

**Comment by hiroi-sora** [comment]
可以的话，把PDF文件上传上来我看看

**Comment by llm163520** [comment]
> 可以的话，把PDF文件上传上来我看看
文件有上传的呢
https://github.com/user-attachments/files/17348843/20240729185649698-6421.pdf

**Comment by hiroi-sora** [comment]
哦哦，懂了。你这个文件是旋转了90°的，需要勾选【纠正文本方向】才能正确识别。

![image](https://github.com/user-attachments/assets/3bcd3c61-2883-4b04-9031-f2376e54ac4c)

**Comment by llm163520** [comment]
如果是API的话这个应该怎么处理呢？

**Comment by hiroi-sora** [comment]
> 如果是API的话这个应该怎么处理呢？

可以传参开启此功能，详见文档。

https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_doc.md#/api/doc

![image](https://github.com/user-attachments/assets/84ae0c47-7e4d-468f-80e0-979974bc2e9f)

**Comment by llm163520** [comment]
可以的了，感谢！
