### ISSUE TITLE
在使用批量OCR的时候，使用命令行来开始任务，提示“Calling "ocrStart" in main thread.”，识别在主线程中执行，那有没有办法监听程序什么时候执行完呢？

### ISSUE THREAD

**Issue by 521Peter** [hiroi-sora/Umi-OCR#688]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

![企业微信截图_17289574077892](https://github.com/user-attachments/assets/af60fe86-54c1-47de-944e-4d7d13d06608)

**Comment by hiroi-sora** [comment]
如果想细粒度的操作OCR过程，建议使用HTTP接口。可以自己控制传输每一张图片，获取结果，写入文件。

**Comment by 521Peter** [comment]
好的，感谢

**Comment by hiroi-sora** [comment]
> 如果批量添加图片，之后执行ocr操作，有概率部分图片没能添加到列表中

可能你程序的操作太快了。Umi添加图片的时候会进行一些检测，需要一点点时间。如果一次性添加大量图片然后立刻开始OCR，可能后面的图片来不及添加到任务列表里。

你的代码，两次 exec 之间 sleep 0.5秒 应该就可以避免了。
