### ISSUE TITLE
如果二维码类型切换图片跟着换就好了

### ISSUE THREAD

**Issue by pewjs** [hiroi-sora/Umi-OCR#690]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win10

### Reproduction steps 复现步骤

如果二维码类型切换图片跟着换就好了

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![QX7UDMBMT)B@YWVF%KHH@1M](https://github.com/user-attachments/assets/c050fcf2-524e-47de-8701-84915aa31f70)

**Comment by hiroi-sora** [comment]
此功能已完成，将在下个版本更新。
