### ISSUE TITLE
作者大大您好，我在使用贵软件的过程中通过http使用qrcode生成的功能，我有点疑惑就是我设置了400*400的像素   但是软件返回生成的qrcode像素一直都是29*29，我测试了很多次包括我右键本地保存生成的qrcode，只有本地保存才能是我设置的像素，http生产的好像是固定29*29。这就导致了http请求生成出来的qrcode像素太小，图片也很小，实际使用可能会有点不太方便，作者大大看能否在下个版本的更新中更新一下这个小功能呢，爱你作者

### ISSUE THREAD

**Issue by CL168888** [hiroi-sora/Umi-OCR#693]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

附上我自己测试写的代码，用的易语言写的
text ＝ “123456”
data ＝ “{” ＋ #引号 ＋ “text” ＋ #引号 ＋ “:” ＋ #引号 ＋ text ＋ #引号 ＋ “}”
back ＝ 编码_usc2到ansi (到文本 (网页_访问_对象 (“http://127.0.0.1:1224/api/qrcode”, 1, data, , , “Content-Type:application/json”, , , , , , , , , , , , , )))
调试输出 (back)
json.解析 (back, , )
文本 ＝ json.取通用属性 (“data”, )
json.清除 ()
调试输出 (文本)

图片框1.图片 ＝ 编码_BASE64解码 (文本, )
写到文件 (取运行目录 () ＋ “\123456.jpg”, 图片框1.图片)

这里我试了很多次通过http请求出来的qrcode图片像素一直都是29*29   哭哭...

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![46e8397bd26e64903a1c4b3322ad2f9](https://github.com/user-attachments/assets/da374891-c2de-4a09-9132-259c18c31f07)

**Comment by CL168888** [comment]
![image](https://github.com/user-attachments/assets/cd8522a7-8b30-4ddd-9b06-94763002f77a)
这是我在用的ocr软件截图

**Comment by qwedc001** [comment]
[二维码API的文档](https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/http/api_qrcode.md#2-%E4%BA%8C%E7%BB%B4%E7%A0%81%E4%BB%8E%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90%E5%9B%BE%E7%89%87) 中已经明确提供了宽高的参数说明，你传个参数进去写400px就行吧

**Comment by hiroi-sora** [comment]
在软件界面中设置的二维码图像分辨率，只对界面生效，不影响http接口。
请在http请求中设置分辨率参数，见上述文档。
