### ISSUE TITLE
请问使用软件批量OCR时，无法将图片或者文件夹拖入候选框是什么原因呢？或者是否可以选择图片文件夹目录呢？

### ISSUE THREAD

**Issue by JianguoYu** [hiroi-sora/Umi-OCR#698]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

批量处理时无法拖入文件夹是什么原因呢？

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![PixPin_2024-10-22_12-09-02](https://github.com/user-attachments/assets/0698ed15-124c-4e10-9aeb-d433dc06ec1b)

**Comment by hiroi-sora** [comment]
> 无法将图片或者文件夹拖入候选框是什么原因呢？

这应该是win10/win11祖传的bug，在网上搜索 `win10 无法拖入` 即可找到很多解答。

可参考：
- https://www.bilibili.com/read/cv6924395/
- https://zhuanlan.zhihu.com/p/508842446

> 是否可以选择图片文件夹目录呢？

标签页的左上角有个 **打开图片** 的按钮，你可以先打开目标文件夹，按 ctrl+A 选中全部文件，再点击打开。

**Comment by JianguoYu** [comment]
谢谢作者的回复，很有帮助




yjg
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiroi-sora/Umi-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月24日(星期四) 凌晨1:49
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hiroi-sora/Umi-OCR] 请问使用软件批量OCR时，无法将图片或者文件夹拖入候选框是什么原因呢？或者是否可以选择图片文件夹目录呢？ (Issue #698)





  
无法将图片或者文件夹拖入候选框是什么原因呢？
  
这应该是win10/win11祖传的bug，在网上搜索 win10 无法拖入 即可找到很多解答。
 
可参考：
  
https://www.bilibili.com/read/cv6924395/
 
https://zhuanlan.zhihu.com/p/508842446
   
是否可以选择图片文件夹目录呢？
  
标签页的左上角有个 打开图片 的按钮，你可以先打开目标文件夹，按 ctrl+A 选中全部文件，再点击打开。
