### ISSUE TITLE
边缘过窄的图片，识别结果不准确

### ISSUE THREAD

**Issue by ksom11** [hiroi-sora/Umi-OCR#7]
![屏幕截图 2022-07-28 133123](https://user-images.githubusercontent.com/87938578/181428295-3f5bb383-d814-48aa-bd9a-a7caba3803b5.png)

**Comment by hiroi-sora** [comment]
您例图的上下边缘太窄，这会阻碍OCR文本检测算法的解析。这是PaddleOCR文本检测（det）目前的一个缺陷，它需要一定的额外空间来确定文字范围框。

只要加大图片的高度，就能让识别准确率恢复正常：

👇原图识别：`由于没有选择（CWS）方式`
![窄.png](https://tupian.li/images/2022/07/28/-.png)

👇增加高度：`由于没有选择俯仰或倾斜方式，飞行方式指示器显示A/P处于驾驶盘操纵（CWS）方式。`
![宽.png](https://tupian.li/images/2022/07/28/-9d0bc0f3b5dcb98f.png)


因此，这个问题的临时解决方法：
1. 截取上下边缘更多的素材图片用于识别。据我测试，只要上下边缘 >= **一个字符的高度**，就不会影响识别准确度。

可能的程序优化方式：（我暂时不考虑实现这些优化）
1. 针对性地训练文本检测det模型用于该场景。
2. 在OCR前预处理，为高度过窄的图片自动添加空白边缘。

关于其他家API：
- 我测试了腾讯OCR**在线**接口，似乎没有这个问题。你有大量需求的话，也许可以寻找使用腾讯在线api（**收费**）的同类项目。

**Comment by ksom11** [comment]
感谢答复

**Comment by hiroi-sora** [comment]
新版本 `v1.2.6` 已经彻底解决这个问题了。随着识别引擎的更新，窄边图片不会降低准确度

![image29d8fcdbb38e8b73.png](https://tupian.li/images/2022/09/01/image29d8fcdbb38e8b73.png)
