### ISSUE TITLE
文档批量识别，文档中同时存在中英符号识别错误

### ISSUE THREAD

**Issue by gzy9049** [hiroi-sora/Umi-OCR#702]
![111](https://github.com/user-attachments/assets/93eb3128-7f38-466d-9b2c-38d7ce599b9f)
英文模型识别，这串字符是对的，中文是乱码。用中文模型，中文能识别，但是这串字符里的“-”识别不出来。

有什么解决的建议么

后面又试了一下，把PDF提取成图片，DPI设置高一些，识别的准确率非常高。文档识别是否有类似参数，可以配置DPI来提高图片的质量

**Comment by gzy9049** [comment]
后面又试了一下，把PDF提取成图片，DPI设置高一些，识别的准确率非常高。文档识别功能是否有类似参数，可以配置DPI来提高图片的质量

**Comment by hiroi-sora** [comment]
> 文档识别功能是否有类似参数，可以配置DPI来提高图片的质量

程序默认是从PDF中提取原始图片数据进行识别。如果你想使用整页提取图片的方式并提高DPI，请参照以下步骤：

1. 调节隐藏的渲染参数。用记事本打开 `Umi-OCR\UmiOCR-data\py_src\mission\mission_doc.py` ，前面第19行有个：
```
MinSize = 1080  # 最小渲染分辨率
```
它表示将PDF渲染为图片时，最短边的边长。您可以调高此数值，如 `MinSize = 2160` 。

2. 重新启动Umi-OCR，在批量文档标签页的设置中，内容提取模式改为 **整页强制OCR**。
3. 如有需要，设置文字识别→限制图像边长 也可以同步调高。
4. 进行PDF任务即可应用上述设定。

**Comment by gzy9049** [comment]
> > 文档识别功能是否有类似参数，可以配置DPI来提高图片的质量
> 
> 程序默认是从PDF中提取原始图片数据进行识别。如果你想使用整页提取图片的方式并提高DPI，请参照以下步骤：
> 
> 1. 调节隐藏的渲染参数。用记事本打开 `Umi-OCR\UmiOCR-data\py_src\mission\mission_doc.py` ，前面第19行有个：
> 
> ```
> MinSize = 1080  # 最小渲染分辨率
> ```
> 
> 它表示将PDF渲染为图片时，最短边的边长。您可以调高此数值，如 `MinSize = 2160` 。
> 
> 2. 重新启动Umi-OCR，在批量文档标签页的设置中，内容提取模式改为 **整页强制OCR**。
> 3. 如有需要，设置文字识别→限制图像边长 也可以同步调高。
> 4. 进行PDF任务即可应用上述设定。

明白了，感谢大佬回复，我试着操作一下。我这里对PDF进行文字识别，一直使用的是整页强制OCR。我需要识别的PDF中几乎没有图片和文字，都是一些设计软件导出的PDF图纸，上边的文字是类似矢量图一类的线条画出来的，所以只能通过整页强制OCR来处理
