### ISSUE TITLE
新版1.32源代码运行出错？

### ISSUE THREAD

**Issue by githubmango0509** [hiroi-sora/Umi-OCR#71]
作者您好，新版打包版运行正常，但用源代码运行出错，‘No module named 'ocr.tbpu.merge_line_h_n_paragraph_english'
多国语言包已打上，请帮看一下是什么问题，谢谢！

**Comment by hiroi-sora** [comment]
已补充，重新clone即可

**Comment by githubmango0509** [comment]
好的，非常感谢！
