### ISSUE TITLE
急！！！！ocr的类和函数函数：PPOCR_pipe，runBytes

### ISSUE THREAD

**Issue by sanwei111** [hiroi-sora/Umi-OCR#718]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

PPOCR_pipe类中有一个函数：runBytes。这个runBytes是把buffered = BytesIO()的结果反转录得到文字，其中未涉及到ocr模型的推理，想问问ocr模型在哪里发挥作用？？？？

**Comment by hiroi-sora** [comment]
`PPOCR_pipe` 本质是一个收发器，向OCR进程发送指令、回收结果，本身不负责OCR的推理。

实际的OCR引擎是相同目录下的 PaddleOCR-json.exe 。

参考：
- https://github.com/hiroi-sora/PaddleOCR-json
- https://github.com/hiroi-sora/RapidOCR-json
