### ISSUE TITLE
打包为内置引擎组件的单个exe文件

### ISSUE THREAD

**Issue by AI-student-wl** [hiroi-sora/Umi-OCR#72]
感谢你的工作，我按照源码打包提示，PaddleOCR-json要和.exe放在同一目录下再能运行，我想打包在一起，就和开源的完整exe一样，有什么办法吗

**Comment by hiroi-sora** [comment]
可以的，手动指定 pyinstaller 的配置参数文件将资源文件包含在exe内，可参考  [issue  #3](https://github.com/hiroi-sora/Umi-OCR/issues/3#issuecomment-1106732053) 。但这样后期导入多国语言包可能比较麻烦，有需要的话先放置好语言包再一起打包exe。

**Comment by AI-student-wl** [comment]
![image](https://user-images.githubusercontent.com/72002667/205476255-26315f01-aa98-4fcd-9371-b652c52ad9e5.png)
我将文件修改了，但exe还是找不到引擎

**Comment by AI-student-wl** [comment]
![image](https://user-images.githubusercontent.com/72002667/205476543-fb514013-54af-4ad0-a11f-d8b8fc7640f8.png)
![image](https://user-images.githubusercontent.com/72002667/205476554-7fd92e43-a858-4465-9110-fd1060192ff8.png)

**Comment by hiroi-sora** [comment]
首先，.spec文件中修改`    datas=[('PaddleOCR-json','PaddleOCR-json')],`
然后，`ocr\engine.py` 第92行改为如下代码：
```python
        # 检查引擎路径
        ocrToolPath = Config.get('ocrToolPath')
        flag = False
        if os.path.isfile(ocrToolPath):  # 指定路径存在引擎组件
            flag = True
        else:  # 不存在，则尝试去临时目录找
            try:
                import sys
                ocrToolPath = os.path.join(sys._MEIPASS, ocrToolPath)
                if os.path.isfile(ocrToolPath):
                    flag = True
            except:  # 非打包模式或无法读取临时目录
                pass
        if not flag:
            raise Exception(
                f'未在以下路径找到引擎组件\n【{ocrToolPath}】\n\n请将引擎组件【PaddleOCR-json】文件夹放置于指定路径！')
```

![image](https://user-images.githubusercontent.com/56373419/205483987-7b43d2b4-8292-4d6e-8247-bfaa26bf708c.png)

![image](https://user-images.githubusercontent.com/56373419/205484034-42c5bfcc-7a7b-43eb-ab74-25355ad21b3f.png)

**Comment by AI-student-wl** [comment]
感谢帮助，我成功的生成了exe!!!
