### ISSUE TITLE
有个字识别不到

### ISSUE THREAD

**Issue by SasamiyaNatsuki** [hiroi-sora/Umi-OCR#724]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.2/2.1.4

### Windows version 系统版本

win10

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

用paddle版本无法识别砝码的砝字，但是rapid版本却可以识别，我还以为是2.1.2版本的问题，下了个2.1.4版本的paddle版本一样不识别

### Problem screenshots or related files (optional) 问题截图或相关文件（可选）

![图片1](https://github.com/user-attachments/assets/1bcd73aa-06cb-49e4-b443-aa2cf65f4c90)

**Comment by JiaZeShi** [comment]
加大空白边距试试
