### ISSUE TITLE
win7_x64_TesseractOCR_best_v1.1.1: 动态导入包失败：No module named 'win7_x64_TesseractOCR_best_v1'

### ISSUE THREAD

**Issue by optttt** [hiroi-sora/Umi-OCR#725]
win7_x64_TesseractOCR_best_v1.1.1: 动态导入包失败：No module named 'win7_x64_TesseractOCR_best_v1'
插件报错

**Comment by qwedc001** [comment]
？？这个问题我不是很早之前就修了，难道是因为大家点进去submodule跳转到错误的release了
最新版release应该没有这个问题了

**Comment by qwedc001** [comment]
把后面的版本号删掉就可以了，等着我更新一下release打包文件
