### ISSUE TITLE
我做了一个Umi-OCR调用微信ocr功能的插件

### ISSUE THREAD

**Issue by eaeful** [hiroi-sora/Umi-OCR#727]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

我做的这个插件WeChatOCR 插件主要是分为两个版本：
1：插件自带微信本地 OCR 模型版本（WechatOCR_umi_plugin_zidai ocr）
插件内置了关键文件：wechatocr.exe、wechat 文件夹、mmmojo.dll 和 mmmojo_64.dll等。
无需安装微信，也无需运行微信，即可直接调用插件内的微信 OCR 功能完成文字识别。
注意：可能存在版权或许可问题，本版本的分发仅用于技术交流和学习目的，请勿用于商业用途

2：微信 OCR 用户自定义路径版本（WechatOCR_umi_plugin_zixingshezhi lujing）
用户需在 Umi-OCR 的全局设置中，手动填写以下路径：
电脑中的微信安装目录的完整路径。
电脑中的WeChatOCR.exe 文件路径。

优点：
避免分发闭源文件，无版权风险。
用户完全控制所需文件的来源和版本。

推荐人群：
对合规性和合法性有更高要求的用户。

熟悉文件配置并愿意进行手动设置的用户。 要使用此版本，您需要准备以下内容：
wechatocr.exe：例如
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WeChatOCR\7079\extracted\WeChatOCR.exe
wechat 文件夹：例如
C:\Program Files (x86)\Tencent\WeChat\[3.9.8.25]

配置完成后，即可调用本地微信进行文字识别。
项目网址：https://github.com/eaeful/WechatOCR_umi_plugin

**Comment by qwedc001** [comment]
您可以将本插件的信息加入到 [Umi-OCR_plugins](https://github.com/hiroi-sora/Umi-OCR_plugins) 库并提交 Pull Request。
感谢您的贡献！
另外建议一下，项目的结构应该仅保留与 Umi 相关的接口文件（那几个 Python 代码），其他的部分应该仅打包到 release 中。
建议将有关微信版权部分单独做一份 eula 出来，不过这个不做也行，看你的意愿

**Comment by eaeful** [comment]
我已经在[Umi-OCR_plugins](https://github.com/hiroi-sora/Umi-OCR_plugins) 库提交了 Pull Request，不知道我提交的方式对不对，我第一次用Pull Request，有错误还请指正和修改。项目的结构也仅保留了与 Umi 相关的接口文件，release没有变动。

**Comment by damaokaiyang** [comment]
![ocr](https://github.com/user-attachments/assets/9cb7394c-8d27-4169-840c-4a4a7e47cb3a)

![image](https://github.com/user-attachments/assets/9764cfed-70af-4a7c-92a6-be74cb7b70b5)

使用插件WechatOCR_umi_plugin_full，初始化失败，win10系统，2.1.4版本

**Comment by eaeful** [comment]
> ![ocr](https://private-user-images.githubusercontent.com/9900670/394653232-9cb7394c-8d27-4169-840c-4a4a7e47cb3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgwMzAsIm5iZiI6MTczMzkxNzczMCwicGF0aCI6Ii85OTAwNjcwLzM5NDY1MzIzMi05Y2I3Mzk0Yy04ZDI3LTQxNjktODQwYy00YTRhN2U0N2NiM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE0ODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YxM2VlNDkwZWY2NjNmYzYxZjYyODRkMzRhZjQwODBhMzdiMjI3NTk2ODVhZjhkMWI0OTYyNmRkNDMxNTU3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cMOfc6UEWGN9JoYK1U7hOS6RMz7WVU4Uobs1bwid2rU)
> 
> ![image](https://private-user-images.githubusercontent.com/9900670/394651988-9764cfed-70af-4a7c-92a6-be74cb7b70b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgwMzAsIm5iZiI6MTczMzkxNzczMCwicGF0aCI6Ii85OTAwNjcwLzM5NDY1MTk4OC05NzY0Y2ZlZC03MGFmLTRhN2MtOTJhNi1iZTc0Y2I3YjcwYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTE0ODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ4ZDdmYThhMDg5MDU4YjIwYjg3ZDY1MjdkOTE2YWYxYjUwNzgwYTM3NGQ4NDllN2I0YjJjZGZmZTNlZWRmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qMjeBCloFWwIVrRKuURhWJbSUFw7EnnqVsvnPctcuvs)
> 
> 使用插件WechatOCR_umi_plugin_full，初始化失败，win10系统，2.1.4版本使用插件WechatOCR_umi_plugin_full，初始化失败，win10系统，2.1.4版本
> 
> 使用插件WechatOCR_umi_plugin_full，初始化失败，win10系统，2.1.4版本

你下载的是Releases里面的版本吗？
