### ISSUE TITLE
希望加入 Linux 版本的支持

### ISSUE THREAD

**Issue by Yubo-Cao** [hiroi-sora/Umi-OCR#73]
能否将 PaddleOCR CPP 引擎部分代码也作为软件的一部分放在仓库中？这样 Linux 和 Mac 用户自己下载编译即可。截图功能十之八九是要残废，但是应该影响不大。

**Comment by hiroi-sora** [comment]
引擎本来就是开源哒，见 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json)
