### ISSUE TITLE
怎么在无gui的ubuntu启动

### ISSUE THREAD

**Issue by Kisjjw** [hiroi-sora/Umi-OCR#730]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

我的设备是一个没有图形化界面的armbian系统，只能通过命令行启动，请问我该怎么做

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR_runtime_linux?tab=readme-ov-file#%E5%8F%AF%E9%80%89%E6%97%A0%E5%A4%B4%E6%A8%A1%E5%BC%8F

**Comment by Kisjjw** [comment]
> * https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md#3-%E8%BF%90%E8%A1%8C%E5%AE%B9%E5%99%A8https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md#3-%E8%BF%90%E8%A1%8C%E5%AE%B9%E5%99%A8
> * https://github.com/hiroi-sora/Umi-OCR_runtime_linux?tab=readme-ov-file#%E5%8F%AF%E9%80%89%E6%97%A0%E5%A4%B4%E6%A8%A1%E5%BC%8F直接使用：

我使用了无头的方式，但是启动的时候，还是会出现这样：
gds@gds:~/Umi-OCR$ ./umi-ocr.sh
Use the default Python environment.
pwd: /home/gds/Umi-OCR
Use GUI mode.
Error: $DISPLAY is not set.

我目前是在有gui的虚拟机上通过ssh连进去启动的，是不是要换成彻底没有gui的服务器上使用

**Comment by hiroi-sora** [comment]
> 我目前是在有gui的虚拟机上通过ssh连进去启动的，是不是要换成彻底没有gui的服务器上使用

系统有无GUI不影响Umi的无头模式。无头模式可以在桌面系统环境下正常使用的。

根据你的日志中 `Use GUI mode.` ，可见启动脚本并没有进入无头模式的分支。请确保设置了环境变量 `export HEADLESS=true` 。

**Comment by Kisjjw** [comment]
> > 我目前是在有gui的虚拟机上通过ssh连进去启动的，是不是要换成彻底没有gui的服务器上使用
> 
> 系统有无GUI不影响Umi的无头模式。无头模式可以在桌面系统环境下正常使用的。
> 
> 根据你的日志中 `Use GUI mode.` ，可见启动脚本并没有进入无头模式的分支。请确保设置了环境变量 `export HEADLESS=true` 。

噢，我忘记这样设置只在当前会话下成功了，现在ok了，感谢
