### ISSUE TITLE
关于化工领域非常用字的识别场景

### ISSUE THREAD

**Issue by itsAnstar** [hiroi-sora/Umi-OCR#734]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复的建议。

### Expected behavior 预期的功能

**场景：在化工领域中使用OCR识别的大多是各种化工材料/原料名，当前引擎可以识别一部分，但仍会出现偶发的认错少认的情况**

**请问如果我想使用自己的数据集贡献给识别引擎作为样本，应该遵循何种规则，具体流程如何**

祝好

**Comment by hiroi-sora** [comment]
你好。

> 请问如果我想使用自己的数据集贡献给识别引擎作为样本，应该遵循何种规则，具体流程如何

本项目注重于上层工具应用的开发，底层使用的是开源OCR识别引擎，如 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 等。您可尝试到引擎项目下面寻求帮助。

未来我们也考虑引入商业OCR引擎接口（百度腾讯等），有需要的用户可以在服务商处购买垂直领域特化的订阅服务，导入Umi中使用。
