### ISSUE TITLE
希望添加新功能---检测内容

### ISSUE THREAD

**Issue by AI-student-wl** [hiroi-sora/Umi-OCR#74]
希望在处理列表和识别内容中间添加一栏检测内容，这部分将文本检测结果显示出来，这样看起来更直观。
![image](https://user-images.githubusercontent.com/72002667/206100241-3336be22-c837-42f6-8aff-23b91c528147.png)

**Comment by hiroi-sora** [comment]
建议收到~

**Comment by AI-student-wl** [comment]
您好，我对于检测结果功能，自己做了一些尝试，在ocr.engine中我找到了data，里面包括检测区域的坐标，我尝试逻辑如下：在win_main.py中，定义一个initTab1_1()，里面2个ballon（上一张，下一张），ballon的command对应的函数里面定义画布和显示图像（需要image list和data），这样我可以尽可能不改动太多代码。不知道能否得到您的帮助，感谢你的工作！

**Comment by hiroi-sora** [comment]
感谢你的建议，这确实是个可行思路。

不过，我有个重构大部分界面的中期目标，在此之前我不会在现有基础上添加太多新界面功能，你可以自己写着试试。如果碰到问题，可以参考 win_select_area.py ，里面有绘制文本检测框的代码。

本软件有多种任务模式，如批量处理图片、单张截屏快速识图、以及未来的PDF识别等。目前，不同的任务共用一部分页面，如批量识图和快速识图都将文字输出到同一个`识别内容选项卡`里。随着以后添加越来越多的任务和功能，界面会变得越来越臃肿杂乱。

为此，我打算改成用一系列顶部标签页来表示不同任务。每个任务的组件和输出面板收纳到各自的标签页中，不会干涉到别的任务的界面。你所提的检测框展示组件，预计将放到快捷识图的标签页中。

![image](https://user-images.githubusercontent.com/56373419/206632902-9af9bd5d-79f7-44f9-818a-e2fdce8512bd.png)

总之，短期内我不打算新增检测框展示的功能。

**Comment by hiroi-sora** [comment]
[v2版本](https://github.com/hiroi-sora/Umi-OCR_v2) 的截图OCR标签页中已支持显示检测框。
