### ISSUE TITLE
引擎启动不了

### ISSUE THREAD

**Issue by fbstorm** [hiroi-sora/Umi-OCR#75]
![image](https://user-images.githubusercontent.com/100028477/206517760-9459d8d3-8685-46aa-a5aa-46ded2d92edc.png)
![image](https://user-images.githubusercontent.com/100028477/206518070-fec3f769-a09d-421b-ac6a-af785a1f7730.png)
不知道为什么

**Comment by hiroi-sora** [comment]
CPU型号？

**Comment by fbstorm** [comment]
> CPU型号？

![image](https://user-images.githubusercontent.com/100028477/206651854-2f0514c6-fbe8-42b8-9092-58a98bbdf099.png)
![image](https://user-images.githubusercontent.com/100028477/206651904-7c842df7-eca1-418c-96bb-06202304206e.png)
内存8G
intel核显，贫民机

**Comment by hiroi-sora** [comment]
很遗憾，11代以前的赛扬U不支持AVX指令集，所以引擎组件无法兼容。

**Comment by fbstorm** [comment]
好的，谢谢谢谢
