### ISSUE TITLE
关于快捷键冲突的问题

### ISSUE THREAD

**Issue by xiaoyao-wang** [hiroi-sora/Umi-OCR#751]
### Issues

- [X] I have browsed through the Issues. 我已浏览过Issues，确定没有重复提问。

### Umi-OCR version 程序版本

2.1.4

### Windows version 系统版本

win11

### OCR plugins Used 使用的OCR插件

PaddleOCR

### Reproduction steps 复现步骤

个人习惯是 CTRL+1 用作 ocr 快捷键，但是在浏览器和其他一些软件比如 Adobe Acrobat 中，这个快捷键一般会切换到第一个标签页。

在 umi 中如果这么设置快捷键会同时触发这两个功能。
在使用 umi 时如果保持 隐藏等待时间 这一设置项的默认值 0.2s，会先跳到第一个标签页再进行 ocr。
修改为 0.0s 可以一定程度解决这个问题，使用快捷键后识别界面是当前标签页，当完成选中识别内容退出识别界面后才会出现在第一个标签页。

已经用了好几年的 umi 了，一直有这个问题，一般是把标签页拖到第一个再识别。
但是我使用的截屏软件在设置类似快捷键时不会出现这样的问题，即只会触发截屏软件的快捷键功能不会触发浏览器的快捷键功能。

**Comment by hiroi-sora** [comment]
可以通过这个工具解决：
https://github.com/hiroi-sora/Umi-OCR/issues/402

**Comment by xiaoyao-wang** [comment]
解决了 感谢
