### ISSUE TITLE
日文识别正确率过低

### ISSUE THREAD

**Issue by Qyuuuuuu** [hiroi-sora/Umi-OCR#76]
感觉日文识别正确率过低，基本上百分之70左右都是错字的，不知道这个可不可以修正一下

**Comment by hiroi-sora** [comment]
我试了下，v2日文库的正确率似乎比v3库好很多。

v2版日文识别库：[japan(v2).zip](https://github.com/hiroi-sora/Umi-OCR/files/10201312/japan.v2.zip)
以上解压放到PaddleOCR-json文件夹里，然后上一层的Umi-OCR_config.json添加一项：
```
            "日文v2": {
          	  "path": "PaddleOCR_json_config_japan(v2).txt"
	     },
```
![image](https://user-images.githubusercontent.com/56373419/206882457-d53bbc06-1304-4df8-ba69-8accb0d9c5d5.png)
