### ISSUE TITLE
合并txt后,输出能不能去除原图片名字

### ISSUE THREAD

**Issue by anton2925** [hiroi-sora/Umi-OCR#77]
就是由原本：
合并输出：
≦ 名字1.png ≧
名字1内容
≦ 名字2.png ≧
名字2内容
....
end
变成：
名字1内容
名字2内容
.....
end

**Comment by hiroi-sora** [comment]
可以，之所以图片名字用 ` ≦ ≧ ` 这组特殊符号括起来，就是便于后续处理的。

用任意支持正则表达式的编辑器，比如vscode，打开txt文件。打开查找-替换（ctrl+f），勾选启用正则，然后将 `≦.*≧` 全部替换成空就可以了。如果想连空行一并删掉，可以替换  `\n\n\n≦.*≧\n\n` 。

![image](https://user-images.githubusercontent.com/56373419/207010490-754aefe0-e2cc-4439-89f2-031624e06f4a.png)
