### ISSUE TITLE
PaddleOCR_json.exe - 系统错误

### ISSUE THREAD

**Issue by chacles** [hiroi-sora/Umi-OCR#78]
---------------------------
PaddleOCR_json.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 api-ms-win-core-processtopology-obsolete-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

确认有AVX指令，这错误感觉需要安装VC框架，我试了2个版本都不行。

**Comment by hiroi-sora** [comment]
请问你是win10/11吗？这个报错我之前尝试移植win7的时候似乎出现过，不太好解决。与vc库应该无关，这是win8以上系统自带的一个dll。

如果你是win10+，尝试下载这个dll放到程序目录下看看能不能用：
[api-ms-win-core-processtopology-obsolete-l1-1-0.zip](https://github.com/hiroi-sora/Umi-OCR/files/10215770/api-ms-win-core-processtopology-obsolete-l1-1-0.zip)

**Comment by chacles** [comment]
> 

系统是Windows 2008 R2，服务器的系统，如果不好解决就算了，win10没问题。

**Comment by vector090** [comment]
Win7 系统，下载几个 DLL 放到 PaddleOCR-json 目录里就可以正常运行了：

[api-ms-win-core-processtopology-obsolete-l1-1-0.zip](https://github.com/hiroi-sora/Umi-OCR/files/10215770/api-ms-win-core-processtopology-obsolete-l1-1-0.zip) 群主贴的那个

[api-ms-win-core-libraryloader-l1-2-0](https://d.wenjian.net/dll/a/api-ms-win-core-libraryloader-l1-2-0.rar)

[api-ms-win-eventing-provider-l1-1-0](https://d.wenjian.net/dll/a/api-ms-win-eventing-provider-l1-1-0.rar)

**Comment by hiroi-sora** [comment]
@vector090 

经测试，此方法有效。（可能还需要安装VC运行库。）

非常感谢你提供的信息！解决了困扰此项目一年多的问题！
