### ISSUE TITLE
批量处理照片时报错"向识别器进程写入图片地址失败，疑似子进程已崩溃"

### ISSUE THREAD

**Issue by WhiteSKing** [hiroi-sora/Umi-OCR#80]
你好，就是基于你的这个程序，写批处理脚本，一般处理10张图片片左右就开始报错"向识别器进程写入图片地址失败，疑似子进程已崩溃","子进程已崩溃"。另外会弹出窗口提示“PaddleOCR_json.exe已停止工作，windows可以联机检查该问题的解决方案”，想请问下你们有没遇到这种问题，是什么原因造成的？（ps:电脑是win7系统）

**Comment by hiroi-sora** [comment]
本程序引擎组件确实对win7兼容性不佳，一般情况下是跑不起来的。不过你这一开始能跑，之后崩溃的情况我也没遇见过。

是每次到同一张图片时崩溃吗？

**Comment by WhiteSKing** [comment]
你好，我检查到了，是因为我图片下载的是缓存的临时文件，大小只有0kb，所以报错了。程序没有问题。电脑win刚开始引擎无法启动，好像下载了两个dll文件，后面就可以运行了。
