### ISSUE TITLE
是否添加str字幕

### ISSUE THREAD

**Issue by KSSW** [hiroi-sora/Umi-OCR#82]
使用Subtitle Edit软件 用HTML索引保存所有图像
![360截图20221224195049921](https://user-images.githubusercontent.com/76238373/209434877-c324e599-3026-437e-a134-73a97680b570.png)
![360截图20221224195116497](https://user-images.githubusercontent.com/76238373/209434876-aac846ad-a5b5-4cd8-a774-e1a35a39bd76.png)
文件：index.html
![360截图20221224195545412](https://user-images.githubusercontent.com/76238373/209435010-780ccea1-dece-4eec-b8ab-417d875963dd.png)
是否添加str字幕，希望支持添加

**Comment by hiroi-sora** [comment]
这个需求看起来比较小众，短期内没有足够的动力添加，抱歉。

或者可以参考：先用Umi-OCR输出原始信息jsonl，再用脚本后续处理 [issues #70](https://github.com/hiroi-sora/Umi-OCR/issues/70#issuecomment-1336065350)

**Comment by 6Tom** [comment]
喔，这种字幕原来是这么做的哦，说白了栅格化文字是为了保护不被轻易复制啊

我前两天头一次见这种图形字幕，刚开始还以为就是普通的外挂字幕，但是文字我选不中，有点懵，然后发现是图片

**Comment by KSSW** [comment]
所以我在搞这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiroi-sora/Umi-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月29日(星期四) 上午8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiroi-sora/Umi-OCR] 是否添加str字幕 (Issue #82)





 
喔，这种字幕原来是这么做的哦，说白了栅格化文字是为了保护不被轻易复制啊
 
我前两天头一次见这种图形字幕，刚开始还以为就是普通的外挂字幕，但是文字我选不中，有点懵，然后发现是图片
