### ISSUE TITLE
这么优秀的软件怎么可以不支持命令行模式呢？

### ISSUE THREAD

**Issue by davidWeiZhou** [hiroi-sora/Umi-OCR#85]
要求增加命令行模式，像tesseract那样，打开cmd，输入："umi_ocr.exe" ".\001.bmp" ".\001.txt"，这样的话，就可以在很多软件中使用了，比如，我可以在Autohotkey中使用cmd命令调用你这个，问题是，现在，你不支持命令行啊，好郁闷啊。

这么优秀的软件，居然不支持命令行模式，请求增加这个功能，感谢万分！

**Comment by hiroi-sora** [comment]
感谢建议。
已经收到很多人希望出命令行模式的建议，我会将这个功能提上日程。

**Comment by hihvan** [comment]
期待更新这个功能，这样我就可以直接使用Snipaste 截图自动复制然后umi直接出ocr结果了。Snipaste 截图可以自动选择元素，非常方便。有个exec（）的命令行 研究了半天发现弄不了。期待作者更新

**Comment by wcmiracle** [comment]
软件真的太好用了，要是支持命令行，我就可以用python调用了

**Comment by hiroi-sora** [comment]
命令行调用开发完毕，欢迎体验 [v1.3.3 测试版](https://github.com/hiroi-sora/Umi-OCR/issues/96) 。

**Comment by hiroi-sora** [comment]
`v1.3.3` 正式版已发布，含命令行调用功能。
