### ISSUE TITLE
功能建议：弹出悬浮的识别成功与否的提示

### ISSUE THREAD

**Issue by Freddd13** [hiroi-sora/Umi-OCR#86]
最近用quicker，发现这个提示很好，既不用设置弹出主窗口又能得到执行识别的反馈，大佬能不能做下：
![image](https://user-images.githubusercontent.com/50367552/213899095-4a98e200-dc02-4304-b2e8-9e664c0cc59c.png)

**Comment by hiroi-sora** [comment]
了解。之前试着做过用windows原生通知栏弹出提示，但调试了一段时间API发现限制比较大，异步容易出bug，无奈放弃了。

自己构建一个通知悬浮窗也是不错的方式，我会研究一下。

**Comment by hiroi-sora** [comment]
开发完毕，欢迎体验 [v1.3.3 测试版](https://github.com/hiroi-sora/Umi-OCR/issues/96) 。

**Comment by hiroi-sora** [comment]
包含此功能的 `v1.3.3` 正式版已发布。

**Comment by Freddd13** [comment]
感谢！无敌~
