### ISSUE TITLE
More GUI languages supported?

### ISSUE THREAD

**Issue by konjski-tramvaj** [hiroi-sora/Umi-OCR#89]
Hi,

wanted to know if GUI could be translated to english to popularize and spread this neat program.

BR.

**Comment by hiroi-sora** [comment]
Thank you for your support.
I have the same plan. In the future, I may restructure this project and focus on multilingual support.

**Comment by konjski-tramvaj** [comment]
> Thank you for your support. I have the same plan. In the future, I may restructure this project and focus on multilingual support.

thank you very much for consideration.
