### ISSUE TITLE
Umi 是什么意思

### ISSUE THREAD

**Issue by wanghaocun** [hiroi-sora/Umi-OCR#90]
平时对软件/技术/缩写等习惯了解名字的来源
对**Uni-OCR**想了很久没有找到合理的解释
只知道 _优米 / 乌米_ 作为人名
还有 _umijs_ 是一个前端框架
所以  想问下作者 _Umi-OCR_ 名字的来源 😲 
@hiroi-sora

**Comment by hiroi-sora** [comment]
哈哈，确实来源于人名。
如Readme中的前言，本项目的初衷是为了方便整理影视和游戏截图。项目初期，常用于调试的数据集中有一位名叫加藤うみ（Kato Umi）的人物，本项目借用了她的名字。うみ意为“大海”或者“张开羽翼飞向未来”。
另外也有向隔壁[Dango-Translator](https://github.com/PantsuDango/Dango-Translator)致敬的意思，Umi和Dango的名称和Logo都起源于同一家公司的作品。

**Comment by wanghaocun** [comment]
嗯  了解了该项目名字的来源  现在记忆更深刻了  作者的 **_Umi-OCR_** 以后会是我本地工具的一款利器  👍 
同时  你又让我知道了 **_Dango-Translator_** 这款利器  下午体验了一下  着实厉害  向你们无私开源致敬  ✨
