### ISSUE TITLE
功能建议：增加二维码、条码的识别

### ISSUE THREAD

**Issue by shishirong** [hiroi-sora/Umi-OCR#95]

**Comment by hiroi-sora** [comment]
收到 √ 考虑考虑

**Comment by bitjerry** [comment]
希望新版增加这个功能

**Comment by hiroi-sora** [comment]
### 扫码功能已经开发完成了，将在下个预览版本发布。

支持多种格式的二维码、条形码，支持一图多码。可截屏 / 粘贴 / 拖入本地图片进行识别。

![image](https://github.com/hiroi-sora/Umi-OCR/assets/56373419/f8ade8e5-6e41-4fd2-9009-c4c63e7aaa57)

**Comment by xmsz-stu** [comment]
可以支持小程序二维码识别吗

**Comment by hiroi-sora** [comment]
@xmsz-stu 

抱歉，微信小程序二维码使用私有协议，内容经过加密，只能使用微信自己的接口进行解析和解密。本项目没有接入微信的计划，因此不能识别小程序码。
