### ISSUE TITLE
开机启动时第一次文字识别报错

### ISSUE THREAD

**Issue by rollgotobed** [hiroi-sora/Umi-OCR#97]
没截图报错内容，但检查了一下，大约是开机启动时 `PaddleOCR_json.exe` 这个程序没有一起启动的原因。

开机后第一次识别报错，然后软件启动，之后的识别就没有问题了。

**Comment by hiroi-sora** [comment]
`PaddleOCR_json.exe`是引擎组件，它并不会与主程序同时启动的，只会根据需要在OCR任务时启动。

“开机后第一次识别报错” 大概是报了什么信息呢？可复现吗？
