### ISSUE TITLE
你好，点击使用就显示这个是什么问题呀？

### ISSUE THREAD

**Issue by lanaouo** [hiroi-sora/Umi-OCR#98]
![1678415461169](https://user-images.githubusercontent.com/127462222/224208150-241981da-59ba-4154-ace3-dec4b28b57ff.jpg)

![image](https://user-images.githubusercontent.com/127462222/224208201-f105b19b-64aa-4ea3-8c7a-4355fe2e8d19.png)

**Comment by hiroi-sora** [comment]
大概率由CPU不支持AVX指令集引起。

> 常见的家用CPU一般都支持AVX指令集，如下：

| AVX   | 支持的产品系列                                           | 不支持                                                      |
| ----- | -------------------------------------------------------- | ----------------------------------------------------------- |
| Intel | 酷睿Core，至强Xeon，11代及以后的赛扬Celeron和奔腾Pentium | 凌动Atom，安腾Itanium，10代及以前的赛扬Celeron和奔腾Pentium |
| AMD   | 推土机架构及之后的产品，如锐龙Ryzen、速龙Athlon、FX 等   | K10架构及之前的产品                                         |

> 可通过 [CPU-Z](https://www.cpuid.com/downloads/cpu-z/cpu-z_2.03-cn.zip) 软件查看自己CPU的指令集信息。

![image](https://user-images.githubusercontent.com/56373419/224217325-a3fc8d8d-577e-445b-a1a4-0e50a930ef9d.png)

**Comment by lanaouo** [comment]
感谢解疑，那是不是就无法使用了？只能更换cpu吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiroi-sora/Umi-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hiroi-sora/Umi-OCR] 你好，点击使用就显示这个是什么问题呀？ (Issue #98)





 
大概率由CPU不支持AVX指令集引起。
  
常见的家用CPU一般都支持AVX指令集，如下：
     AVX 支持的产品系列 不支持 
    Intel 酷睿Core，至强Xeon，11代及以后的赛扬Celeron和奔腾Pentium 凌动Atom，安腾Itanium，10代及以前的赛扬Celeron和奔腾Pentium 
  AMD 推土机架构及之后的产品，如锐龙Ryzen、速龙Athlon、FX 等 K10架构及之前的产品 
    
可通过 CPU-Z 软件查看自己CPU的指令集信息。

**Comment by hiroi-sora** [comment]
> 感谢解疑，那是不是就无法使用了？只能更换cpu吗？

本地OCR涉及大量的图像处理和密集的数学运算，而AVX指令集就是用于提高CPU处理密集型计算任务的效率；所以本项目目前依赖于AVX。

不支持AVX指令集的CPU，可能定位是入门级或者工控机专用，本身性能也比较弱。如果有需要在这样的机器上使用OCR，或许用在线识别的软件更好。

**Comment by hiroi-sora** [comment]
[测试版本](https://github.com/hiroi-sora/Umi-OCR/tree/dev/rapid/1.3.4) 已支持无AVX指令集的CPU。
