### ISSUE TITLE
“剪贴板中未查询到图片信息”提示污染历史识别记录

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [hiroi-sora/Umi-OCR#99]
目前，“剪贴板中未查询到图片信息”会直接接着上一次的识别记录显示，污染了“识别记录”的文本。

希望可以将这条报错信息与历史记录分开显示。
![图片](https://user-images.githubusercontent.com/63943573/224532260-bd0c9989-d7a3-42b9-91df-9317b9725edb.png)

**Comment by MaxHasBeenUsed** [comment]
还有，有想过如果可以实现：“如果剪切板中最新的一条不是图片，那么识别剪切板中第二新（或顺序检测数个）的记录”就太好了。

想到这个是因为启用了“自动复制识别内容”后如果发现效果不理想，想调整设置重新识别一遍的时候，由于剪切板中最新的记录是刚刚自动复制的文字，会导致识别失败。

但是这样应该要持续监控剪切板？不知道作者愿不愿意做，也不知道使用者愿不愿意用，所以就没单独提 issue。在这里简单提一下，也许会有什么其他更好的曲线救国方案。

**Comment by hiroi-sora** [comment]
> 希望可以将这条报错信息与历史记录分开显示。

即将发布的1.3.3新版本中新增了通知弹窗功能，”未查询到图片信息“这些通知也会显示在屏幕弹窗中。

![image](https://user-images.githubusercontent.com/56373419/224534566-a487ec1b-50ac-4699-be80-1565ca8e2213.png)

不过，这些通知依然会显示在识别内容历史记录中。我认为你说的”污染历史识别记录“不会影响正常使用。如果要禁用通知在主面板的输出，又需要新增一些开关和配置项来迎合其他用户的习惯，我觉得弊大于利。

当然，新版本发布后，你可以把通知输出到主面板的那行语句删掉，然后自己打个包来用。
![image](https://user-images.githubusercontent.com/56373419/224535529-dc5bbce1-a072-44dd-a779-8712b51ac63b.png)


> 识别剪切板中第二新（或顺序检测数个）的记录

我主要担心误判的问题，比方说我截了一张图A，识别，复制，这样剪贴板中就有两条记录（图片A，文本A）。然后我又截了一张图B来识别，但因为剪贴板占用的异常，图B并没有存入剪贴板。接着程序顺序检测，识别的还是图片A。导致我识别的是图B，出来的却是A的文本。这种误判错误更无法接受。

**Comment by MaxHasBeenUsed** [comment]
> 禁用通知在主面板的输出

我的意思是**采用不同的样式进行显示**，而不是不显示。比如目前“快捷识图 YYYY-MM-DD HH:MM:SS”会用蓝色字，并前后空行。类似的我希望“未查询到图片信息”也用某种方法与识别内容**区分开**。

提出这个问题是因为见上图，如果我想要翻历史记录，复制某一次的识别内容，“未查询到图片信息”的提示会干扰到我对**识别内容结束节点**的判断。例如，如果没有这个提示，结束的节点就是一个空行和蓝色的“快捷识图 YYYY-MM-DD HH:MM:SS”，这非常直观。

至于另一个问题，确实我没有考虑到这些。感谢解释！

**Comment by hiroi-sora** [comment]
抱歉，是我误解了你的意思。

> 采用不同的样式进行显示

okok，加了个红色样式，通知信息以红色显示。如下图

![image](https://user-images.githubusercontent.com/56373419/224544824-725fad0b-3e94-4064-b2e7-b1cc431db0b7.png)

**Comment by hiroi-sora** [comment]
包含此功能的 `v1.3.3` 正式版已发布。
